TEAMMATES/teammates

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionB.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html

Missing giverSections in some responses in InstructorFeedbackResultsPageUiTest.json #2808

---

src/test/java/teammates/test/cases/common/FieldValidatorTest.java

Incorrect testing methods in FieldValidatorTest #2807

---

devdocs/process.md
src/main/java/teammates/common/datatransfer/FeedbackSessionResponseStatus.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/webapp/jsp/instructorFeedbackResultsByGiverQuestionRecipient.jsp
src/main/webapp/jsp/instructorFeedbackResultsByGiverRecipientQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByRecipientGiverQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByRecipientQuestionGiver.jsp
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView1.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView2.html
src/test/resources/pages/instructorFeedbackResultsPageRubricGQRView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricGRQView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricQuestionView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricRGQView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricRQGView.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html

Resumed from #2687 
Fixes #2535

InstructorFeedbackResultsView: show the team ID of students who did not submit #2535

---

src/main/resources/InstructorSampleData.json
src/test/resources/pages/NJIfeedbackSessionSuccessEdited.html

Wrong recipient in instructorSampleData #2827

---

src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/ui/controller/InstructorCommentsPageAction.java
src/main/java/teammates/ui/controller/InstructorCourseAddAction.java
src/main/java/teammates/ui/controller/InstructorCourseArchiveAction.java
src/main/java/teammates/ui/controller/InstructorCoursesPageAction.java
src/main/java/teammates/ui/controller/InstructorHomePageAction.java
src/main/java/teammates/ui/controller/PageData.java
src/main/webapp/jsp/instructorCourses.jsp
src/main/webapp/jsp/instructorHome.jsp
src/main/webapp/jsp/instructorStudentList.jsp
src/test/java/teammates/test/cases/ui/InstructorCourseArchiveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/resources/data/InstructorHomePageUiTest3.json

Archiving should be per-instructor, not per-course #1787

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEnrollPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorSearchPageUiTest.java

 modify tests to case-match the 'expected' file names to actual file names #2824 

---

src/main/java/teammates/common/datatransfer/CourseDetailsBundle.java
src/main/java/teammates/common/util/Const.java
src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/ui/controller/InstructorFeedbackAddAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackCopyAction.java
src/main/java/teammates/ui/controller/InstructorFeedbacksPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbacksPageData.java
src/main/webapp/jsp/instructorFeedbacks.jsp
src/test/java/teammates/test/cases/ui/InstructorFeedbacksPageActionTest.java
src/test/resources/pages/NJIfeedbackSessionPublished.html
src/test/resources/pages/NJIfeedbackSessionRemind.html
src/test/resources/pages/NJIfeedbackSessionUnpublished.html
src/test/resources/pages/instructorFeedbackAllSessionTypes.html
src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
src/test/resources/pages/instructorFeedbackEmptyAll.html
src/test/resources/pages/instructorFeedbackEmptySession.html
src/test/resources/pages/instructorFeedbackPublishSuccessful.html
src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
src/test/resources/pages/instructorFeedbacksAllSessionTypesWithHelperView.html
src/test/resources/pages/newlyJoinedInstructorFeedbacksPage.html

instructorSessions: omit archived courses from drop-down list #2771

---

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/resources/data/InstructorHomePageUiTest3.json

Private feedback sessions should not be visible to other instructors #2845

---

src/main/webapp/stylesheets/teammatesCommon.css

Change cell-hover colour for rubric question #2810

---

src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html

InstructorFeedbackResultsPageUiTest failing on dev server due to profile picture links #2860

---

src/main/java/teammates/common/datatransfer/InstructorAttributes.java
src/main/java/teammates/storage/entity/Instructor.java

Archiving doesn't work for older courses #2863

---

src/main/webapp/stylesheets/teammatesCommon.css

Change cursor to pointer for the [Edit] link in the comments for the create feedback form #2301

---

src/main/webapp/index.html

index.html: update entry count placeholder to a six digit number #2766 

---

src/main/java/teammates/common/util/ActivityLogEntry.java
src/main/webapp/deadlineExceededErrorPage.jsp
src/test/resources/pages/deadlineExceededErrorPage.html

/admin/stylesheets/teammatesCommon.css not found #2869

---

src/test/resources/pages/NJIfeedbackSessionSuccessEdited.html

AdminHomePageUiTest fails due to hard-coded value #2876

---

src/main/java/teammates/client/scripts/DataMigrationForIsArchivedAttribute.java
src/main/java/teammates/storage/api/InstructorsDb.java

Fixes #2884 
When the isArchived attribute was first added to Instructor, one of the methods wasn't updated to modify the isArchived attribute. This pull request fixes that too.

Migrate legacy data for isArchived variable #2884

---

src/main/java/teammates/common/util/ActivityLogEntry.java
src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
src/main/java/teammates/ui/controller/AdminActivityLogPageData.java
src/main/webapp/js/adminActivityLog.js

adminActivityLogPage: very slow to load #2883

---

src/main/java/teammates/ui/controller/PageData.java
src/main/webapp/jsp/instructorFeedbackResultsByGiverQuestionRecipient.jsp
src/main/webapp/jsp/instructorFeedbackResultsByGiverRecipientQuestion.jsp
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsPageRubricGQRView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricGRQView.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html

Moderations cannot be accessed in masquarade mode #2850

---

devdocs/settingUp.md

Fixes #2886
Java 8 is not recommended by GAE

update settingup.md for java 8 and eclipse luna #2886

---

src/main/java/teammates/common/datatransfer/FeedbackQuestionAttributes.java
src/test/resources/data/StudentFeedbackSubmitPageUiTest.json
src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
src/test/resources/pages/studentFeedbackSubmitPageModified.html
src/test/resources/pages/studentFeedbackSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html

Incorrect phrasing in visibility description #2703

---

src/main/java/teammates/common/datatransfer/FeedbackRubricQuestionDetails.java
src/test/java/teammates/test/cases/ui/browsertests/FeedbackRubricQuestionUiTest.java
src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html

ArrayIndexOutOfBoundsException in rubrics question #2900

---

src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionHelperView.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionB.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView1.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView2.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html

InstructorFeedbackResultsPage: Missing responses are not shown when recipient is General and grouping by Question #2843

---

src/main/java/teammates/ui/controller/AdminSearchPageAction.java
src/main/webapp/jsp/adminSearch.jsp

admin search: link student name to student record under course owner's pages #2907

---

src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.js

Wrong error message when the too many reponses to retrieve #2705

---

src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackQuestionDetails.java
src/main/webapp/jsp/instructorFeedbackResultsByQuestion.jsp
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView1.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView2.html
src/test/resources/pages/instructorFeedbackResultsPageRubricGQRView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricQuestionView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricRQGView.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html

instructor: feedback results: show 'no response' instead of 'N/A' #2819

---

src/main/java/teammates/common/util/ActivityLogEntry.java
src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java

admin activity log: make local time available for actions of unregistered users #2896

---

src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/ui/controller/PageData.java
src/main/webapp/jsp/instructorEvals.jsp
src/main/webapp/jsp/instructorFeedbacks.jsp
src/main/webapp/jsp/instructorHome.jsp
src/test/java/teammates/test/cases/logic/CoursesLogicTest.java

Fixes #2880 
InstructorHomePage and instructorFeedbacksPage should be slightly faster
The migration script for #2884 should have been run, or this may produce different behavior for archived courses.

PageData: Optimize getInstructorFeedbackSessionActions #2880

---

src/main/java/teammates/common/datatransfer/CommentSearchResultBundle.java
src/main/java/teammates/common/datatransfer/FeedbackResponseCommentSearchResultBundle.java
src/main/java/teammates/common/datatransfer/SearchResultBundle.java
src/main/java/teammates/common/datatransfer/StudentSearchResultBundle.java

NPE in search #2913

---

src/main/java/teammates/ui/controller/AdminSearchPageAction.java
src/main/java/teammates/ui/controller/AdminSearchPageData.java
src/main/webapp/js/adminSearch.js
src/main/webapp/jsp/adminSearch.jsp

admin search results: show course name #2922

---

src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java

'Session disappeared' error during copying #2937

---

src/main/java/teammates/logic/automated/FeedbackSubmissionAdjustmentAction.java

Add stack trace to log for FeedbackSubmissionAdjustmentAction #2944

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/common/util/EmailTemplates.java
src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/Emails.java
src/main/java/teammates/logic/core/StudentsLogic.java
src/main/java/teammates/ui/controller/ActionFactory.java
src/main/java/teammates/ui/controller/AdminSearchPageAction.java
src/main/java/teammates/ui/controller/AdminSearchPageData.java
src/main/java/teammates/ui/controller/AdminStudentGoogleIdResetAction.java
src/main/java/teammates/ui/controller/AdminStudentGoogleIdResetPageData.java
src/main/resources/studentEmailFragment-googleIdReset.html
src/main/webapp/js/adminSearch.js
src/main/webapp/jsp/adminSearch.jsp

admin search results: give a button to reset google ID of a student #2919

---

devdocs/settingUp.md

settingUp.md : Improve example for logging in as instructor #2968

---

src/main/java/teammates/client/scripts/InstructorEntityViewer.java
src/main/webapp/js/instructorCourseEdit.js
src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html

Some tutors see all students while some see only students in the section

---

src/main/webapp/about.html

Updated contributor list:
Chi Cheng
Devang Gaur
Gu Junchao
Han Zijian
Josephine Kwa
Kang Hong Jin
Manvi Jain
Qua Zi Xian
Ryan Chang
Subhodip Kumar
Svitlana Nesterenko
Tang Ning
Tania Chattopadhyay
Yang Mo

Update contributor list

---

src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java
src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/storage/api/FeedbackResponsesDb.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java

studentFeedbackSubmitSave takes too long #2975

---

devdocs/settingUp.md

settingUp.md : grammatical inconsistency/typo present #2931

---

src/main/resources/feedbackQuestionContribResultStatsStudentViewTemplate.html
src/main/webapp/jsp/studentEvalResults.jsp
src/test/resources/pages/NJIstudentFeedbackResultsPage.html
src/test/resources/pages/studentEvalResultsExtreme1HTML.html
src/test/resources/pages/studentEvalResultsExtreme2HTML.html
src/test/resources/pages/studentEvalResultsExtreme3HTML.html
src/test/resources/pages/studentEvalResultsNotSubmittedHTML.html
src/test/resources/pages/studentEvalResultsP2PDisabled.html
src/test/resources/pages/studentEvalResultsTheOtherDidn'tSubmitHTML.html
src/test/resources/pages/studentEvalResultsTwoMembersTypicalHTML.html
src/test/resources/pages/studentEvalResultsTypicalHTML.html
src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html

student view of contribution question results: use a darker blue for panel heading #2996

---

src/main/java/teammates/common/datatransfer/AccountAttributes.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageAction.java
src/main/java/teammates/ui/controller/StudentFeedbackSubmissionEditPageAction.java
src/main/webapp/entityNotFoundPage.jsp
src/test/java/teammates/test/cases/ui/StudentFeedbackSubmissionEditPageActionTest.java
src/test/resources/pages/entityNotFoundPage.html
src/test/resources/pages/studentProfilePictureStudentDoesNotExist.html

@damithc I have ran StudentFeedbackSubmitPageUiTest, StudentFeedbackSubmissionEditPageAction, and AllAccessControlUiTests. The testing station is currently running the AllTests

Rapid 'response page' requests from a single student #3012

---

src/main/java/teammates/ui/controller/PageData.java

PageData::getTimeZoneOptionsAsHtml needs a space before selected=\"selected\" #1780

---

src/main/webapp/dev/devman.html

Typo in devman.html #3027 

---

src/main/webapp/js/feedbackResponseComments.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
src/test/resources/pages/instructorFeedbackResultsDeleteComment.html

  Edit New issue instructor response comments: after editing, visibility change in database is not reflected in UI

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
src/main/webapp/js/feedbackSubmissionsEdit.js
src/main/webapp/jsp/feedbackQuestionSubmissionEdit.jsp
src/test/java/teammates/test/cases/ui/StudentFeedbackSubmissionEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackSubmitPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java
src/test/resources/pages/instructorFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageGracePeriod.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPagePrivate.html
src/test/resources/pages/instructorFeedbackSubmitPageModified.html
src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageDeadLineExceeded.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPageModified.html
src/test/resources/pages/studentFeedbackSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html

student feedback submission: Do not auto select the recipient name #2989

---

src/main/webapp/studentHelp.html

Fixes #2867. The modified version can be seen [here](http://4-18-dot-teammates-karan173.appspot.com/studentHelp.html).

studentHelp.html: mention that students need not 'join' #2867

---

src/main/webapp/stylesheets/adminAccountManagement.css

adminAccountManagement.css isn't referenced in adminAccountManagement.jsp. #3052

---

src/main/webapp/instructorHelp.html

Fixes #2338 
@LowWeiLin : Sir Kindly verify and instruct further steps.
Thanks

Inconsistent link text in instructor help page #2338

---

src/main/webapp/instructorHelp.html

Add more FAQs to instructor help #2336 

---

src/main/webapp/js/instructor.js

instructor session publish confirmation dialog: evaluation --> session #2929

---

src/main/webapp/jsp/studentFeedbackResults.jsp
src/test/resources/pages/studentFeedbackResultsPageCONSTSUM.html
src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html
src/test/resources/pages/studentFeedbackResultsPageMCQ.html
src/test/resources/pages/studentFeedbackResultsPageMSQ.html
src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html
src/test/resources/pages/studentFeedbackResultsPageOpen.html
src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html

Fixes #2283 
@LowWeiLin 
Sir,
I have closed the last pull request because it already contained the unrelated commit's from another issue. I have then updated my local repository again, and solved the stuff related to this issue. Kindly review and instrcut further steps for this request.
Thanks for the cooperation.

studentFeedbackResults: page title is given as 'submit feedback' #2283

---

src/test/resources/test.template.properties

Change misleading comment in test.template.properties #3037

---

src/test/testng.xml

Remove GodModeTest from AllTests #3073

---

src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java

NPE in InstructorFeedbackEditSaveAction #3039

---

src/main/java/teammates/ui/controller/Action.java

Add severe log in Action.java #3100

---

src/main/webapp/js/instructorSearch.js

 Instructor: Add a confirmation dialog to 'delete student' button #2902 

---

src/main/webapp/about.html

Added my name to multiple contributions section

---

src/main/webapp/js/feedbackSubmissionsEdit.js

Cannot click MCQ options when there are more than 10 team members #3110

---

src/main/java/teammates/ui/controller/InstructorStudentCommentAddAction.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseDetailsPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCourseDetailsPage.java

Fixed #3115 
cause: arbitrary assert_not_null for student email causes this problem.
test cases has been added to stop regression

 Instructor Unable to comment on all students in a given course #3115

---

src/main/java/teammates/ui/controller/FeedbackQuestionSubmissionEditSaveAction.java
src/main/webapp/jsp/feedbackQuestionSubmissionEdit.jsp
src/test/java/teammates/test/cases/ui/AllActionsAccessControlTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackQuestionSubmissionEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/StudentFeedbackQuestionSubmissionEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/FeedbackRubricQuestionUiTest.java
src/test/java/teammates/test/pageobjects/FeedbackQuestionSubmitPage.java
src/test/resources/data/FeedbackRubricQuestionUiTest.json
src/test/resources/pages/instructorFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageFilled.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageGracePeriod.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPagePrivate.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageDeadLineExceeded.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageFilled.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageOpen.html

Unable to submit Rubrics responses through feedbackQuestionSubmissionEdit #3053

---

src/main/webapp/js/instructor.js

instructor session unpublish confirmation dialog: evaluation --> session #3077

---

src/main/webapp/jsp/instructorFeedbackResultsByGiverQuestionRecipient.jsp
src/main/webapp/jsp/instructorFeedbackResultsByGiverRecipientQuestion.jsp
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsPageRubricGQRView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricGRQView.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html

InstructorFeedbackResultsPage: italicise text for giver with no responses #2832

---

src/main/java/teammates/ui/controller/Action.java

Add severe log in Action.java for legacy regkey #3135

---

src/main/webapp/jsp/adminAccountManagement.jsp
src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java

Instructor count includes testing accounts in adminAccountManagementPage #3050

---

src/main/webapp/jsp/instructorHeader.jsp

instructorHeader.jsp has redundant branches #2265

---

src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
src/main/webapp/js/adminActivityLog.js
src/main/webapp/jsp/adminActivityLog.jsp

auto-click search more button if no log found after maximum amount of logs per request have been searched #3090

---

src/main/java/teammates/common/datatransfer/FeedbackConstantSumQuestionDetails.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/resources/data/FeedbackSessionQuestionTypeTest.json
src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html

Statistics for Constant Sum question are rounded off in the csv file #3134

---

src/main/java/teammates/storage/api/EntitiesDb.java

EntitiesDb : condition checking of elapsedTime is better to use >= instead of ==   #1146

---

devdocs/settingUp.md

settingUp.md: Improve the instructions for getting join link for student login #3131

---

src/main/webapp/js/instructor.js

InstructorHomePage: remind all confirmation, change evaluations to feedback #3117

---

src/main/webapp/jsp/instructorStudentList.jsp
src/test/resources/pages/instructorStudentList.html
src/test/resources/pages/instructorStudentListPageDisplayArchivedCourses.html
src/test/resources/pages/instructorStudentListPageDisplayArchivedCoursesWithMoreOptions.html
src/test/resources/pages/instructorStudentListPageHideArchivedCourses.html
src/test/resources/pages/instructorStudentListPageHideArchivedCoursesWithMoreOptions.html
src/test/resources/pages/instructorStudentListPageLiveSearch.html
src/test/resources/pages/instructorStudentListPageNoStudent.html
src/test/resources/pages/instructorStudentListPageSearchShowEmail.html
src/test/resources/pages/instructorStudentListPageWithPicture.html
src/test/resources/pages/instructorStudentListWithHelperView.html
src/test/resources/pages/newlyJoinedInstructorStudentListPage.html

Fixes #2774
I changed the style of the "Enroll" button.
Before
After
Besides, I also changes all the test output files in the test driver so it can pass all the tests.

instructor>students tab : format the 'enroll' button differently #2774

---

README.md

Html guide link modified in README.md
Fixes #3166

Update the link to HTML style guide #3166

---

src/main/java/teammates/storage/entity/Student.java

Fixed #3183 
editted the description of courseID in Student.java
Signed-off-by: Chan Jun Wei <chanjunweimy@gmail.com>

In Student.java, the description of courseID is not correct #3183 

---

devdocs/process.md

 process.md: Remove remote myfork from Step 3 of fixing issues #3116

---

src/main/java/teammates/ui/controller/AdminEmailLogPageData.java
src/main/webapp/js/adminEmailLog.js
src/main/webapp/jsp/adminEmailLog.jsp

Add filter descriptions for 'Admin email log' page #3201

---

src/main/java/teammates/logic/automated/CompileLogs.java
src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java

reduce log reading #3207

---

src/main/java/teammates/common/datatransfer/FeedbackParticipantType.java
src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
src/test/resources/data/StudentFeedbackResultsPageUiTest.json
src/test/resources/pages/studentFeedbackResultsPageOpen.html
src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html

Responses to Giver's Team in studentFeedbackResultsPage cannot be seen #3228

---

src/main/webapp/dev/devman.html

Spelling mistakes of the word 'overview' in devman.html #3218

---

src/test/java/teammates/test/cases/ui/InstructorCoursesPageActionTest.java

reduntant code in InstructorCoursesPageActionTest.java #3213

---

src/main/webapp/js/feedbackResponseComments.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorCommentsPageUiTest.java
src/test/resources/data/InstructorCommentsPageUiTest.json
src/test/resources/pages/instructorCommentsPageForCourseWithURIEncodedSessionName.html

# in session name gives problems #3184

---

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java

Fixes #2547. Dev green. Also have tested publishing option on staging.

Results published email sent even if the option is unticked. #2547

---

src/main/webapp/about.html

Add my name (Shiluka Dharmasena) to contributors list

Add my name to contributors list

---

src/main/webapp/js/instructor.js

InstructorHomePage: change delete course confirmation message #3118

---

src/main/webapp/WEB-INF/classes/.gitignore
src/main/webapp/dev/mashup.jsp

Fixes #3234 
Mashup.jsp e-mails don't match MashupPageUiTest.json e-mails. This causes Entity Not Found errors on the mashup page.

Mashup.jsp fails to display Instructor Student pages #3234

---

src/main/webapp/js/instructorFeedbackEdit.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java

Infinite loop when editing NUMSCALE question #3193

---

src/main/java/teammates/common/datatransfer/CourseAttributes.java
src/main/java/teammates/storage/entity/Course.java
src/test/resources/data/InstructorHomePageUiTest3.json

Fixes #2923 
Dev green and ready for immediate review

InstructorHomePageUiTest fails on dev server #2923

---

src/main/java/teammates/ui/controller/StudentHomePageAction.java

Fixes #3259
Dev green and ready for immediate review

StudentHomePageUiTest fails often at persistence check #3259

---

src/main/webapp/jsp/instructorFeedbackResultsByRecipientGiverQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByRecipientQuestionGiver.jsp
src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html
src/test/resources/pages/instructorFeedbackResultsDeleteComment.html
src/test/resources/pages/instructorFeedbackResultsPageRubricRGQView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricRQGView.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html

InstructorFeedbackResults, RQG/RGQ view: no response texts are not italicized #3181

---

devdocs/settingUp.md

settingUp.md is missing JavaScript 4 spaces instructions #3271

---

src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionHelperView.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionB.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView1.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView2.html
src/test/resources/pages/instructorFeedbackResultsPageRubricQuestionView.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html

Fixes #3273
Dev green and ready for review.
I have made sure I have covered all the hash values in the guilty files by:
1. matching the number of instances of `studentemail={*}&courseid={*}&` in each file. each has to be equal to the number of lines of additions/deletions done. all matches.
2. matching the total line addition and deletion to the guilty commit (1433 deletions). matches as well.
can always refer to the guilty commit here: SHA: dc8e70e4260c4250f5a3e632f0d51af391c716b9

Test cases failing due to courseId and studentEmail hashes #3273

---

src/main/webapp/js/instructorFeedbackEdit.js

Add comments documenting why previousFormDataMap is declared outside and document following function #3268

---

src/main/webapp/js/instructorFeedbackEdit.js

Multiple global variables declared in instructorFeedbackEdit.js #3267

---

src/main/webapp/js/instructorFeedbackEdit.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java

Ensure at least one option in Distribute points (among options) question #3262

---

src/main/java/teammates/common/util/Sanitizer.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageData.java
src/main/webapp/js/common.js
src/main/webapp/js/feedbackSubmissionsEdit.js
src/main/webapp/jsp/feedbackSubmissionEdit.jsp
src/test/java/teammates/test/cases/common/SanitizerTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java
src/test/java/teammates/test/driver/HtmlHelper.java
src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java
src/test/javascript/CommonJsTest.js
src/test/resources/data/StudentFeedbackSubmitPageUiTest.json
src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
src/test/resources/pages/studentFeedbackSubmitPageModified.html
src/test/resources/pages/studentFeedbackSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html

Fixes #3204 
In feedbackSubmissionsEdit.js, the value of __curSelectedOption__ and __selectedOption__ may contain character ', which will make javascript confused.
for example: curSelectedOption = __team 1 '__
then the part __"option[value='"+curSelectedOption+"']"__ becomes __"option[value='team 1 '']"__

Name of receiver disappears #3204

---

src/main/java/teammates/storage/api/EntitiesDb.java
src/main/java/teammates/storage/api/EvaluationsDb.java
src/main/java/teammates/storage/api/InstructorsDb.java
src/main/java/teammates/storage/api/StudentsDb.java
src/main/java/teammates/ui/controller/InstructorStudentCommentClearPendingAction.java

Change the persistence delay log message to INFO level #3277

---

src/main/java/teammates/ui/controller/PageData.java

PageData: Wrong method documentation for "getInstructorFeedbackSessionActions:" #3154

---

src/main/webapp/jsp/instructorFeedbackEdit.jsp
src/test/resources/pages/NJIfeedbackSessionSuccessEdited.html
src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
src/test/resources/pages/instructorFeedbackEditCopyFail.html
src/test/resources/pages/instructorFeedbackEditCopyPage.html
src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html

Instructor edit feedback session: Rephrase "Who is giving feedback to whom?" #3297

---

src/main/webapp/js/feedbackSubmissionsEdit.js

Fixed #3112 
Only these 3 lines need to be changed. The other are for selecting/finding/affecting multiple HTML elements so no need to change them.
Dev green.

feedbackSubmissionEdit.js: Check and change jQuery selectors using partial match to exact match #3112

---

src/main/webapp/js/instructorFeedbackResults.js
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionHelperView.html

'Expand questions' button is not visible on InstructorFeedbackResultsPage if results are loaded by ajax #3300

---

src/main/webapp/jsp/instructorFeedbackResultsTop.jsp
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionHelperView.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html

Rephrase 'expand questions' tooltip for big datasets #2320

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java

InstructorFeedbackEditPageUiTest: Waiting for wrong WebElement #3305

---

src/main/webapp/about.html

Moved my name (Shiluka Dharmasena) from [One-time contributions] to [Multiple contributions]

Add my name 'Shiluka' to contributors list as a multiple contributor

---

src/test/resources/pages/login.html

AllAccessControlUiTests fails due to different number of feedback accumulated #3374

---

src/main/java/teammates/ui/controller/FeedbackSessionStatsPageAction.java
src/main/webapp/jsp/instructorFeedbackStats.jsp
src/test/java/teammates/test/cases/ui/FeedbackSessionStatsPageActionTest.java

Refinements include:
Minimal coding convention changes, this wasn't a very big slice so there is really nothing much to refine.
Java Side
. FeedbackSessionStatsPageAction.java
Java Servlet Side
. instructorFeedbackStats.jsp
Testing Side
. FeedbackSessionStatsPageActionTest.java

Refine FeedbackSessionStats Slice

---

src/main/webapp/js/instructorFeedbackEdit.js

Eval statement - ability to run any script instructorFeedbackEdit.js #3334

---

src/main/java/teammates/common/datatransfer/FeedbackConstantSumQuestionDetails.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java

 instructorResultDownload: constant sum summary section --> comma in student name splits into columns #2785

---

src/main/java/teammates/common/datatransfer/FeedbackMcqQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackMsqQuestionDetails.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java

Commas not sanitized in MSQ/MCQ summaries when downloaded #3381

---

src/main/webapp/jsp/instructorFeedbackResultsByGiverQuestionRecipient.jsp
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html

Change "Given Responses Statistics" to "Statistics for Given Responses" #3349

---

src/main/java/teammates/common/datatransfer/FeedbackRubricQuestionDetails.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java

Fixes #3382 
Uses the same table format as the HTML view.

 No summary statistics for rubric questions in downloaded csv #3382

---

src/main/webapp/about.html

Here is the link to my contributions: https://github.com/TEAMMATES/repo/issues?utf8=%E2%9C%93&q=assignee%3Aweaveranoop

Included Anoop Shukla in contributors names list

---

src/main/java/teammates/common/datatransfer/FeedbackConstantSumQuestionDetails.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/resources/data/FeedbackSessionQuestionTypeTest.json

Fixes #2851 .
Added teamName to the fragments  variable which gets added to the csv
variable

Add Team column to constant sum statistics in csv file #2851

---

src/main/java/teammates/client/scripts/DataMigrationForResponseRate.java

Update DataMigrationForResponseRate to only update sessions with zero response rate #3388

---

src/main/webapp/jsp/feedbackQuestionSubmissionEdit.jsp
src/main/webapp/jsp/feedbackSubmissionEdit.jsp
src/test/resources/pages/instructorFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageFilled.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageGracePeriod.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPagePrivate.html
src/test/resources/pages/instructorFeedbackSubmitPageFullyFilled.html
src/test/resources/pages/instructorFeedbackSubmitPageModified.html
src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageDeadLineExceeded.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageFilled.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
src/test/resources/pages/studentFeedbackSubmitPageModified.html
src/test/resources/pages/studentFeedbackSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html

Cannot see full respondent name in submitted responses #2990

---

src/main/java/teammates/client/scripts/AddSectionsToLargeCourses.java

Script to add sections to large courses with no sections #3396

---

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java

Fixes #2722
@imouto1994 has another branch that is fixing the same issue, but with a different approach.

studentHomePage is too slow to load when there are many sessions #2722

---

src/main/java/teammates/client/scripts/AddSectionsToLargeCourses.java

AddSectionsToLargeCourses is too slow #3402

---

src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageAction.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageData.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
src/main/webapp/jsp/feedbackSubmissionEdit.jsp
src/main/webapp/jsp/instructorFeedbackSubmissionEdit.jsp
src/main/webapp/jsp/studentFeedbackSubmissionEdit.jsp
src/test/java/teammates/test/cases/ui/InstructorFeedbackSubmissionEditPageActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackSubmissionEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/StudentFeedbackSubmissionEditPageActionTest.java
src/test/java/teammates/test/cases/ui/StudentFeedbackSubmissionEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackSubmitPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java
src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java
src/test/resources/pages/InstructorEditStudentFeedbackPageModified.html
src/test/resources/pages/InstructorEditStudentFeedbackPageOpen.html

Refinements to note:
. Investigated TODOS sprinkled around the files
. For TODOS that were not done, I've implemented them
. For TODOS that have already been done, I've removed them
. Removed related HTML/JSP problems by re-indenting to obviously show which block belongs to which branch
. Because of above, mis-aligned closing tags and opening tags are now easily spotted and fixed
. Added some comment(s) to tests to document what they're testing
. Added some comment(s) to tests that may test differently based on what browser is used to test and why they are passing correctly / failing correctly
. For tests that may pass or fail depending on browser being used, they have been disabled with comments describing why it has been disabled
Coverage status:
. All good and passing
. Exception: …

Refine FeedbackSubmissionEdit slice #3409

---

src/main/resources/InstructorSampleData.json
src/test/resources/pages/NJIstudentFeedbackResultsPage.html
src/test/resources/pages/NJIstudentFeedbackSubmissionEdit.html

fix #3413
changed values in the .json file
changed test outputs to pass the test suit

Invalid Contribution response data in instructorSampleData.json #3413

---

src/main/java/teammates/ui/controller/InstructorFeedbackPreviewAsInstructorAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackPreviewAsStudentAction.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackPreviewAsInstructorActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackPreviewAsStudentActionTest.java

Refinements to note:
. Formatting changes purely, this is a very small slice compared to the rest, it's Jsp etc. also rides on other slices so I'll leave the refinements for those to the other slices as refining those will automatically refine this
Coverage status:
. Already 100% except for the part where it is commented that it rarely happens, gatekeeper also usually handles it
. Dev green

Refine InstructorFeedbackPreview Slice #3420

---

src/main/java/teammates/common/datatransfer/UserType.java
src/main/java/teammates/logic/api/GateKeeper.java
src/main/java/teammates/ui/controller/InstructorCourseArchiveAction.java
src/main/java/teammates/ui/controller/InstructorEditStudentFeedbackPageAction.java
src/main/java/teammates/ui/controller/InstructorEditStudentFeedbackSaveAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentAddAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentDeleteAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentEditAction.java
src/test/java/teammates/test/cases/ui/InstructorCourseArchiveActionTest.java

refine InstructorCourseArchiveAction.java
refactor GateKeeper.java

refine InstructorCourseArchiveAction Slice

---

src/main/java/teammates/storage/entity/Instructor.java
src/main/java/teammates/ui/controller/Action.java
src/main/java/teammates/ui/controller/ActionResult.java
src/main/java/teammates/ui/controller/InstructorCourseAddAction.java
src/main/java/teammates/ui/controller/PageData.java
src/main/webapp/jsp/instructorCourseEdit.jsp
src/test/java/teammates/test/cases/ui/InstructorCourseAddActionTest.java
src/test/resources/data/typicalDataBundle.json

redo InstructorCourseAddAction Slice

refine InstructorCourseAddAction Slice

---

src/main/java/teammates/common/datatransfer/FeedbackQuestionBundle.java
src/main/java/teammates/common/exception/EnrollException.java
src/main/java/teammates/common/exception/EntityAlreadyExistsException.java
src/main/java/teammates/common/exception/EntityDoesNotExistException.java
src/main/java/teammates/common/exception/ExceedingRangeException.java
src/main/java/teammates/common/exception/InvalidParametersException.java
src/main/java/teammates/common/exception/JoinCourseException.java
src/main/java/teammates/common/exception/NotImplementedException.java
src/main/java/teammates/common/exception/NullPostParameterException.java
src/main/java/teammates/common/exception/PageNotFoundException.java
src/main/java/teammates/common/exception/TeammatesException.java
src/main/java/teammates/common/exception/UnauthorizedAccessException.java
src/main/java/teammates/ui/controller/InstructorFeedbackQuestionSubmissionEditPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackQuestionSubmissionEditSaveAction.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackQuestionSubmissionEditPageActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackQuestionSubmissionEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackQuestionSubmitPageUiTest.java
src/test/resources/data/typicalDataBundle.json

Refinements to note:
. Used modifyParamValue instead of magically changing param values in tests
. Investigated TODOS, done = removed, not done = done, tested in another form / area = removed
. Major formatting overhaul based on new 120 char guidelines
. Included all exceptions formatting refinements in this slice
. Before this slice refinement, instructor test was not actually testing an edit done in grace period, this refinement fixes that
Coverage status:
. Due to above where grace period was truly tested, test coverage was also slightly improved
. Areas whereby they are already taken care of by another entity or cannot be tested have had comments inserted

Refine InstructorFeedbackQuestionSubmission Slice #3439

---

src/main/java/teammates/common/datatransfer/CourseAttributes.java
src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/storage/api/CoursesDb.java
src/main/java/teammates/ui/controller/InstructorCourseDeleteAction.java
src/main/webapp/jsp/instructorCourses.jsp
src/test/java/teammates/test/cases/ui/InstructorCourseDeleteActionTest.java

refined CoursesLogic.java
refined CoursesDb.java
refined CourseAttributes
refined IntructorCourseDeleteAction
refined InstructorCourseDeleteActionTest
refined instructorCourses.jsp
The test has fully covered all the branches in IntructorCourseDeleteAction.java

refine IntructorCourseDeleteAction

---

src/main/java/teammates/common/datatransfer/StudentAttributes.java
src/main/java/teammates/common/util/StringHelper.java
src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/ui/controller/AjaxResult.java
src/main/java/teammates/ui/controller/InstructorCourseDetailsPageAction.java
src/test/java/teammates/test/cases/ui/InstructorCourseDetailsPageActionTest.java

refined Logic.java
refined StudentAttributes.java
refined StringHelper.java
refined AjaxResult.java
Refined InstructorCourseDetailsAction.java
Added a test case to fully cover all the branches in InstructorCourseDetailsAction.java

Refine InstructorCourseDetailsPageAction Slice

---

src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java

Fixes #3443, now it should work for both unix and windows machines

InstructorFeedbackResultsPageUiTest test failing line 272-273 #3443

---

src/test/java/teammates/test/cases/testdriver/BackDoorTest.java

Fixes #3463 
Fixed by simply waiting until BackDoor returns something other than "null".

Random NPE in BackDoorTest #3463

---

src/main/webapp/js/common.js

Fixes #3346 
Refer to the issue thread for explanation.

instructor view results: contribution question, giver column sorting is broken #3346

---

src/main/webapp/js/common.js
src/test/resources/pages/tableSort.html

Fixes #3468 
My bad for not ensuring dev green when merging #3466 before. It is dev green this time.

(URGENT) Fix for #3346 breaks TableSortTest #3468

---

src/main/java/teammates/client/scripts/DataMigrationForSearchableInstructors.java
src/main/java/teammates/client/scripts/DataMigrationForSearchableStudents.java
src/main/java/teammates/ui/controller/AdminEmailLogPageData.java
src/main/java/teammates/ui/controller/StudentCommentsPageData.java
src/test/java/teammates/test/util/FileHelper.java

Remove all TODO: Auto-generated method stub #3474

---

src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java

Fixes #3462 by waiting for the button to load (takes awhile via AJAX when we run entire test suite)

InstructorFeedbackPageUiTest test fail sometimes line 500 #3462

---

src/main/webapp/js/instructorCourseEdit.js
src/main/webapp/js/instructorCourseEditAjax.js
src/main/webapp/jsp/instructorCourseEdit.jsp
src/test/resources/pages/instructorCourseEdit.html
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditDeleteInstructorSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html

Refined all files related to the frontend of instructorCourseEditPageAction, including:
instructorCourseEdit.html
instructorCourseEdit.js
instructorCourseEdit.jsp
instructorCourseEditAjax.js
instructorCourseEditCoowner.html
instructorCourseEditDeleteInstructorSuccessful.html
instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
instructorCourseEditEditInstructorPrivilegesModal.html
instructorCourseEditEditInstructorPrivilegesSuccessful.html
instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
instructorCourseEditHelper.html
Dev green
The backend of this slice will be done in the next PR.

Refine frontend of instructorCourseEditPageAction slice

---

src/main/java/teammates/ui/controller/InstructorCourseEditPageAction.java
src/main/java/teammates/ui/controller/InstructorCourseEditPageData.java
src/test/java/teammates/test/cases/ui/InstructorCourseEditPageActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java

refined InstructorCourseEditPageAction.java
refined InstructorCourseEditPageData.java
refined InstructorCourseEditPageActionTest.java
refined InstructorCourseEditPageUiTest.java
removed an obsolete function in InstructorCourseEditPageData.java.
added a test case in InstructorCourseEditPageActionTest.java to fully cover the code.
dev green

refined backend of InstructorCourseEditPageAction slice

---

src/test/testng-new.xml

New testng config file #3491

---

src/main/java/teammates/client/scripts/AddSectionsToLargeCourses.java
src/main/java/teammates/client/scripts/ModifyInstituteOfStudentsInCourse.java
src/main/java/teammates/common/util/ActivityLogEntry.java
src/main/java/teammates/logic/automated/AdminEmailPrepareTaskQueueWorkerServlet.java
src/main/java/teammates/logic/core/AdminEmailsLogic.java
src/main/java/teammates/logic/core/InstructorsLogic.java
src/main/java/teammates/logic/core/StudentsLogic.java
src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java
src/main/java/teammates/ui/controller/AdminEmailGroupReceiverListUploadAction.java
src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java
src/test/java/teammates/test/cases/logic/CoursesLogicTest.java
src/test/java/teammates/test/cases/storage/ProfilesDbTest.java
src/test/java/teammates/test/cases/ui/StudentFeedbackResultsPageActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/AllAccessControlUiTests.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorSubmissionAdjustmentUiTest.java
src/test/java/teammates/test/pageobjects/InstructorStudentRecordsPage.java

Remove all Java Problems Marker Part 2 #3475

---

src/main/webapp/jsp/feedbackSubmissionEdit.jsp
src/main/webapp/jsp/instructorCourseStudentDetails.jsp
src/main/webapp/jsp/instructorFeedbackResultsByGiverQuestionRecipient.jsp
src/main/webapp/jsp/instructorFeedbackResultsByGiverRecipientQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByRecipientGiverQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByRecipientQuestionGiver.jsp
src/main/webapp/jsp/instructorStudentRecords.jsp
src/main/webapp/jsp/studentFeedbackResults.jsp
src/test/resources/pages/InstructorCourseStudentDetailsRegistered.html
src/test/resources/pages/InstructorEditStudentFeedbackPageModified.html
src/test/resources/pages/InstructorEditStudentFeedbackPageOpen.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/studentFeedbackResultsPageCONSTSUM.html
src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html
src/test/resources/pages/studentFeedbackResultsPageMCQ.html
src/test/resources/pages/studentFeedbackResultsPageMSQ.html
src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html
src/test/resources/pages/studentFeedbackResultsPageOpen.html
src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html

Fix question text-preserve-space indentation and add comments #3426

---

src/test/java/teammates/test/pageobjects/InstructorHomePage.java

InstructorHomePageUiTest line 329 sometimes fail #3515

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java

Fixes #3494, and the initial issue #2293

InstructorFeedbackPageUiTest can sometimes fail as per screenshot #3494

---

src/test/java/teammates/test/cases/ui/InstructorCourseDeleteActionTest.java
src/test/resources/pages/instructorHomeCourseDeleteSuccessful.html

refined instructorHomeCourseDeleteSuccessful.html
added test case to fully cover the code.

Refined frontend of InstructorCourseDeleteAction slice

---

src/main/webapp/js/instructorCourseDetails.js
src/main/webapp/jsp/instructorCourseDetails.jsp
src/main/webapp/jsp/studentCourseDetails.jsp
src/main/webapp/stylesheets/studentCourseDetails.css
src/test/javascript/InstructorCourseDetailsJsTest.js
src/test/resources/pages/InstructorCourseDetailsEmptyCourse.html
src/test/resources/pages/InstructorCourseDetailsWithSections.html
src/test/resources/pages/InstructorCourseDetailsWithSectionsWithHelperView.html
src/test/resources/pages/InstructorCourseDetailsWithoutSections.html
src/test/resources/pages/instructorCourseDetailsAddInstructor.html
src/test/resources/pages/instructorCourseDetailsStudentDeleteSuccessful.html
src/test/resources/pages/newlyJoinedInstructorCourseDetailsPage.html
src/test/resources/pages/studentCourseDetailsWithTeammatesHTML.html
src/test/resources/pages/studentCourseDetailsWithoutTeammatesHTML.html

Refined the following .html, .js, .jsp and .css files:
instructorCourseDetails.js
instructorCourseDetails.jsp
studentCourseDetails.jsp
studentCourseDetails.css
InstructorCourseDetailsJsTest.js
InstructorCourseDetailsEmptyCourse.html
InstructorCourseDetailsWithSections.html
InstructorCourseDetailsWithSectionsWithHelperView.html
InstructorCourseDetailsWithoutSections.html
instructorCourseDetailsAddInstructor.html
instructorCourseDetailsStudentDeleteSuccessful.html
newlyJoinedInstructorCourseDetailsPage.html
studentCourseDetailsWithTeammatesHTML.html
studentCourseDetailsWithoutTeammatesHTML.html
Deleted these empty files:
adminSearch.css
instructorEvalEdit-print.css
instructorEvalResults-print.css
instructorHome-print.css
studentCourseDetails-print.css

Refine frontend of InstructorCourseDetailsPageAction slice

---

src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java

waitForModalToLoad() can occasionally fail InstructorFeedbacksPage #3528

---

src/main/java/teammates/ui/controller/StudentHomePageAction.java
src/test/java/teammates/test/cases/ui/StudentHomePageActionTest.java

Refactored the backend
I will do the frontend in another pull request

Refine backend of StudentHomePageActionSlice

---

src/main/webapp/js/instructorFeedbackEdit.js

 Instructors: After saving a new question, scroll to the newly added question #3455

---

src/main/webapp/jsp/instructorFeedbacks.jsp
src/test/resources/pages/NJIfeedbackSessionPublished.html
src/test/resources/pages/NJIfeedbackSessionRemind.html
src/test/resources/pages/NJIfeedbackSessionUnpublished.html
src/test/resources/pages/instructorFeedbackAllSessionTypes.html
src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
src/test/resources/pages/instructorFeedbackDoneEditing.html
src/test/resources/pages/instructorFeedbackEditCopySuccess.html
src/test/resources/pages/instructorFeedbackEmptyAll.html
src/test/resources/pages/instructorFeedbackEmptySession.html
src/test/resources/pages/instructorFeedbackPublishSuccessful.html
src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
src/test/resources/pages/instructorFeedbacksAllSessionTypesWithHelperView.html
src/test/resources/pages/newlyJoinedInstructorFeedbacksPage.html

Split off from #3435
Covers only the JSP part of the InstructorFeedbacksAction slice.
The changes in the html files are due to the indentation.
Java: #3543 ; JS: #3542 
* Fixed indentation and followed coding standards.
* Updated tests where needed.
I will handle the JavaScript and Java changes in another PR since the JSP file has a lot of changes on account of its length.

Refine JSP of InstructorFeedbacksPageAction slice

---

src/main/webapp/js/ajaxResponseRate.js
src/main/webapp/js/instructorFeedbackAjaxRemindModal.js
src/main/webapp/js/instructorFeedbacks.js
src/main/webapp/js/instructorFeedbacksAjax.js

Covers only the JS part of the InstructorFeedbacksAction slice.
Dev green as of 09c82a8.
Java: #3543 ; JSP: #3521 
* Followed coding standards.
* Rewrote code which needed improvement in terms of clarity / efficiency.

Refine JS of InstructorFeedbacksPageAction slice

---

src/main/java/teammates/common/datatransfer/TeamDetailsBundle.java
src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/StudentsLogic.java
src/main/java/teammates/ui/controller/StudentCourseDetailsPageAction.java
src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
src/test/java/teammates/test/cases/ui/StudentCourseDetailsPageActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentCourseDetailsPageUiTest.java

refined StudentCourseDetailsPageAction.java
refined StudentCourseDetailsPageActionTest.java
refined StudentCourseDetailsPageUiTest.java
refined StudentCourseDetailsPageAction.java
Added getTeamForStudent function to StudentsLogic
Added a test case for the function

Refined backend of StudentCourseDetailsPageAction Slice

---

src/test/resources/pages/studentCourseJoinConfirmationHTML.html

Fixes #3499.
Tested and passed on the staging server.

StudentCourseJoinConfirmationPageUiTest is failing on live server #3499

---

src/main/java/teammates/logic/core/StudentsLogic.java

added SortByName function when getting a team details

AdminHomePageUiTest failing on line 264 #3547

---

src/main/java/teammates/common/datatransfer/FeedbackSessionAttributes.java
src/main/java/teammates/common/util/FeedbackSessionTemplates.java
src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/storage/api/EntitiesDb.java
src/main/java/teammates/storage/api/FeedbackQuestionsDb.java
src/main/java/teammates/ui/controller/InstructorFeedbackAddAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackCopyAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackDeleteAction.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackCopyActionTest.java

Split off from #3435
Covers the slices concerning adding / copying / deleting sessions.
Dev green as of 3a5d4c8.
* Fixed indentation, code format.
* Rewrote segments for readability / consistency.
* Removed unused / unneeded code.
* Updated tests where needed.
Should I continue on with their tests in this PR or handle it in another?
The front-end for this is in another slice.

Refine InstructorFeedbackAdd/Copy/DeleteAction Slice

---

src/main/webapp/js/instructorStudentRecords.js

InstructorStudentRecords fails on sessions with # or + #3555

---

README.md

Fixes #3533
Current version:
https://docs.google.com/document/d/17oo2cUDfcMeKGqjl1TKHNrqMEmW6L_QusFyRKGzH96I/pub?embedded=true

Update JavaScript Style Guide #3533

---

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/ui/controller/InstructorFeedbacksPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbacksPageData.java
src/test/java/teammates/test/cases/ui/InstructorFeedbacksPageActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java

Covers only the Java part of the InstructorFeedbacksAction slice.
Dev green as of 31b12cc.
JSP: #3521 ; JS: #3542 
* Edited according to coding standards.
* Removed unused methods.

Refine Java files of InstructorFeedbacksPageAction slice

---

src/main/java/teammates/common/datatransfer/CommentSearchResultBundle.java
src/test/resources/pages/instructorCommentsPageSearchNormal.html
src/test/resources/pages/instructorSearchPageSearchComments.html
src/test/resources/pages/instructorSearchPageSearchStudentComments.html

fixes #3562
Changed HashMap to TreeMap
Fixed output files

Unexpected order of Keys in HashMap #3562

---

src/main/java/teammates/ui/controller/InstructorFeedbackUnpublishAction.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackUnpublishActionTest.java

Refine InstructorFeedbackUnpublish Java Slice #3567

---

src/test/resources/pages/studentProfileEditDivExistingValues.html
src/test/resources/pages/studentProfilePageDefault.html
src/test/resources/pages/studentProfilePictureNotFound.html
src/test/resources/pages/studentProfilePictureStudentDoesNotExist.html
src/test/resources/pages/studentProfilePictureUnauthorized.html

This is part of one of my previous slices, where I manually refined the HTML files.

Refined StudentProfile HTML files with God mode

---

src/test/resources/data/StudentFeedbackResultsPageUiTest.json
src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html

Wrong giver in StudentFeedbackResultsPageUiTest.json #3576

---

src/main/webapp/js/student.js

Just a small portion of JavaScript refinement used in student pages, others that are shared by instructor and students have mostly been refined

Refine Student Specific JavaScript Slice #3579

---

src/main/webapp/js/additionalQuestionInfo.js

Just one file is additionally used and it still has console logs used for debugging purposes in it so I took the liberty of removing it

Refine StudentFeedbackResults Specific JavaScript Slice #3580

---

src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyAction.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackEditCopyActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackEditCopyPageActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackEditPageActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditCopyUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

Continuation of #3467.
General refactoring.
Dev green at b6eb73f.
Coverage is fine with only branches for things like race conditions or null checks missed.
I would like to ask if 2265689 and df354a2 should be done, though.

Refine Tests for InstructorFeedbackEdit/EditCopy Slices

---

src/test/java/teammates/test/cases/ui/InstructorFeedbackAddActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackCopyActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackDeleteActionTest.java

Continuation of #3502.
Mainly for coding style, with one additional test added in for invalid session name.
Coverage is fine with only branches for race conditions / null checks missed.

Refine Tests for InstructorFeedbackAdd/Copy/DeleteAction Slice

---

src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentEditAction.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackResponseCommentEditActionTest.java

Formatted style and added tests to improve test coverage

Refine InstructorFeedbackResponseCommentEditAction and its test

---

src/main/webapp/js/instructorFeedbacks.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java

InstructorFeedbacks: incorrect timezone #3585

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionHelperView.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionHelperView2.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html
src/test/resources/pages/instructorFeedbackResultsDeleteComment.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionB.html
src/test/resources/pages/instructorFeedbackResultsPageEmpty.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView1.html
src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView2.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html

Also one of my previous slices.

Refined InstructorFeedbackResults HTML files with God mode

---

src/main/java/teammates/ui/controller/StudentFeedbackResultsPageAction.java
src/main/java/teammates/ui/controller/StudentFeedbackResultsPageData.java
src/test/java/teammates/test/cases/ui/StudentFeedbackResultsPageActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackResultsPageUiTest.java

In here:
1. Code formatting
2. Improved code coverage
3. Removed TODOs (Implemented in this PR)
4. Inserted comments for parts as to why code isn't being covered (covered but a higher level entity but can be used as a safety net if higher level entity let it goes through which is not easily producible)

Refine StudentFeedbackResultsPageAction Java Slice #3578

---

README.md

Point JavaScript Style Guide to Teammates TEAM Google Drive File #3598

---

src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html

Part of #3588. Includes ConstSumOption, ConstSumRecipient, and Contrib. Wildcards all intact.

Refined Feedback...QuestionUiTest HTML files with God mode part 1

---

src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html

Part of #3588. Includes MCQ, MSQ, and NumScale. Wildcards all intact.

Refined Feedback...QuestionUiTest HTML files with God mode part 2

---

src/test/resources/pages/instructorFeedbackResultsPageRubricGQRView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricGRQView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricQuestionView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricRGQView.html
src/test/resources/pages/instructorFeedbackResultsPageRubricRQGView.html
src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
src/test/resources/pages/studentFeedbackResultsPageRubric.html
src/test/resources/pages/studentFeedbackSubmitPageRubricSuccess.html

Part of #3588. Includes Rubric only as there are many test files involved in Rubric alone. Wildcards all intact.

Refined Feedback...QuestionUiTest HTML files with God mode part 3

---

src/test/resources/pages/InstructorSearchPageSearchCommentsAsHelper.html
src/test/resources/pages/InstructorSearchPageSearchStudentsForStudent1.html
src/test/resources/pages/InstructorSearchPageSearchStudentsForStudent2.html
src/test/resources/pages/instructorSearchPageDefault.html
src/test/resources/pages/instructorSearchPageSearchComments.html
src/test/resources/pages/instructorSearchPageSearchFeedbackResponseComments.html
src/test/resources/pages/instructorSearchPageSearchNone.html
src/test/resources/pages/instructorSearchPageSearchStudentComments.html

Refined InstructorSearch HTML files with God mode

---

src/test/resources/pages/StudentHomeFeedbackDeletedHTML.html
src/test/resources/pages/StudentHomeHTML.html
src/test/resources/pages/StudentHomeHTMLEmpty.html
src/test/resources/pages/StudentHomeHTMLPersistenceCheck.html
src/test/resources/pages/StudentHomeTypicalHTML.html

Part of #3588. All wildcards intact.

Refined StudentHome HTML files with God mode

---

src/test/resources/pages/studentCommentsPageForStudent1.html
src/test/resources/pages/studentCommentsPageForStudent2.html
src/test/resources/pages/studentCommentsPageForStudent3.html

Refined StudentComments HTML files with God mode

---

src/test/resources/pages/studentCourseDetailsWithTeammatesHTML.html
src/test/resources/pages/studentCourseDetailsWithoutTeammatesHTML.html
src/test/resources/pages/studentCourseJoinConfirmationHTML.html

Part of #3588. Got wildcard in logout link which is already reverted back.

Refined StudentCourse HTML files with God mode

---

src/test/resources/pages/studentFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageDeadLineExceeded.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageFilled.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageClosed.html

Part of #3588. No wildcards affected.

Refined StudentFeedbackQuestionSubmit HTML files with God mode

---

src/test/resources/pages/instructorFeedbackEditCopyFail.html
src/test/resources/pages/instructorFeedbackEditCopyPage.html
src/test/resources/pages/instructorFeedbackEditCopySuccess.html

Part of #3588. All wildcards intact.

Refined InstructorFeedbackEditCopy HTML files with God mode

---

src/test/resources/pages/instructorFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageGracePeriod.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPagePrivate.html

Part of #3588. No wildcards affected.

Refined InstructorFeedbackQuestionSubmit HTML files with God mode

---

src/test/resources/pages/studentFeedbackResultsPageCONSTSUM.html
src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html
src/test/resources/pages/studentFeedbackResultsPageEmpty.html
src/test/resources/pages/studentFeedbackResultsPageMCQ.html
src/test/resources/pages/studentFeedbackResultsPageMSQ.html
src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html
src/test/resources/pages/studentFeedbackResultsPageOpen.html
src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html

Part of #3588. There are so many more deletions because the parts outside frameBodyWrapper (used in verifyHtmlMainContent) are all discarded. All important wildcards intact.

Refined StudentFeedbackResults HTML files with God mode

---

src/test/resources/pages/InstructorCourseDetailsEmptyCourse.html
src/test/resources/pages/InstructorCourseDetailsWithSections.html
src/test/resources/pages/InstructorCourseDetailsWithSectionsWithHelperView.html
src/test/resources/pages/InstructorCourseDetailsWithoutSections.html
src/test/resources/pages/InstructorCourseEnrollPage.html
src/test/resources/pages/InstructorCourseStudentDetailsRegisteredWithHelperView.html
src/test/resources/pages/InstructorCourseStudentDetailsUnregistered.html
src/test/resources/pages/InstructorCourseStudentEditPage.html
src/test/resources/pages/InstructorCourseStudentEditUnregisteredPage.html
src/test/resources/pages/instructorArchiveStatusNotAffected.html
src/test/resources/pages/instructorCourseDetailsStudentDeleteSuccessful.html
src/test/resources/pages/instructorCourseEnrollError.html
src/test/resources/pages/instructorCourseJoinConfirmationHTML.html
src/test/resources/pages/instructorCoursesAddDupIdFailed.html
src/test/resources/pages/instructorCoursesAddInvalidIdFailed.html
src/test/resources/pages/instructorCoursesAddMissingParamsFailed.html
src/test/resources/pages/instructorCoursesAddSuccessful.html
src/test/resources/pages/instructorCoursesArchiveSuccessful.html
src/test/resources/pages/instructorCoursesDeleteSuccessful.html
src/test/resources/pages/instructorCoursesMultipleCourses.html
src/test/resources/pages/instructorCoursesNoCourse.html
src/test/resources/pages/instructorCoursesUnarchiveSuccessful.html

Part of #3588. Not including InstructorCourseEdit HTML files because that group alone has ~6000 additions and ~6000 deletions. All wildcards intact.

Refined InstructorCourses HTML files with God mode

---

src/main/webapp/js/feedbackSubmissionsEdit.js

Refine InstructorFeedbackSubmissionEdit JavaScript Slice #3561

---

src/main/java/teammates/common/datatransfer/StudentAttributes.java
src/main/java/teammates/ui/controller/FeedbackQuestionSubmissionEditSaveAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackQuestionSubmissionEditSaveAction.java
src/main/java/teammates/ui/controller/StudentFeedbackQuestionSubmissionEditPageAction.java
src/main/java/teammates/ui/controller/StudentFeedbackQuestionSubmissionEditSaveAction.java
src/test/java/teammates/test/cases/ui/StudentFeedbackQuestionSubmissionEditPageActionTest.java
src/test/java/teammates/test/cases/ui/StudentFeedbackQuestionSubmissionEditSaveActionTest.java
src/test/resources/data/typicalDataBundle.json

Just the Java side, will split up the JavaScript side and the JSP side into two other PRs when dealing with the instructor side of things
In here:
1. Code formatting
2. Improved code coverage
3. Inserted comments for parts as to why code isn't being covered (acts as a safety net)
4. Removed an unused method from both the abstract class and it's subclasses

Refine StudentFeedbackQuestionSubmission Java Slice #3568

---

src/main/webapp/jsp/instructorCourseEdit.jsp
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html

fix #3606
fixed instructorCourseEdit.jsp and related HTML files

Extra '<' in instructorCourseEdit.jsp breaking 'View Details' modal #3606

---

src/main/java/teammates/common/datatransfer/StudentAttributesFactory.java
src/main/java/teammates/ui/controller/StudentFeedbackSubmissionEditPageAction.java
src/main/java/teammates/ui/controller/StudentFeedbackSubmissionEditSaveAction.java
src/test/java/teammates/test/cases/ui/StudentFeedbackSubmissionEditPageActionTest.java
src/test/java/teammates/test/cases/ui/StudentFeedbackSubmissionEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java
src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json

In here:
1. Code formatting
2. Improved code coverage 
3. Removed TODOs (already done or shouldn't be done / implemented in this PR)
4. Inserted comments for parts as to why code isn't being covered (covered but a higher level entity but can be used as a safety net if higher level entity let it goes through which is not easily producible)
5. Migrated test data to one that is catered for this for finer grain testing

Refine StudentFeedbackSubmissionEdit Java Slice #3573

---

src/test/resources/data/typicalDataBundle.json

InstructorHomePageActionTest randomly fails #3626

---

src/main/webapp/js/instructorStudentListAjax.js
src/test/resources/pages/instructorStudentList.html
src/test/resources/pages/instructorStudentListPageDisplayArchivedCourses.html
src/test/resources/pages/instructorStudentListPageHideArchivedCourses.html
src/test/resources/pages/instructorStudentListPageNoStudent.html
src/test/resources/pages/instructorStudentListPageWithPicture.html
src/test/resources/pages/instructorStudentListWithHelperView.html

Huge text chunk in instructorStudentList HTML files #3632

---

src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java
src/test/resources/data/StudentFeedbackResultsPageUiTest.json
src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html

Unable to anonymize team recipients for Numscale questions #2697

---

src/main/webapp/jsp/instructorComments.jsp
src/main/webapp/jsp/instructorFeedbackEdit.jsp
src/main/webapp/jsp/instructorStudentRecords.jsp
src/main/webapp/jsp/studentProfilePage.jsp
src/test/resources/pages/instructorFeedbackEditCopyFail.html
src/test/resources/pages/instructorFeedbackEditCopyPage.html
src/test/resources/pages/instructorFeedbackEditEmpty.html

Remove whitespace between textarea in instructorFeedbackEdit.jsp #3635

---

src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentsLoadAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentsLoadPageData.java

Added some minor style refinements

Refine InstructorFeedbackResponseCommentsLoad 

---

src/main/java/teammates/ui/controller/InstructorStudentCommentAddAction.java
src/test/java/teammates/test/cases/ui/InstructorStudentCommentAddActionTest.java

Formatted style and improved test coverage

Refine InstructorStudentCommentAddAction and its test

---

src/main/java/teammates/ui/controller/PageData.java
src/main/webapp/WEB-INF/tags/student/navBar.tag
src/main/webapp/WEB-INF/tags/student/studentPage.tag

Adds the generic page and navbar tags for the student side.

JSTL - Student generic pages

---

src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackSubmissionEditPageAction.java
src/main/java/teammates/ui/controller/StudentFeedbackSubmissionEditPageAction.java

Part of #3650. Applies to both Instructor and Student.

Suppress redundant queries in FeedbackSubmissionEditPageAction, part 1

---

src/main/webapp/dev/mashup.jsp

 Add intro to mashup.jsp #1743 

---

src/main/java/teammates/common/datatransfer/InstructorAttributes.java
src/main/java/teammates/common/datatransfer/StudentAttributes.java
src/main/java/teammates/ui/controller/StudentCourseDetailsPageAction.java
src/main/java/teammates/ui/controller/StudentCourseDetailsPageData.java
src/main/java/teammates/ui/template/StudentCourseDetailsPanel.java
src/main/webapp/WEB-INF/tags/student/courseDetails/displayDetails.tag
src/main/webapp/WEB-INF/tags/student/courseDetails/displayInstructors.tag
src/main/webapp/WEB-INF/tags/student/courseDetails/displayTeammates.tag
src/main/webapp/jsp/studentCourseDetails.jsp
src/test/java/teammates/test/cases/ui/StudentCourseDetailsPageActionTest.java

StudentCourseDetailsPage slice

JSTL student course details

---

src/main/java/teammates/common/util/FieldValidator.java
src/main/java/teammates/ui/controller/Action.java
src/test/java/teammates/test/cases/common/FieldValidatorTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentProfilePageUiTest.java

Fixes #3679 
AdminActivityLogPage also won't give problems anymore.
Haven't checked if there are other places with this vulnerability but since I fixed the core of the problem they should be fixed as well.

StudentProfilePage vulnerable to scripting #3679

---

src/main/webapp/jsp/instructorComments.jsp
src/test/resources/pages/instructorCommentsForTypicalCourseWithCommentsWithHelperView.html
src/test/resources/pages/instructorCommentsPageAddFrc.html
src/test/resources/pages/instructorCommentsPageDeleteFrc.html
src/test/resources/pages/instructorCommentsPageEditFrc.html
src/test/resources/pages/instructorCommentsPageForCourseWithURIEncodedSessionName.html
src/test/resources/pages/instructorCommentsPageForCourseWithoutComment.html
src/test/resources/pages/instructorCommentsPageForEmptyCourse.html
src/test/resources/pages/instructorCommentsPageForTypicalCourseWithComments.html
src/test/resources/pages/instructorCommentsPageShowCommentsForAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPrivate.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPublic.html
src/test/resources/pages/instructorCommentsPageShowCommentsForSessionCommentPanel.html
src/test/resources/pages/instructorCommentsPageShowCommentsForStudentCommentPanel.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAllStatus.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromOthers.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromYou.html
src/test/resources/pages/newlyJoinedInstructorCommentsPage.html

Fixes #3684
This one suffers the same plight as instructor home page, let's shift the search bar down on to the next line for now and open issues for both pages to fix them as seperate issues (aka create a specific page tag for them, not urgent since we're on the JSTL dev branch).
Also did these changes manually cause manual changes make the HTML change less and makes it easier to review.
Have also checked that this is dev green.

Too many variations of JSP pertaining to page body and body header (InstructorComments specific) #3684

---

src/main/webapp/jsp/instructorCourseEdit.jsp
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html

Too many variations of JSP pertaining to page body and body header (InstructorCourseEdit specific) #3685

---

src/main/webapp/WEB-INF/tags/bodyHeader.tag
src/main/webapp/WEB-INF/tags/page.tag

Change JSTL generic page tag(s) to be in line with standardized format #3720

---

src/main/webapp/js/instructorStudentRecords.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/java/teammates/test/pageobjects/InstructorStudentRecordsPage.java

Broken cancel button in InstructorStudentRecords comment edit #3733

---

src/main/webapp/WEB-INF/tags/page.tag
src/main/webapp/jsp/adminAccountDetails.jsp
src/main/webapp/jsp/adminAccountManagement.jsp
src/main/webapp/jsp/adminActivityLog.jsp
src/main/webapp/jsp/adminEmail.jsp
src/main/webapp/jsp/adminEmailLog.jsp
src/main/webapp/jsp/adminHome.jsp
src/main/webapp/jsp/adminSearch.jsp
src/main/webapp/jsp/adminSessions.jsp
src/main/webapp/jsp/instructorFeedbacks.jsp
src/test/resources/pages/InstructorHomeHTMLPersistenceCheck.html
src/test/resources/pages/instructorFeedbackEmptyAll.html
src/test/resources/pages/instructorSearchPageDefault.html

Fixes #3708
refer to #3708 for more details.

Consistency of including favicon, CSS, JavaScript etc. inside the HTML head tag across the board #3708

---

src/main/webapp/jsp/studentComments.jsp
src/main/webapp/jsp/studentCourseJoinConfirmation.jsp
src/main/webapp/jsp/studentFeedbackQuestionSubmissionEdit.jsp
src/main/webapp/jsp/studentFeedbackResults.jsp
src/main/webapp/jsp/studentFeedbackSubmissionEdit.jsp
src/main/webapp/jsp/studentHome.jsp
src/main/webapp/jsp/studentProfilePage.jsp
src/test/resources/pages/studentCommentsPageForStudent1.html
src/test/resources/pages/studentCourseJoinConfirmationHTML.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html

Consistency of including favicon, CSS, JavaScript etc. inside the HTML head tag across the board (Student Specific) #3739

---

src/main/webapp/jsp/instructorComments.jsp
src/test/resources/pages/instructorCommentsPageForEmptyCourse.html

Add back missing imports from some pages in JSTL-Dev #3761

---

src/main/webapp/WEB-INF/tags/instructor/search/commentsForStudentsSearchResults.tag
src/main/webapp/jsp/instructorSearch.jsp
src/test/resources/pages/InstructorSearchPageSearchCommentsAsHelper.html
src/test/resources/pages/InstructorSearchPageSearchStudentsForStudent1.html
src/test/resources/pages/InstructorSearchPageSearchStudentsForStudent2.html
src/test/resources/pages/instructorSearchPageDefault.html
src/test/resources/pages/instructorSearchPageSearchComments.html
src/test/resources/pages/instructorSearchPageSearchFeedbackResponseComments.html
src/test/resources/pages/instructorSearchPageSearchNone.html
src/test/resources/pages/instructorSearchPageSearchStudentComments.html

Fixes #3765 
Changes to HTML files
Instructor search page UI test passes now

Fix instructor search page ui test

---

src/main/java/teammates/ui/controller/InstructorStudentCommentClearPendingAction.java

Refine InstructorStudentCommentClearPendingAction

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/InstructorFeedbackRemindParticularStudentsPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackRemindParticularStudentsPageData.java
src/main/webapp/js/instructorFeedbackAjaxRemindModal.js
src/main/webapp/jsp/instructorFeedbackRemindModal.jsp
src/test/java/teammates/test/cases/ui/InstructorFeedbackRemindParticularStudentsPageActionTest.java

Give InstructorFeedbacks remind modal its own jsp #3757

---

src/main/webapp/jsp/adminAccountDetails.jsp
src/main/webapp/jsp/adminAccountManagement.jsp
src/main/webapp/jsp/adminActivityLog.jsp
src/main/webapp/jsp/adminEmail.jsp
src/main/webapp/jsp/adminEmailLog.jsp
src/main/webapp/jsp/adminHome.jsp
src/main/webapp/jsp/adminSearch.jsp
src/main/webapp/jsp/adminSessions.jsp
src/main/webapp/jsp/instructorFeedbacks.jsp
src/main/webapp/jsp/instructorHome.jsp
src/main/webapp/jsp/instructorSearch.jsp
src/test/resources/pages/InstructorHomeHTMLPersistenceCheck.html
src/test/resources/pages/instructorFeedbackEmptyAll.html
src/test/resources/pages/instructorSearchPageDefault.html

Fixes #3802 
The reason I singled this one out is because I faced conflicts when cherry-picking. It's because some of the improvements are done on the then-existing `page.tag` and the already-migrated .jsp files. For this reason also, I have to manually fix some of the .jsp files (Feedbacks, Home, and Search).
Now it's all resolved and standardized.

Minimize the surprise for master branch when JSTL-Dev is merged in, part 3b #3802

---

src/main/webapp/WEB-INF/tags/bodyFooter.tag
src/main/webapp/WEB-INF/tags/page.tag
src/test/resources/pages/InstructorHomeHTMLPersistenceCheck.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html

Standardises the footer to always show, and hide only the institution in the middle if the user does not have one.
Anyone, review, please.

JSTL - Always show footer without institution for unregistered users

---

src/main/webapp/jsp/instructorHome.jsp
src/test/resources/pages/InstructorHomeHTMLPersistenceCheck.html

Fixes #3816 
JSTL equivalent: #3815

 Inconsistent showing of footer for unregistered users. #3816

---

src/main/webapp/WEB-INF/tags/instructor/instructorPage.tag
src/main/webapp/WEB-INF/tags/instructor/instructorPageCustom.tag
src/main/webapp/WEB-INF/tags/page.tag
src/main/webapp/WEB-INF/tags/student/studentPage.tag
src/main/webapp/WEB-INF/tags/student/studentPageCustom.tag

Adds 2 tags (for instructor / student) that allows pages to change the navigation bar and body footer.

JSTL - Tags for optional navigation bar / body footer

---

src/main/webapp/WEB-INF/tags/student/studentMessageOfTheDay.tag

@taniach could you take a look at this, you're going to need it for your PRs at #3754 and #3760

JSTL - Student Message of the Day

---

src/main/java/teammates/ui/controller/Action.java
src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
src/main/java/teammates/ui/controller/AdminEmailCreateGroupReceiverListUploadUrlAction.java
src/main/java/teammates/ui/controller/AdminEmailCreateImageUploadUrlAction.java
src/main/java/teammates/ui/controller/AdminEmailGroupReceiverListUploadAction.java
src/main/java/teammates/ui/controller/AdminEmailImageUploadAction.java
src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java
src/main/java/teammates/ui/controller/AdminStudentGoogleIdResetAction.java
src/main/java/teammates/ui/controller/AjaxResult.java
src/main/java/teammates/ui/controller/FeedbackSessionStatsPageAction.java
src/main/java/teammates/ui/controller/InstructorCourseDetailsPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackQuestionVisibilityMessageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentAddAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentDeleteAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentEditAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageAction.java
src/main/java/teammates/ui/controller/StudentProfileCreateFormUrlAction.java
src/test/java/teammates/test/cases/ui/FeedbackSessionStatsPageActionTest.java
src/test/java/teammates/test/cases/ui/InstructorCourseDetailsPageActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackResultsPageActionTest.java

Remove destination parameter in AjaxResult #3834

---

src/main/java/teammates/ui/controller/InstructorHomePageData.java
src/main/java/teammates/ui/controller/StudentHomePageData.java
src/main/java/teammates/ui/template/CourseTable.java
src/main/java/teammates/ui/template/StudentFeedbackSessionActions.java
src/main/webapp/WEB-INF/tags/student/home/courseTable.tag
src/test/java/teammates/test/cases/ui/pagedata/StudentHomePageDataTest.java

Fixes #3823 
@yj-soh there you go

Migrate StudentHome page actions to its own template file #3823

---

src/main/webapp/jsp/studentProfilePage.jsp
src/test/resources/pages/instructorStudentListPageSearchNoMatch.html
src/test/resources/pages/studentFeedbackResultsPageEmpty.html
src/test/resources/pages/studentProfilePageDefault.html

Fixes #3841 
Confirmed JSTL green. Someone just need to quickly review this, set it as toMerge, and I will merge it (or maybe that someone can just merge it him/herself).

Ensure JSTL green again #3841

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/resources/pages/instructorFeedbackEditManuallyPublished.html

InstructorFeedbackEditPageUiTest line 155 commented out #3818

---

src/main/webapp/about.html

Add an acknowledgement section to the about.html page #3830

---

src/main/webapp/js/datepicker.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java

instructor feedback edit: changing the 'close time' changes the start time automatically #3692

---

src/main/java/teammates/ui/controller/InstructorCourseJoinAction.java
src/main/java/teammates/ui/controller/InstructorCourseJoinConfirmationPageData.java
src/main/webapp/WEB-INF/tags/bodyHeader.tag
src/main/webapp/jsp/instructorCourseJoinConfirmation.jsp
src/test/java/teammates/test/cases/ui/pagedata/InstructorCourseJoinConfirmationPageDataTest.java
src/test/resources/pages/instructorCourseJoinConfirmationHTML.html

I'm so happy again. These last jsp files of the Course are quite short.
@yj-soh please review this as well.

JSTL - InstructorCourseJoinConfirmationPage

---

src/main/java/teammates/common/datatransfer/StudentAttributes.java
src/main/java/teammates/ui/controller/InstructorCourseEnrollPageAction.java
src/main/java/teammates/ui/controller/InstructorCourseEnrollPageData.java
src/main/java/teammates/ui/controller/InstructorCourseEnrollResultPageData.java
src/main/java/teammates/ui/controller/InstructorCourseEnrollSaveAction.java
src/main/java/teammates/ui/template/EnrollResultPanel.java
src/main/webapp/jsp/instructorCourseEnroll.jsp
src/main/webapp/jsp/instructorCourseEnrollResult.jsp
src/test/java/teammates/test/cases/ui/InstructorCourseEnrollPageActionTest.java
src/test/java/teammates/test/cases/ui/InstructorCourseEnrollSaveActionTest.java
src/test/java/teammates/test/cases/ui/pagedata/InstructorCourseEnrollPageDataTest.java
src/test/java/teammates/test/cases/ui/pagedata/InstructorCourseEnrollResultPageDataTest.java
src/test/resources/pages/instructorCourseEnrollError.html

I'm so happy when doing this one.
@yj-soh Could you review it as soon as possible? I need this for the next JSTL.

JSTL - InstructorCourseEnrollPage

---

src/test/resources/pages/instructorCourseJoinConfirmationHTML.html

Used {$test.instructor} in the output file

Fixed output file of InstructorCourseJoinConfirmationPage

---

src/main/webapp/dev/mashup.jsp
src/main/webapp/js/adminSearch.js
src/main/webapp/js/common.js
src/main/webapp/js/instructor.js
src/main/webapp/js/instructorStudentListAjax.js
src/main/webapp/js/student.js
src/test/resources/pages/instructorCourseJoinConfirmationHTML.html

Move tool-tipping function into common.js #3858

---

src/main/webapp/js/instructorFeedbacks.js

Prefix jQuery wrapped objects with $ in instructorFeedbacks.js #3798

---

src/test/java/teammates/test/cases/ui/pagedata/InstructorCourseStudentDetailsEditPageDataTest.java
src/test/java/teammates/test/cases/ui/pagedata/InstructorCourseStudentDetailsPageDataTest.java
src/test/resources/pages/InstructorCourseStudentEditPage.html

JSTL - *PageDataTest for InstructorCourseStudentDetails (+Edit)

---

src/main/webapp/jsp/instructorStudentRecordsAjax.jsp
src/test/resources/pages/instructorStudentRecords.html
src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html

Fixes #3855 
@kanghj I think other than me you're the one who'll want this to be merged quick so I'm assigning this to you

Standardize feedback response divs #3855

---

src/main/webapp/jsp/instructorFeedbackResponseCommentsAdd.jsp
src/main/webapp/jsp/instructorFeedbackResponseCommentsLoad.jsp
src/main/webapp/jsp/instructorSearch.jsp
src/main/webapp/jsp/studentComments.jsp
src/test/resources/pages/instructorCommentsPageAddFrc.html
src/test/resources/pages/instructorCommentsPageDeleteFrc.html
src/test/resources/pages/instructorCommentsPageEditFrc.html
src/test/resources/pages/instructorCommentsPageForCourseWithURIEncodedSessionName.html
src/test/resources/pages/instructorCommentsPageForTypicalCourseWithComments.html
src/test/resources/pages/instructorCommentsPageSearchNormal.html
src/test/resources/pages/instructorCommentsPageShowCommentsForAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPrivate.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPublic.html
src/test/resources/pages/instructorCommentsPageShowCommentsForSessionCommentPanel.html
src/test/resources/pages/instructorCommentsPageShowCommentsForStudentCommentPanel.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAllStatus.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromOthers.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromYou.html
src/test/resources/pages/instructorFeedbackResultsAddComment.html
src/test/resources/pages/instructorSearchPageSearchComments.html
src/test/resources/pages/instructorSearchPageSearchFeedbackResponseComments.html
src/test/resources/pages/studentCommentsPageForStudent1.html
src/test/resources/pages/studentCommentsPageForStudent2.html
src/test/resources/pages/studentCommentsPageForStudent3.html

Missing FRC whitespace standardization #3892

---

src/main/java/teammates/ui/controller/InstructorSearchPageData.java
src/main/java/teammates/ui/controller/StudentFeedbackResultsPageData.java
src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java
src/main/java/teammates/ui/template/StudentFeedbackResultsResponseComment.java
src/main/webapp/WEB-INF/tags/instructor/search/feedbackResponseComment.tag
src/main/webapp/WEB-INF/tags/student/feedbackResults/response.tag
src/test/resources/pages/instructorCommentsPageSearchNormal.html

JSTL-Dev is currently _not_ green. This fix is necessary to make it green.
If somebody is willing to review.

Fix JSTL-Dev due to FRC standardization

---

src/main/webapp/jsp/instructorStudentRecordsAjax.jsp
src/test/resources/pages/instructorStudentRecords.html
src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html

Fixes #3896
@kanghj you're the one most advantaged by this PR (even more so than myself I guess), so you can review :p

Standardize some parts of RecordsAjax for migration #3896

---

src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/test/resources/data/StudentFeedbackResultsPageUiTest.json
src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html
src/test/resources/pages/studentFeedbackResultsPageOpen.html
src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html

Fix #3833
@junhaoyap Could you take a look at this.

StudentFeedbackPageUiTest line 109 fails occasionally #3833

---

src/main/java/teammates/ui/template/ElementTag.java
src/main/webapp/WEB-INF/tags/instructor/course/activeCoursesTable.tag
src/main/webapp/WEB-INF/tags/instructor/course/archivedCoursesTable.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseEditAddInstructorPanel.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseEditCourseInfo.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorListPanelHeading.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseEditTunePermissionsDivForInstructor.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseEditTuneSectionPermissionsDiv.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseEditTuneSessionPermissionsDiv.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseInformationContainer.tag
src/main/webapp/WEB-INF/tags/instructor/course/studentInformationButtons.tag
src/main/webapp/WEB-INF/tags/instructor/course/studentsTable.tag
src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag
src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/previewSessionForm.tag
src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionEditForm.tag
src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionFeedbackPathSettings.tag
src/main/webapp/WEB-INF/tags/instructor/feedbacks/copyFromModal.tag
src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsForm.tag
src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsFormAdditionalSettings.tag
src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsFormHeader.tag
src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsTable.tag
src/main/webapp/WEB-INF/tags/instructor/home/coursePanel.tag
src/main/webapp/WEB-INF/tags/instructor/search/commentsForStudentsSearchResults.tag
src/main/webapp/WEB-INF/tags/student/home/coursePanel.tag

 Repetition of forEach for ElementTag attributes #3905

---

src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java

 InstructorFeedbackPageuUiTest unstable at line 866. #3808

---

src/main/webapp/js/feedbackResponseComments.js

Multiple setTimeOut in feedbackResponseComments.js slows down the AJAX #3925

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditCopyUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentHomePageUiTest.java
src/test/java/teammates/test/driver/TestProperties.java
src/test/java/teammates/test/pageobjects/AdminAccountDetailsPage.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java
src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java
src/test/java/teammates/test/pageobjects/InstructorHomePage.java
src/test/java/teammates/test/pageobjects/StudentProfilePage.java
src/test/resources/test.template.properties

Fixes #3934 
I tried running the full test suite and it passes without any problem (sadly not straight green), the timing also remains more or less the same despite the longer timeout (15 seconds standardized).

Control the test timeout values from test.properties #3934

---

src/main/java/teammates/common/util/Sanitizer.java
src/main/java/teammates/common/util/Url.java

I was doing #3811 and my first stop was `Url.java`. This class really needs some good ol' refinement.

Refine Url.java

---

devdocs/settingUp.md

Have a tiny bit more information about where in Preferences they can go to to add the SDK.

Instructions for setting up can be slightly confusing #3960

---

src/main/webapp/jsp/instructorStudentRecords.jsp
src/test/resources/pages/instructorStudentRecords.html
src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html
src/test/resources/pages/instructorStudentRecordsPageNoRecords.html
src/test/resources/pages/instructorStudentRecordsPageWithPrivateFeedback.html
src/test/resources/pages/instructorStudentRecordsWithHelperView.html

Flawed logic in InstructorStudentRecords comment visibility for recipient's section #3948

---

src/main/webapp/js/instructorCourseEdit.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html

Fix #3915
@kanghj hope you dont mind xD

instructorCourseEditPage: custom access-level should display a default configuration #3915

---

src/main/java/teammates/ui/template/CourseEditInstructorPanel.java
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html

Fixed #3946
@yj-soh could you review this PR?

Custom role gives all privileges when adding a new instructor #3946

---

src/main/webapp/js/instructorStudentRecords.js
src/main/webapp/jsp/instructorStudentRecords.jsp
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java
src/test/resources/pages/instructorStudentRecords.html
src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html
src/test/resources/pages/instructorStudentRecordsPageNoRecords.html
src/test/resources/pages/instructorStudentRecordsPageWithPrivateFeedback.html
src/test/resources/pages/instructorStudentRecordsWithHelperView.html

And yet another testimonial on how unstandardized things are...
I can guarantee this is the last standardization needed for this slice because I've managed to do the migration (the ones that reuse existing stuffs, at least) on top of this branch.

Modification of InstructorStudentRecords before JSTL migration

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyPageData.java
src/main/webapp/js/instructor.js
src/main/webapp/jsp/instructorFeedbackCopyModal.jsp
src/test/java/teammates/test/cases/ui/InstructorFeedbackEditCopyActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorHomePage.java
src/test/resources/pages/instructorFeedbackEditCopyPage.html

InstructorFeedbacks: a failure to copy a feedback session should not redirect the user #3919

---

src/main/java/teammates/ui/controller/AdminHomePageData.java
src/main/webapp/WEB-INF/tags/admin/adminPage.tag
src/main/webapp/WEB-INF/tags/admin/home/adminCreateInstructorAccountForm.tag
src/main/webapp/WEB-INF/tags/admin/home/adminHomePageForm.tag
src/main/webapp/WEB-INF/tags/admin/navBar.tag
src/main/webapp/jsp/adminHome.jsp
src/test/java/teammates/test/cases/ui/pagedata/AdminHomePageDataTest.java

Created adminPage.tag
Cherry-picked navBar.tag commits from JSTL-AdminAccountDetailsPage

JSTL-AdminHomePage

---

src/main/webapp/jsp/adminHome.jsp

Remove jQuery file paths from jsIncludes in adminHome.jsp #4012

---

src/main/java/teammates/common/util/Const.java
src/main/webapp/WEB-INF/tags/instructor/home/search.tag
src/test/resources/pages/InstructorHomeHTML.html
src/test/resources/pages/InstructorHomeHTMLEmpty.html
src/test/resources/pages/InstructorHomeHTMLPersistenceCheck.html
src/test/resources/pages/InstructorHomeHTMLResponseRateFail.html
src/test/resources/pages/InstructorHomeHTMLSortByDate.html
src/test/resources/pages/InstructorHomeHTMLSortById.html
src/test/resources/pages/InstructorHomeHTMLSortByName.html
src/test/resources/pages/InstructorHomeHTMLWithHelperView.html
src/test/resources/pages/InstructorHomeNewInstructorWithSampleCourse.html
src/test/resources/pages/InstructorHomeNewInstructorWithoutSampleCourse.html
src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
src/test/resources/pages/instructorHomeCourseDeleteSuccessful.html
src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
src/test/resources/pages/instructorStudentList.html
src/test/resources/pages/instructorStudentListPageDisplayArchivedCourses.html
src/test/resources/pages/instructorStudentListPageHideArchivedCourses.html
src/test/resources/pages/instructorStudentListPageNoCourse.html
src/test/resources/pages/instructorStudentListPageNoStudent.html
src/test/resources/pages/instructorStudentListPageWithPicture.html
src/test/resources/pages/instructorStudentListWithHelperView.html
src/test/resources/pages/newlyJoinedInstructorHomePage.html
src/test/resources/pages/newlyJoinedInstructorHomePageSampleCourseArchived.html
src/test/resources/pages/newlyJoinedInstructorStudentListPage.html

Updated the HTML in test cases as well
fixes #2353

 tooltip and placeholder for search bar in InstructorStudentList need to be changed #2353 

---

src/main/webapp/js/feedbackSubmissionsEdit.js

feedbackSubmissionsEdit.js: prepareContribQuestions and prepareMSQQuestions matching wrong elements #4009

---

src/main/java/teammates/common/datatransfer/FeedbackSessionResponseStatus.java
src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
src/main/java/teammates/ui/template/InstructorFeedbackResultsNoResponsePanel.java
src/main/webapp/WEB-INF/tags/instructor/results/noResponsePanel.tag
src/main/webapp/jsp/instructorFeedbackResultsBottom.jsp
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperOne.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperTwo.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html

resultsBottom.jsp with tags and JSTL.
Can and should be further improved after we finalise how the `*PageData` is going to be.
Changes to HTML files:
* Unnecessary whitespace in a class attribute
Only assigned to you, @kanghj, since it's your branch.
If you want someone else to review, just change it.

JSTL - Instructor Feedback Results, resultsBottom

---

src/test/java/teammates/test/cases/ui/browsertests/AdminSearchPageUiTest.java
src/test/java/teammates/test/pageobjects/AdminSearchPage.java
src/test/resources/pages/adminSearchPageDefault.html
src/test/resources/pages/adminSearchPageSearchNone.html
src/test/resources/pages/adminSearchPageSearchStudent1.html

I used a wildcard for the table contents. Please run the test and check that it passes on your computer.

AdminSearchPageUiTest

---

src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java
src/test/resources/pages/adminHomePageCreateInstructorSuccess.html

Added verify html for create instructor success

AdminHomePageCreateInstructorUiTest

---

src/main/java/teammates/common/util/ActivityLogEntry.java
src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java
src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java
src/test/resources/pages/adminActivityLogPage.html

Due to the fact that the number of logs is different from each time running the test, I only check the UI of the first log and apply the wildcard {*} for the rest. Please check the HTML file. @kanghj

JSTL - AdminActivityLogPageUiTest

---

src/test/java/teammates/test/cases/ui/browsertests/AdminEmailLogPageUiTest.java
src/test/java/teammates/test/pageobjects/AdminEmailLogPage.java
src/test/resources/pages/adminEmailLogPage.html

Added UI test for AdminEmailLogPage
In HTML output, I replace the entire table body by the wildcard and test the rest.

JSTL-AdminEmailLogPageUiTest

---

src/main/webapp/js/instructor.js

Fix #3175
Now it looks like this when loading

Null course ID in InstructorFeedbackEditCopyAction #3175

---

src/main/webapp/WEB-INF/tags/admin/activity/filterPanel.tag
src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/copyQuestionModal.tag
src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionEditForm.tag
src/main/webapp/WEB-INF/tags/instructor/feedbacks/copyFromModal.tag
src/main/webapp/WEB-INF/tags/instructor/moreInfo.tag
src/main/webapp/WEB-INF/tags/shared/feedbackResponseComment.tag
src/main/webapp/WEB-INF/tags/student/feedbackResults/questionWithResponses.tag
src/main/webapp/WEB-INF/tags/student/feedbackResults/response.tag
src/main/webapp/WEB-INF/tags/student/feedbackSubmissionEdit/feedbackSessionDetailsPanel.tag
src/main/webapp/WEB-INF/tags/student/feedbackSubmissionEdit/questionWithResponses.tag
src/main/webapp/WEB-INF/tags/student/profile/studentProfileDiv.tag
src/main/webapp/WEB-INF/tags/student/profile/uploadPhotoModal.tag
src/main/webapp/WEB-INF/tags/student/studentMessageOfTheDay.tag
src/main/webapp/jsp/studentCourseDetails.jsp
src/test/resources/pages/InstructorCourseStudentDetailsRegistered.html
src/test/resources/pages/instructorFeedbackEditEmpty.html
src/test/resources/pages/instructorFeedbackEditManuallyPublished.html
src/test/resources/pages/instructorFeedbackEmptyAll.html
src/test/resources/pages/instructorFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/instructorFeedbackSubmitPageAwaiting.html
src/test/resources/pages/studentCommentsPageForStudent1.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageAwaiting.html
src/test/resources/pages/studentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html
src/test/resources/pages/studentProfilePageDefault.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html

Fixes #4031 
@JosephineKwa this shouldn't be hard, hope you don't mind reviewing!

Change HTML comments to JSP comments in tags/jsp files #4031

---

src/main/webapp/js/feedbackSubmissionsEdit.js

Fixes #3878 
@kanghj your favorite PR to review -- short and sweet.

Replace jQuery.fn.reverse with an existing jQuery function #3878

---

src/main/webapp/js/common.js

Fixes #3877 
@bamboo3250 should be easy to review :D

Replace Element.prototype.documentOffSetTop with jQuery's offset #3877

---

src/test/java/teammates/test/cases/ui/browsertests/AdminSessionsPageUiTest.java
src/test/java/teammates/test/pageobjects/AdminSessionsPage.java
src/test/resources/pages/adminSessionsPage.html
src/test/resources/pages/adminSessionsPageHideFilter.html
src/test/resources/pages/adminSessionsPageShowFilter.html

Used wild cards for the filter dates, table contents and table count.

AdminSessionsPageUiTest

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java
src/test/resources/data/InstructorCourseEditPageUiTest.json
src/test/resources/pages/instructorCourseDetailsAddInstructor.html
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/instructorCourseEditManager.html
src/test/resources/pages/instructorCourseEditObserver.html
src/test/resources/pages/instructorCourseEditTutor.html

Improve InstructorCourseEditPageUITest #3943

---

src/main/java/teammates/common/datatransfer/CommentAttributes.java
src/main/java/teammates/common/util/Const.java
src/main/java/teammates/common/util/TimeHelper.java
src/main/java/teammates/ui/template/Comment.java

COMMENTS_SIMPLE_DATE_FORMATTER will mess date display or break down page #4055

---

src/main/java/teammates/ui/controller/InstructorCommentsPageData.java
src/main/java/teammates/ui/controller/PageData.java
src/main/java/teammates/ui/controller/StudentCommentsPageData.java
src/test/java/teammates/test/cases/ui/pagedata/StudentCommentsPageDataTest.java

Move getRecipientNames() from *CommentsPageData to PageData #4039

---

src/main/webapp/WEB-INF/tags/instructor/results/questionPanel.tag
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionB.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsPageOpenViewForHelperOne.html
src/test/resources/pages/instructorFeedbackResultsPageOpenViewForHelperTwo.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestion.html
src/test/resources/pages/newlyJoinedInstructorFeedbackResultsPage.html

Fixes #4046
instructorFeedbackResultsSortQuestion.html, instructorFeedbackResultsPageOpen.html, and instructorFeedbackResultsSortQuestionSearch.html were edited manually. The rest are by godmode. I will probably just godmode those 3 files after review.

Show missing response rows instead of an empty table #4046

---

src/main/webapp/js/datepicker.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

datepicker.js: variables are not initialised correctly #3714

---

src/main/webapp/js/instructorFeedbackResults.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java

InstructorResultsPage: "Collapse" button isn't working for participants without responses #4073

---

src/test/java/teammates/test/driver/HtmlHelper.java

StudentFeedbackSubmitPageUiTest is failing due to MOTD #4087

---

devdocs/process.md

Update dev docs to mention new convention for branch names #4084

---

src/test/resources/pages/instructorFeedbackResultsAddComment.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperOne.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperTwo.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html
src/test/resources/pages/instructorFeedbackResultsDeleteComment.html
src/test/resources/pages/instructorFeedbackResultsPageEmpty.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientGiverQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientGiverQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiverTeam.html

Fixes #4088 
Regenerated the InstructorFeedbackResultsPageUiTest's html files by godmode, which automatically handles conversion of hashes and dates into wildcards.

InstructorFeedbackResultsPageUiTest failing due to profile pic #4088

---

src/main/webapp/js/feedbackSubmissionsEdit.js
src/main/webapp/js/instructorCourseEdit.js
src/main/webapp/js/instructorCourseEditAjax.js
src/main/webapp/js/instructorFeedbackEdit.js
src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.js
src/main/webapp/js/instructorFeedbackResultsAjaxByGRQ.js
src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.js
src/main/webapp/js/instructorFeedbackResultsAjaxByRGQ.js
src/main/webapp/js/instructorFeedbackResultsAjaxByRQG.js
src/main/webapp/js/instructorFeedbackResultsAjaxResponseRate.js
src/main/webapp/js/instructorFeedbacksAjax.js
src/main/webapp/js/instructorHome.js
src/main/webapp/js/instructorStudentListAjax.js
src/main/webapp/js/studentMotd.js

Remove unnecessary console.logs from JS files #4072

---

src/main/webapp/WEB-INF/tags/instructor/course/commentArea.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseInformationContainer.tag
src/main/webapp/WEB-INF/tags/instructor/courseStudentDetails/studentInformationTable.tag
src/main/webapp/WEB-INF/tags/shared/comment.tag
src/main/webapp/WEB-INF/tags/shared/commentsPanel.tag
src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentForm.tag
src/main/webapp/instructorHelp.html

Title should not be data-original on our HTML template #3983

---

src/main/java/teammates/common/util/Const.java
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperOne.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperTwo.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html

Rephrase error message when too many responses. #4097

---

src/test/java/teammates/test/pageobjects/AppPage.java

Fixes #4100 
@kanghj after reviewing, you can just merge this.

Update godmode's replaceAll to follow new ${version} convention #4100

---

src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java

Remove unnecessary construction of responseRows in results page #4110

---

src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
src/main/java/teammates/ui/template/InstructorFeedbackResultsParticipantPanel.java
src/main/java/teammates/ui/template/InstructorFeedbackResultsResponseRow.java
src/main/java/teammates/ui/template/InstructorFeedbackResultsSecondaryParticipantPanelBody.java

Reduce calls to getQuestionDetails and getStudentProfilePictureLink #4114

---

src/main/webapp/WEB-INF/tags/instructor/home/sort.tag
src/main/webapp/jsp/instructorHome.jsp
src/test/resources/pages/InstructorHomeHTMLEmpty.html
src/test/resources/pages/InstructorHomeNewInstructorWithSampleCourse.html
src/test/resources/pages/InstructorHomeNewInstructorWithoutSampleCourse.html
src/test/resources/pages/adminHomePageCreateInstructorSuccess.html
src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
src/test/resources/pages/instructorHomeCourseDeleteSuccessful.html
src/test/resources/pages/newlyJoinedInstructorHomePage.html
src/test/resources/pages/newlyJoinedInstructorHomePageSampleCourseArchived.html

Fix #3909
Now it always show "Add new course" button with sort buttons and disables sort buttons when the number of active courses <= 1

"Add New Course" button missing for newly added instructor #3909

---

src/main/webapp/js/statusMessage.js
src/main/webapp/js/studentMotd.js

statusMessage.js has missing closing bracket #4104

---

src/main/webapp/js/feedbackSubmissionsEdit.js

Add hyphen in feedbackSubmissionsEdit.js at line 175 #4120

---

src/main/webapp/js/instructorFeedbackResults.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java

Tooltip for Expand / Collapse Sections button does not update when clicked #3953

---

src/main/webapp/js/adminActivityLog.js
src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java
src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java

fixed #4132 
@kanghj do you mind having a look?

adminActivityLog: cannot retrieve time in user timezone #4132

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java

Fixes #4140 
@taniach, help me check if this improves things.

InstructorFeedbackResultsPageUiTest failing on dev server due to panel collapsing #4140

---

src/main/java/teammates/ui/controller/InstructorFeedbackEditPageData.java
src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java
src/main/webapp/js/instructorFeedbackEdit.js
src/test/java/teammates/test/cases/ui/InstructorFeedbackEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
src/test/resources/pages/instructorFeedbackEditSuccess.html
src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html

Fix #3693
I changed RedirectResult to AjaxResult when submitting the form. When the AjaxResult is returned, it will  show and focus on status message. 
@kanghj Could you review this one?

instructor feedback edit: previous values are lost when reporting incorrect end time #3693

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/ui/controller/InstructorHomeCourseAjaxPageData.java
src/main/java/teammates/ui/controller/InstructorHomePageAction.java
src/main/java/teammates/ui/controller/InstructorHomePageData.java
src/main/webapp/WEB-INF/tags/instructor/home/coursePanel.tag
src/main/webapp/js/instructorHome.js
src/main/webapp/jsp/instructorHome.jsp
src/main/webapp/jsp/instructorHomeAjaxCourse.jsp
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorHomePage.java
src/test/resources/data/InstructorHomePageUiTestUnloadedCourse.json
src/test/resources/pages/InstructorHomeHTML.html
src/test/resources/pages/InstructorHomeHTMLResponseRateFail.html
src/test/resources/pages/InstructorHomeHTMLSortByDate.html
src/test/resources/pages/InstructorHomeHTMLSortById.html
src/test/resources/pages/InstructorHomeHTMLSortByName.html
src/test/resources/pages/InstructorHomeHTMLWithHelperView.html
src/test/resources/pages/InstructorHomeHTMLWithUnloadedCourse.html
src/test/resources/pages/InstructorHomeNewInstructorWithSampleCourse.html
src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
src/test/resources/pages/newlyJoinedInstructorHomePage.html

Fixes #4108 
@kanghj 
I'm not too sure about the *Logic classes, so could you take a closer look over those at least?

 InstructorHome: load courses incrementally by ajax #4108 

---

src/main/java/teammates/client/scripts/RepairFeedbackSessionResponseRate.java

For #4134, to find feedback sessions with a similar problem.

Student who submitted responses shown as not submitted #4134

---

src/main/java/teammates/ui/controller/InstructorSearchPageAction.java
src/test/resources/data/InstructorSearchPageUiTest.json
src/test/resources/pages/InstructorSearchPageSearchCommentsAsHelper.html

Fixes #4139
The filter function is restored, but currently I'm getting this when search for FRCs returns no result:
Still fixing it.

No filter for response comments in InstructorSearch #4139

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseDetailsPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentCommentsPageUiTest.java

Rename testConent -> testContent in InstructorCourseDetailsPageUiTest and StudentCommentsPageUiTest #4138

---

src/main/resources/feedbackQuestionRubricSubmissionFormTemplate.html
src/main/webapp/js/feedbackSubmissionsEdit.js
src/main/webapp/stylesheets/teammatesCommon.css
src/test/resources/pages/studentFeedbackSubmitPageRubricSuccess.html

Rubric questions: show unmarked rows in a different color #4135

---

src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackContributionResponseDetails.java
src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/test/java/teammates/test/cases/ui/pagedata/StudentCommentsPageDataTest.java
src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientGiverQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientGiverQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiverTeam.html

Fixes #3789 
Currently, only the statistics table displayed on the webpage has been changed. The CSV statistics table still leaves out students who did not respond/did not get a response. I will fix it in a separate PR.

instructor feedback results: contribution questions: students who did not receive any response are missing from the summary table #3789

---

src/main/webapp/js/statusMessage.js

Status message is not hidden behind nav bar

---

src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java

NullPointerException when attempting to download feedback results #4168

---

src/main/webapp/js/statusMessage.js

StudentFeedbackQuestionSubmitPageUiTest failing on dev server #4176

---

src/test/testng.xml

Two logic tests (both passing) not included in full test suite #4180

---

src/test/java/teammates/test/automated/FeedbackSessionClosingReminderTest.java
src/test/java/teammates/test/automated/FeedbackSessionOpeningReminderTest.java
src/test/java/teammates/test/automated/FeedbackSessionPublishedReminderTest.java

Bug in feedback session opening reminder test #4185

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/InstructorHomeCourseAjaxPageData.java
src/main/java/teammates/ui/controller/InstructorHomePageAction.java
src/main/java/teammates/ui/controller/InstructorHomePageData.java
src/main/java/teammates/ui/controller/StudentHomePageData.java
src/main/java/teammates/ui/template/CourseTable.java
src/main/java/teammates/ui/template/HomeFeedbackSessionRow.java
src/main/java/teammates/ui/template/InstructorHomeFeedbackSessionRow.java
src/main/java/teammates/ui/template/StudentHomeFeedbackSessionRow.java
src/main/webapp/WEB-INF/tags/instructor/home/courseTable.tag
src/main/webapp/jsp/instructorHome.jsp
src/test/java/teammates/test/cases/ui/pagedata/StudentHomePageDataTest.java

Fixes #4166 
Also indirectly fixes #4173 
Anyone available to take a look?

 Refactor InstructorHome-related files #4166

---

src/main/java/teammates/ui/controller/InstructorCourseEditPageData.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java

instructor permission fine tuning doesn't work for some tutors #4206

---

src/test/resources/pages/adminSessionsPage.html
src/test/resources/pages/adminSessionsPageHideFilter.html
src/test/resources/pages/adminSessionsPageShowFilter.html

AdminSessionsPageUiTest failing #4189

---

src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/resources/data/FeedbackSessionQuestionTypeTest.json

Add tests for CSV feedback results download #4175

---

src/test/java/teammates/test/pageobjects/InstructorHomePage.java

InstructorHomePageUiTest failing on dev #4162

---

src/test/java/teammates/test/driver/HtmlHelper.java
src/test/java/teammates/test/pageobjects/AppPage.java

Fix #4170
Basically, when a difference is detected, we change real values, which are supposed to be wildcards, back to wildcards then do the comparison.

Page comparison failures include wildcards #4170

---

src/main/java/teammates/ui/controller/InstructorFeedbacksPageData.java
src/main/java/teammates/ui/controller/InstructorHomeCourseAjaxPageData.java
src/main/java/teammates/ui/controller/InstructorHomePageAction.java
src/main/java/teammates/ui/controller/PageData.java

Fixes #4212.
I was right about this having to do with the logic method inside, so this also fixes #3735 and fixes #3794.
As an additional benefit, there are more redundant db queries that are suppressed.

InstructorFeedbacksPageDataTest fails if not run on full test suite #4212

---

src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/storage/api/CoursesDb.java
src/test/java/teammates/test/cases/logic/CoursesLogicTest.java

Fixes #4214 
InstructorHomePage is much faster now, loads under a second on dev, for an account with over 100 courses.
There are still more function to be improved, will do as separate issues according to the page/feature that uses it.

Improve performance of functions in CoursesLogic #4214

---

src/test/java/teammates/test/pageobjects/AppPage.java

fix #4225
@wkurniawan07 hope you can review this one.

Duplicated jquery-ui.min.js in processPageSourceForFailureCase #4225

---

src/main/webapp/jsp/adminSearch.jsp
src/test/resources/pages/adminSearchPageDefault.html
src/test/resources/pages/adminSearchPageSearchNone.html
src/test/resources/pages/adminSearchPageSearchStudent1.html
src/test/testng.xml

Fixes #4188 
@wkurniawan07 I believe " in place of &quot; will work too. Used &quot; here because the diff for expected-actual shows as &quot;

AdminSearchPageUiTest failing #4188

---

src/test/resources/pages/adminEmailLogPage.html
src/test/testng.xml

fix #4186
@taniach could you see if I have to change anything else or not?

AdminEmailLogPageUiTest failing #4186

---

src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestion.html

InstructorFeedbackResultsPageUiTest fails and freezes at line 281 #4221

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditPageAction.java
src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java

Fixes #4246 
Will fix up the tests when I have time later.
@wkurniawan07 
Can you do this while looking over #4239?
They're related and I'll be merging this into that after both are reviewed.

Keep instructors' actions for students consistent in case of student not found #4246

---

src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/ui/controller/InstructorCoursesPageAction.java

Remove redundant queries from InstructorCoursesPageAction #4216

---

src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

Tests randomly fails when unable to find datepicker elements #4227

---

src/test/java/teammates/test/cases/ui/InstructorStudentListPageActionTest.java
src/test/java/teammates/test/cases/ui/StudentCommentsPageActionTest.java
src/test/java/teammates/test/cases/ui/StudentHomePageActionTest.java

Fixes #4253 
See issue thread for explanations.

InstructorStudentListPageActionTest fails unless run alone #4253

---

src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
src/test/resources/data/typicalDataBundle.json

Response is cleared on 2nd student's submission if giver type is "Teams in this course" and the recipient is "Giver" #2767

---

src/main/webapp/WEB-INF/web.xml
src/main/webapp/deadlineExceededErrorPage.jsp
src/main/webapp/entityNotFoundPage.jsp
src/main/webapp/errorPage.jsp
src/main/webapp/feedbackSessionNotVisible.jsp
src/main/webapp/js/instructor.js
src/main/webapp/pageNotFound.jsp
src/main/webapp/unauthorized.jsp
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorHomePage.java

Null course ID #4184

---

src/main/webapp/js/instructorStudentList.js

instructorStudentsList: filtering doesn't work for some workflows #4258

---

src/main/webapp/js/instructorFeedbackEdit.js

status message for updating sessions should be green #4191

---

src/test/java/teammates/test/driver/HtmlHelper.java
src/test/java/teammates/test/pageobjects/AppPage.java

Fix #4244
@wkurniawan07 Could you review this?

Remove redundant sanitization in HtmlHelper #4244

---

src/main/java/teammates/common/datatransfer/FeedbackConstantSumQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackMcqQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackMsqQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackNumericalScaleQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackRubricQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/main/java/teammates/common/datatransfer/FeedbackTextQuestionDetails.java
src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
src/main/java/teammates/ui/controller/PageData.java
src/main/java/teammates/ui/controller/StudentFeedbackResultsPageData.java

Suppress Feedback*QuestionDetails and FeedbackSessionResultsBundle dependency to PageData #4249

---

src/main/java/teammates/common/datatransfer/FeedbackNumericalScaleQuestionDetails.java
src/test/resources/data/StudentFeedbackResultsPageUiTest.json
src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html

FeedbackNumericalScaleQuestionDetails: recipients with only responses from the current user appearing in stats table #4267

---

src/main/webapp/WEB-INF/tags/instructor/results/questionPanel.tag
src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.js
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperOne.html
src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperTwo.html
src/test/resources/pages/instructorFeedbackResultsFilteredByNoSection.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsFilteredBySectionB.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsPageOpenViewForHelperOne.html
src/test/resources/pages/instructorFeedbackResultsPageOpenViewForHelperTwo.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestion.html
src/test/resources/pages/newlyJoinedInstructorFeedbackResultsPage.html

InstructorFeedbackResults: show question tables without responses in grey #4145

---

src/main/java/teammates/storage/api/FeedbackResponsesDb.java

Exception: Cannot read fields from a deleted object #4265

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

Fix #4252
@taniach Could you review this PR? I believe checking for content and color of statusMessage will be sufficient?

InstructorFeedbackEditPageUiTest HTMLs do not check the status message for the feedback session successfully updated #4252

---

src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/CoursesLogic.java

Remove redundant queries in InstructorFeedbacksPageAction #4264

---

src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/ui/controller/InstructorCoursesPageAction.java

Wrong logic for getArchivedCourseIds in CoursesLogic #4288

---

src/test/java/teammates/test/pageobjects/AppPage.java
src/test/java/teammates/test/pageobjects/InstructorHomePage.java

Fixes #4272 
Note that this fixes the possibility of failing on line 365 too.

Test fails on Mac InstructorHomePageUiTest line 358 #4272

---

src/test/java/teammates/test/cases/ui/browsertests/BaseUiTestCase.java
src/test/java/teammates/test/driver/HtmlHelper.java
src/test/resources/pages/adminAccountDetails.html
src/test/resources/pages/adminAccountManagementPage.html
src/test/resources/pages/adminActivityLogPage.html
src/test/resources/pages/adminEmailCompose.html
src/test/resources/pages/adminEmailLogPage.html
src/test/resources/pages/adminHomePageCreateInstructorSuccess.html
src/test/resources/pages/adminSearchPageDefault.html
src/test/resources/pages/adminSessionsPage.html

Fixes #4262
@yj-soh please, simple one :)

Remove hardcoded "defaultAdmin" #4262

---

src/test/java/teammates/test/pageobjects/InstructorHomePage.java

InstructorHomePageUiTest failing frequently #4301

---

src/test/resources/pages/instructorStudentList.html
src/test/resources/pages/instructorStudentListPageDisplayArchivedCourses.html
src/test/resources/pages/instructorStudentListPageHideArchivedCourses.html
src/test/resources/pages/instructorStudentListPageSearchStudent.html
src/test/resources/pages/instructorStudentListPageSearchStudentMultiple.html
src/test/resources/pages/instructorStudentListPageWithPicture.html
src/test/resources/pages/instructorStudentListWithHelperView.html

InstructorStudentListPageUiTest is broken on dev server #4304

---

src/test/java/teammates/test/cases/BaseTestCase.java

BaseTestCase.java code for injecting real account details is inconsistent #4305

---

src/main/webapp/js/common.js
src/main/webapp/js/contextualcomments.js
src/main/webapp/js/feedbackSubmissionsEdit.js
src/main/webapp/js/instructorCourseEdit.js
src/main/webapp/js/instructorFeedbackEdit.js
src/main/webapp/js/instructorStudentRecords.js
src/main/webapp/js/omniComment.js
src/main/webapp/js/statusMessage.js
src/main/webapp/js/studentProfile.js

Fixes #4171 
This took longer than expected.
It's JS, so @junhaoyap, please take a look if you have the time.
b315f29 and b8cefa5 are changes in behaviour, @kanghj can you take a brief look at their descriptions and check if it might break anything?

 Make a function in common.js to scroll to a specified element #4171 

---

src/test/java/teammates/test/pageobjects/AppPage.java

fixes #4324 
@kanghj review this?

Godmode does not work properly for Ajax Html comparison #4324

---

src/test/java/teammates/test/pageobjects/AppPage.java

fixes #4310 
@LowWeiLin I think they are no html files to be regenerated (I searched via regex in sublime)

GodMode not working for InstructorStudentListPageUiTest #4310

---

src/main/webapp/js/instructor.js

Fixes #4306
This allows alt-click to work.

null course id in InstructorFeedbackEditCopyAction #4306

---

src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/Emails.java
src/main/java/teammates/ui/controller/ActionFactory.java
src/main/java/teammates/ui/controller/ControllerServlet.java
src/main/resources/systemErrorEmailTemplate.html
src/test/java/teammates/test/cases/logic/EmailsTest.java

Add more details to log emails #4329

---

src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
src/test/resources/pages/instructorFeedbackResultsFilteredByNoSection.html
src/test/resources/pages/instructorFeedbackResultsPageOpen.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html
src/test/resources/pages/instructorFeedbackResultsSortQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html

'moderate' button throws unauthorized error when the giver is an instructor #4275

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/resources/pages/instructorFeedbackResultsDuplicateQuestionNumberPanel1.html
src/test/resources/pages/instructorFeedbackResultsDuplicateQuestionNumberPanel2.html

InstructorFeedbackResultsPageUiTest failing on line 135 #4338

---

src/main/java/teammates/logic/core/Emails.java

Error when adding email to task queue: log more info #4290

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/AdminHomePageAction.java
src/main/java/teammates/ui/controller/AdminHomePageData.java
src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java
src/main/webapp/WEB-INF/tags/admin/home/adminCreateInstructorAccountWithOneBoxForm.tag
src/main/webapp/jsp/adminHome.jsp
src/test/java/teammates/test/cases/ui/AdminHomePageActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java
src/test/java/teammates/test/cases/ui/pagedata/AdminHomePageDataTest.java
src/test/java/teammates/test/pageobjects/AdminHomePage.java
src/test/resources/pages/adminHomePageCreateInstructorSuccess.html

fix #4266
The data for the new form needs 3 columns separated by either \t or |.
@kanghj could you review this PR?

adminCreateAccount: give an option to give all data in one line #4266

---

src/test/java/teammates/test/cases/ui/browsertests/GodModeTest.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/resources/pages/adminEmailCompose.html
src/test/resources/pages/godmodeExpectedOutput.html
src/test/resources/pages/godmodeExpectedPartOutput.html
src/test/resources/pages/instructorFeedbackEditCopyPage.html
src/test/resources/pages/studentCourseJoinConfirmationHTML.html

Fixes #4354 and fixes #4355 
It is a combined pull request as both are related

StudentCourseJoinConfirmationPageUiTest failing on live server #4354 and InstructorFeedbackEditCopyUiTest failing on live server #4355

---

devdocs/process.md

fixes #4350 
@damithc sir, I believe you are the best person to review this

Update Developer Manual for Reviewers to ignore whitespace using "?w=1" #4350

---

src/main/java/teammates/ui/controller/InstructorCoursesPageAction.java
src/main/java/teammates/ui/controller/InstructorCoursesPageData.java
src/main/webapp/WEB-INF/tags/instructor/course/activeCoursesTable.tag
src/main/webapp/WEB-INF/tags/instructor/course/archivedCoursesTable.tag
src/main/webapp/WEB-INF/tags/instructor/course/loadCoursesTableByAjaxForm.tag
src/main/webapp/js/instructorCourses.js
src/main/webapp/js/instructorCoursesAjax.js
src/main/webapp/jsp/instructorCourses.jsp
src/main/webapp/jsp/instructorFeedbacks.jsp
src/test/java/teammates/test/cases/ui/InstructorCoursesPageActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCoursesPage.java
src/test/resources/pages/instructorArchiveStatusNotAffected.html
src/test/resources/pages/instructorCoursesAddDupIdFailed.html
src/test/resources/pages/instructorCoursesAddInvalidIdFailed.html
src/test/resources/pages/instructorCoursesAddMissingParamsFailed.html
src/test/resources/pages/instructorCoursesAddSuccessful.html
src/test/resources/pages/instructorCoursesArchiveSuccessful.html
src/test/resources/pages/instructorCoursesDeleteSuccessful.html
src/test/resources/pages/instructorCoursesMultipleCourses.html
src/test/resources/pages/instructorCoursesNoCourse.html
src/test/resources/pages/instructorCoursesUnarchiveSuccessful.html
src/test/resources/pages/newlyJoinedInstructorCoursesPageSampleCourseUnarhived.html

instructor courses page: load course list using ajax #4284

---

src/main/webapp/js/common.js
src/main/webapp/js/instructorCoursesAjax.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCoursesPage.java
src/test/resources/pages/instructorCoursesNoCourse.html

InstructorCoursesEditPageUiTest fails on line 438 #4397

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentListPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentCourseDetailsPageUiTest.java
src/test/resources/pages/instructorStudentListPageSearchNoMatch.html
src/test/resources/pages/instructorStudentListWithHelperView.html
src/test/resources/pages/instructorStudentRecords.html
src/test/resources/pages/studentCourseDetailsWithTeammatesHTML.html

Fixes #4373 
Explanation for `InstructorStudentList`: the previous "full check" is a false positive because it's actually checking `InstructorSearchPage`, and this has been done in its own UI test.

Add full HTML check for InstructorStudentList, InstructorStudentRecords, and StudentCourseDetails UI test #4373

---

src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java

'Incorrect question number' warning triggered wrongly #4407

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCoursesPage.java

InstructorCoursesPageUiTest failing on live server #4406

---

src/main/java/teammates/common/datatransfer/FeedbackResponseCommentAttributes.java
src/main/java/teammates/ui/template/FeedbackResponseComment.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/resources/pages/InstructorSearchPageSearchCommentsAsHelper.html
src/test/resources/pages/instructorCommentsPageAddFrc.html
src/test/resources/pages/instructorCommentsPageDeleteFrc.html
src/test/resources/pages/instructorCommentsPageEditFrc.html
src/test/resources/pages/instructorCommentsPageForCourseWithURIEncodedSessionName.html
src/test/resources/pages/instructorCommentsPageForTypicalCourseWithComments.html
src/test/resources/pages/instructorCommentsPageSearchNormal.html
src/test/resources/pages/instructorCommentsPageShowCommentsForAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPrivate.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPublic.html
src/test/resources/pages/instructorCommentsPageShowCommentsForSessionCommentPanel.html
src/test/resources/pages/instructorCommentsPageShowCommentsForStudentCommentPanel.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAllStatus.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromOthers.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromYou.html
src/test/resources/pages/instructorSearchPageSearchComments.html
src/test/resources/pages/instructorSearchPageSearchFeedbackResponseComments.html
src/test/resources/pages/instructorStudentRecords.html
src/test/resources/pages/studentCommentsPageForStudent1.html
src/test/resources/pages/studentCommentsPageForStudent2.html
src/test/resources/pages/studentCommentsPageForStudent3.html
src/test/resources/pages/studentFeedbackResultsPageOpen.html
src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html

Fixes #4032
@JosephineKwa this shouldn't be hard to review.

Change the time formatting for FeedbackResponseComments to follow Comments #4032

---

src/test/java/teammates/test/pageobjects/AppPage.java

Fixes #4409 
The solution will also allow things like `V1.1.1.1.1.1.1` but I guess it's fine?

Tests fail when the version number has a minor component #4409

---

src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java

AdminHomePageUiTest failing due to coursesPage ajax #4414

---

src/main/java/teammates/ui/controller/InstructorFeedbacksPageAction.java

Improve speed of initial load for InstructorFeedbacksPage #4413

---

src/main/java/teammates/common/exception/EntityAlreadyExistsException.java
src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
src/main/java/teammates/storage/api/EntitiesDb.java

studentFeedbackSubmissionEditSave: java.lang.AssertionError: null #4398

---

src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java

Fixes #4159 
I realised this issue had been fixed in PR #4287 , however the test was failing again when I tried running it again this time round. Specifically, on lines 121 and 230. Both were due to ajax elements not completely loading before verification.

InstructorCommentsPageUiTest failing on live server #4159

---

src/test/javascript/AllJsUnitTests.html
src/test/javascript/InstructorStudentListJsTest.js

Add corner test cases for filtering in InstructorStudentListPage #4280

---

src/main/java/teammates/common/util/Const.java
src/main/webapp/js/common.js
src/test/java/teammates/test/cases/ui/InstructorCourseAddActionTest.java
src/test/resources/pages/instructorCoursesAddInvalidIdFailed.html

Status message for 'Add new course' should say spaces are not allowed in course ID #3991

---

src/main/webapp/js/instructorCourseEdit.js

Fixes #4384 
@junhaoyap Will you have the time to review this batch of short PRs (#4390 - #4395)?

 Add error handling for instructorCourseEdit.js #4384 

---

src/main/webapp/js/instructorFeedbackEdit.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

Add AJAX request error handling for instructorFeedbackEdit.js #4386 

---

src/main/webapp/js/instructorFeedbacks.js
src/main/webapp/js/instructorFeedbacksAjax.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java

Add AJAX request error handling for instructorFeedbacksAjax.js #4387 

---

src/main/webapp/js/instructorStudentListAjax.js

Add AJAX request error handling for instructorStudentListAjax.js #4388

---

src/main/webapp/js/studentMotd.js

Add AJAX request error handling for studentMotd.js #4389

---

src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java
src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java
src/test/java/teammates/test/pageobjects/AppPage.java

Fixes #4356 
@damithc it 3 minutes good enough, or how long does it take?

AdminAccountManagementPageUiTest failing on live server #4356

---

src/main/webapp/js/common.js

student feedback submission: cannot see team member names #4442

---

src/test/java/teammates/test/pageobjects/AppPage.java

Many test failures on dev server #4443

---

src/test/java/teammates/test/pageobjects/AppPage.java

Tests failing on dev server due to god mode #4452

---

src/main/webapp/js/instructorStudentRecords.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java

Assertion failure in InstructorStudentCommentAddAction #4405

---

src/test/java/teammates/test/cases/ui/browsertests/StudentProfilePageUiTest.java

StudentProfilePageUiTest failing on line 89 #4450

---

src/main/webapp/js/instructorCourseEditAjax.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java

Add AJAX request error handling for instructorCourseEditAjax.js #4385 

---

src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

InstructorFeedbackEditPageUiTest failing on live server #4160

---

src/main/webapp/about.html

@damithc please review and I'll merge it, didn't open an issue but I can if you want me to, it's just a fix for my name :)

Fix Jun Hao's name

---

src/main/java/teammates/common/util/TimeHelper.java
src/main/java/teammates/logic/core/Emails.java
src/test/java/teammates/test/cases/logic/EmailsTest.java

Make the time stamp in emails unambiguous #4419

---

src/test/java/teammates/test/driver/TestProperties.java
src/test/java/teammates/test/pageobjects/AppPage.java

TestProperties check for God mode needs to be (much) stricter #4431

---

src/test/java/teammates/test/cases/ui/browsertests/FeedbackRubricQuestionUiTest.java
src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java

FeedbackRubricQuestionUiTest failing on live server #3640

---

src/main/webapp/WEB-INF/tags/admin/adminPage.tag
src/main/webapp/WEB-INF/tags/bodyFooter.tag
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/resources/pages/godmode.html
src/test/resources/pages/godmodeExpectedOutput.html

Fixes #4477 
Tested in the admin UI tests, regeneration works perfectly.

Enable God mode to wildcard admin institute #4477

---

src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionA.html

instructor feedback results: students not in section shown in 'by section view' #4485

---

src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java

Refactor InstructorCommentsPage.java #4438

---

src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
src/main/java/teammates/ui/controller/AdminActivityLogPageData.java
src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java

Admin activity log search: show the earliest time searched #4358

---

src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

Test fails on InstructorFeedbackEditPageUiTest due to datepicker element #4273

---

src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java

Change getId to getGoogleId in AdminActivityLogPageAction #4502

---

src/main/java/teammates/common/datatransfer/FeedbackQuestionAttributes.java
src/main/webapp/js/instructorFeedbackEdit.js
src/test/java/teammates/test/cases/common/FeedbackQuestionAttributesTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

Fixes #4509
@LowWeiLin for your review. If you are not free today, you can assign someone else.

Visibility checkboxes does not match preview #4509

---

src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java

AdminActivityLogPageUiTest fails at line 86 #4508

---

src/main/webapp/WEB-INF/tags/student/profile/uploadPhotoModal.tag
src/main/webapp/js/studentProfile.js
src/main/webapp/stylesheets/teammatesCommon.css
src/test/java/teammates/test/cases/ui/browsertests/StudentProfilePageUiTest.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/java/teammates/test/pageobjects/StudentProfilePage.java
src/test/resources/pages/studentProfilePageDefault.html
src/test/resources/pages/studentProfilePictureModalDefault.html

student profile pic upload: upload button should only be enabled when there is something to upload #4473

---

src/test/java/teammates/test/driver/HtmlHelper.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/resources/pages/adminAccountDetails.html
src/test/resources/pages/adminHomePageCreateInstructorSuccess.html
src/test/resources/pages/godmodeExpectedOutput.html
src/test/resources/pages/instructorStudentListPageWithPicture.html
src/test/resources/pages/login.html
src/test/resources/pages/studentCourseJoinConfirmationHTML.html
src/test/resources/pages/studentProfilePictureModalEdit.html

Fixes #4447 and I believe it also fixes #4353.
Refer to [this gist I made](https://gist.github.com/wkurniawan07/e1fb00be615bb34ca01f) for the rationale behind the solution.
Only one small problem though: I can't think of a better name than `GodModePartOne` and `GodModePartTwo` :p

Review the workflow of HTML processing in comparisons #4447

---

src/main/java/teammates/common/datatransfer/FeedbackQuestionAttributes.java

Remove irrelevant visibility options when feedback question is retrieved #4516

---

src/main/webapp/js/instructor.js

Fixes #4523
Did not include a test since the test for the state of the button can only happen after form submission, but the page might change too quickly before the test

Duplicates of questions in session #4523

---

src/main/java/teammates/common/util/TimeHelper.java
src/main/java/teammates/ui/controller/InstructorHomeCourseAjaxPageData.java
src/main/java/teammates/ui/template/InstructorHomeFeedbackSessionRow.java
src/main/webapp/WEB-INF/tags/instructor/home/courseTable.tag
src/main/webapp/js/instructorHome.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorHomePage.java
src/test/resources/data/InstructorHomePageUiTest3.json
src/test/resources/pages/InstructorHomeHTML.html
src/test/resources/pages/InstructorHomeHTMLResponseRateFail.html
src/test/resources/pages/InstructorHomeHTMLSortByDate.html
src/test/resources/pages/InstructorHomeHTMLSortById.html
src/test/resources/pages/InstructorHomeHTMLSortByName.html
src/test/resources/pages/InstructorHomeHTMLSortSessionsByEndDate.html
src/test/resources/pages/InstructorHomeHTMLSortSessionsByName.html
src/test/resources/pages/InstructorHomeHTMLSortSessionsByStartDate.html
src/test/resources/pages/InstructorHomeHTMLWithHelperView.html
src/test/resources/pages/InstructorHomeHTMLWithUnloadedCourse.html
src/test/resources/pages/InstructorHomeNewInstructorWithSampleCourse.html
src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
src/test/resources/pages/newlyJoinedInstructorHomePage.html

instructorHomePage: Show start/end date for sessions #4426

---

src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java
src/test/resources/data/FeedbackSessionQuestionTypeTest.json

Incorrect logic for handling responses due to changing teams #4484

---

src/main/java/teammates/common/util/ActivityLogEntry.java

Log user's id in ActivityLogEntry when there is an error #4531

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java

Fixes #4505 
@wkurniawan07 for your review:)

InstructorFeedbackEditPageUiTest failing on live server #4505

---

src/main/java/teammates/common/datatransfer/InstructorAttributes.java
src/main/java/teammates/common/datatransfer/InstructorPrivileges.java
src/main/java/teammates/ui/controller/InstructorFeedbackAddAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackCopyAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackSubmissionEditPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackSubmissionEditSaveAction.java
src/main/java/teammates/ui/controller/InstructorFeedbacksPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbacksPageData.java
src/main/java/teammates/ui/controller/InstructorHomeCourseAjaxPageData.java
src/main/java/teammates/ui/controller/PageData.java
src/main/java/teammates/ui/template/InstructorFeedbackSessionActions.java
src/test/java/teammates/test/cases/ui/pagedata/InstructorFeedbacksPageDataTest.java

Inefficient permission check in InstructorFeedbackSessionActions #4506

---

.settings/com.google.appengine.eclipse.core.prefs
devdocs/settingUp.md

Fixes #4499 
Upgrading guide will be out soon. Tentatively, this will be merged earliest next week (end of next milestone) so everyone can have an ample time to upgrade.

Upgrade to SDK 1.9.27 #4499

---

src/main/webapp/js/instructorFeedbackEdit.js

Fixes #4495 
@kanghj not sure if you remember, but you reviewed this before :p

Null giver type, null recipient type #4495

---

src/main/webapp/WEB-INF/tags/student/profile/uploadPhotoModal.tag
src/main/webapp/js/studentProfile.js
src/main/webapp/stylesheets/teammatesCommon.css
src/test/java/teammates/test/pageobjects/StudentProfilePage.java
src/test/resources/pages/studentProfilePictureModalEdit.html

Student profile picture edit: not clear how to crop #4472

---

src/main/webapp/WEB-INF/tags/student/studentMessageOfTheDay.tag
src/main/webapp/js/studentMotd.js
src/test/java/teammates/test/driver/HtmlHelper.java
src/test/java/teammates/test/driver/TestProperties.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/resources/pages/newlyJoinedInstructorStudentFeedbackSubmissionEdit.html
src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html
src/test/resources/pages/studentFeedbackSubmitPageClosed.html
src/test/resources/pages/studentFeedbackSubmitPageEmpty.html
src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
src/test/resources/pages/studentFeedbackSubmitPageGracePeriod.html
src/test/resources/pages/studentFeedbackSubmitPageModified.html
src/test/resources/pages/studentFeedbackSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
src/test/resources/pages/studentFeedbackSubmitPageRubricSuccess.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html

Fixes #4543 
Tested with two different MOTD URLs, worked smoothly.

Allow MOTD to be tested with appropriate placeholders instead of ignoring completely #4543

---

src/main/webapp/js/index.js

Closes #4551
@wkurniawan07 please!
By the way, I realized that there are no tests for index.html (well since it's not dynamic I don't see a big point for it) but just saying because I ran the entire suite and it all passed, any thoughts on whether this would be a big deal?

Update entry count in homepage #4551

---

src/main/java/teammates/common/util/ActivityLogEntry.java
src/test/java/teammates/test/cases/ui/StudentFeedbackSubmissionEditPageActionTest.java
src/test/java/teammates/test/driver/AssertHelper.java

Change admin activity log's id to use email instead of google id #4527

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java

IllegalArgumentException: name cannot be null or empty #4540

---

src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java
src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java

Fixes #4507 and fixes #4116
Sorry but I've had enough of this :p

AdminInstructorAccountAddAction: replace Data Persistence checked twice with a log.warning #4507

---

src/main/webapp/jsp/instructorCourseEdit.jsp
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/instructorCourseEditManager.html
src/test/resources/pages/instructorCourseEditObserver.html
src/test/resources/pages/instructorCourseEditTutor.html
src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html

instructorCourseEdit page: Add an 'info' icon for the link for more info #4205

---

src/main/java/teammates/ui/controller/Action.java

Change the ambiguous error message in Action.java Line 239 #4573

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/InstructorCourseDetailsPageAction.java
src/test/java/teammates/test/cases/ui/InstructorCourseDetailsPageActionTest.java
src/test/resources/pages/InstructorCourseDetailsEmptyCourse.html

instructorCourseDetailsPage: give a link to enroll students if there are no students #3966

---

src/main/java/teammates/common/util/TimeHelper.java
src/test/java/teammates/test/cases/common/TimeHelperTest.java

Tests are failing because comments dates are wrong #4615

---

src/main/java/teammates/common/datatransfer/FeedbackRankOptionsResponseDetails.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java

Missing newline in rank options response's csv string #4618

---

src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java

Fixes #4334 
Review FeedbackSessionsLogic with ?w=1. https://github.com/TEAMMATES/repo/commit/dabd58b89318e81fb2ce49c06a1cf4fb47779b96?w=1

Remove redundant queries for instructor feedback results #4334

---

.classpath

Project output folder is polluted by JS test files #4627

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseDetailsPageUiTest.java
src/test/java/teammates/test/driver/EmailAccount.java

Fixes #4636 
Straightforward but crucial fixes. Anyone welcome to review.

Errors in InstructorCourseDetailsPageUiTest #4636

---

src/main/java/teammates/common/datatransfer/FeedbackRankOptionsQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackRankOptionsResponseDetails.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/resources/data/FeedbackSessionQuestionTypeTest.json

Rank question: ranked values not visible in the csv file #4634

---

src/test/java/teammates/test/cases/BaseTestCase.java
src/test/java/teammates/test/cases/automated/FeedbackSessionEmailTaskQueueTest.java
src/test/java/teammates/test/cases/logic/AccountsLogicTest.java
src/test/java/teammates/test/cases/logic/BackDoorLogicTest.java
src/test/java/teammates/test/cases/logic/CommentsLogicTest.java
src/test/java/teammates/test/cases/logic/CoursesLogicTest.java
src/test/java/teammates/test/cases/logic/EmailsTest.java
src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java
src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/java/teammates/test/cases/logic/InstructorsLogicTest.java
src/test/java/teammates/test/cases/logic/LogicTest.java
src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
src/test/java/teammates/test/cases/logic/TeamEvalResultTest.java
src/test/java/teammates/test/cases/storage/AccountsDbTest.java
src/test/java/teammates/test/cases/storage/CommentsDbTest.java
src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
src/test/java/teammates/test/cases/storage/FeedbackResponseCommentsDbTest.java
src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
src/test/java/teammates/test/cases/storage/InstructorsDbTest.java
src/test/java/teammates/test/cases/storage/ProfilesDbTest.java
src/test/java/teammates/test/cases/storage/StudentsDbTest.java
src/test/java/teammates/test/cases/ui/browsertests/SystemErrorEmailReportTest.java

Remove the tuning of logging level during testing #1027

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java

Improve test in InstructorCourseEditPageUiTest #4411

---

src/main/resources/feedbackSessionTeamEvaluationTemplate.json
src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html

Fixed #4533.
Changed 3 occurrences of string "Please rate the estimated contribution of the following recipients." to "My estimate of how much each team member contributed.".

Rephrase contribution question in the sample session #4533

---

src/test/java/teammates/test/cases/BaseTestCase.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseDetailsPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseJoinConfirmationPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorSubmissionAdjustmentUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentCourseJoinConfirmationPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentHomePageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentProfilePageUiTest.java
src/test/resources/data/InstructorCourseDetailsPageUiTest.json
src/test/resources/data/InstructorCourseJoinConfirmationPageUiTest.json
src/test/resources/data/InstructorSubmissionAdjustmentUiTest.json
src/test/resources/data/StudentCourseJoinConfirmationPageUiTest.json
src/test/resources/data/StudentHomePageUiTest.json
src/test/resources/data/StudentProfilePageUiTest.json

Inject real accounts to DataBundle via java instead of via json #4647

---

src/main/webapp/features.html

 Typo in home page: eve --> even #4665 

---

src/test/java/teammates/test/cases/ui/browsertests/FeedbackRankQuestionUiTest.java

Fixes #4681
Thanks for noticing it, @wkurniawan07!

GodMode set in FeedbackRankQuestionUiTest #4681

---

src/main/java/teammates/client/scripts/DataMigrationForSanitizedData.java
src/main/java/teammates/client/scripts/DataMigrationForSanitizedDataInStudentAttributes.java
src/main/java/teammates/common/datatransfer/StudentAttributes.java
src/main/java/teammates/logic/core/StudentsLogic.java
src/main/java/teammates/storage/api/StudentsDb.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageData.java
src/main/java/teammates/ui/template/StudentInfoTable.java
src/main/java/teammates/ui/template/StudentListStudentData.java
src/main/java/teammates/ui/template/StudentListTeamData.java
src/main/webapp/WEB-INF/tags/admin/search/studentRow.tag
src/main/webapp/WEB-INF/tags/instructor/courseStudentDetails/studentInformationTable.tag
src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag
src/main/webapp/WEB-INF/tags/instructor/studentList.tag
src/main/webapp/jsp/instructorCourseEnrollResult.jsp
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseStudentDetailsEditPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java
src/test/java/teammates/test/cases/ui/pagedata/InstructorStudentListAjaxPageDataTest.java
src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
src/test/resources/pages/studentFeedbackSubmitPageModified.html
src/test/resources/pages/studentFeedbackSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html

fix #2801
I removed sanitization from StudentAttributes class so there is a little change in the order of team names in the test output. 
Before, it was:
Team &amp;gt;&amp;&#35;39;&amp;quot;&amp;lt; 1
Team 2
Team 3
Then it became:
Team 2
Team 3
Team >'"< 1

html sanitized team name is stored in database #2801

---

src/main/java/teammates/common/util/ActivityLogEntry.java
src/test/java/teammates/test/cases/common/ActivityLogEntryTest.java

Duplicated functions in ActivityLogEntry.java #4457

---

src/test/resources/data/InstructorCommentsPageUiTest.json
src/test/resources/data/InstructorSearchPageUiTest.json
src/test/resources/data/typicalDataBundle.json
src/test/resources/pages/InstructorSearchPageSearchCommentsAsHelper.html
src/test/resources/pages/instructorCommentsPageAddFrc.html
src/test/resources/pages/instructorCommentsPageDeleteFrc.html
src/test/resources/pages/instructorCommentsPageEditFrc.html
src/test/resources/pages/instructorCommentsPageForTypicalCourseWithComments.html
src/test/resources/pages/instructorCommentsPageShowCommentsForAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPrivate.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPublic.html
src/test/resources/pages/instructorCommentsPageShowCommentsForSessionCommentPanel.html
src/test/resources/pages/instructorCommentsPageShowCommentsForStudentCommentPanel.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAllStatus.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromOthers.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromYou.html
src/test/resources/pages/instructorSearchPageSearchComments.html
src/test/resources/pages/instructorSearchPageSearchFeedbackResponseComments.html
src/test/resources/pages/studentCommentsPageForStudent1.html
src/test/resources/pages/studentCommentsPageForStudent2.html
src/test/resources/pages/studentCommentsPageForStudent3.html

Fixes #4701 
Anyone welcome to review, this should be very quick.

Hardcoded 1-3 Feb 2016 preventing dev green #4701

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorHomePage.java

InstructorHomePageUiTest sometimes fails at line 400 #4685

---

src/main/resources/feedbackQuestionConstSumResultStatsRecipientFragment.html
src/main/resources/feedbackQuestionConstSumResultStatsRecipientTemplate.html
src/main/resources/feedbackQuestionRankResultStatsRecipientFragment.html
src/main/resources/feedbackQuestionRankResultStatsRecipientTemplate.html
src/test/resources/pages/instructorFeedbackResultsPageRankGQRView.html
src/test/resources/pages/instructorFeedbackResultsPageRankQuestionView.html
src/test/resources/pages/instructorFeedbackResultsPageRankRQGView.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipient.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipientTeam.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestion.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiver.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiverTeam.html

Fixes #4683
Distribute points (among recipients) question
Rank (among recipients) question

Move team before giver/reciepent for feedback result statistics #4683

---

src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java

Fixes #4563 
@bamboo3250  for your review :)

timeout in InstructorFeedbackResultsPage on live server #4563

---

src/test/java/teammates/test/cases/ui/browsertests/StudentProfilePageUiTest.java
src/test/java/teammates/test/pageobjects/StudentProfilePage.java

StudentProfilePageUiTest fails on live server #4504

---

devdocs/process.md

 Edit New issue fix typos in process.md #4733

---

src/main/java/teammates/ui/controller/InstructorCourseDetailsPageData.java
src/main/java/teammates/ui/controller/InstructorStudentListAjaxPageAction.java

InstructorStudentListAjaxPageAction: UnknownFormatConversionException Conversion = 'm' #4739

---

src/main/java/teammates/ui/controller/AdminHomePageData.java
src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java
src/main/webapp/WEB-INF/tags/admin/home/adminCreateInstructorAccountForm.tag
src/main/webapp/WEB-INF/tags/admin/home/adminCreateInstructorAccountWithOneBoxForm.tag
src/main/webapp/js/adminHome.js
src/main/webapp/jsp/adminHome.jsp
src/test/java/teammates/test/cases/ui/AdminInstructorAccountAddActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java
src/test/java/teammates/test/pageobjects/AdminHomePage.java
src/test/resources/pages/adminHomePage.html

Admin create instructor page: the form allows adding multiple instructors #4641

---

devdocs/process.md

Document new label group m #4742

---

src/main/java/teammates/logic/backdoor/BackDoorServlet.java
src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/driver/BackDoor.java

Fixes #4705
A check is added when updating question number (similar to `updateFeedbackQuestion`).

NullPointerException in InstructorFeedbackQuestionEditAction #4705

---

devdocs/settingUp.md

 Update TestNG download link in settingUp.md #4689 

---

src/main/webapp/about.html

Typo in the about page #4760

---

src/main/java/teammates/ui/controller/AdminActivityLogPageData.java
src/main/webapp/WEB-INF/tags/admin/activity/filterPanel.tag

adminActivityLogPage: allow filtering for id #4529

---

devdocs/process.md

Document the label group e #4756

---

src/main/webapp/about.html

Update contributor list in about.html #4750

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCoursesPage.java
src/test/resources/pages/instructorCoursesStatsAjaxFailure.html
src/test/resources/pages/instructorCoursesStatsAjaxSuccessful.html

Fixes #4711 
Failure is caused by the ajax wait, because the wait is not capable of waiting for _multiple_ ajax loaders. `verifyHtmlAjax(MainContent)` can and that's the solution.

InstructorCoursesPageUiTest sometimes fails #4711

---

src/test/java/teammates/test/cases/testdriver/BackDoorTest.java

Fixes #4668
I'll go by the assumption that this is what I think it is, and I've noticed this since quite some time back. The solution applied here has been used in many other places as well.

NPE in updateStudentCascade while running BackDoorTest #4668

---

devdocs/process.md

Fixes #4747.
@yj-soh, @JosephineKwa, @junhaoyap, @taniach, @wkurniawan07, @bamboo3250 , @LowWeiLin, @thyageshm, @kanghj

Process.md: fill in area leads for aspect, feature and tech. #4747

---

src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
src/test/resources/pages/instructorFeedbackResultsPageWithSanitizedData.html

Fixes #4803.
Running the test without the fix results in an error on the results page. This is a quick hotfix, @bamboo3250 should have a a deeper look soon.
@LowWeiLin, are you around to review this? or pick someone else.

NPE in FeedbackContributionQuestionDetails #4803

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/AdminEmailComposePageAction.java
src/main/java/teammates/ui/controller/AdminEmailComposeSaveAction.java

Extract status message constants from AdminEmailComposePageAction and AdminEmailComposeSaveAction #4136

---

src/test/java/teammates/test/cases/storage/StudentsDbTest.java

StudentsDbTest failing on its first run #4787

---

src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
src/main/java/teammates/ui/template/InstructorFeedbackResultsFilterPanel.java
src/main/webapp/WEB-INF/tags/instructor/results/byQuestionResults.tag
src/main/webapp/WEB-INF/tags/instructor/results/bySectionPanels.tag
src/main/webapp/WEB-INF/tags/instructor/results/filterPanel.tag
src/main/webapp/WEB-INF/tags/instructor/results/participantGroupByQuestionPanel.tag
src/main/webapp/WEB-INF/tags/instructor/results/participantGroupBySecondaryParticipantPanel.tag
src/main/webapp/WEB-INF/tags/instructor/results/participantPanel.tag
src/main/webapp/WEB-INF/tags/instructor/results/questionPanel.tag
src/main/webapp/WEB-INF/tags/instructor/results/sectionPanel.tag
src/main/webapp/WEB-INF/tags/instructor/results/teamPanel.tag
src/main/webapp/jsp/instructorFeedbackResultsByGiverQuestionRecipient.jsp
src/main/webapp/jsp/instructorFeedbackResultsByGiverRecipientQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByRecipientGiverQuestion.jsp
src/main/webapp/jsp/instructorFeedbackResultsByRecipientQuestionGiver.jsp
src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html

 The 'expand students' button disappear after expanding panel #4352

---

src/test/java/teammates/test/cases/testdriver/BackDoorTest.java

Add a new test case for backdoor delete feedback question operation #4762

---

src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java

FeedbackSessionsLogicTest: remove redundant comments #4645

---

src/main/java/teammates/ui/controller/InstructorCourseInstructorDeleteAction.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java

InstructorCourseJoinAuthenticatedActionr: No institute found for the course #4728

---

src/main/webapp/js/common.js
src/main/webapp/js/contextualcomments.js
src/main/webapp/js/instructorStudentRecords.js
src/main/webapp/js/omniComment.js
src/test/javascript/CommonJsTest.js

Fixes #3922 
Updated function:
```javascript
function isBlank(str) {
if (typeof str !== 'string' && !(str instanceof String)) {
return false;
}
return str.trim() === '';
}
```
Will first check if the input is of type String. Then use the `trim` method and compare it with empty string.
@wkurniawan07 Can help to review? :smiley:

The function isBlank in multiple JavaScript files can be simplified #3922

---

src/main/java/teammates/common/exception/TeammatesException.java
src/main/java/teammates/logic/core/Emails.java
src/main/java/teammates/storage/search/SearchManager.java

Admin severe log alert: No line breaks in stack trace #4759

---

src/main/java/teammates/common/util/StringHelper.java
src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java
src/test/java/teammates/test/cases/common/StringHelperTest.java

Move trimCourseIdToMaximumLengthIfNecessary() in AdminInstructorAccountAddAction to StringHelper class #4745

---

devdocs/process.md

Update process.md about reviewer assignment #4826

---

src/main/webapp/js/adminSearch.js

change the admin highlight functionality to use more general function of common.js #4822

---

README.md

 Fix typo on README.md #4833 

---

devdocs/settingUp.md

'Deploy' icon missing from settingUp.md #4780

---

devdocs/settingUp.md

Wrong explanation for persistence.xml in settingUp.md #4628

---

src/main/java/teammates/logic/backdoor/BackDoorServlet.java
src/test/java/teammates/test/cases/testdriver/BackDoorTest.java
src/test/java/teammates/test/driver/BackDoor.java

Add a new test case for backdoor create feedback response operation #4848

---

src/main/webapp/about.html

Update about.html with new contributors until V5.70 #4869

---

src/main/java/teammates/common/util/StringHelper.java
src/main/java/teammates/ui/controller/PageData.java
src/main/java/teammates/ui/template/Comment.java
src/test/java/teammates/test/cases/common/StringHelperTest.java

Move removeBracketsForArrayString to StringHelper #3979

---

src/test/java/teammates/test/cases/ui/browsertests/FeedbackRankQuestionUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/FeedbackRubricQuestionUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentListPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java
src/test/java/teammates/test/pageobjects/AppPage.java

Decommission verifyHtml(MainContent)WithRetry and merge it with verifyHtml(MainContent) #4876

---

src/test/javascript/CommonJsTest.js
src/test/javascript/CommonTestFunctions.js
src/test/javascript/InstructorCourseDetailsJsTest.js
src/test/javascript/InstructorCoursesJsTest.js
src/test/javascript/InstructorEnrolmentJsTest.js
src/test/javascript/InstructorFeedbackEditJsTest.js
src/test/javascript/InstructorFeedbacksJsTest.js
src/test/javascript/InstructorJsTest.js
src/test/javascript/InstructorStudentListJsTest.js
src/test/javascript/StudentJsTest.js
src/test/javascript/SubmissionCountJsTest.js
src/test/javascript/qunit.css
src/test/javascript/qunit.js
src/test/resources/pages/allJsUnitTests.html

Fixes #4858 
[Upgrade Reference](http://qunitjs.com/upgrade-guide-2.x/)

Update QUnit framework from v1.10.0 to v1.22.0 #4858

---

src/main/java/teammates/common/util/ActivityLogEntry.java

ActivityLogEntry: Remove redundant code in getMessageInfo #4850 

---

src/main/webapp/js/instructorHome.js

Add space in confirmation message for archiving courses. #3914

---

src/main/webapp/js/instructorFeedbacks.js

 instructorFeedbacks: start time isn't given a default value at 11pm #3926 

---

src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java
src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java

FeedbackQuestionsLogic: Refactor methods with response rate check #4838

---

src/main/webapp/jsp/instructorFeedbackResponseCommentsLoad.jsp
src/test/resources/pages/instructorCommentsForTypicalCourseWithCommentsWithHelperView.html

instructorFeedbackResponseCommentsLoad empty div has empty style attribute #3982

---

src/main/java/teammates/storage/search/SearchQuery.java
src/test/java/teammates/test/cases/ui/browsertests/AdminSearchPageUiTest.java

 Instructor student search: '(' causes server error #4596 

---

src/main/java/teammates/logic/backdoor/BackDoorLogic.java

admin add account : request times out #4920

---

src/main/java/teammates/logic/core/Emails.java

No line breaks in severe log alerts #4896

---

src/main/webapp/js/feedbackResponseComments.js

 A wild 21 in the middle of feedbackResponseComments.js  #3875 

---

src/main/java/teammates/ui/controller/InstructorHomePageAction.java

admin activity log: instructor home page ajax requests are shown as null #4719

---

src/main/java/teammates/common/datatransfer/StudentAttributes.java
src/test/java/teammates/test/cases/BaseComponentTestCase.java
src/test/java/teammates/test/cases/testdriver/BackDoorTest.java

Add transient keword to createdAt and updatedAt in Student #4936

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyPageAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyPageData.java
src/main/webapp/jsp/instructorFeedbackCopyModal.jsp
src/test/java/teammates/test/cases/ui/InstructorFeedbackEditCopyActionTest.java
src/test/resources/pages/instructorFeedbackEditCopyFail.html
src/test/resources/pages/instructorFeedbackEditCopyPage.html

Remove currentPage parameter from instructorFeedbackCopyModal.jsp #4932

---

CONTRIBUTING.md

Add a CONTRIBUTING.md to the repo #4242

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageAction.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackSubmissionEditPageActionTest.java
src/test/java/teammates/test/cases/ui/StudentFeedbackSubmissionEditPageActionTest.java

Magic string in FeedbackSubmissionEditPageAction.java #4960

---

src/main/java/teammates/ui/controller/InstructorFeedbackCopyAction.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/resources/pages/instructorFeedbackCopyTrimmedSuccess.html

instructorFeedbackSessionCopy: session name should be trimmed automatically #2589

---

src/main/webapp/js/datepicker.js

Fixes #4950 
Detail reason could be found at [here](https://github.com/TEAMMATES/teammates/issues/4950#issuecomment-194369745)

instructor add session: closing time text box gives an NaaN error on Safari #4950

---

devdocs/process.md

Add 'active member' expectations to the process.md #4859

---

src/test/resources/pages/instructorFeedbackCopyTrimmedSuccess.html

Fixes #4979
@wkurniawan07 could you help me take a quick look?

Test failing at InstructorFeedbackPageUiTest line 461 #4979

---

src/test/java/teammates/test/cases/storage/StudentsDbTest.java

Entities not removed after testing in StudentsDbTest #4646

---

src/main/webapp/js/datepicker.js

In datepicker.js, defaultDate set to today should use the variable today and not instantiate a new Date object #4964

---

src/test/java/teammates/test/cases/ui/browsertests/FeedbackRankQuestionUiTest.java

Wrong Test Segment description in FeedbackRankQuestionUiTest #4992

---

devdocs/settingUp.md

settingUp.md: Include additional instructions for Mac users on parts that differ from Windows. #4631

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditCopyUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java

InstructorFeedbackEditCopyUiTest failing on live server #4957

---

src/main/webapp/about.html

Fixes #4945 
@damithc, waiting for theaverageguy to give his name. the rest have been updated

Update about.html with contributors from V5.71 #4945

---

src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/FeedbackResponseCommentsLogic.java
src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java
src/main/java/teammates/storage/entity/FeedbackResponseComment.java
src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java
src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java

updateFeedbackResponsesForChangingEmail: change not cascaded to feedback response comments #4694

---

src/main/webapp/js/common.js

instructor/admin search: results are not highlighted if the search words are in double quotes #4889

---

src/main/java/teammates/common/datatransfer/FeedbackRubricQuestionDetails.java
src/test/resources/pages/studentFeedbackResultsPageRubric.html
src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
src/test/resources/pages/studentFeedbackSubmitPageModified.html
src/test/resources/pages/studentFeedbackSubmitPageOpen.html
src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
src/test/resources/pages/studentFeedbackSubmitPageRubricSuccess.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html

Rubrics: don't show numerical values of options in students' view #5015

---

src/main/webapp/index.html

Rephrase the link to user map in index.html #5020

---

src/main/webapp/about.html

Update about.html with contributors from V5.72 #5011

---

src/test/java/teammates/test/pageobjects/InstructorStudentListPage.java

InstructorStudentListPageUiTest fails at line 172 #5017

---

devdocs/settingUp.md

Not explicit creation of main config files in settingUp devdoc. #5018

---

src/main/webapp/js/feedbackResponseComments.js

In feedbackResponseComments.js event handlers are being attached too many times #3883

---

src/main/java/teammates/common/util/StringHelper.java
src/test/java/teammates/test/cases/common/StringHelperTest.java

Fixes #5062
@wkurniawan07 Could you have a quick look?

csvToHtmlTable() in StringHelper doesn't support double quote escaping #5062

---

src/main/webapp/js/instructor.js

Unsupported pseudo: hover #4925

---

src/main/webapp/js/instructorFeedbackAjaxRemindModal.js

Disable remind particular student submission button until list of student has been loaded #3660

---

src/main/webapp/js/instructorCourseDetails.js

Unused parameters in toggleSendRegistrationKey() for instructorCourseDetails #3895

---

src/main/webapp/about.html

Outdated links in the about page #4771

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/InstructorCourseInstructorEditSaveAction.java
src/test/java/teammates/test/cases/ui/InstructorCourseInstructorEditSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html

instructorCourseEditInstructor: the feedback message can mention which instructor was edited #2523

---

src/test/java/teammates/test/pageobjects/AppPage.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
src/test/java/teammates/test/pageobjects/InstructorHomePage.java

InstructorHomePageUiTest and InstructorFeedbackEditCopyUiTest failing #5032

---

src/main/java/teammates/common/datatransfer/InstructorAttributes.java
src/main/java/teammates/common/datatransfer/InstructorPrivileges.java
src/main/java/teammates/ui/controller/AdminSearchPageAction.java
src/test/java/teammates/test/cases/common/InstructorPrivilegesTest.java
src/test/java/teammates/test/cases/ui/browsertests/AdminSearchPageUiTest.java
src/test/resources/data/InstructorSearchPageUiTest.json

admin search: The link for student name should go to the course owners page #4291

---

src/main/java/teammates/common/datatransfer/StudentAttributesFactory.java
src/main/java/teammates/common/util/Sanitizer.java
src/test/java/teammates/test/cases/common/SanitizerTest.java
src/test/java/teammates/test/cases/ui/InstructorCourseEnrollSaveActionTest.java

All names should be trimmed of leading, trailing, and duplicate internal spaces #3706

---

src/main/java/teammates/common/util/Const.java
src/test/java/teammates/test/cases/ui/pagedata/FeedbackSubmissionEditPageDataTest.java
src/test/java/teammates/test/cases/ui/pagedata/StudentFeedbackResultsPageDataTest.java
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageClosed.html
src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html
src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html

Conflicting messages when a session is closed #4666

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseJoinConfirmationPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditCopyUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentProfilePageUiTest.java
src/test/java/teammates/test/pageobjects/AppPage.java

Fixes #4914 
No significant change to testing as of now, but this would be an important stepping stone to #4825.

Decommission verifyStatusWithRetry and merge it with verifyStatus #4914

---

devdocs/settingUp.md

settingUp.md: an extra character before the repo url #4975

---

devdocs/settingUp.md

settingUp.md: Update QUnit Version to 1.22.0 #5105

---

src/main/java/teammates/storage/search/StudentSearchQuery.java

 instructor/admin search: better matches can be missing from results #4890 

---

src/main/webapp/WEB-INF/tags/admin/home/adminCreateInstructorAccountForm.tag
src/main/webapp/WEB-INF/tags/admin/home/adminCreateInstructorAccountWithOneBoxForm.tag
src/test/resources/pages/adminHomePage.html

Fixes #4357
Added headings to the two forms explaining why each form is used and added an explanation on how to add multiple users to the first form.

admin create instructor page: Add some explanations about the forms #4357

---

src/main/webapp/js/instructorFeedbacks.js

InstructorFeedbacks shows wrong date for new form due to UTC conversion rounding #5012

---

devdocs/settingUp.md

Mention Troubleshooting guide at the top of settingUp.md #5113

---

src/main/webapp/about.html

Update about.html with contributors from V5.73 #5104

---

src/main/java/teammates/ui/controller/AdminActivityLogPageData.java
src/main/java/teammates/ui/controller/AdminEmailLogPageData.java

Fixes #5099 
Removed System.out.print in AdminActivityLogPageData : Line 271 ,  AdminEmailLogPageData : Line 114.

Remove System.out.print in AdminActivityLogPageData and AdminEmailLogPageData #5099 .

---

src/main/webapp/js/datepicker.js

Fixes #4949
Triggering the click manually via JS did __not__ open the datepicker. Immediately I know what's wrong.

Intermittent failure in InstructorFeedbackEditPageUiTest #4949

---

src/main/webapp/js/index.js

Update entry count in home page #5159

---

src/main/resources/InstructorSampleData.json
src/test/resources/pages/newlyJoinedInstructorCommentsPage.html

Fixes #5167
Travis should be able to reach green here.

Hardcoded 1-2 Apr preventing dev green #5167

---

src/test/java/teammates/test/cases/ui/browsertests/AdminSessionsPageUiTest.java

AdminSessionsPageUiTest fails frequently on line 66 on Travis #5171

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/Action.java
src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java

Error messages for each field should be shown on separate lines #5085

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/Action.java
src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java

This reverts commit 06453c15511fc188d937c236508c2bcb53203dc3, reversing
changes made to e55acf2fb2ed59d1842762468e380934ea2beb64.

Revert "[5085] Error messages for each field should be shown on separate lines"

---

devdocs/settingUp.md
src/main/java/teammates/common/util/Config.java
src/main/java/teammates/common/util/Const.java
src/main/java/teammates/ui/controller/PageData.java
src/test/java/teammates/test/driver/HtmlHelper.java
src/test/resources/pages/godmode.html
src/test/resources/pages/godmodeExpectedOutput.html
src/test/resources/pages/godmodeExpectedPartOutput.html

Fixes #5175 
Not sure who's best to review this, though.

Use a cleaner method to determine a build's environment #5175

---

src/main/webapp/about.html

Update about.html with contributors from V5.74 #5150

---

src/main/java/teammates/common/util/TimeHelper.java
src/main/java/teammates/storage/api/FeedbackSessionsDb.java
src/test/java/teammates/test/cases/common/TimeHelperTest.java

Create isTimeWithinPeriod method in TimeHelper #5185

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
src/test/testng-local.xml
src/test/testng-travis.xml

Include InstructorFeedbackResultsPageUiTest in Travis test #5189

---

src/main/webapp/js/common.js
src/main/webapp/js/instructorFeedbackResults.js
src/main/webapp/js/instructorStudentRecords.js
src/main/webapp/jsp/instructorStudentRecords.jsp
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorStudentRecordsPage.java
src/test/resources/pages/instructorStudentRecords.html
src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html
src/test/resources/pages/instructorStudentRecordsPageWithPrivateFeedback.html

Fixes #2591 
Achieved UI:
1. Collapsed
2. Expanded

Make feedback sessions in 'all records' page collapsible/expandable #2591

---

src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java

InstructorCommentsPageUiTest fails at line 167 #5204

---

src/main/resources/build.template.properties

Generated links should use HTTPS #4852

---

src/main/resources/feedbackQuestionContribResultStatsFragment.html
src/main/webapp/instructorHelp.html
src/test/resources/pages/instructorFeedbackResultsPageWithSanitizedData.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionA.html
src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestion.html

feedbackQuestionContributionResultsStatsFragment.html has <%=idx%> #2487

---

src/main/java/teammates/common/util/EmailLogEntry.java
src/main/webapp/WEB-INF/tags/admin/email/draftEmail.tag
src/main/webapp/WEB-INF/tags/admin/email/log/emailLogTable.tag
src/main/webapp/WEB-INF/tags/admin/email/sentEmail.tag
src/main/webapp/WEB-INF/tags/admin/email/trashEmail.tag
src/main/webapp/WEB-INF/tags/admin/search/instructorRow.tag
src/main/webapp/WEB-INF/tags/admin/search/studentRow.tag
src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorListPanelBody.tag
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/instructorCourseEditManager.html
src/test/resources/pages/instructorCourseEditObserver.html
src/test/resources/pages/instructorCourseEditTutor.html

readonly="readonly" should be simply readonly to follow HTML standard #5206

---

src/main/java/teammates/common/datatransfer/FeedbackRubricQuestionDetails.java

Changes the indentation of class FeedbackRubricQuestionDetails.java in order to maintain code consistency #5187

---

src/main/webapp/about.html

Update about.html with contributors from V5.75 #5192

---

src/main/java/teammates/common/util/FieldValidator.java
src/main/java/teammates/storage/search/SearchQuery.java
src/test/java/teammates/test/cases/ui/browsertests/AdminSearchPageUiTest.java

 Instructor search displays more results than it should #3985 

---

src/main/webapp/about.html

Update about.html with contributors from V5.76 and V5.77 #5222

---

devdocs/settingUp.md

 Add a 'Table of Content' to the settingUp.md #5112 

---

devdocs/settingUp.md
devdocs/troubleshooting-guide.md
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java
src/test/java/teammates/test/driver/TestProperties.java
src/test/java/teammates/test/pageobjects/Browser.java
src/test/resources/test.template.properties

Remove support for non-Firefox browsers for testing #5264

---

src/main/webapp/WEB-INF/tags/admin/home/adminCreateInstructorAccountWithOneBoxForm.tag
src/test/resources/pages/adminHomePage.html

 admin create account page: data format can be misleading #5162

---

src/main/webapp/js/datepicker.js

 Remove unused jquery method calls in datepicker.js #5276 

---

src/test/java/teammates/test/cases/common/AccountAttributesTest.java
src/test/java/teammates/test/cases/common/StudentAttributesTest.java
src/test/java/teammates/test/cases/logic/BackDoorLogicTest.java
src/test/java/teammates/test/cases/ui/InstructorCourseEnrollSaveActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/AdminEmailPageUiTest.java

Remove magic strings that are already defined in FieldValidator #5281

---

src/main/webapp/js/common.js
src/main/webapp/js/countryCodes.js
src/main/webapp/js/feedbackSubmissionsEdit.js
src/main/webapp/js/instructor.js
src/main/webapp/js/instructorCourseEdit.js
src/main/webapp/js/instructorFeedbackEdit.js
src/main/webapp/js/instructorFeedbacks.js
src/main/webapp/js/instructorStudentListAjax.js
src/main/webapp/js/instructorStudentRecords.js
src/main/webapp/js/omniComment.js
static-analysis/teammates.eslintrc

This time the rules involve around the theme of conditionals: no-else-return, no-lonely-if, no-fallthrough, and default-case. To illustrate:
```javascript
if (condition) {
return 123;
} else { // no-else-return will complain
if (anotherCondition) { // no-lonely-if will complain
switch (variable) {
case 1:
var a = 1;
// no-fallthrough will complain
case 2:
case 3: // but no-fallthrough is fine with this
var a = 2;
break;
// default-case will complain
}
}
}
```

Add new rules to ESLint - Conditionals

---

src/test/java/teammates/test/cases/testdriver/BackDoorTest.java
src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackQuestionSubmitPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentProfilePageUiTest.java
src/test/java/teammates/test/cases/ui/pagedata/StudentFeedbackResultsPageDataTest.java
src/test/java/teammates/test/pageobjects/AdminHomePage.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
src/test/java/teammates/test/pageobjects/StudentProfilePage.java
src/test/resources/pages/studentFeedbackQuestionSubmitPageDeadLineExceeded.html

Fixes #5302 
The explanations can be found in each commit message.
There's a recent newcomer, `AllJsTests.java`, but I haven't got enough information as for why it failed occasionally.
Add: one more than I haven't fixed is `InstructorFeedbackPageUiTest.testCopyActions`. Also haven't got enough information.

Fix tests that fail often in Travis #5302

---

src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java

InstructorFeedbackPageUiTest is failing on live server #4956

---

src/test/java/teammates/test/pageobjects/InstructorCoursesPage.java
src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java
static-analysis/teammates-checkstyle.xml

Added generic whitespace rule
Refer to [here](http://checkstyle.sourceforge.net/config_whitespace.html#GenericWhitespace) for more information about the rule.

Add new rules to Checkstyle-Generic whitespace

---

devdocs/staticAnalysis.md

Add checkstyle plugin setup instructions #5326

---

src/client/java/teammates/client/scripts/DataMigrationAppendInstitutionForAccounts.java
src/client/java/teammates/client/scripts/OfflineBackup.java
src/main/java/teammates/common/datatransfer/FeedbackMsqQuestionDetails.java
src/main/java/teammates/common/datatransfer/FeedbackMsqResponseDetails.java
src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/main/java/teammates/common/datatransfer/StudentAttributes.java
src/main/java/teammates/common/util/FieldValidator.java
src/main/java/teammates/common/util/Sanitizer.java
src/main/java/teammates/logic/backdoor/BackDoorLogic.java
src/main/java/teammates/logic/core/CoursesLogic.java
src/main/java/teammates/logic/core/StudentsLogic.java
src/main/java/teammates/storage/api/AccountsDb.java
src/main/java/teammates/storage/search/SearchQuery.java
src/main/java/teammates/ui/controller/AdminActivityLogPageData.java
src/main/java/teammates/ui/controller/AdminEmailLogPageData.java
src/main/java/teammates/ui/controller/InstructorCoursesPageData.java
src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
src/main/java/teammates/ui/controller/PageData.java
src/test/java/teammates/test/cases/BaseComponentTestCase.java
src/test/java/teammates/test/cases/testdriver/BackDoorTest.java
src/test/java/teammates/test/cases/ui/StudentCourseJoinAuthenticatedActionTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java

Preferable way of checking if string is empty #5331

---

src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/logic/core/InstructorsLogic.java
src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/java/teammates/test/cases/logic/InstructorsLogicTest.java

Unused code in Logic #5346

---

src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/logic/core/Sendgrid.java
src/main/java/teammates/storage/api/FeedbackResponsesDb.java
src/main/java/teammates/ui/controller/InstructorCourseAddAction.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
src/test/java/teammates/test/cases/ui/StudentFeedbackResultsPageActionTest.java
src/test/java/teammates/test/cases/ui/browsertests/AutomatedSessionRemindersTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackSubmitPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentCourseJoinConfirmationPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java
src/test/java/teammates/test/pageobjects/StudentHomePage.java
static-analysis/teammates-checkstyle.xml

Fixes LocalVariableName and ParameterName

Add new rules to Checkstyle - Local variables and parameter names

---

src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java

Avoid tautology in InstructorFeedbackResultsPageData.java #5330

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageAction.java
src/main/webapp/WEB-INF/tags/instructor/results/filterPanel.tag

Extract sort types for feedback session results into constants #5332

---

src/main/java/teammates/ui/controller/InstructorCourseDetailsPageAction.java
src/main/java/teammates/ui/controller/InstructorCourseDetailsPageData.java
src/test/java/teammates/test/cases/ui/pagedata/InstructorCourseDetailsPageDataTest.java

InstructorCourseDetailsPageData: students parameter in init method is not used #5550

---

src/main/webapp/about.html

Update about.html with contributors from V5.79 #5527

---

src/main/webapp/js/omniComment.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorCommentsPageUiTest.java
src/test/resources/pages/instructorCommentsPageShowCommentsForPrivate.html
src/test/resources/pages/instructorCommentsPageShowCommentsForPublic.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAll.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromAllStatus.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromOthers.html
src/test/resources/pages/instructorCommentsPageShowCommentsFromYou.html

Fixes #5512 
Also fixed test failure on line 261 of InstructorCommentsPageUiTest.

instructorCommentsPage: Question Panels are not hidden when content is empty #5512

---

devdocs/troubleshooting-guide.md

Fixes #5650
@chowyb since you're the one complaining about this 😛

Add portion on updating dependencies to troubleshooting guide #5650

---

src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentAjaxPageData.java

Fix InstructorFeedbackResponseCommentAjaxPageData getCommentIds #5689

---

src/main/webapp/js/richTextEditor.js

Module for rich-text editor #5681

---

src/main/java/teammates/logic/core/EmailGenerator.java
src/test/java/teammates/test/cases/automated/FeedbackSessionClosingReminderTest.java
src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java
src/test/resources/emails/systemCrashReportEmail.html

Sessions not viewable/answerable to students still sends email copy to instructors #5699

---

build.gradle
src/main/java/teammates/common/util/Sanitizer.java
src/test/java/teammates/test/cases/common/SanitizerTest.java

Rich-text sanitization #5700

---

src/main/java/teammates/logic/core/FeedbackResponsesLogic.java

 Remove erroneously committed development log message #5595

---

src/main/webapp/js/adminEmail.js
src/main/webapp/js/richTextEditor.js
src/main/webapp/jsp/adminEmail.jsp

Rich-text editor module for admin email #5708

---

src/main/java/teammates/common/util/Sanitizer.java
src/test/java/teammates/test/cases/common/SanitizerTest.java

Expand rich-text whitelist #5715

---

src/main/webapp/about.html

Update about.html with contributors from V5.81 #5590

---

src/main/java/teammates/common/util/StringHelper.java

Typo in StringHelper.java: repression #5253

---

src/main/webapp/about.jsp

Update about.html with contributors from V5.82 #5731

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java

Fixes #5735
Need testing in live server however since it's failing there.

 InstructorFeedbackResultsPageUiTest fails on live server #5735 

---

src/main/webapp/about.jsp

Update about.jsp with contributors from V5.83 #5815

---

src/main/java/teammates/storage/api/FeedbackQuestionsDb.java

Utility method for converting List<FeedbackQuestions> to List<FeedbackQuestionAttributes> #5835

---

src/main/java/teammates/common/datatransfer/FeedbackQuestionAttributes.java
src/main/java/teammates/common/datatransfer/FeedbackSessionAttributes.java
src/main/java/teammates/common/datatransfer/InstructorAttributes.java
src/main/java/teammates/common/datatransfer/StudentAttributes.java
src/test/java/teammates/test/cases/BaseComponentTestCase.java

verifyPresentInDatastore should not modify parameters #5833

---

src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorListPanelBody.tag
src/main/webapp/instructorHelp.jsp
src/main/webapp/js/instructorCourseEdit.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseEditPageUiTest.java
src/test/resources/pages/instructorCourseEditAddInstructor.html
src/test/resources/pages/instructorCourseEditCancelEditCoownerForm.html
src/test/resources/pages/instructorCourseEditCancelEditCustomInstructorForm.html
src/test/resources/pages/instructorCourseEditCancelEditCustomInstructorPermissionsForm.html
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/instructorCourseEditManager.html
src/test/resources/pages/instructorCourseEditObserver.html
src/test/resources/pages/instructorCourseEditTutor.html
src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html

courseEditInstructorListPanelBody.tag: form id contains a stray caret #5655

---

src/test/resources/data/MashupPageUiTest.json

MashupPageUiTest is failing #5851

---

src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/ui/controller/InstructorFeedbackQuestionCopyAction.java
src/main/webapp/js/instructorFeedbackEdit.js
src/main/webapp/jsp/instructorFeedbackQuestionCopyModal.jsp
src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackQuestionCopyActionTest.java
src/test/resources/pages/instructorFeedbackCopyQuestionModal.html

Fixes #5844
Although this is for #5839, I'll try to merge this to master first, since that other pull requests can't pass all tests yet, making it harder to review this. 
The new fields won't do anything on this PR, and will be unused

Add courseId and feedbackSessionName input fields to InstructorFeedbackQuestionCopy modal #5844

---

src/test/java/teammates/test/cases/ui/AdminSearchPageActionTest.java

Reword TODO into proper comment for AdminSearchPage #5596

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java

InstructorFeedbackEditPageUiTest failing on live server #5869

---

src/main/webapp/enableJS.jsp

Fixes #5832
Fixed the typo
Changed 'conformation' to 'confirmation'

Typo in enableJS.jsp: conformation #5832

---

src/main/webapp/about.jsp

Update about.jsp with contributors from V5.85 #5825

---

src/main/webapp/js/common.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorSearchPageUiTest.java
src/test/resources/pages/InstructorSearchPageSearchCommentsAsHelper.html
src/test/resources/pages/InstructorSearchPageSearchStudentsForStudent1.html
src/test/resources/pages/InstructorSearchPageSearchStudentsForStudent2.html

Search result highlighting doesn't work if the words are not in order #5897

---

src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorListPanelBody.tag
src/test/resources/pages/instructorCourseEditAddInstructor.html
src/test/resources/pages/instructorCourseEditCoowner.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
src/test/resources/pages/instructorCourseEditHelper.html
src/test/resources/pages/instructorCourseEditManager.html
src/test/resources/pages/instructorCourseEditObserver.html
src/test/resources/pages/instructorCourseEditTutor.html
src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html

Instructor edit course: Show 'Not joined yet' for instructors yet to join #5901

---

devdocs/settingUp.md
src/test/java/teammates/test/cases/ui/browsertests/AllJsTests.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentListPageUiTest.java
src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java
src/test/java/teammates/test/driver/HtmlHelper.java
src/test/java/teammates/test/driver/TestProperties.java
src/test/java/teammates/test/pageobjects/AppPage.java
src/test/java/teammates/test/pageobjects/Browser.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java
src/test/resources/pages/instructorFeedbackEditEmpty.html
src/test/resources/pages/instructorFeedbackEmptyAll.html
src/test/resources/test.template.properties

Fixes #5929 
Will explain the finer details in the code sections themselves.

Revive the support for Chrome browser for testing #5929

---

src/main/webapp/about.jsp

Update about.jsp with contributors from V5.87 #5947

---

src/main/java/teammates/common/datatransfer/FeedbackPathAttributes.java
src/main/java/teammates/common/datatransfer/FeedbackQuestionAttributes.java
src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
src/main/java/teammates/logic/api/Logic.java
src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
src/main/java/teammates/ui/controller/StudentFeedbackResultsPageData.java
src/main/java/teammates/ui/controller/StudentHomePageAction.java
src/main/java/teammates/ui/template/FeedbackSubmissionEditQuestion.java
src/main/webapp/js/instructorFeedbackEdit/customFeedbackPaths.js
src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
src/test/java/teammates/test/cases/ui/FeedbackSessionStatsPageActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackQuestionEditActionTest.java
src/test/java/teammates/test/cases/ui/InstructorFeedbackRemindParticularStudentsPageActionTest.java
src/test/resources/data/typicalDataBundle.json
src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html

Created this PR for early review, its not entirely completed yet. In particular I haven't added many tests for it yet. I will continue to work on it as it is being reviewed.
1. Added functionality to support the correct display of feedback results for questions with custom feedback paths
2. Edited student home page to display sessions containing questions with custom feedback paths for students 
Again this is under the assumption that all the feedback paths input are valid.

Custom Feedback Paths: Results

---

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java

Fixes #5993 
Not sure how switching preview by instructor/preview by student smoothens the test run, but I managed to get 5 continuous passes that way (when preview by student goes first I got stopped at 2nd run or so).

InstructorFeedbackEditPageUiTest failing on dev server #5993

---

src/main/java/teammates/common/util/Const.java
src/main/java/teammates/logic/automated/CourseJoinRemindEmailWorkerServlet.java
src/main/java/teammates/logic/core/StudentsLogic.java
src/main/webapp/WEB-INF/queue.xml
src/main/webapp/WEB-INF/web.xml
src/test/java/teammates/test/cases/automated/CourseJoinRemindEmailTaskQueueTest.java

Fixes #6011 
Re-opened from #6012

Send join reminder: timeout in big courses #6011

---

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java

instructorFeedbackResultsDownload crashes for big courses #6019

---

src/main/webapp/js/timezone.js

Instructor create course: should show timezone offset #6010

---

src/main/webapp/js/common.js
src/main/webapp/js/instructorFeedbackEdit.js
src/main/webapp/js/instructorFeedbacks.js

Instructor copy session: 'copy' button doesn't show any activity after clicking #5986

---

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
src/main/java/teammates/storage/api/FeedbackSessionsDb.java
src/test/java/teammates/test/cases/automated/FeedbackSessionOpeningReminderTest.java
src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java

Fixes #6018
Might break some tests, will let Travis run first.

session opening reminders timeout #6018

---

src/main/webapp/WEB-INF/tags/student/courseDetails/displayTeammates.tag
src/main/webapp/js/common.js
src/main/webapp/js/instructor.js
src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.js
src/main/webapp/js/instructorFeedbackResultsAjaxByGRQ.js
src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.js
src/main/webapp/js/instructorFeedbackResultsAjaxByRGQ.js
src/main/webapp/js/instructorFeedbackResultsAjaxByRQG.js
src/main/webapp/js/instructorStudentListAjax.js
src/main/webapp/jsp/studentCourseDetails.jsp
src/main/webapp/stylesheets/teammatesCommon.css
src/test/java/teammates/test/cases/ui/StudentCourseDetailsPageActionTest.java
src/test/java/teammates/test/cases/ui/StudentProfileEditSaveActionTest.java
src/test/resources/pages/newlyJoinedInstructorStudentCourseDetailsPage.html
src/test/resources/pages/studentCourseDetailsWithTeammatesHTML.html
src/test/resources/pages/studentCourseDetailsWithoutTeammatesHTML.html

student view team: Show team member profile photo #5943

---

src/main/java/teammates/ui/controller/AdminSearchPageAction.java
src/main/webapp/js/common.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorSearchPageUiTest.java
src/test/resources/pages/InstructorSearchPageSearchStudentsForStudent2WithExactString.html

admin search: results are not highlighted #5982

---

src/main/java/teammates/common/datatransfer/FeedbackSessionAttributes.java

Feedback session closed email not working properly in non-UTC timezone #6053

---

src/main/java/teammates/ui/controller/InstructorHomeCourseAjaxPageData.java
src/main/java/teammates/ui/template/ElementTag.java
src/main/webapp/WEB-INF/tags/instructor/home/coursePanel.tag
src/main/webapp/instructorHelp.jsp
src/main/webapp/stylesheets/teammatesCommon.css
src/test/resources/pages/InstructorHomeHTML.html
src/test/resources/pages/InstructorHomeHTMLResponseRateFail.html
src/test/resources/pages/InstructorHomeHTMLSortByDate.html
src/test/resources/pages/InstructorHomeHTMLSortById.html
src/test/resources/pages/InstructorHomeHTMLSortByName.html
src/test/resources/pages/InstructorHomeHTMLSortSessionsByEndDate.html
src/test/resources/pages/InstructorHomeHTMLSortSessionsByName.html
src/test/resources/pages/InstructorHomeHTMLSortSessionsByStartDate.html
src/test/resources/pages/InstructorHomeHTMLWithHelperView.html
src/test/resources/pages/InstructorHomeHTMLWithUnloadedCourse.html
src/test/resources/pages/InstructorHomeNewInstructorWithSampleCourse.html
src/test/resources/pages/InstructorSearchPageSearchCommentsAsHelper.html
src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
src/test/resources/pages/newlyJoinedInstructorFeedbackSessionPublished.html
src/test/resources/pages/newlyJoinedInstructorFeedbackSessionRemind.html
src/test/resources/pages/newlyJoinedInstructorFeedbackSessionUnpublished.html
src/test/resources/pages/newlyJoinedInstructorHomePage.html

Instructor home page: reorganize buttons on the course panel #5983

---

src/main/webapp/about.jsp

Update about.jsp with contributors from V5.89 #6044

---

src/main/webapp/js/userMap.js

Fixes #5226
This is a simple one. I updated the text as indicated in the issue.

Users map: institution(s) --> institutions #5226

---

src/main/webapp/js/instructorFeedbackEdit.js
src/main/webapp/js/instructorFeedbackEdit/visibilityOptions.js
src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html

'Instructor only' visibility is buggy #6078

---

docs/design.md

Typo in design.md: mechanims #5252

---

docs/design.md

Fixes #5251 
Changed "the , the" to "the" on line 55.

Extra "the" and comma in design.md #5251

---

src/main/webapp/about.jsp

Update about.jsp with contributors from V5.90 #6117

---

README.md
src/main/webapp/about.jsp
src/main/webapp/index.jsp

Mention about participation in GSoC 2016 in README and about page #6119

---

src/main/java/teammates/storage/search/SearchManager.java

Fixes #6131
Hey hopefully this is what you were looking for.

Remove strange logging in SearchManager.java #6131

---

src/main/webapp/index.jsp

Fixes #6129 
Changed line 57 from "130" to "190"

Update number of contributors in index.jsp #6129

---

docs/orientation-guide.md

Fixes #6143
Add link to setting up guide.

Missing link in the Orientation Guide #6143

---

src/main/webapp/mashup.jsp

Fixes #6146 
I placed the usermap.jsp below request.jsp & put the link name as UserMap Page. Please let me know in case any of them need to be modified.

Add usermap page to mashup.jsp #6146
