TEAMMATES/teammates

src/main/java/teammates/client/scripts/DataMigrationForInstructorsCourseArchiving.java, src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/CoursesLogic.java, src/main/java/teammates/logic/core/EvaluationsLogic.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/logic/core/InstructorsLogic.java, src/main/java/teammates/storage/api/InstructorsDb.java, src/main/java/teammates/storage/entity/Instructor.java, src/main/java/teammates/ui/controller/InstructorFeedbackAddAction.java, src/main/java/teammates/ui/controller/InstructorFeedbackCopyAction.java, src/main/java/teammates/ui/controller/InstructorFeedbacksPageAction.java, src/main/java/teammates/ui/controller/InstructorHomePageAction.java, src/test/java/teammates/test/cases/logic/CoursesLogicTest.java, src/test/java/teammates/test/cases/logic/EvaluationsLogicTest.java, src/test/java/teammates/test/cases/storage/InstructorsDbTest.java, src/test/resources/data/typicalDataBundle.json
Fixes #1711 
Need to run the migration script DataMigrationForInstructorsCourseArchiving.java to create isArchived indexes for filtering.
Script also generates registration key if null.
There are still repeated DB calls, where instructor list is retrieved multiple times. Added todos for that issue.
=> Reduce the load on the backend for 'Omit archived courses' #1711

src/test/java/teammates/test/cases/ui/StudentCommentsPageActionTest.java, src/test/java/teammates/test/cases/ui/StudentHomePageActionTest.java
Fixes #2859
Fixing the priority/order of the tests seems to prevent the conflict.
This does not solve the root cause however, as both tests (and many others) use the typicalDataBundle.json for testing.
=> StudentHomePageActionTest and StudentCommentsPageActionTest fail if they run together #2859

src/main/webapp/stylesheets/teammates.css
=> Duplicated definitions of '#navbar li a' and '#navbar li a:hover' in teammates.css #3093

runtests.sh
Instead of hardcoding all the jar files in the classpath, use wildchars to include the jars in a folder. This will reduce hard to debug errors due to typos in hardcoded jar file names.
Running the failed tests 5 times can be put in a loop that is run 5 times, instead of writing the same line 5 times.
Please review and push to master if the changes look good. Fixes #3123
=> Simplified and updated runtests.sh #3123

runtests.bat
Instead of hardcoding all the jar files in the classpath, use wildchars to include the jars in a folder. This will reduce hard to debug errors due to typos in hardcoded jar file names.
Running the failed tests 5 times can be put in a loop that is run 5 times, instead of writing the same line 5 times.
Please review and push to master. Fixes #3125
=> Simplified and updated runtests.bat. #3125

src/main/java/teammates/common/datatransfer/FeedbackSessionAttributes.java, src/main/java/teammates/ui/controller/StudentCommentsPageAction.java
Fixes #2679. Dev green. Now - 
1) First the Comments for students, ordered in reverse chronological order of comment
creation time appears. (This was already the case)
2) Next each Feedback session appears. Those sessions which have the latest comment come first. (This was NOT the case earlier).
3) Within each feedback session, questions are sorted as per their question no (This was already the case)
4) Within each question, comments are sorted such that earlier comment comes first (This was already the case)
Let me know if any changes are to be made.  
@damithc
=> studentCommentsView page should be sorted 'recent on top' #2679

src/main/webapp/stylesheets/teammatesCommon.css
Fixes #3214.
Few text-editors were highlighting it. So, I thought of correcting it to comply with the general spelling of the color used in the web.
=> Word 'gray' misspelled as 'grey' in teammatesCommon.css #3214

src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java, src/main/java/teammates/common/util/Const.java, src/main/webapp/instructorHelp.html, src/main/webapp/jsp/instructorEvalResults.jsp, src/main/webapp/jsp/instructorEvalSubmission.jsp, src/main/webapp/jsp/instructorStudentRecords.jsp, src/test/resources/pages/instructorEvalResultsClosedEval.html, src/test/resources/pages/instructorEvalResultsOpenEval.html, src/test/resources/pages/instructorEvalResultsOpenEvalByReviewee.html, src/test/resources/pages/instructorEvalResultsOpenEvalByReviewer.html, src/test/resources/pages/instructorEvalResultsP2PDisabled.html, src/test/resources/pages/instructorEvalResultsP2PDisabledByReviewee.html, src/test/resources/pages/instructorEvalResultsP2PDisabledByReviewer.html, src/test/resources/pages/instructorEvalResultsPublishedEval.html, src/test/resources/pages/instructorEvalSubmissionView.html, src/test/resources/pages/instructorEvalSubmissionViewP2pDisabled.html, src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html, src/test/resources/pages/instructorFeedbackResultsPageOpen.html, src/test/resources/pages/instructorFeedbackResultsPageOpenWithHelperView2.html, src/test/resources/pages/instructorFeedbackResultsSortQuestion.html, src/test/resources/pages/instructorFeedbackResultsSortQuestionSearch.html, src/test/resources/pages/instructorStudentRecords.html, src/test/resources/pages/instructorStudentRecordsAjaxLoading.html, src/test/resources/pages/instructorStudentRecordsPageWithPrivateFeedback.html
Fixes #3255 
Dev green.
Currently uses a HTML escape character in the constant.
Would it be preferable to sanitise it further down the chain?
Also, I changed the string in instructorHelp.html to maintain consistency.
=> Instructor feedback results: typo in tooltip about CC #3255

src/main/webapp/stylesheets/teammatesCommon.css
Fixes #3293 
As mentioned in the issue, the new CSS improves the responsiveness of the navbar by, at 992px and below, transforming it into a hamburger bar and forcing the navbar container to exhibit container-fluid behaviour (auto width, as opposed to the normal responsive-fixed-width container behaviour).
=> Main Titles(h1 tags) are covered by navigation bar for a certain page width #3293

src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java
Fixes #3315
The root cause of this issue is this action in line 217:
`coursesPage.addCourse(validCourse.id, validCourse.name);`
Of course this action is perfectly valid. The trouble, however, comes if this test fails due to any reason after that action is successfully executed, but before we reach the testDeleteAction() part.
_Because there is no BackDoor operation to delete the course._
As such, any subsequent re-run of the test will result in:
And this fails the comparison in line 128.
=> Test failing in instructorCoursesPageUiTest #3315

src/main/java/teammates/common/util/Const.java, src/main/java/teammates/ui/controller/FeedbackQuestionSubmissionEditPageAction.java, src/main/java/teammates/ui/controller/FeedbackQuestionSubmissionEditPageData.java, src/main/java/teammates/ui/controller/FeedbackQuestionSubmissionEditSaveAction.java, src/main/java/teammates/ui/controller/StudentFeedbackResultsPageAction.java, src/main/java/teammates/ui/controller/StudentFeedbackResultsPageData.java, src/main/webapp/jsp/studentFeedbackQuestionSubmissionEdit.jsp, src/main/webapp/jsp/studentFeedbackResults.jsp, src/main/webapp/jsp/studentFeedbackSubmissionEdit.jsp, src/main/webapp/stylesheets/teammatesCommon.css, src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageClosed.html, src/test/resources/pages/unregisteredStudentFeedbackQuestionSubmitPageOpen.html, src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html, src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html, src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html, src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Fixes #3291 
In addition to the "Submit Feedback" page, other pages that an unregistered student can see (Submit Feedback Question & View Feedback Results) are also updated.
* **Submit Feedback**
* **Submit Feedback Question**
* **View Feedback Results**
=> Show a 'You are submitting as ...." message when an unregistered student submit responses #3291

src/main/webapp/js/instructorFeedbackEdit.js
Fixes #2536 
Tracing down, I found out that the source of the problem is here:
Somehow, this dropdown value is not updated to Giver's team members and Giver. It looks trivial, 
however the effect snowballed down like this:
1. Remember that options other than Giver's team members and Giver are disabled.
2. Because it is disabled _and_ "selected", it will be passed as null, and there goes our NPE.
I fixed it by changing .attr in the js file to .prop. However I'm really at a loss of explanation why.
1. Not because of .attr. If it was, the other dropdown (givertype) should've given problems as well but it didn't.
2. Not because of too many options. I tried reducing the # of options to 4 (same as givertype), still happened.
3. Even more confusing: when I looked at the HTML source of the …
=> New contribution question: Null recipient type #2536

src/main/java/teammates/client/scripts/DataMigrationEvaluationsToFeedbackSessions.java, src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java, src/main/java/teammates/storage/api/EntitiesDb.java, src/main/java/teammates/storage/api/FeedbackQuestionsDb.java
Fixes #3365
I used createFeedbackQuestionForTemplate, which does not check for the existence of the feedback session, instead of createFeedbackQuestion in case of problems with eventual consistency.
DataMigrationForResponseRate should be run after running DataMigrationEvaluationsToFeedbackSessions should update the response rate.
=> Update DataMigrationEvaluationsToFeedbackSessions to delete evaluations #3365

src/main/webapp/js/instructorFeedbackEdit.js, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
Fixes #3357
This issue is very reminiscent of #3184 in the sense that the cause is exactly the same: # in session name. As such the remedy is also the same.
I can't use `encodeURIComponent` because it will also encode the + used in the URL in place of space, and that will cause problems.
Also, I'm two tests away from dev green, but they're failing in master anyway (#3371 and #3374) so I guess I won't be fixing them here.
(edit: I stand corrected: `encodeURIComponent` is the better solution as it also fixes #3376 )
=> Assertion failure in FeedbackQuestionSubmissionEditPageAction #3357

src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
Fixes #3417 
The problem lies in this code block:
For the assertion in line 184 to pass, `sessionList` must contain `session` which is defined above. `getFeedbackSessionsClosingWithinTimeLimit` will return feedback sessions that are _strictly before_ the time limit, accurate to the milliseconds.
Failure occurs if between lines 178 and 179 the time elapsed is less than one millisecond (apparently it's possible). That is why adding waitBriefly (10 ms) solves the problem.
=> FeedbackSessionsLogicTest occasionally fails at line 184 #3417

src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java, src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java
Fixes #3440 
(deleted the old explanation: they're totally off tangent and not addressing the issue).
The fails occur if the log entries are all from test e-mail accounts (ending with .tmt), because they will be _invisible_ in the logs table.
=> AdminActivityLogPageUiTest occasional fails due to IndexOutOfBoundException #3440

src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Fixes #3444 
This problem arises because of how Firefox deals with events depending on whether the webdriver browser is in focus or not.
On master, this test actually passes if the browser is running and we actively look at it and let it run because it is in focus and the onchange event will fire in that case.
However, when we allow the tests to run in the background and we go into Eclipse and start doing our own things like debugging, thinking of how we can write better code etc., Firefox is no longer in focus and sending Tab keys in the AppPage.java might not work as we intended it to.
Notice how this test seems to fail randomly and then when there are less and less tests running suddenly it passes? That's because when there are less browsers on, we have a higher chance or tendency to …
=> FeedbackNumScaleQuestionUiTest test fail randomly on line 113-114 #3444

src/test/java/teammates/test/cases/common/StudentProfileAttributesTest.java
Fixes #3450 
Not a fix per se, but rather an explanation on how to actually make the test work without fail.
Trying to figure out if the setting can be changed such that this can be forced to everyone.
=> Inconsistent behavior of getJsonString in test #3450

.launches/All tests.launch, .launches/Component tests.launch, .launches/Frequent tests.launch, .launches/Heavy tests.launch, .launches/Integration tests.launch, .launches/Occasional tests.launch, .launches/Run failed tests.launch, .launches/Staging tests.launch
Fixes #3452 
Changed launching of component tests to stack size 2mb, will help with reducing number of random failures
=> BackDoorTest.java sometimes fail due to java.lang.StackOverflowError #3452

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
Fixes #3445 
We look back back to commit 9a74903205eb66407024433ea29d3f14c7e1c422, where the comment row ID suffixes are changed (possibly due to change in implementation).
_Notice that there's a line that's missed._
And that's it. We're forced to wait for 30 seconds for a non-existent element.
=> InstructorFeedbackResultsPageUiTest test waiting excessively long around line 456-458 #3445

src/main/webapp/js/index.js
Fixes #3477
In case anyone is interested
After adding for null check, no more red blobs -> 
Once index.js is loaded, there is a set interval for looping testimonials but no check as to whether the element is there, when on our js test html it is null and every 5000 ms it will loop and result in an error, sometimes during our entire testing suite if the assert from Java comes later than that, it will find that there is a JavaScript error and that looping error is the one that is found, not an actual JavaScript testing error.
=> executeJsTests can sometimes fail #3477

src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Fixes #3485 by giving the modal waiting time to go up to 5 seconds
It used to be allowed up to 1 second, sometimes it fails but most of the time it doesn't.
Considering that this wait can return early from Selenium if it is found, it shouldn't affect the timing by too much (most of the time it takes < 1 second anyway). On the off chance that it takes > 1 second we should let it continue finding it -> this happens most often when we run the entire test suite and it might take longer to find elements due to taking longer to load.
=> InstructorFeedbackEditCopyUiTest can sometimes fail #3485

src/test/resources/data/InstructorCommentsPageUiTest.json
Fixes #3524 
InstructorCommentsPage arranges the courses based on the createdAt time, which the json file didn't provide previously (as the result the page result is random).
=> InstructorCommentsPageUiTest occasionally fails at line 105 #3524

src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java
Fixes #3537
Gave it 5 seconds to be loaded, can return earlier (and most likely will), it used to timeout because Selenium isn't waiting for it after clicking add, which can make it timeout with an exception in 16ms, error is prone when running entire test suite and it might take longer than 16ms for the error message to actually load
=> InstructorCommentsPageUiTest occasionally fails at line 177 #3537

src/test/java/teammates/test/pageobjects/InstructorHomePage.java
Fixes #3538 
By waiting briefly to let AJAX finish, instantly verifying the HTML sometimes make it try to verify while it is still loading
=> AdminHomePageUiTest occasionally fails when verifying for NJI #3538

src/main/java/teammates/common/util/Sanitizer.java, src/main/webapp/jsp/instructorCourseJoinConfirmation.jsp
Fixes #3430 
Along with it, also '#' and '+' which did give problems as well (although I don't think there are institutes with those characters in their name :p)
=> '&' is not handled properly in the page footer #3430

src/test/java/teammates/test/cases/ui/browsertests/StudentCourseJoinConfirmationPageUiTest.java
Fixes #3607 
This is one of the pages that can be left behind when it fails:
And everything suddenly becomes obvious.
=> StudentCourseJoinConfirmationPageUiTest fails due to invalid login page #3607

src/main/webapp/WEB-INF/cron.xml
Fixes #3602.
Removed the cron jobs for evaluations, update the backup cron job to use Google Cloud Storage instead of the blobstore. 
Note that using the google cloud storage requires the use of a cloud storage bucket, and the url's gs_bucket_name parameter needs to be modified to use it.
=> Update the backup cron job #3602

src/test/java/teammates/test/pageobjects/StudentProfilePage.java
Fixes #3624 
There has been a TODO to remove it for quite some time, might as well remove it now since I saw it while working on the random failing test case.
=> Remove unused method in StudentProfilePage Page Object #3624

.classpath, devdocs/settingUp.md, src/test/java/teammates/test/pageobjects/Browser.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
Fixes #3643 
Download Selenium [here](http://selenium-release.storage.googleapis.com/index.html?path=2.46/), only `selenium-java-2.46.0-srcs.jar` (found inside the Java zip) and `selenium-server-standalone-2.46.0.jar` are required. Place them on `src/test/resources/lib/selenium/`.
Update Firefox to the latest one (38.0.5) [here](https://www.mozilla.org/en-US/firefox/new/).
Eclipse will show a few warnings due to deprecations and what-nots but everything will still work.
=> Migrate to latest version of Selenium + Firefox #3643

src/main/webapp/WEB-INF/tags/instructor/instructorPage.tag, src/main/webapp/WEB-INF/tags/page.tag
Changes a condition in page.tag to display the footer if the account has an institute rather than whether it is an instructor.
=> JSTL - page.tag fix.

src/main/java/teammates/logic/core/CoursesLogic.java, src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
Extension of #3651.
`getFeedbackSessionsForUserInCourse` checks first for course presence, which is redundant since we have already queried for the course beforehand.
The added method (`getFeedbackSessionsForUserInCourseSkipCheck`) is not new per se but rather a separation from the existing method.
=> Suppress redundant queries in StudentHomePageAction, part 3

src/test/java/teammates/test/cases/ui/StudentFeedbackResultsPageActionTest.java
The test failure is caused by the incorrectly used `TimeHelper.now`. The intention is correct (as can be seen in the comment), but `TimeHelper.now` is not the correct tool to use. Here is why:
Between lines 188 and 191, time will elapse, perhaps just a few milliseconds or even hundreds of microseconds. However, if the time elapsed is enough to change the recorded time (precision up to seconds) in the `expectedInfoList`, the test will fail.
For example:
Line 188 `pageData`, `resultVisibleFromTime` 00:00:00.500
Line 191 `dataBundle`, `resultVisibleFromTime` 00:00:00.502
This is perfectly fine. But if this happens:
Line 188 `pageData`, `resultVisibleFromTime` 00:00:00.999
Line 191 `dataBundle`, `resultVisibleFromTime` 00:00:01.001
The test will fail.
To achieve the same without having to …
=> StudentFeedbackResultsPageActionTest occasionally fails at line 199 #3700

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
Extension of #3651.
The number of query made for the same InstructorAttributes is the amount of feedback session, which is redundant.
=> Suppress redundant queries in StudentHomePageAction, part 4

src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/ui/controller/StudentHomePageAction.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
Extension of #3651.
`isFeedbackSessionCompletedByStudent` queries for FeedbackSessionAttributes from the supplied session name and course ID, but these supplied parameters came from previously queried FeedbackSessionAttributes, making querying the Attributes once again redundant.
Again, the added method is not new per se but rather a separation from the existing method.
=> Suppress redundant queries in StudentHomePageAction, part 5

src/main/webapp/js/common.js, src/main/webapp/js/contextualcomments.js, src/main/webapp/js/feedbackResponseComments.js, src/main/webapp/js/instructorStudentList.js, src/main/webapp/js/omniComment.js
Fixes #3876 
This is a safe way of ensuring that we have a functionality we need in older browsers that may not support ES6 but also use the native (already included) function on newer browsers.
This also helps to prevent confusion by ensuring that all strings have the same behavior rather than it having a certain behavior in some context and then not in some other context.
=> Multiple String.prototype.contains() strewn across the app #3876

src/main/java/teammates/ui/controller/InstructorCourseDetailsPageAction.java, src/main/webapp/WEB-INF/tags/instructor/course/studentsTable.tag, src/test/java/teammates/test/cases/ui/InstructorCourseDetailsPageActionTest.java, src/test/resources/pages/InstructorCourseDetailsEmptyCourse.html
Fix #3933
@damithc Does this look good to you?
=> Instructor Course Details Page shows table header with no body if there are no students #3933

src/main/java/teammates/common/util/FieldValidator.java, src/main/java/teammates/common/util/Url.java, src/test/java/teammates/test/cases/common/SessionAttributesTest.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackResultsDownloadActionTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackSubmissionEditPageActionTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
Fixes #3942 
Also added some `System.out.println`s for the ones to check for file content.
=> Remove unnecessary System.out.printlns from Java files #3942

src/main/webapp/WEB-INF/tags/instructor/results/byGiverQuestionRecipient.tag, src/main/webapp/WEB-INF/tags/instructor/results/byQuestionResults.tag, src/main/webapp/WEB-INF/tags/instructor/results/resultsPage.tag, src/main/webapp/jsp/instructorFeedbackResultsByGiverQuestionRecipient.jsp, src/main/webapp/jsp/instructorFeedbackResultsByQuestion.jsp, src/main/webapp/jsp/instructorFeedbackResultsByRecipientQuestionGiver.jsp
There are two methods for this, check and see if 72dcfc5 or 1e6eefa would work better.
The latter allows for common JS file imports, but may be more restrictive.
The `data` passed in is for resultsTop and resultsBottom later.
=> Generic page / tag for FeedbackResults pages.

src/main/resources/feedbackQuestionContribResultStatsStudentViewAdditionalInfo.html, src/main/webapp/instructorHelp.html, src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html, src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html
Fixes #1554 
The old issue description referenced `studentEvalResults.jsp`, but I think that has been refactored into smaller bits now. I tracked down the old link to to this html `feedbackQuestionContribResultStatsStudentViewAdditionalInfo.html` and updated the link there to the google docs one. Let me know if I got it wrong, thanks!
=> studentEvalResults: the link to the description of the point calculation points to the now defunct spec.html #1554

src/main/webapp/WEB-INF/tags/instructor/home/courseTable.tag, src/main/webapp/jsp/instructorHome.jsp, src/test/resources/pages/InstructorHomeHTML.html, src/test/resources/pages/InstructorHomeHTMLResponseRateFail.html, src/test/resources/pages/InstructorHomeHTMLSortByDate.html, src/test/resources/pages/InstructorHomeHTMLSortById.html, src/test/resources/pages/InstructorHomeHTMLSortByName.html, src/test/resources/pages/InstructorHomeHTMLWithHelperView.html, src/test/resources/pages/InstructorHomeNewInstructorWithSampleCourse.html, src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
fixed #2346
@damithc This is what it looks like now. Is that okay?
This is what it was before #3917
=> Instructor Home page: show a message when a course has no sessions/evals, instead of having no panel body. #2346

src/main/java/teammates/common/datatransfer/FeedbackContributionQuestionDetails.java, src/main/java/teammates/common/util/FeedbackQuestionFormTemplates.java, src/main/resources/feedbackQuestionContribAdditionalInfoTemplate.html, src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html, src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html
Fixes #3742 
EDIT (message copied from commit https://github.com/ngzhian/repo/commit/6ec5b680440c6e4c2d986ffd22d99b4289319437)
This is to fix a regression introduced in the previous commit,
which made the "more info" link beside the panel title of a
contribution question move visible, but made the "more info"
link beside the question title itself less visible.
=>  Change colour of 'how to interpret' link in student feedback results page #3742 

src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
Fixes #4094.
Tested on a few ui tests on staging. The first time it tries to login, google will want to authenticate by sending your mobile phone an SMS, so it's best to run one ui test first.
Might also need to allow access to less secure apps, but this has been around for a while already so it shouldn't be a problem now. https://www.google.com/settings/security/lesssecureapps
=> Live/staging tests not compatible with new google login page #4094

.settings/com.google.gdt.eclipse.core.prefs, .settings/com.google.gdt.eclipse.core.template.prefs, devdocs/settingUp.md
Following the discussion in #4165 to split into two PRs.
Note that the moment this is merged, the original `.prefs` file will be gone (as part of one of the commits). Just re-create it with the template file and change all the `*` as per the instruction. This only needs to be done once.
=> Remove all warning markers in Eclipse, part 2 #4164

src/main/java/teammates/common/datatransfer/FeedbackSessionAttributes.java, src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsForm.tag, src/main/webapp/WEB-INF/tags/student/feedbackSubmissionEdit/feedbackSessionDetailsPanel.tag
Fixes #4199 
`getInstructionsString()` is used only from the front-end, never from the back-end side.
@taniach @kanghj 
Is there any particular requirement for the `<c:out>` sanitization over `Sanitizer.sanitizeForHtml()` here?
@taniach 
On a related topic, should the `feedbackSubmissionEdit` tagdir be under `student`?
=>  Sanitization problem in feedback instructions #4199 

src/main/java/teammates/common/util/Const.java, src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java, src/test/java/teammates/test/cases/ui/InstructorCourseStudentDetailsEditSaveActionTest.java
Fixes #4218 
A similar problem happens clicking on the "Edit" link pointed at an invalid student.
(e.g. open edit link in new tab, edit student's email, click on edit link in initial tab)
Also, the other buttons reply only with error messages like "The student you tried to view details for does not exist." aside from Delete which returns a success. Should any of their behaviour be changed to be consistent with this one or vice versa (regarding the line about eventual consistency)?
Should either of those be handled in this PR?
(Regarding the delete button, it's due to a method that "Fails silently if no match found." according to its comment.)
=>  NPE in InstructorCourseStudentDetailsEditSaveAction #4218

src/test/java/teammates/test/cases/ui/pagedata/StudentHomePageDataTest.java
Fixes #4254 
This is the cause:
The "0" there indicates that the feedback session closes 0 hours before now (i.e, _now_). 
However, putting 0 there is dangerous because for the feedback session to be considered closed, the time at the point of the comparison has to be _after_ the set closing time. The difference needed is only one millisecond, however, the program execution happens very fast and often it doesn't take even one millisecond from the point the closing time is set to the point the comparison is made, which fails the test.
=> StudentHomePageDataTest fails very often in package/full run #4254

src/test/java/teammates/test/driver/AssertHelper.java
Fixes #4260 
If the sanitized &lt; and &gt; makes it hard to view in diff mode, here's the screenshot in Eclipse javadoc:
=> Limitations to wildcard not documented #4260

src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java
Fixes #4179 
Prof @damithc, I couldn't replicate the test failure at line 110 of `InstructorCommentsPageUiTest` on the live server. However, 2 other lines were constantly failing on my live server. Specifically line 175 and 219. It seems to be because the page doesn't wait for the ajax to load before locating the element.
=> InstructorCommentsPageUiTest failing on live server #4179

src/main/webapp/js/instructor.js, src/main/webapp/js/instructorFeedbackResults.js, src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.js, src/main/webapp/js/instructorFeedbackResultsAjaxByGRQ.js, src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.js, src/main/webapp/js/instructorFeedbackResultsAjaxByRGQ.js, src/main/webapp/js/instructorFeedbackResultsAjaxByRQG.js, src/main/webapp/js/instructorFeedbackResultsAjaxResponseRate.js, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
Fixes #4276
The "The results is too large to be viewed. Please choose to view the results by questions or download the results." might be affected because of #4184, where the error code returned by the page now (correctly) triggers the error callback instead of the success callback. We already have an issue for that message, will try to fix that soon.
=> instructorSessionResults: there is no way to recover from failed ajax calls #4276

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentListPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java, src/test/java/teammates/test/pageobjects/AppPage.java
Fixes #4359 
This PR (and issue) will first add the capability for full HTML check after ajax load. The missing page checks are to be added in another (few) issue(s).
=> Enable full HTML check after ajax load #4359

src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
Fixes #4328.
Verified that the log severe triggers in the test case (in InstructorFeedbackResultsUiTest) for invalid question numbers
=> Detect invalid question numbers in feedback sessions #4328

src/test/java/teammates/test/cases/ui/browsertests/AdminAccountDetailsPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/AdminEmailPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/AdminHomePageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/BaseUiTestCase.java, src/test/resources/pages/adminAccountDetails.html, src/test/resources/pages/adminAccountManagementPage.html, src/test/resources/pages/adminEmailCompose.html, src/test/resources/pages/adminHomePageCreateInstructorSuccess.html
Fixes #4377 
As discussed, although this solves the problem at hand, removing the HTML comparisons altogether may be better for the long run. In that case, at least this will suppress all the failures until the point where all HTML comparisons are gone.
P.S. this hasn't been tested in staging yet.
=> Admin UI tests in full run failing due to admin username contamination #4377

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
Fixes #3639.
The test can fail if the admin isn't a instructor. 
If the download url is invalid, the user is redirected back to instructorHomePage because of <code>assertPostParamNotNull</code>, but without the usual user parameter.
Even if the test isn't failing because of this, I added more information to the assert statement, so at least we will know which page is the test redirected to
=> InstructorFeedbackResultsPageUiTest failing on live server #3639

src/test/java/teammates/test/cases/testdriver/HtmlHelperTest.java, src/test/java/teammates/test/driver/HtmlHelper.java, src/test/java/teammates/test/pageobjects/AppPage.java
Fixes #4470 
- In `assertSameHtml` two extra params are introduced: `isPart` and `isDifferenceToBeShown`. Setting `isPart` to be true gives `*SameHtmlPart` in place of `*SameHtml` and setting `isDifferenceToBeShown` to be true gives `assert*` in place of `are*`.
- In `verifyHtml`, also two extra params are introduced: `by` and `isAfterAjaxLoad`. Setting `by` to be non-null gives `verify*Part/MainContent` and setting `isAfterAjaxLoad` to be true gives `verifyHtmlAjax*`. Just realized we don't have `verifyHtmlAjaxPart` :p (not needed for now though).
=> Highly duplicated methods used in HTML comparison #4470

src/main/webapp/WEB-INF/tags/instructor/instructorPage.tag, src/main/webapp/WEB-INF/tags/instructor/instructorPageCustom.tag, src/main/webapp/WEB-INF/tags/page.tag, src/main/webapp/js/adminSearch.js, src/main/webapp/js/instructor.js, src/main/webapp/js/instructorFeedbackEdit.js, src/main/webapp/js/instructorFeedbackResults.js, src/main/webapp/js/instructorFeedbacks.js, src/main/webapp/js/instructorFeedbacksSpecific.js, src/main/webapp/jsp/instructorFeedbackEdit.jsp, src/main/webapp/jsp/instructorFeedbacks.jsp, src/test/resources/pages/instructorFeedbackEditEmpty.html, src/test/resources/pages/instructorFeedbackEditManuallyPublished.html, src/test/resources/pages/instructorFeedbackEmptyAll.html
Fixes #3769 
I kept the two `onload`s on `index.js` and `checkBrowserVersion.js` because the only file that uses both, `index.html`, doesn't use jQuery, perhaps rightly so because `index.html` intends to check for compatibility as well.
=> Use $(document).on('ready'... instead of onload #3769

src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentListPageUiTest.java, src/test/java/teammates/test/driver/HtmlHelper.java, src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/InstructorStudentListPage.java, src/test/resources/pages/instructorStudentListPageWithPicture.html
Fixes #3947, fixes #3572, fixes #2700 (wow, the number of duplicates).
The existing popup test via HTML comparison in `InstructorStudentListPageUiTest` is now tested with Selenium's web element comparison. It's more fault-tolerant this way.
@junhaoyap, if you please.
=> Popovers in tests are not being ignored #3947

src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java, src/test/java/teammates/test/pageobjects/AppPage.java
Fixes #4565
Explanation: if the test navigates to the next page before going to the logout link generated by appengine in logout.jsp, then the user remains logged in, triggering an exception when the test expects a log in page. 
For the feedback submission page, if the user is still logged in and goes to the submission page for unregistered student, the test is logged out and redirected to the login page
=> Several test cases failing on live server due to a login issue #4565

src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java, src/main/java/teammates/ui/controller/AdminActivityLogPageData.java, src/main/webapp/WEB-INF/tags/admin/activity/filterPanel.tag, src/main/webapp/js/adminActivityLog.js, src/main/webapp/jsp/adminActivityLog.jsp
Fix #4511
I added one more parameter to the submit form in jsp and javascript to help us keep track the start searching time extended. The start time generated by this function will overwrite the start time in query and it will only be extended by clicking on "Search More" but not "Older Logs".
=> admin activity log: Give a way to search more logs when searching for activities of a user #4511

src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java, src/main/java/teammates/ui/controller/AdminActivityLogPageData.java, src/main/java/teammates/ui/controller/AdminSearchPageData.java, src/main/webapp/WEB-INF/tags/admin/activity/filterPanel.tag, src/main/webapp/WEB-INF/tags/admin/search/instructorRow.tag, src/main/webapp/WEB-INF/tags/admin/search/studentRow.tag
fix #4525
The issue happens only when the user is unregistered and his name is used in the query instead of his google id. Therefore, to solve this, I introduce "course" attribute to the query to indicate the course that unregistered user is belonged to. The query to search for activities of the user will be done via Search page by clicking on "View recent actions".
@kanghj could you review this?
=> admin activity log: wrong user time zone reported #4525

src/main/java/teammates/common/datatransfer/StudentAttributes.java, src/main/java/teammates/common/util/Sanitizer.java, src/main/java/teammates/logic/core/Emails.java, src/main/java/teammates/ui/controller/Action.java, src/main/java/teammates/ui/controller/AdminSearchPageData.java, src/main/java/teammates/ui/controller/PageData.java, src/main/java/teammates/ui/controller/StudentCourseJoinAction.java, src/main/java/teammates/ui/controller/StudentCourseJoinAuthenticatedAction.java, src/main/java/teammates/ui/controller/StudentCourseJoinConfirmationPageData.java, src/main/webapp/jsp/studentCourseJoinConfirmation.jsp, src/test/java/teammates/test/cases/common/StudentAttributesTest.java, src/test/java/teammates/test/cases/logic/EmailsTest.java, src/test/java/teammates/test/cases/ui/StudentCourseJoinActionTest.java, src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackQuestionSubmitPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackResultsPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java, src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/DevServerLoginPage.java, src/test/java/teammates/test/pageobjects/GoogleLoginPage.java, src/test/java/teammates/test/pageobjects/LoginPage.java, src/test/java/teammates/test/pageobjects/StudentCourseJoinConfirmationPage.java, src/test/resources/pages/studentCourseJoinConfirmationLoggedInHTML.html, src/test/resources/pages/studentFeedbackResultsPageNewlyRegistered.html
Fixes #4572 and fixes #4562 (the test failure in the latter has the same cause).
This issue also highlights our alarming failure in handling next URL. Just doing what is suggested [here](https://github.com/TEAMMATES/repo/issues/4572#issuecomment-157297754) is insufficient.
1. `nextUrl` can be anything from the pages that do not require Google login (they are defined in `Const.SystemParams`) for this to happen.
2. Instead of just status message, it is better to change the content of the box entirely because the intention of confirming the Google ID is not exactly the same:
3. True enough, encoding the URL doesn't work because behind the screen Google does its own encoding and decoding. One (and maybe the only) workaround is replacing dangerous characters (i.e `&`, `+`, `#`) with …
=> Users go to old home page when trying to submit for new course #4572

src/test/java/teammates/test/driver/HtmlHelper.java
Fixes #4608 
Two significant sources of the slow-ness:
1. There's _four_ times looping for each div when trying to check if it's ignored or not.
2. The expected HTML files are converted to standard HTML. This is redundant; during regeneration they _have_ been converted to standard HTML.
And more optimizations are achieved by bypassing unnecessary boolean checks, like the unused void elements.
=> Optimize inefficient processes in HtmlHelper #4608

src/main/java/teammates/ui/controller/AdminSessionsPageAction.java, src/main/java/teammates/ui/controller/AdminSessionsPageData.java, src/main/webapp/jsp/adminSessions.jsp
Fix #4598 
Change "Total" in admin status to "Ongoing"
Add "Opened" field which shows total number of sessions that are under "Opened" status.
Add "Institutions" field which shows total number of institutions (exclude "unknown").
=> admin sessions page: show more stats #4598

src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackResultsDownloadActionTest.java
Fixes #4629 (and as a consequent of this method update, fixes #4630)
However, there is this one "naughty" test case. 
Eclipse does not show any differences between the compared results, but the test fails. If you look carefully, there seems to be no differences (refer to line 1187 of FeedbackSessionLogicTest.java). This is currently commented and if so, all testcases are passed. 
Here is the screenshot of said test. It doesn't show everything, but there are no indication of mistakes whatsoever (at least what I saw in my Eclipse).
=> FeedbackSessionsLogicTest: use a cleaner method to compare the csv results #4629

src/main/java/teammates/common/datatransfer/StudentAttributes.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/storage/entity/Student.java, src/test/java/teammates/test/cases/storage/StudentsDbTest.java
Fixes #4684 
I have modified the tests as well to check whether students with no createdAt and updatedAt timestamp to return the default timestamp as well.
=> Add default date for student timestamp #4684

src/main/webapp/js/index.js, src/test/javascript/SubmissionCountJsTest.js
Fixes #4271 
Essentially it is the instantiation of new `Date` in js that caused the test to be prone to location-based failures. Beyond that, there's another flaw in that each month is treated as 30 days. We know that 12 * 30 = 360 < 365/366 days in a year.
The test cases are checked manually for correctness (2 submissions per hour starting at 36,000):
- Case 1: from 20 Dec 2013 to 21 Dec 2013, 1 day = 24 hrs = 48 submissions. It should be 36,048.
- Case 2: from 30 Nov 2013 to 21 Dec 2013, 21 days = 504 hrs = 1,008 submissions. It should be 37,008.
- Case 3: from 30 Nov 2016 to 21 Dec 2076, 21936 days (assuming the calculator I used is correct) = 1,052,928 submissions. It should be 1,088,928.
For case 3 I have to cherry-pick new dates because apparently Firefox has a bug in parsing some …
=> Submission counter algorithm is flawed #4271

src/main/java/teammates/logic/core/Emails.java
Fixes #4703, fixes #4557 (two duplicate issues)
`sendLogReport` is in particular problematic because the variable `email` appears out of nowhere and makes everything null. Somebody should've copy-pasted it from `sendErrorReport` :p
=> Not enough info in 'severe error log compilation' email #4703

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java
Fixes #4755 
Failure is caused by the "edit visibility" button being clicked before the div finished rendering. Sort of a race condition.
=> InstructorFeedbackEditPageUiTest failing on dev server #4755

src/main/java/teammates/common/util/ActivityLogEntry.java, src/main/java/teammates/logic/core/Emails.java, src/main/java/teammates/ui/controller/ControllerServlet.java
Fixes #4550
Here's what happened: take a look at these lines in `ControllerServlet`:
```java
MimeMessage email = new Logic().emailErrorReport(req, e); // can be null
log.severe(ActivityLogEntry.generateSystemErrorReportLogMessage(req, email));
```
Here, if the variable `email` is null, the log will have no data, which is what is seen in the issue thread.
How can the variable `email` be null? Further probing will bring us to this function in `Emails.java`:
```java
public MimeMessage sendErrorReport(HttpServletRequest req, Throwable error) {
MimeMessage email = null;
try {
...
email = generateSystemErrorEmail(...) // this function can throw Exception
...
} catch (Exception e) {
logSevereForErrorInSendingItem("crash report", email, e);
}
return email;
}
```
That is, the `email` will be null …
=> Severe logs without error data #4550

src/test/java/teammates/test/cases/ui/browsertests/FeedbackRankQuestionUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/FeedbackRubricQuestionUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentListPageUiTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java, src/test/java/teammates/test/pageobjects/AppPage.java
Fixes #4817
The existing `verifyHtmlAjax(MainContent)` is not hijacked; the method has always been `verifyHtml(MainContent)WithRetry` all along, but previously its usage was only for ajax load. Now it's extended to panel collapsing/expanding.
=> FeedbackRubricQuestionUiTest failing on dev server #4817

src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/Browser.java, src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java, src/test/java/teammates/test/pageobjects/InstructorHomePage.java
Fixes #1800
`waitForPageToLoad` is not removed yet because while the `WebDriver` has an equivalent for that, it [functions differently](http://www.seleniumhq.org/docs/appendix_migrating_from_rc_to_webdriver.jsp#waitforpagetoload-returns-too-soon) (i.e considers "a page is loaded" differently) and using it causes a considerable amount of test failures due to timing issues, so resolving it warrants its own issue.
Hopefully the `TimeoutException` thrown by `selectWindow` is now suppressed.
=> Eliminate use of WebDriverBackedSelenium in Browser.java #1800

devdocs/settingUp.md, src/main/java/teammates/client/remoteapi/RemoteApiClient.java, src/main/webapp/WEB-INF/web.xml
Fixes #4753
As in https://cloud.google.com/appengine/docs/java/tools/remoteapi#configuring_remote_api_on_an_app_engine_client , we have to replace `credentials(testProperties.TEST_ADMIN_ACCOUNT, testProperties.TEST_ADMIN_PASSWORD)`, which uses deprecated ClientLogin, by `useApplicationDefaultCredential()`, which uses OAuth protocol to get access to staging server.
In order to get access to staging server, we have to run `gcloud auth login` in local PC terminal (but make sure you have installed Google Cloud SDK first, https://cloud.google.com/sdk/downloads).
For dev server, we don't have to do this but I need someone to test it without installing Google Cloud SDK (we could try running my sanitization script `DataMigrationForSanitizedDataInStudentAttributes`).
=> Update client API to OAuth #4753

src/test/java/teammates/test/cases/ui/browsertests/InstructorCommentsPageUiTest.java, src/test/resources/pages/instructorCommentsPageAddFrc.html, src/test/resources/pages/instructorCommentsPageEditFrc.html
Fixes #4877 
Essentially this is just switching the order of the comments displayed, but it's needed to fix the test. The problem is removed for good because we won't ever go back to "before 1 Mar '16".
=> InstructorCommentsPageUiTest fails in dev due to dates #4877

src/main/webapp/mashup.jsp
Fixes #4538 
1. Fix student's email address (.com to .tmt) so `instructorCourseStudentDetailsPage`, `instructorCourseStudentEditPage`, `instructorStudentRecordsPage`, `instructorFeedbackPreviewAsStudentPage`, `instructorFeedbackPreviewAsInstructorPage` and `studentCourseJoinConfirmationPage` could be correctly loaded.
2. Use local jqeury library instead of taking from CDN
3. Fix a typo so `instructorHelp` iframe's height could be shown properly.
4. Add red line boundaries between static page
5. Load error pages regardless of 500 status.
=> Multiple problems in MashupPageUiTest #4538

src/main/java/teammates/ui/controller/AdminAccountManagementPageAction.java, src/main/webapp/WEB-INF/tags/admin/navBar.tag, src/main/webapp/WEB-INF/tags/admin/search/instructorRow.tag, src/main/webapp/js/adminSearch.js, src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java, src/test/resources/pages/adminAccountDetails.html, src/test/resources/pages/adminHomePage.html
Fixes #4837
As discussed on Wednesday, I temporarily removed Account Management Page from navbar and added an URL to redirect from Search Page to Account Management Page for each registered instructor.
I also disabled unit test for Account Management Page since we have to renovate it sooner or later anyway.
=> admin accounts management page is not scalable #4837

src/main/webapp/js/instructor.js
Fixes #4801.
This doesn't cause a change in behaviour currently, so there are no modifications to testing. But it causes tests to fail in #4749
=> Instructor feedback copy modal: form data can be sent multiple times #4801

src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
Fixes #4018 
Not entirely sure that this is the best way, but this works and is more representative of what's happening, rather than `USER_IS_TEAM`.
=> USER_IS_TEAM is wrongly used in FeedbackSessionResultsBundle #4018

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java, src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
Fixes #4948 and fixes #4564 (two duplicate issues).
True enough, there are more than one cause for failure in this particular test (`testFrontEndActions`), but this PR addresses both of them.
=> InstructorFeedbackResultsPageUiTest failing on dev server #4948

src/test/java/teammates/test/pageobjects/InstructorHomePage.java
Fixes #4161 
Take a look at the source of the failure: waiting for `session-1`, instead of the usual `session0`. The failure comes because there is a need to wait for the course table to be loaded, and not waiting will result in the row ID to be `-1` (as shown in the method `getCourseRowId`), so waiting here will (99%) guarantee that the course table is loaded before any processing is done.
=> InstructorHomePageUiTest failing on live server #4161

src/test/java/teammates/test/cases/ui/browsertests/StudentProfilePageUiTest.java
Fixes #4796 
There should be a wait for the student photo upload modal to re-appear, but lines 174 and 217 waited for it erroneously.
The `verifyStatusWithRetry` on line 218 was added because after uploading photo the modal doesn't immediately disappear so immediate "waiting to appear" will result in false positive.
=> StudentProfilePageUiTest is failing on the live server #4796

src/test/java/teammates/test/pageobjects/AdminHomePage.java, src/test/java/teammates/test/pageobjects/AppPage.java
Fixes #5004 
Wasn't entirely sure why the fix works because if the previous one is subjected to race conditions (it "waits for the ajax loader gif to disappear before it even appears"), this one has the chance to be as well (i.e it "waits for the button to be clickable even before it becomes unclickable"), but apparently it doesn't happen.
This will also fix the `InvalidElementStateException` that occasionally appears at later line of the same test.
=> AdminHomePageUiTest failing frequently #5004

src/test/java/teammates/test/pageobjects/AppPage.java
Fixes #4158 
Basically, the previous method was not configured for SSL connection at all.
The current method has a downside in that there is no SSL certificate check, but this shouldn't be a problem considering that this is a non-production code and it is reasonable to assume that the testing environment is only *.appspot.com.
=> InstructorCourseEnrollPageUiTest failing on live server #4158

src/main/java/teammates/common/datatransfer/FeedbackConstantSumQuestionDetails.java, src/main/java/teammates/common/datatransfer/FeedbackNumericalScaleQuestionDetails.java, src/main/java/teammates/common/datatransfer/FeedbackQuestionDetails.java, src/main/java/teammates/common/datatransfer/FeedbackRankRecipientsQuestionDetails.java, src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java, src/main/java/teammates/common/util/Sanitizer.java, src/main/webapp/WEB-INF/tags/instructor/results/participantGroupBySecondaryParticipantPanel.tag, src/main/webapp/WEB-INF/tags/instructor/results/secondaryParticipantPanelSide.tag, src/main/webapp/WEB-INF/tags/instructor/results/teamPanel.tag
Fixes #4622.
When sanitizing people's names for csv files, remember to call `StringHelper.recoverFromSanitizedText()` method.
My Concerns:
1. I only changed the codes that caused issue #4622. However, I saw codes that look like `Sanitizer.sanitizeForCsv(humanName)` somewhere else as well. Should I change them accordingly to `Sanitizer.sanitizeForCsv(StringHelper.recoverFromSanitizedText(humanName))`?
2. Alternatively, should I just call `StringHelper.recoverFromSanitizedText()` inside `Sanitizer.sanitizeForCsv()`?
=> Slash is html encoded in csv file #4622

devdocs/settingUp.md, src/test/javascript/blanket.js, src/test/resources/pages/allJsUnitTests.html
Fixes #5040 
Use [Blanket.js](https://github.com/alex-seville/blanket/blob/master/docs/getting_started_browser.md). It's easier to configure on the front-end comparing with other frameworks
Now one can enable/disable displaying coverage when view the result of `AllJsTest`
The coverage will look like this
=> Add code coverage for JavaScript tests #5040

src/main/java/teammates/logic/core/Emails.java, src/main/resources/userEmailTemplate-feedbackSession.html, src/main/resources/userEmailTemplate-feedbackSessionClosing.html, src/main/resources/userEmailTemplate-feedbackSessionPublished.html
=> EmailTemplates contains ${joinFragment} placeholders that are unused #4967

src/test/java/teammates/test/cases/ui/browsertests/AllJsTests.java
=>  AllJsTests line 47: expected failed cases should always be 0 #5098

src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java, src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java, src/test/java/teammates/test/cases/storage/StudentsDbTest.java
Fixes #4955 
I have moved the deletion of possibly conflicting entities before test is run in three files. I don't know whether the other files need them since there are no deletion of entities after each tests in each of those files.
=> Delete possibly-conflicting entities in Db tests before test is run #4955

src/test/java/teammates/test/cases/ui/browsertests/BaseUiTestCase.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java, src/test/java/teammates/test/driver/TestProperties.java, src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/Browser.java, src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java
Fixes #4825 
Note that `waitForPageToLoad` is a very important method that can't be decommissioned (trivially), but there is a way to make it work without resorting to Selenium RC and that way is implemented in this PR. Somehow I believe that this is the method used behind the screen by Selenium's `waitForPageToLoad` anyway.
Now we're one step closer to upgrading to Selenium 3, whenever that day is.
Also, I actually have fixed the `AdminSessionsPageUiTest` failure here as well, but #5172 seems to have taken care of it :p
=> Eliminate the usage of Selenium's built-in waitForPageToLoad #4825

src/main/webapp/WEB-INF/tags/errorPage.tag, src/main/webapp/deadlineExceededErrorPage.jsp, src/main/webapp/entityNotFoundPage.jsp, src/main/webapp/errorPage.jsp, src/main/webapp/feedbackSessionNotVisible.jsp, src/main/webapp/logout.jsp, src/main/webapp/pageNotFound.jsp, src/main/webapp/unauthorized.jsp, src/test/resources/pages/entityNotFoundPage.html, src/test/resources/pages/errorPage.html, src/test/resources/pages/pageNotFound.html, src/test/resources/pages/unauthorized.html
Fixes #5231 
`logout.jsp` has noticeably different look and not captured in tests (because that page is not tested).
Before:
After:
Other affected pages are tested and only have minor to no changes.
=> Use a standardized tag to construct the skeleton of error pages #5231

src/main/java/teammates/common/datatransfer/FeedbackQuestionAttributes.java, src/main/java/teammates/logic/backdoor/BackDoorLogic.java, src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java, src/main/java/teammates/ui/controller/InstructorFeedbackEditPageData.java, src/main/java/teammates/ui/template/FeedbackQuestionEditForm.java, src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionEditForm.tag, src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionFeedbackPathSettings.tag, src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionVisibilityOptions.tag, src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java, src/test/java/teammates/test/cases/ui/pagedata/InstructorFeedbackEditPageDataTest.java
Fixes #5208.
~~Waiting to see if travis passes. Tests are incoming~~
Changed the use of question numbers on the edit page to be based on questionIndex instead, which is determined from the position of the question in the sorted question list. 
Questions are now sorted by questionId, if the question numbers are the same, so that if duplicate question numbers occur, the user will always see them in the same order.
A minimal test, which have been verified to fail on the master branch, is added. However, checking for the actual contents of the page is difficult, since the order of questions is determined by questionId (assigned by the database), so that was omitted. 
A more complete treatment will be required and done separately, by setting the order of questions as a property of the session …
=> Make instructor feedback edit page resilient to duplicate question numbers #5208

src/main/java/teammates/ui/controller/AdminEmailLogPageData.java, static-analysis/teammates-checkstyle.xml
Added no whitespace after rule for bitwise complement `~`, prefix decrement `--`, dot `.`, prefix increment `++`, logical complement `!`, unary minus `-`, unary plus operators `+`.
I'm not sure what the whitespace after policy for typecasts should be like though.
=> Add new rules to Checkstyle-No whitespace after operators

devdocs/staticAnalysis.md, src/main/webapp/js/adminEmail.js, src/main/webapp/js/administrator.js, src/main/webapp/js/contextualcomments.js, src/main/webapp/js/feedbackResponseComments.js, src/main/webapp/js/googleAnalytics.js, src/main/webapp/js/index.js, src/main/webapp/js/omniComment.js, src/main/webapp/js/studentProfile.js, static-analysis/teammates.eslintrc
Three more rules, this time on naming conventions:
- new-cap, disallows things like `new lowerCaseObject()`
- no-underscore-dangle, applies on both variable names and method names
- camelcase, self-explanatory
In some places the rules are suppressed because we're using names provided by external libraries.
=> Add new rules to ESLint - naming conventions

src/main/webapp/js/ajaxResponseRate.js, src/main/webapp/js/common.js, src/main/webapp/js/instructorCourseDetails.js, src/main/webapp/js/instructorFeedbackResults.js, src/main/webapp/js/studentProfile.js, src/main/webapp/js/userMap.js, static-analysis/teammates.eslintrc
This one revolves around constructors, in particular where the `new` keyword is discouraged.
Also added the "one-var" rule:
```javascript
var a = 1, b = 2; // bad
var a = 1;
var b = 2; // good
```
=> Add new rules to ESLint - Constructors

src/main/webapp/js/administrator.js, src/main/webapp/js/common.js, src/main/webapp/js/datepicker.js, src/main/webapp/js/statusMessage.js, src/main/webapp/js/userMap.js, static-analysis/teammates.eslintrc
This ruleset involves the theme of void-ness: null, undefined, NaN. Rules added:
- no-eq-null: disallows `a == null`, requires `a === null`
- use-isnan: disallows `a == NaN` (no violations)
- no-undef-init: disallows `var a = undefined;` (also no violations)
The resolution is as follows:
- If the var is user-supplied (e.g function parameter), check for both null and undefined.
- If the var is to check possible array out-of-bounds index access or object non-existent property access, check for undefined.
- If the var is to check regex non-match, check for null.
The last two corresponds to JS' implementation.
=> Add new rules to ESLint - Voids

src/client/java/teammates/client/scripts/DataGenerator.java, src/client/java/teammates/client/scripts/PerformanceProfiler.java, src/main/java/teammates/logic/core/AccountsLogic.java, src/main/java/teammates/logic/core/FeedbackResponsesLogic.java, src/main/java/teammates/storage/api/FeedbackQuestionsDb.java, src/main/java/teammates/storage/api/FeedbackResponsesDb.java, src/main/java/teammates/storage/api/ProfilesDb.java, src/main/java/teammates/ui/controller/AdminEmailGroupReceiverListUploadAction.java, src/main/java/teammates/ui/controller/AdminEmailImageUploadAction.java, src/main/java/teammates/ui/controller/PageData.java, src/test/java/teammates/test/cases/automated/SubmissionsAdjustmentTest.java, src/test/java/teammates/test/cases/logic/AccountsLogicTest.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/logic/TeamEvalResultTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackAddActionTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackCopyActionTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackEditPageActionTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackEditSaveActionTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackQuestionAddActionTest.java, src/test/java/teammates/test/cases/ui/InstructorFeedbackQuestionCopyActionTest.java, src/test/java/teammates/test/cases/ui/browsertests/InstructorSubmissionAdjustmentUiTest.java, src/test/java/teammates/test/driver/BackDoor.java, src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/FeedbackQuestionSubmitPage.java, src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbacksPage.java, static-analysis/teammates-checkstyle.xml
Added method parameter pad rule. 
The method parameter pad rule checks that there is no whitespace between the identifier of a method definition, constructor definition, method call, or constructor invocation; and the left parenthesis of the parameter list. 
Example: 
```
// Allowed
String myMethod(param1, param2) {
// Method body
}
// Not Allowed
String myMethod (param1, param2) {
// Method body
}
```
=> Add new rules to Checkstyle-Method parameter pad

src/main/webapp/js/adminActivityLog.js, src/main/webapp/js/adminEmail.js, src/main/webapp/js/adminEmailLog.js, src/main/webapp/js/adminSearch.js, src/main/webapp/js/checkBrowserVersion.js, src/main/webapp/js/common.js, src/main/webapp/js/feedbackResponseComments.js, src/main/webapp/js/feedbackSubmissionsEdit.js, src/main/webapp/js/instructorCourseDetails.js, src/main/webapp/js/instructorCourseEdit.js, src/main/webapp/js/instructorFeedbackEdit.js, src/main/webapp/js/instructorFeedbackResults.js, src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.js, src/main/webapp/js/instructorFeedbackResultsAjaxByGRQ.js, src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.js, src/main/webapp/js/instructorFeedbackResultsAjaxByRGQ.js, src/main/webapp/js/instructorFeedbackResultsAjaxByRQG.js, src/main/webapp/js/instructorStudentListAjax.js, src/main/webapp/js/omniComment.js, src/main/webapp/js/studentProfile.js, static-analysis/teammates-eslint.yml
The rule is a parallel of PMD's ConfusingTernary rule. It's recommended by Google's style guide so we shouldn't go wrong with it.
Also enforced the no-multiple-empty-lines rule. It was fixed some time back but not enforced, but since Checkstyle enforced it for Java we might as well enforce it in JS too.
=> Add new rules to ESLint - no negated condition

src/client/java/teammates/client/scripts/ImportData.java, src/client/java/teammates/client/scripts/OfflineBackup.java, src/client/java/teammates/client/scripts/ParallelProfiler.java, src/client/java/teammates/client/scripts/PerformanceProfiler.java, src/client/java/teammates/client/scripts/UploadBackupData.java, src/main/java/teammates/common/datatransfer/AccountAttributes.java, src/main/java/teammates/common/datatransfer/AdminEmailAttributes.java, src/main/java/teammates/common/datatransfer/FeedbackQuestionAttributes.java, src/main/java/teammates/common/datatransfer/FeedbackQuestionDetails.java, src/main/java/teammates/common/datatransfer/FeedbackResponseAttributes.java, src/main/java/teammates/common/datatransfer/FeedbackResponseCommentAttributes.java, src/main/java/teammates/common/datatransfer/FeedbackSessionAttributes.java, src/main/java/teammates/common/datatransfer/InstructorAttributes.java, src/main/java/teammates/common/datatransfer/StudentAttributes.java, src/main/java/teammates/logic/api/GateKeeper.java, src/main/java/teammates/logic/automated/AdminEmailPrepareTaskQueueWorkerServlet.java, src/main/java/teammates/logic/backdoor/BackDoorLogic.java, src/main/java/teammates/logic/core/CoursesLogic.java, src/main/java/teammates/logic/core/Emails.java, src/main/java/teammates/logic/core/InstructorsLogic.java, src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java, src/test/java/teammates/test/cases/storage/StudentsDbTest.java, src/test/java/teammates/test/pageobjects/AppPage.java, static-analysis/teammates-checkstyle.xml
Added end-of-line left curly brace placement rule. Checks that left curly brace should be at the end of line.
Added same line right curly brace placement rule for `catch`, `else`, `if`, `try` tokens.
Added alone on the line right curly brace placement rule for the rest of the available tokens for the right curly brace placement rule.
For the same line and alone on the line right curly brace options, refer to [here](http://checkstyle.sourceforge.net/property_types.html#rcurly) for more details.
I was confused by the right curly brace placement for the `do` token, as putting it under the same line option gives errors, so I left it under the alone on the line option.
=> Add new rules to Checkstyle - Left right curly brace placement

src/main/webapp/js/instructorFeedbackEdit.js, static-analysis/teammates-eslint.yml
It's there before but modified following the Java style guide:
```javascript
switch (case) {
case ABC: // correct
something();
break;
case DEF: // incorrect
anotherThing();
break;
default:
break;
}
```
There's only one instance of switch/case in the entire JS files so it's a very fast fix.
=> Add new rules to ESLint - indentation for switch/case

devdocs/settingUp.md
Fixes #5534 
Skipping Travis since this cannot cause any failure.
=> Move the instructions to download App Engine SDK to after cloning the repo #5534

src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
Fixes #5583. Have verified that the test fails if ran after `testModerateResponsesButton`
=> False positive in InstructorFeedbackResultsPageUiTest #5583

build.gradle, devdocs/dependencies.md, devdocs/settingUp.md
Fixes #5615
Another oversight on my part because `gradle.properties` is generated concurrently with `.classpath` which may cause problems.
Skipping Travis for the usual reason that this cannot cause failure.
=> Buildpath error after running resetEclipseDeps gradle task #5615

build.gradle, src/main/java/teammates/common/exception/EmailSendingException.java, src/main/java/teammates/logic/automated/AdminEmailWorkerServlet.java, src/main/java/teammates/logic/core/EmailSender.java, src/main/java/teammates/logic/core/EmailSenderService.java, src/main/java/teammates/logic/core/JavamailService.java, src/main/java/teammates/logic/core/MailgunService.java, src/main/java/teammates/logic/core/MailjetService.java, src/main/java/teammates/logic/core/SendgridService.java
Fixes #5725 
I was already feeling funny when doing the `EmailSenderService` migration because I knew full well that `throws Exception` should not be allowed, but I thought it was another one of PMD's bugs. Now we know why.
=> PMD rules for production code is not enforced #5725

src/main/resources/jersey-multipart-config.properties
Fixes #5737 
According to [this answer](http://stackoverflow.com/questions/6301973/multipart-file-upload-on-google-appengine-using-jersey-1-7), version 1.x of jersey library require the shorter `bufferThreshold` property (the longer one is for 2.x) but I include both just to be safe, it should not have any side effects.
=> MailGun cannot send emails on live server #5737

CONTRIBUTING.md
Fixes #5539 
Skipping CI build as this cannot cause any failures.
=>  CONTRIBUTING.md links to the old contributor orientation guide #5539

.travis.yml, devdocs/staticAnalysis.md, src/main/webapp/js/adminAccountManagement.js, src/main/webapp/js/instructorCourseEnrollPage.js, src/main/webapp/js/instructorFeedbackEdit.js, src/main/webapp/js/userMap.js, static-analysis/teammates-eslint.yml
Fixes #5822 
Version 3.0.0 is a major release from their side and [their documentation](http://eslint.org/docs/user-guide/migrating-to-3.0.0) comprehensively lines out what needs to be done to migrate, all of which have been done via this PR (in particular updating the rules list and specifying the minimum node.js version).
=> Add version number to ESLint #5822

README.md
Fixes #5599 
Edited (security issues muted, LoCs updated):
By the way, the organization in VersionEye is independent of GitHub's, i.e I created a separate organization named TEAMMATES and I am the only member. It is possible to create a somewhat official account for TEAMMATES, all that needs to be done is updating the project's badge after it is done.
Otherwise I will simply host and manage the account for the next year or so.
(on an unrelated note, the number of LoCs reflected are inaccurate, especially the CSS one)
=> Add VersionEye to the repo #5599

src/main/webapp/js/instructorFeedbackEdit.js, src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackEditPageUiTest.java, src/test/java/teammates/test/pageobjects/AppPage.java
Fixes #5541
Scrolling to status message is already included into **setStatusMessage** function.
=> instructorFeedbackEdit: page should scroll to status message after saving #5541

.travis.yml, build.gradle, devdocs/settingUp.md, devdocs/staticAnalysis.md, src/main/webapp/package.json, static-analysis/EmptyClass.java
Fixes #5972 
The empty class workaround is no longer needed because with the tools declared via Gradle, they can be resolved and downloaded on demand.
=> Use proper versioning for all static analysis tools #5972

src/client/java/teammates/client/scripts/DataMigrationForSentClosingEmailFieldInSessions.java, src/main/java/teammates/common/datatransfer/FeedbackSessionAttributes.java, src/main/java/teammates/logic/automated/FeedbackSessionClosedMailAction.java, src/main/java/teammates/logic/automated/FeedbackSessionClosingMailAction.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/api/FeedbackSessionsDb.java, src/main/java/teammates/storage/entity/FeedbackSession.java, src/test/java/teammates/test/cases/common/FeedbackSessionAttributesTest.java, src/test/java/teammates/test/cases/logic/StudentsLogicTest.java, src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
Fixes #5999 
Still running some tests (in particular for checking backward-compatibility), but feel free to review what's already here.
=> Timeouts in session closing and closed reminders #5999

src/main/java/teammates/storage/datastore/Datastore.java
Fixes #5891 
Deleted the function named finishRequest from Datastore.java.
This issue was tagged as d.firstTimer.
=> Remove finishRequest in Datastore.java #5891

src/main/webapp/about.jsp
Fixes #5988 
The [ci skip] commit message allows Travis to skip the build, since this is a change that cannot possibly break any test.
=> Update about.jsp with contributors from V5.88 #5988

src/main/webapp/js/instructorFeedbackEdit/visibilityOptions.js
Fixes #6070 
Failing test NOT yet written because it requires quite a bit of setting up (creating the responses that will cause the "responses will be deleted" message to appear)
=> Response deletion warning message not shown when visibility edited #6070

src/main/webapp/stylesheets/teammatesCommon.css
Fixes #6074 
Removed redundant CSS definition for padding-top-0
=> Redundant CSS definition for padding-top-0 #6074

src/main/java/teammates/storage/api/StudentsDb.java
Fixes #6064
We can skip the extra query and check for an existing student if the email isn't changed. There is no change to any test since there is no change in testable behavior.
=> 'email is being used' error while enrolling students #6064

src/test/java/teammates/test/driver/HtmlHelper.java
Fixes #4383 
Please let me know in case I missed any changes to be made.
=> Remove all regex comparison in HtmlHelper (that is all calls to AssertHelper.isContainsRegex) to make html comparison faster #4383

src/test/java/teammates/test/driver/TestProperties.java
=> Missing a space in assertion failure message in verifyReadyForGodMode method #6161

.travis.yml
Fixes #6199 
The fix is exactly the same as what was removed by Travis in their "offending" change.
=> Fix path to npm executable in .travis.yml #6199

src/test/java/teammates/test/driver/HtmlHelper.java
Fixes #6201 
Manually ensured that dev green is reached in both Windows and OSX.
=> Test failures in enrollment result due to line endings in HTML attribute value #6201

src/main/webapp/about.jsp
Fixes #6386 
I've tried my best to update the names, but since it's quite a big milestone (big = high sprint velocity, lots of new contributors), many names may fall through the cracks. If I miss any I will update in V5.94.
=> Update about.jsp with contributors from V5.93 #6386

src/main/java/teammates/logic/core/AccountsLogic.java, src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java, src/main/java/teammates/ui/controller/ControllerServlet.java, src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java, src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java, src/test/java/teammates/test/pageobjects/InstructorCoursesPage.java
Fixes #6459 
Removed all the duplicate "the"s in java files
=> Duplicate "the" in java files #6459

.launches/All tests (GodMode).launch.xml, .launches/All tests.launch.xml, .launches/CI tests.launch.xml, .launches/Staging tests.launch.xml, .travis.yml, README.md, appveyor.yml, build.gradle, docs/development.md, docs/orientation-guide.md, docs/staticAnalysis.md, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorStudentListPageUiTest.java, src/test/java/teammates/test/cases/testdriver/TestNgTest.java, src/test/java/teammates/test/driver/PriorityInterceptor.java, src/test/java/teammates/test/pageobjects/BrowserPool.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java, src/test/resources/data/InstructorFeedbackEditCopyTest.json, src/test/testng-ci.xml
Fixes #6238. The third commit also fixes #6179 and fixes #6009.
I'm not sure from which branch the badge pulls the status from, although this is just a minor edit if needed.
Also, I do not include the static analysis tools here (let Travis do the job) but easy to include if needed.
=> Set up AppVeyor to run tests on Windows #6238

.travis.yml
Fixes #6509
Take exit code of `git diff` command into account when deciding whether to skip CI. CI is only skipped if `git diff` returns successfully (code 0) and `grep` command reports no lines selected (code 1). If `git diff` returns with an error (non-zero code), the CI will run normally.
=> CI tests skipped after merge branch #6509

src/client/java/teammates/client/remoteapi/RemoteApiClient.java
Fixes #6532 
Instead of initializing a second PMF, get the PMF from `EntitiesDb` itself to create the needed `PersistenceManager`.
Tested and confirmed to return everything to normal on dev server.
=> Bug report: Client scripts are not runnable #6532

src/main/java/teammates/common/datatransfer/FeedbackQuestionBundle.java
Fixes #6438 
This one just removes the method `getRecipientEmails(String)` method from `FeedbackQuestionBundle.java`. Nothing in the codebase seems to be using this. Its implementation ( removed in this PR) is its only existence in the codebase.
=> Remove FeedbackQuestionBundle::getRecipientEmails method #6438

.codecov.yml, .travis.yml, README.md, build.gradle, docs/staticAnalysis.md
Fixes #5317 
Let's hope I get this configured correctly.
=> Integrate Codecov to the CI build #5317

src/test/java/teammates/test/cases/browsertests/AllAccessControlUiTests.java
=> Bug report: AllAccessControlUiTests failure in production server due to wrong password #6579

src/main/webapp/js/userMapData.json
Fixes #6621 
There is an entry with trailing comma in `userMapData.json` which is not a valid JSON syntax. Fixing it fixes the problem.
=> Bug report: User map does not load #6621

src/main/java/teammates/common/util/Assumption.java, src/main/java/teammates/ui/automated/AutomatedAction.java, src/main/java/teammates/ui/automated/FeedbackSessionRemindParticularUsersEmailWorkerAction.java, src/main/java/teammates/ui/controller/Action.java, src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java
Fixes #6526
Outline of solution:
* add getNonNullRequestParamValue and getNonNullRequestParamValues methods to Action and AutomatedAction
* Make Assumption.assertPostParamNotNull accept any type for the post parameter
* Add some usage of these methods
=> Create versions of getRequestParamValue and getRequestParamValues where null is not expected #6526

src/main/webapp/about.jsp
Fixes #6682 
[Preview of about.jsp page after this change](https://teammates-wkurniawan07.appspot.com/about.jsp).
- Commit 1: as per usual, just by tracing this milestone's contributors.
- Commit 2: wrong names (missing/misplaced surnames etc.) were traced manually, outdated GitHub username were found by listing the usernames in the textbox for opening new issues and observing which ones did not get hyperlinked.
- Commit 3: did a `git log` for 10000 entries and checked with `about.jsp` on the usernames that are not listed (automated). Traced on GitHub manually to find out whether single or multiple contributions.
- Commit~~s~~ 4 ~~and 5~~: as per how the community structure is like currently.
If some things need not be done on this PR, I will undo the relevant …
=> Update about.jsp with contributors from V5.97 #6682

src/main/webapp/js/datepicker.js
Fixes #6693 
> Tell us how you solved the issue
I just remove the unused methods getMinDateForEndDate and getMaxDateForStartDate, as described in the issue.
Is ready for review
=> Remove unused methods in datepicker.js #6693

docs/settingUp.md
Added warning for windows user to use forward slash instead of backward slash while entering the path to JDK.
Fixes #6723
> Added warning for windows user to use forward slash instead of backward slash while entering the path to JDK.
=> Setup guide: mention the Java path should use '/'    #6723

docs/development.md
=> development.md: Timezone needs to be specified in IntelliJ dev server run configuration during testing #6780

src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java
Fixes #6777
**Possible Reason**
I guess maybe testNG takes too much time to figure out the dependency (`dependsOnGroups = "..."`) and thus result in test case failures?
> 1. AdminActivityLogPageActionTest: change `dependsOnGroups` to `priority`
> 1. In testNG, `priority` starts from `0`, which is the highest priority. Note that I use `priority=2` instead of `priority=1` for better understanding as some developers may think it start from `1`. And actually, as long as the `manyLogs` group run separately from `typicalLogs` group. You can set any priority that bigger or equal to 1.
=> Random test fail in *LogicTest.java recently #6777

docs/settingUp.md
=> Change `File` to `Configure` in Step 2 of instructions for setting up IntelliJ  fixes #6726  

src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java
Fixes #6857
> Delete the line as xpdavid suggested.
actualMsg = actualMsg.replace("<mark>", "").replace("</mark>", "");
=> Remove useless replacement of text in AdminActivityLogPageActionTest #6857

src/main/java/teammates/common/util/Const.java, src/test/java/teammates/test/cases/browsertests/AllJsTests.java, src/test/java/teammates/test/pageobjects/QUnitPage.java
Fixes #6935 
Removed the check for coverage in staging server; that is, testing against staging server will only check that all the unit tests pass.
Coverage check is still done in dev server during CI run which is sufficient.
=> AllJsTests failing on the live server #6935

src/main/java/teammates/storage/api/StudentsDb.java
Fixes #6975
Typo in header comment for searchStudentInWholeSystemMethod in
StudentDb. Changed from ‘admin’ to ‘admin.’
Fixed typo in header comment for searchStudentInWholeSystemMethod in “src/main/java/teammates/storage/api/StudentsDb.java”
Changed from ‘amdin’ to ‘admin.’
=> Fix typo in header comments for searchStudentsInWholeSystem method in StudentDb #6975

src/test/java/teammates/test/cases/browsertests/InstructorCourseDetailsPageUiTest.java
Fixes #6934
Wait for status message to appear on same page after ajax request to remind student so it doesn't show up unexpectedly on a subsequent page.
=> InstructorCourseDetailsPageUiTest failing on live server #6934

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, build.gradle, docs/staticAnalysis.md, static-analysis/teammates-eslint-es6.yml
Fixes #7020 
- Suppressed rules that caused error on Windows: `linebreak-style` and `func-names` (the latter did not really cause error, but made a lot of noise in the build log).
- Separated NPM scripts from Gradle. We could alternatively try [Gradle Node plugin](https://github.com/srs/gradle-node-plugin), but this needs more research and trial/error.
- Renamed `staticAnalysis` to `lint` in Gradle tasks to standardize with NPM's.
=> gradlew.bat staticAnalysis does not run on Windows #7020

src/main/webapp/js/common.es6
Fixes #7036 
Added the polyfill [as defined here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes) with some improvements (thanks to ESLint complaints).
=> Add polyfill for String.prototype.includes #7036

src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
Fixes #7064 and the recent heightened failure CI rate that delayed #7033.
The recent build failures are mostly due to timing issues - popovers seem to disappear faster after 972a10f, leading to an error when trying to validate the popover's content. This solution optimises the `InstructorFeedbackResultsPage` page object to remove unnecessary waiting.
**Details**
Ideally, the popover's content should be validated as soon as it appears. However, in many places, the element is grabbed in a separate call to `findElement` after `waitForElementPresence` returns. This is unnecessary as the underlying Selenium methods in `waitForElementPresence` already return the element once it appears and can be used to do validation. This solution makes use of this to eliminate …
=> InstructorFeedbackResultsPageUiTest unstable on local dev server #7064

src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
Fixes #7082
Pending stability measure (basically running the Travis build multiple times and counting successes and failures). Will update below.
- Use specific selectors for popovers (avoids validating the wrong popover)
- Don’t dismiss popovers (unnecessary due to usage of more specific selectors; can help prevent stale element exceptions)
- Retry once upon stale element exception (handles loading gif transforming into actual image)
=> InstructorFeedbackResultsPageUiTest view photo test unstable #7082

docs/README.md, docs/community.md, docs/glossary.md, docs/issues.md, docs/maintainer-guide.md, docs/process.md, docs/settingUp.md
Fixes #7055 
My last contribution as project lead before I bow out. 🙇
- Added everything that I think is important to know to be a project maintainer
- 429ca8a: I'm proposing a rule change that no one should push branches to the main repository unless necessary (I'm leading by example here!). Let me know your thoughts on this.
- Many parts of the guides are newly formalised by yours truly, e.g. the waiting times for certain actions. They can be strict or non-strict, entirely up to your discretion. If you think some parts need tweaks, let me know as well.
Finally, let me know what else you want to be included, and I'll try to accommodate.
=> Create a maintainer guide #7055

src/main/java/teammates/common/util/HttpRequestHelper.java
Fixes #7192 
Removes the unused `getParamMap` method and imports.
=> Remove HttpRequestHelper#getParamMap method #7192

src/main/webapp/request.jsp
Fixes #7202 
The google doc form embedded in the request.jsp file is not loading. The google doc alone was loading fine when accessed directly. However it was redirecting to a new URL. I updated the link present in the jsp file to the new link which is working. After updating, I tested it in my local Dev and Staging server setups, it seems to load fine.
I checked the traffic for the actual link and observed that a status message of 301 - moved permanently appears followed by the redirect to new URL.
Log:
`https://spreadsheets.google.com/embeddedform?formkey=dDNsQmU4QXVYTVRhMjA2dEJWYW82Umc6MQ`
`301 Moved Permanently`
`https://docs.google.com/forms/d/e/1FAIpQLSfmiNsVnVANdB1-cOwkfn9l8Ts8eN-CtolLQwi93Nrug0sngw/viewform?embedded=true&formkey=dDNsQmU4QXVYTVRhMjA2dEJWYW82Umc6MQ`
`200 OK`
This PR …
=> Give an alternative link to the account request form #7202

src/main/java/teammates/common/util/SanitizationHelper.java, src/test/java/teammates/test/cases/util/SanitizationHelperTest.java
Fixes #7256 
Allowed tags and attributes are based on manual testing with the frontend rich text editor and [a google group discussion on owasp java html sanitizer support](https://groups.google.com/forum/#!searchin/owasp-java-html-sanitizer-support/table%7Csort:relevance/owasp-java-html-sanitizer-support/4025rlufu-U/9isDp4FE8HgJ).
=> Whitelist tags that can be created by the rich text editor in the sanitization policy #7256

src/main/java/teammates/common/datatransfer/attributes/AdminEmailAttributes.java, src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java
Fixes #7248
Rich text sanitizer does not sanitize all characters blindly and most input entered through the frontend editor will still be the same after sanitization so there is no need to update current AdminEmailAttributes in the datastore.
=> Sanitize admin email content with sanitizeForRichText #7248

src/main/java/teammates/common/exception/InvalidOriginException.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/common/util/Url.java, src/main/java/teammates/ui/controller/Action.java, src/main/java/teammates/ui/controller/ControllerServlet.java, src/main/webapp/invalidOrigin.jsp, src/test/java/teammates/test/cases/browsertests/InstructorHomePageUiTest.java, src/test/java/teammates/test/driver/GaeSimulation.java
Fixes #7261
- Implement simple CSRF protection using HTTP referrer validation
- Display an informative error message if validation fails:
Developed together with @leeyimin and @thenaesh; reviewed by @chowyb @damithc @malayaleecoder; deployed to live server some time last week. Publishing to public repo after several days of no problems with the code in actual usage.
=> Add HTTP referrer validation #7261

src/main/java/teammates/storage/search/SearchQuery.java
Fixes #7325 
sanitizeForSearch is removed for queryString as each keyword/ string formed in prepareOrQueryString is properly enclosed with quotes. Each keyword/ string is also left to be tokenized and processed on Google's end in a similar manner as the text in the document. This removes the need for sanitization of the queryString which is added to prevent injection and to simulate the tokenization.
With sanitizeForSearch removed, searching for students (or non-sanitized data in general) is improved as searches using quotes-enclosed string with special html characters can be matched properly with the unsanitized data in the document. Searches without quotes-enclosed strings are also improved as the further tokenization of the tokens are left to be handled on …
=> Fix sanitization of query string in SearchQuery #7325

src/main/webapp/WEB-INF/tags/shared/feedbackSubmissionEdit/questionWithResponses.tag, src/main/webapp/js/feedbackSubmissionsEdit.es6
Fixes #4296 
In `questionWithResponses.tag` previously `moderated-question` was defined as a class, changed it to an ID because it was used for scrolling purpose.
=> questionWithResponses.tag: change "moderated-question" HTML class to an id #4296

src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java, src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java, src/main/java/teammates/ui/pagedata/InstructorCourseEditPageData.java, src/main/webapp/js/adminActivityLog.es6, src/main/webapp/js/adminEmailLog.es6, src/main/webapp/js/instructorCourseEdit.es6, src/test/resources/pages/instructorCourseEditAddInstructor.html, src/test/resources/pages/instructorCourseEditCoowner.html, src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html, src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html, src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html, src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html, src/test/resources/pages/instructorCourseEditHelper.html, src/test/resources/pages/instructorCourseEditManager.html, src/test/resources/pages/instructorCourseEditObserver.html, src/test/resources/pages/instructorCourseEditTutor.html, src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html
Fixes #6961 partially. WIP. 
Gets rid of `onclicks` in the `*Action` and `*PageData` classes, **except** the `toggleSort`s.
=> Remove inline javascript onclicks #6961

appveyor.yml
Fixes #7303 
Solved the issue by updating the appveyor.yml [line 23] to read "- choco install firefox --version 46.0" from "- choco install firefox -version 46.0"
=> appveyor.yml: fix warning in install firefox command #7303

src/main/webapp/WEB-INF/web.xml, src/main/webapp/about.jsp, src/main/webapp/contact.jsp, src/main/webapp/deadlineExceededErrorPage.jsp, src/main/webapp/enableJs.jsp, src/main/webapp/entityNotFoundPage.jsp, src/main/webapp/errorPage.jsp, src/main/webapp/features.jsp, src/main/webapp/feedbackSessionNotVisible.jsp, src/main/webapp/googleAccountHint.jsp, src/main/webapp/index.jsp, src/main/webapp/instructorHelp.jsp, src/main/webapp/invalidOrigin.jsp, src/main/webapp/pageNotFound.jsp, src/main/webapp/partials/instructorHelpAddEditInstructors.jsp, src/main/webapp/partials/instructorHelpComments.jsp, src/main/webapp/partials/instructorHelpFAQ.jsp, src/main/webapp/partials/instructorHelpGettingStarted.jsp, src/main/webapp/partials/instructorHelpSessions.jsp, src/main/webapp/partials/instructorHelpTips.jsp, src/main/webapp/pulse.jsp, src/main/webapp/request.jsp, src/main/webapp/studentHelp.jsp, src/main/webapp/terms.jsp, src/main/webapp/unauthorized.jsp, src/main/webapp/usermap.jsp
Fixes #7403
Demo:
https://teammates-whipermr5.appspot.com/ (root URL home page test)
https://teammates-whipermr5.appspot.com/abc (finite 404 test #6889)
https://teammates-whipermr5.appspot.com/instructorHelp.jsp#gs (UTF-8 test https://github.com/TEAMMATES/teammates/pull/7391#issuecomment-304433019)
- Use custom `welcome-file-list` implementation to serve home page without running into infinite redirect issue (#6889)
- Restore `jsp-config` with default `jsp` encoding specified, originally removed in #7221
- Remove `<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>` line from all static `jsp` files
=> Specify default jsp encoding in web.xml #7403

src/main/java/teammates/ui/controller/Action.java
Fixes #7411
- Compute session token from requested session ID instead of current session ID in case it has changed (if request does not have a session, use ID of new session)
=> Token validation: handle requests with old sessions #7411

docs/settingUp.md, src/test/java/teammates/test/driver/StringHelperExtension.java, src/test/java/teammates/test/driver/TestProperties.java, src/test/resources/pages/adminAccountDetails.html, src/test/resources/test.template.properties
Fixes #6812
- Use random test account names (implemented through appending a random salt to default account names) when in CI to detect and prevent hard-coding
- Remove are-all-test-accounts-ready check
=> Project setup: eliminate the need to modify config file manually after `./gradlew setup` #6812

src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Fixes #6575
- Wait for presence of first message to avoid empty messages array in `verifyVisibilityMessageIsDisplayed` (fixes `IndexOutOfBoundsException`)
- Use retries in place of various `BackDoor.get*` calls (fixes various `AssertionError`s)
=> InstructorFeedbackEditPageUiTest: fix failure against live server #6575

package.json
Fixes #7469
Use double quotes for options in lintspaces as single quotes does not work on Windows.
=> Fix lintspaces on Windows #7469

src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag, src/main/webapp/js/instructorFeedbackEdit/questionRubric.es6
Fixes #7382 
Corrected `textarea` tags as per issue. There shouldn't be any line breaks inside the tag.
=> instructorCourseStudentDetailsEdit and rubric question: Remove spaces inside textarea #7382

src/main/webapp/WEB-INF/tags/instructor/results/responsePanel.tag, src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentAdd.tag, src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentForm.tag, src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentRow.tag, src/main/webapp/js/feedbackResponseComments.es6, src/main/webapp/jsp/instructorFeedbackResponseCommentsLoad.jsp, src/test/resources/pages/instructorFeedbackResultsAddComment.html, src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html, src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html, src/test/resources/pages/instructorFeedbackResultsDeleteComment.html, src/test/resources/pages/instructorFeedbackResultsPageRankRGQView.html, src/test/resources/pages/instructorFeedbackResultsPageRubricGRQView.html, src/test/resources/pages/instructorFeedbackResultsPageRubricRGQView.html, src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html, src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html, src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestion.html, src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestionTeam.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestion.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestionTeam.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientGiverQuestion.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientGiverQuestionTeam.html
Part of #6961
Removed all `onclick`s found in FRC-related pages and replaced them with proper event delegation. Will have significant conflict with #7418.
=> Remove inline javascript onclicks in FRC-related pages #6961

.templates/.idea/runConfigurations/CI_Tests.xml, .templates/.idea/runConfigurations/Failed_Tests.xml, .templates/.idea/runConfigurations/Local_Tests.xml, .templates/eclipseLaunches/All tests.launch.xml, .templates/eclipseLaunches/CI tests.launch.xml, .templates/eclipseLaunches/Failed tests.launch.xml, .templates/eclipseLaunches/Local tests.launch.xml, build.gradle, docs/development.md, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/common/util/JsonUtils.java, src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/ui/controller/ControllerServlet.java, src/main/webapp/WEB-INF/web.xml, src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java
Fixes #7520
- Set time zone to UTC in `ControllerServlet` init
- Add `load-on-startup` flag to `ControllerServlet` in `web.xml` to ensure code runs at server startup
- Fix `StudentProfileAttributesTest` to be independent of system time zone
- Fix `JsonUtils` to always read and write JSON dates in UTC, independent of system time zone (lightens reviewer's burden of checking time zone of date fields in JSON files in PRs that touch them)
=> Project setup: eliminate the need to set the user.timezone VM flag #7520

.travis.yml
Fixes #7548
This is the quickest way to fix #7548 before the Wednesday, 21 June 2017, 14:30 UTC deadline. The more advanced way involves updating to JDK 8, which requires the AppEngine SDK to be updated first (#7529) and also has a caveat that several test cases need to be fixed due to a change in iteration order for HashMaps and HashSets when going from JDK 7 to JDK 8 (https://github.com/TEAMMATES/teammates/commit/69c3ce3988c5f6e4022274ac0a604334af47b8e2). This will be attempted at a later date.
=> .travis.yml: downgrade to Precise image #7548

src/main/resources/package.json
Fixes #7560 
Upgraded qunit library to 2.3.3 (latest). This both serves as an upgrade as well as to circumvent the unpkg caching problem. Verified in both Travis CI and AppVeyor.
=> Fix AllJsTests failure in Travis #7560

src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
Fixes #7170, fixes #7373
`FeedbackContributionQuestionDetails`: Skip results from "Instructors" team when building the (team name)-(team members' emails) map
**Details**
There seems to be an assumption throughout `FeedbackContributionQuestionDetails` that all team members' emails (provided by the method `getTeamMembersEmail`) are student emails. For example, the method `getStudentResults` assigns the name `studentEmail` when it iterates through the team members' emails ([link](https://github.com/TEAMMATES/teammates/blob/2a9b3988d59ea1ad33ba446aef7d8797aa72b7b1/src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java#L484)):
```
for (String studentEmail : teamEmails) {
```
and the method `getTeamResults` has this assignment …
=> Instructor: download results: fix NullPointerException #7170

src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
Fixes #7686
- Use `RetryManager` to retry hover-click process (fixes main `NoSuchElementException` and occasional `StaleElementReferenceException`)
**Other Stability Improvements**
- Use `waitForElementPresence` to get link element in `clickViewPhotoLink` (fixes occasional `TimeoutException`)
- Handle case when AJAX loader GIF URL is encountered instead of profile photo URL (fixes occasional `AssertionError`)
**Stability Measure**
- Number of CI builds where `InstructorFeedbackResultsPageUiTest`'s `testViewPhotoAndAjaxForLargeScaledSession` passed on first try: `55`/`55`
=> InstructorFeedbackResultsPageUiTest: improve stability of hover-triggered popover image verification #7686

src/main/webapp/dev/js/common/visibilityOptions.es6
Fixes #5996 
**Outline of solution**:
Added a `beforeSend` method to the AJAX call in visibilityOptions.es6 where I place the AJAX Loader GIF in `$visibilityMessageDiv.html()`. Borrowed the approach from other AJAX Loader GIFs in other AJAX calls (eg: feedbackResponseComments.es6)
=> Instructor: edit question: show spinner while loading visibility preview #5996

src/main/java/teammates/logic/backdoor/BackDoorLogic.java, src/main/java/teammates/logic/backdoor/BackDoorOperation.java, src/main/java/teammates/logic/backdoor/BackDoorServlet.java, src/main/java/teammates/storage/api/AccountsDb.java, src/main/java/teammates/storage/api/EntitiesDb.java, src/main/java/teammates/storage/api/FeedbackQuestionsDb.java, src/main/java/teammates/storage/api/InstructorsDb.java, src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java, src/test/java/teammates/test/cases/search/InstructorSearchTest.java, src/test/java/teammates/test/driver/BackDoor.java
Fixes #2258 
- Use Objectify deferred operations to queue many writes and flush them at one go
- Save created question entities when writing for later lookup of question IDs
- Avoids the need to perform additional Datastore reads later on when injecting the real IDs into the responses and comments
- Create local mappings of course instructors, session questions and session responses for later lookup when updating session respondents
- The entire update session respondents routine can then be performed completely locally even before any of the data is persisted, eliminating the need to perform additional Datastore reads later
- This also means that persist data bundle only works for self-contained bundles, i.e. the bundle must contain all the instructors, sessions …
=> BackDoorLogic: optimize persistDataBundle method #2258

src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java, src/main/java/teammates/logic/core/InstructorsLogic.java, src/main/java/teammates/storage/api/InstructorsDb.java, src/main/java/teammates/storage/entity/Instructor.java
Fixes #7795
- moved Comparator method `compareByName` from `Instructor` to `InstructorAttributes`.
- moved the sort logic from `InstructorsDb` to `InstructorsLogic`.
Apologies for my mistake in PR #7680
=> Move sorting of instructors from storage layer to logic layer #7795

src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java, src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
Fixes #7669, fixes #7789
The root issue is that the session start time of the session created via UI in the test is inconsistent across systems with different time zones. This results in inconsistent behaviour of the publish button, whose disabled state depends on whether or not the session is waiting to open (and subsequently has a dependency on the session start time).
It turns out that one of the test sessions created during the test had start time unspecified. The test was relying on the browser to fill in the correct start time, based on the default date picker behaviour (next hour from current time). This is fine, except that the same test also specified a time zone (5.75). Now this poses a problem. While start time is autodetected (next hour based on the …
=> InstructorFeedbackSessionsPageUiTest: remove dependency on browser time zone #7669

src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java, src/main/java/teammates/common/util/TimeHelper.java, src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java, src/test/resources/pages/instructorFeedbackSubmitPagePrivate.html
Fixes #7808 
Fixes the recent slew of Travis build errors between UTC 1600 and UTC 0000. The builds were failing due to some aspects being overlooked in #7740. The exact causes are explained by @leeyimin in the Issue Description.
- Handle null end time in a44db4e. This prevents the build error for InstructorFeedbackSubmitPageUiTest.
- Set the session end time to current time in the session's time zone instead of UTC in 5916ccc. This prevents the build error for StudentFeedbackSubmitPageUiTest.
Sorry for taking so long to push these changes. As I explained in https://github.com/TEAMMATES/teammates/issues/7808#issuecomment-317053489, I missed [this line](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/driver/HtmlHelper.java#L394) in …
=> *FeedbackSubmitPageUiTest: Fix dependency on current time #7808

src/main/java/teammates/common/util/FieldValidator.java, src/test/java/teammates/test/cases/BaseTestCase.java, src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java, src/test/java/teammates/test/cases/action/InstructorCourseEditSaveActionTest.java, src/test/java/teammates/test/cases/action/InstructorFeedbackCopyActionTest.java, src/test/java/teammates/test/cases/action/InstructorFeedbackEditCopyActionTest.java, src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorCourseEditPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorCourseStudentDetailsEditPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorCoursesPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java, src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java, src/test/java/teammates/test/cases/datatransfer/CourseAttributesTest.java, src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java, src/test/java/teammates/test/cases/datatransfer/InstructorAttributesTest.java, src/test/java/teammates/test/cases/datatransfer/StudentAttributesTest.java, src/test/java/teammates/test/cases/storage/CoursesDbTest.java, src/test/java/teammates/test/cases/storage/InstructorsDbTest.java, src/test/java/teammates/test/cases/storage/ProfilesDbTest.java, src/test/java/teammates/test/cases/util/FieldValidatorTest.java, src/test/java/teammates/test/driver/FieldValidatorExtension.java, src/test/resources/pages/instructorCoursesAddMissingParamsFailed.html
Fixes #4129 
Change error message from 
_[this]_
`
"" is not acceptable to TEAMMATES as feedback session name because it is empty. 
`
_[to this]_
`
The field <field_name> is empty. 
`
=> Instructor: add courses/sessions: give more specific error messages when a field is empty #4129

appveyor.yml, src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java, src/test/java/teammates/test/driver/TestProperties.java, src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java, src/test/resources/test.appveyor.properties, src/test/resources/test.travis.properties
Fixes #7699
- Fix browser tests on Chrome
- Use Chrome for AppVeyor build
- Remove Firefox install from `appveyor.yml`
- Add Travis- and AppVeyor-specific test properties files
**Results**
- AppVeyor build (Chrome) is [passing](https://ci.appveyor.com/project/whipermr5/teammates/build/1.0.221)
- Using Chrome decreases the build time by 3 minutes 🎉
- Edit: this is probably due to some tests being [skipped](https://github.com/TEAMMATES/teammates/blob/99aaeabcbbf95cdbcbb40b1c80377d9ec87530c7/src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java#L353-L356)
- Travis build (Firefox) is [passing](https://travis-ci.org/whipermr5/teammates/builds/252042555)
=> Fix browser tests that fail on Chrome #7699

src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentRow.tag, src/test/resources/pages/instructorFeedbackResultsAddComment.html, src/test/resources/pages/instructorFeedbackResultsDeleteComment.html, src/test/resources/pages/instructorFeedbackResultsPageGQRWithSanitizedData.html, src/test/resources/pages/instructorSearchPageSearchCommentsAsHelper.html, src/test/resources/pages/instructorSearchPageSearchFeedbackResponseComments.html, src/test/resources/pages/instructorSearchPageSearchTestingSanitization.html, src/test/resources/pages/instructorStudentRecords.html, src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html, src/test/resources/pages/studentFeedbackResultsPageNewlyRegistered.html, src/test/resources/pages/studentFeedbackResultsPageOpen.html, src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html, src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html
Fixes #7719 
- Used bootstrap to achieve the desired changes.
- Added `row` class to `commentBar` parent div
- Surrounded the comment details and `eye icon` with a `col-xs-10`
- Surrounded the edit and delete buttons with `col-xs-2`
**Screenshot of change:**
(Old behaviour can be seen in issue description)
New behaviour:
**Option 1:** (`10-2`)
Note: we can also change the distribution of bootstrap columns to 11-1. This would make the comment bar look like this:
**Option 2:** (`11-1`)
Depending on whatever looks better according to everyone, we can finalise between `10-2` and `11-1` and then I will go ahead with god mode.
=> Instructor: response comments: fix misalignment of edit/delete buttons #7719

src/main/webapp/dev/js/main/studentMotd.es6
Fixes #7794 
Modified the [`fetchMotd`](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/studentMotd.es6#L4) function to this 
```javascript
function fetchMotd(motdUrl, motdContentSelector, motdContainerSelector) {
$.ajax({
type: 'GET',
url: `${window.location.origin}/${motdUrl}`,
success(data) {
const bodyContent = data.match(/<body[^>]*>[\s\S]*<\/body>/gi);
$(motdContentSelector).html(bodyContent);
},
error() {
$(motdContainerSelector).html('');
},
});
}
```
This updated `fetchMotd` on success will only return the data present inside the `Body element` to `student-motd` container.
=> Student: MOTD: include only body of fetched HTML resource file #7794

src/test/java/teammates/test/cases/browsertests/FeedbackRubricQuestionUiTest.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Fixes #7861 
The issue had two parts:
1. **Test failing locally using Firefox**: fixed in daa701b by adding a `waitForElementToBeClickable()` and changing the click method from `WebElement.click()` to our own `AppPage.click(WebElement)`
2. **Test failing both locally and on AppVeyor using Chrome:** fixed by removing the unnecessary `sendKeys()` call in 6d5494b. @VamsiSangam commented  _"move column buttons must be visible, otherwise, the test fails"_ before the line in question. I have left this comment in on purpose so that we can discuss whether or not the line I removed was actually necessary (as that comment implies), but the test passed on both chrome and firefox without this line and the "move column" buttons seemed to be visible anyway when I tried it out using `Thread.sleep()`.
=> FeedbackRubricQuestionUiTest: fix cannot focus element error on Chrome #7861

src/test/java/teammates/test/cases/browsertests/InstructorCourseJoinConfirmationPageUiTest.java
Fixes #7892 
I copied and pasted the correct javadoc link to replace the broken one. This is ready for review.
=> InstructorCourseJoinConfirmationPageUiTest: Fix broken Javadoc link #7892

src/test/java/teammates/test/cases/testdriver/BackDoorTest.java
Fixes #7901 
```diff 
String courseId = "tmapitt.tcc.course";
String name = "Tmapitt testInstr Name";
String email = "tmapitt@tci.tmt";
-        @SuppressWarnings("deprecation")
+        
InstructorAttributes instructor = InstructorAttributes.builder(instructorId, courseId, name, email)
.build();
```
=> BackDoorTest: Remove `@SuppressWarnings("deprecation")` #7901

src/main/webapp/dev/js/main/feedbackSubmissionsEdit.es6
Fixes #7911 
Changed the loading text for the submit button from an empty string to "Submitting ".
=> Student submission page: add loading text to submit button #7911

src/main/java/teammates/common/util/FieldValidator.java, src/test/java/teammates/test/cases/action/AdminInstructorAccountAddActionTest.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditCopyUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/util/FieldValidatorTest.java
Fixes #3436 
- Changed the error message for all input fields which contain ( % or | ).
Previous error message: `All ${fieldName} must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).`
New error message: `A ${fieldName} must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).`
=> Instructor: edit student data: fix typo in error message for team/section name #3436

src/main/resources/feedbackQuestionMcqResultStatsTemplate.html, src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html, src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html, src/test/resources/pages/instructorFeedbackResultsPageOpen.html, src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html, src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html, src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html, src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionATeam.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipient.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipientTeam.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestionTeam.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiver.html, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiverTeam.html, src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
Fixes #7962 
Made table `col-sm-12` so that it occupies full width for all resolutions. UI changes -
=> MSQ and MCQ results: make table occupy full width #7962

src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java, src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/ui/pagedata/InstructorCoursesPageData.java, src/main/java/teammates/ui/template/ActiveCoursesTableRow.java, src/main/java/teammates/ui/template/ArchivedCoursesTableRow.java, src/main/webapp/WEB-INF/tags/instructor/course/activeCoursesTable.tag, src/main/webapp/WEB-INF/tags/instructor/course/archivedCoursesTable.tag, src/main/webapp/dev/js/common/sortBy.es6, src/test/java/teammates/test/driver/HtmlHelper.java, src/test/resources/pages/godmode.html, src/test/resources/pages/godmodeExpectedOutput.html, src/test/resources/pages/godmodeExpectedPartOutput.html, src/test/resources/pages/instructorArchiveStatusNotAffected.html, src/test/resources/pages/instructorCoursesAddDupIdFailed.html, src/test/resources/pages/instructorCoursesAddInvalidIdFailed.html, src/test/resources/pages/instructorCoursesAddMissingParamsFailed.html, src/test/resources/pages/instructorCoursesAddSuccessful.html, src/test/resources/pages/instructorCoursesArchiveSuccessful.html, src/test/resources/pages/instructorCoursesDeleteSuccessful.html, src/test/resources/pages/instructorCoursesMultipleCourses.html, src/test/resources/pages/instructorCoursesNoCourse.html, src/test/resources/pages/instructorCoursesStatsAjaxFailure.html, src/test/resources/pages/instructorCoursesStatsAjaxSuccessful.html, src/test/resources/pages/instructorCoursesUnarchiveSuccessful.html
Fixes #1297 
**Outline of solution:**
- Added a method in CourseAttributes to get createdAt date field as a formatted String.
- Added this string as data to active and archived row classes
- Added this new data to the HTML tags.
- Used the `sort-comparator` from `toggle-sort` to sort by date.
Note: I have formatted the date using the `TimeHelper.formatDateTimeForInstructorHomePage` method. I had originally simply used the `formatDate` method but that was neither as user-readable and universally understood as this nor was it being parsed by JS as a date object (for `sortDate` comparator to work). Let me know if I should change the method name to `formatDateTimeForInstructorHomePageAndCoursesPage`.
**TODO:**
- ~~Run god mode.~~
=> Instructor: courses page: show creation time in active/archived courses #1297

src/main/webapp/WEB-INF/tags/student/studentMessageOfTheDay.tag
Fixes #7997 
**Outline of solution:**
- Simply removed the container class from a div that contained the Student MOTD feature in `studentMessageOfTheDay.tag`
- This `container` was causing the problem as it was a container within the container we already place in all our pages. Container within container is not recommended and leads to problems like these.
=> Student: Feedback Submission Edit: Fix misalignment of Student MOTD #7997

src/main/webapp/WEB-INF/tags/instructor/home/courseTable.tag, src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html, src/test/resources/pages/instructorHomeHTML.html, src/test/resources/pages/instructorHomeHTMLResponseRateFail.html, src/test/resources/pages/instructorHomeHTMLResponseRatePass.html, src/test/resources/pages/instructorHomeHTMLSortByDate.html, src/test/resources/pages/instructorHomeHTMLSortById.html, src/test/resources/pages/instructorHomeHTMLSortByName.html, src/test/resources/pages/instructorHomeHTMLSortSessionsByEndDate.html, src/test/resources/pages/instructorHomeHTMLSortSessionsByName.html, src/test/resources/pages/instructorHomeHTMLSortSessionsByStartDate.html, src/test/resources/pages/instructorHomeHTMLWithHelperView.html, src/test/resources/pages/instructorHomeHTMLWithUnloadedCourse.html, src/test/resources/pages/instructorHomeNewInstructorWithSampleCourse.html, src/test/resources/pages/instructorHomeTestingSanitization.html, src/test/resources/pages/newlyJoinedInstructorHomePage.html
Fixes #8025
Specified fixed grid width (4 columns) for actions column on `lg` resoutions (`col-lg-4`) to ensure sufficient width for all action buttons. The other columns will have less priority and become smaller. On `md` and lower resolutions, the action buttons wrap to multiple lines (no change to current behaviour).
Before:
After:
=> Instructor: home page: fix action buttons going out of table #8025

.travis.yml, appveyor.yml, build.gradle, docs/development.md, docs/setting-up.md, docs/troubleshooting-guide.md, src/client/java/teammates/client/remoteapi/RemoteApiClient.java
Part of #7648.
This is the first part of Cloud SDK migration. This has been worked on since as early as July but can only finalize for the past week due to a blocker issue on Cloud SDK.
**Notes**
- Routine has been tested on Travis CI (Linux-based), AppVeyor (Windows-based), and my own Mac OS-based environment.
- The App Engine version to be used is coupled to the Cloud SDK version. The latest SDK (~~172~~ 173.0.0) has support for Java SDK 1.9.56 which is ~~also~~ *unfortunately not* the latest. (P.S. Cloud SDK releases much more frequently than Java SDK which may or may not be helpful for us)
- Python 2.7 is needed, but only to run the Cloud SDK and not needed for development at all. Unfortunately not supported for Python 3, but [at least we're not Python 3 GAE …
=> Migrate development tools to Google Cloud SDK - CLI/Gradle #7648

docs/setting-up.md
Fixes #8022
Removed the "experimental; limited support" status for intellij, also removed "full support" from eclipse, as it now seemed obsolete.
=> setting-up.md: IntelliJ IDEA: remove `experimental; limited support` status #8022

src/main/webapp/dev/js/main/instructorFeedbackEdit.es6
Near line 130 of instructorFeedbackEdit.es6, a line began with a space -
} from '../common/visibilityOptions.es6';
Changed this to -
} from '../common/visibilityOptions.es6';
(Removed space in the beginning)
Fixes #7621 
(ready for review)
=> instructorFeedbackEdit.es6: Remove unwanted space #7621

build.gradle
Fixes #8113
Test runs:
- [Malformed XML](https://travis-ci.org/whipermr5/teammates/builds/289819078#L870)
- [Non-existent test](https://travis-ci.org/whipermr5/teammates/builds/289819453#L878)
- [Missing dependency](https://travis-ci.org/whipermr5/teammates/builds/289820300#L900)
=> build.gradle: fix misleading message when dependencies are not found #8113

src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/InstructorsLogic.java, src/main/java/teammates/storage/api/InstructorsDb.java, src/test/java/teammates/test/cases/logic/InstructorsLogicTest.java, src/test/java/teammates/test/cases/storage/InstructorsDbTest.java
Fixes #8168 
Removed `getInstructorsForEmail (String)` method from from `Logic`, `InstructorsLogic`, `InstructorsDb` and `testGetInstructorsForEmail` method from InstructorsLogicTest and `InstructorsDbTest`.
Also removed the `getInstructorEntitiesForEmail` method from `InstructorsDb` file, as it was causing pmdMain error.
=> Remove method getInstructorsForEmail(String) #8168

src/main/java/teammates/common/util/ActivityLogEntry.java, src/main/java/teammates/common/util/EmailLogEntry.java, src/main/java/teammates/common/util/LogMessageGenerator.java, src/main/java/teammates/common/util/StringHelper.java, src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java, src/main/java/teammates/ui/pagedata/AdminEmailLogPageData.java, src/test/java/teammates/test/cases/action/AdminEmailComposeSaveActionTest.java, src/test/java/teammates/test/cases/util/StringHelperTest.java, src/test/java/teammates/test/driver/AssertHelper.java
Fixes #7837 
I replaced instances using `StringHelper.join(String delimiter, String... elements)` with the native [`String.join(CharSequence delimiter, CharSequence... elements)` method](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.CharSequence...-).
One key behavior change is that the original `StringHelper.join` throws an `IllegalArgumentException` if `delimiter == null` but `String.join` throws a `NullPointerException` in the same situation.
I updated the test `testJoinWithNullDelimiter` in `teammates.test.cases.util.StringHelperTest` to reflect this change.
=> StringHelper: Remove join(String, String…) #7837

src/main/resources/feedbackQuestionContribResultStatsTemplate.html, src/main/webapp/instructorHelp.jsp, src/main/webapp/partials/instructorHelpAddEditInstructors.jsp, src/main/webapp/partials/instructorHelpArchiving.jsp, src/main/webapp/partials/instructorHelpComments.jsp, src/main/webapp/partials/instructorHelpFAQ.jsp, src/main/webapp/partials/instructorHelpGettingStarted.jsp, src/main/webapp/partials/instructorHelpProfile.jsp, src/main/webapp/partials/instructorHelpSearch.jsp, src/main/webapp/partials/instructorHelpSections.jsp, src/main/webapp/partials/instructorHelpSessions.jsp, src/main/webapp/partials/instructorHelpTips.jsp, src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionATeam.html, src/test/resources/pages/newlyJoinedInstructorFirstFeedbackSessionResultsPage.html, src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
Fixes #8190
- Moved link bookmarks from `<a>` tag into `<li>` or `<h>` tags where relevant to match [`studentHelp.jsp`](http://teammatesv4.appspot.com/studentHelp.jsp)
Demo can be seen [here](https://teammates-cara.appspot.com/instructorHelp.jsp)
=> Instructor: help page: remove link-style formatting from sub-titles #8190

src/client/java/teammates/client/scripts/DataBundleRegenerator.java, src/client/java/teammates/client/scripts/DataGenerator.java, src/client/java/teammates/client/scripts/StatisticsPerInstitute.java, src/main/java/teammates/common/datatransfer/InstructorPrivileges.java, src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackContributionResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java, src/main/java/teammates/logic/api/TaskQueuer.java, src/main/java/teammates/ui/controller/AdminSessionsPageAction.java, src/main/java/teammates/ui/controller/InstructorCourseInstructorAbstractAction.java, src/main/java/teammates/ui/controller/InstructorCourseRemindAction.java, src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java, src/main/java/teammates/ui/pagedata/FeedbackSubmissionEditPageData.java, src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java, src/main/java/teammates/ui/pagedata/InstructorSearchPageData.java, src/main/java/teammates/ui/template/ElementTag.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/pagedata/StudentFeedbackResultsPageDataTest.java, src/test/java/teammates/test/cases/testdriver/TestNgTest.java, src/test/java/teammates/test/driver/BackDoor.java, src/test/java/teammates/test/driver/GaeSimulation.java, src/test/java/teammates/test/driver/MockTaskQueuer.java
Fixes #8216 
I have replaced instances of `Map.Entry<String, String> entry : map.entrySet()` with `map.forEach(key, value)` across different files in the project.
To keep the naming for `key` and `value` consistent while still being descriptive as far as possible, I have named the `key` and `value` according to the following (in order of decreasing priority):
1. If the key and value of `Map.Entry` are named later in the same function, use these names.
e.g.
```
for (Map.Entry<String, HashMap<Integer, HashSet<String>>> entry : institutes.entrySet()) { 
insStat.name = entry.getKey();
insStat.studentTotal = entry.getValue().get(STUDENT_INDEX).size();
...
}
```
becomes `institutes.forEach((insStatName, inStatStudents) -> ...`
2. Otherwise, if the types of the `key` and …
=> Java: Use Java 8 map.forEach to iterate through map entries #8216

build.gradle
Fixes #8324 
- [Guava 22.0 works](https://ci.appveyor.com/project/wkurniawan07/repo/build/1.0.184). It still fails but the failures are those from months back.
- [Guava 23.0 does not work](https://ci.appveyor.com/project/wkurniawan07/repo/build/1.0.183).
=> Fix AppVeyor failure due to Guava version #8324

src/main/webapp/dev/js/main/instructorFeedbackEdit.js
Fixes #8329 
Similar to #8148 `discard` button does not work if user points the mouse to the glyphicon instead of the word `discard`. Fix by replacing `event.target` with `event.currentTarget` to capture the correct element when the event is triggered by a child element.
=> Instructor: discard edit question button: sometimes button does not work #8329

src/main/webapp/partials/instructorHelpGettingStarted.jsp
Fixes #8317
Added the missing label number in the instructor help page.
=> Add missing label number to instructor help page #8317

build.gradle
=> Fix missing group for build script task `setupIntellijStaticAnalysis` #8350

src/main/webapp/dev/js/common/instructorFeedbackResults.js, src/main/webapp/dev/js/main/instructorHome.js
Fixes #8391
Revert `event.currentTarget` to `event.target` where `target` was intended to be clicked target instead of delegated target.
=> Instructor home page: Fix broken panel buttons #8391

docs/ide-setup.md
Fixes #8397
Fix typo, changing HTML tag for XML.
=> ide-setup.md: Typo under text encoding: change HTML to XML #8397

src/test/java/teammates/test/cases/browsertests/BaseUiTestCase.java, src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java, src/test/resources/data/StudentProfilePageUiTest.json
Fixes #8393
As discussed in #8323, this PR fixes the `StudentProfilePageUiTest` class to use the instructor account with Google-Id correctly. Additionally, the test logic is also modified. To test the case when instructor does not have view-student-picture privilege (instructor is just a helper), a new course is created and the instructor lacks the privilege in this course.
=> StudentProfilePageUiTest failing on live server #8393

src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java, src/main/java/teammates/storage/api/FeedbackSessionsDb.java, src/main/java/teammates/storage/entity/FeedbackSession.java
Fixes #8410
- Store offset in `timeZone` field as `ZoneId` string of the corresponding fixed offset time zone
- Rename getter and setter to indicate that the current implementation is only storing offsets rather than real time zones, to be fixed in #84
=> FeedbackSession: repurpose legacy timeZone field #8410

src/main/java/teammates/storage/entity/FeedbackSession.java
Part of #8451
- Populate default values on load so a load/save of a legacy entity is sufficient to convert it
- Actual migration of all legacy entities will be done via script in #8448, since that script will have to load/save all `FeedbackSession` entities in the datastore anyway
=> FeedbackSession: use primitive type for all booleans #8451

src/main/java/teammates/common/exception/TeammatesException.java, src/main/java/teammates/common/util/Config.java, src/main/java/teammates/common/util/ThreadHelper.java, src/main/java/teammates/logic/core/MailgunService.java, src/test/java/teammates/test/cases/logic/EmailSenderTest.java, src/test/java/teammates/test/driver/GmailServiceMaker.java, src/test/java/teammates/test/driver/TestProperties.java
Fixes #8213.
Enhanced the usage of various `AutoCloseable` implementing objects to a `try-with-resources` form.  This will ensure these resources get closed and don't leak.  In keeping with good practice about running in an app server, I didn't close the `HttpServletReponse` output writer instances used to write response objects.
=> Java: Use Java 7 try-with-resources for AutoCloseable resources #8213

src/main/webapp/dev/js/common/questionConstSum.js, src/main/webapp/dev/js/common/questionRank.js, src/main/webapp/dev/js/main/instructorFeedbackEdit.js
Fixes #8463
`rank-option-table` is hidden every time `rank recipients` is toggled. Call a function so that the element is shown every time `rank options` is selected.
=> Instructor: add options (Rank and Distribute Points) question: add more options inputs not appearing #8463

docs/development.md
Fixes #8495 
- Removed `Short Name: Instructor<br>` from development.md
=> development.md: As Instructor: Remove `Short Name` from credentials of Instructor in Setting up guide #8495

docs/setting-up.md
Sepearte package available for Google cloud Java API plugin. For Linux system, the package can be directly installed.
Signed-off-by: Progyan Bhattacharya <progyanb@acm.org>
Fixes #8491 
=> Setup docs: Add installation instructions for Debian and Fedora OS #8491

src/test/resources/data/FeedbackSessionQuestionTypeTest.json
Fixes #8418
Submitting quick fix.
I tried adding tests related to the fix but couldn't as discussed in #8418. Would be happy to add tests (if possible) which check data of `numOfMsqChoices`.
=> FeedbackSessionQuestionTypeTest.json: fix malformed question metadata #8418

src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java, src/main/java/teammates/common/util/JsonUtils.java, src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/CoursesLogic.java, src/main/java/teammates/storage/api/CoursesDb.java, src/main/java/teammates/storage/api/EntitiesDb.java, src/main/java/teammates/ui/controller/InstructorCourseAddAction.java, src/main/java/teammates/ui/controller/InstructorCourseEditSaveAction.java, src/test/java/teammates/test/cases/browsertests/InstructorCoursesPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorHomePageUiTest.java, src/test/java/teammates/test/cases/datatransfer/CourseAttributesTest.java, src/test/java/teammates/test/cases/logic/BackDoorLogicTest.java, src/test/java/teammates/test/cases/logic/CoursesLogicTest.java, src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java, src/test/java/teammates/test/cases/pagedata/InstructorStudentListPageDataTest.java, src/test/java/teammates/test/cases/pagedata/StudentHomePageDataTest.java, src/test/java/teammates/test/cases/storage/CoursesDbTest.java, src/test/java/teammates/test/cases/storage/EntitiesDbTest.java, src/test/java/teammates/test/cases/testdriver/BackDoorTest.java
Part of #8362
This PR changes the `timeZone` field in`CourseAttributes` to `ZoneId` so that other classes that need time zone information can use it directly. Since `CourseAttributes` now always contains valid time zone, validation of the user supplied time zone field is done in `CourseLogic`. This comes after the Action level so usage of `CourseAttributes` in the Action level is removed.
=> TimeHelper: migrate to Java 8's `java.time` #8362 - migrate course `timeZone` field to `ZoneId`

src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java, src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java, src/main/webapp/dev/js/main/adminActivityLog.js, src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java, src/test/java/teammates/test/cases/browsertests/AdminActivityLogPageUiTest.java, src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java, src/test/resources/data/typicalDataBundle.json
Fixes #8594
Times in activity log page now always uses the same format. User's local time is attached with the timezone's name to avoid confusion in case our user timezone detection is wrong.
Also refactor `AdminActivityLogPageAction` and its test to use `java.time`.
=> Admin: recent activity log: show correct 'time stamp in instructor timezone' #8594

src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
Fixes #8709
- `Instant.now()` is unstable in tests
- So we need to hardcode the `modifiedDate` in tests to make it stable
Note:
As the migration to `java.time`  is still going on, there might be more such cases of unstable tests
=> AccountAttributesTest: fix instability due to modified timestamp comparison #8709

src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/api/FeedbackSessionsDb.java, src/main/java/teammates/ui/controller/AdminSessionsPageAction.java, src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java, src/main/java/teammates/ui/pagedata/PageData.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
Part of #8645 
1. Refactor `Date`/`double` fields in `AdminSessionsPageData` and `AdminSessionsPageAction` to `LocalDateTime`/`ZoneId` respectively.
2. Move deprecated calls from `*Logic` classes to `FeedbackSessionsDb` for removal at a later time, when `FeedbackSessionsDb` is migrated.
3. Change timezone dropdown menu (map in `TimeHelper`) to use `ZoneId` internally
- ~~Update timezone autodetection~~ covered by #8687
- ~~Update timezone dropdown list builders~~ 
- Update all affected tests and test resources
We preserve the time offset dropdown menu for the admin's sessions page for usability concerns, since using the regional timezone format (e.g. `Asia/Singapore`) doesn't show the offset from UTC, may not be very friendly to the admin and we don't have any …
=> AdminSessions*: migrate to java.time #8645

src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java, src/main/webapp/WEB-INF/tags/admin/accounts/accountDetailsForInstructorPanel.tag, src/main/webapp/WEB-INF/tags/admin/activity/activityLogTableRow.tag, src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
Fixes #8775
The only time these email addresses are displayed in the frontend are in admin pages. Hence, handling of double sanitisation (which happens when displaying existing accounts with already-sanitised emails) is not done.
=> AccountAttributes: remove HTML sanitization before saving for email #8775

src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java, src/main/java/teammates/storage/api/FeedbackQuestionsDb.java, src/main/java/teammates/storage/entity/FeedbackQuestion.java, src/main/java/teammates/ui/controller/InstructorFeedbackQuestionAddAction.java, src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java, src/main/java/teammates/ui/controller/InstructorFeedbackQuestionVisibilityMessageAction.java, src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
Part of #7190
- Created Builder class for `FeedbackQuestionAttributes`
- Added test 
Note to reviewer:
I have not use builder for instances like the one below so that a `NullPostParameterException` can be thrown if any parameter is null :
https://github.com/TEAMMATES/teammates/blob/a5240982dce465a8889cfe020094b559a7f9cb69/src/main/java/teammates/ui/controller/InstructorFeedbackQuestionAddAction.java#L81-L138
=> Use builder instead of telescoping constructor antipattern in FeedbackQuestionAttributes class #7190

src/main/java/teammates/common/datatransfer/attributes/AdminEmailAttributes.java, src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java, src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java, src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/logic/api/EmailGenerator.java, src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java, src/main/java/teammates/ui/controller/AdminSessionsPageAction.java, src/main/java/teammates/ui/controller/InstructorFeedbackAbstractAction.java, src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java, src/main/java/teammates/ui/pagedata/InstructorFeedbackResponseCommentAjaxPageData.java, src/main/java/teammates/ui/pagedata/InstructorHomeCourseAjaxPageData.java, src/main/java/teammates/ui/pagedata/StudentHomePageData.java, src/main/java/teammates/ui/template/AdminAccountManagementAccountTableRow.java, src/main/java/teammates/ui/template/AdminActivityLogTableRow.java, src/main/java/teammates/ui/template/AdminEmailTableRow.java, src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java, src/main/java/teammates/ui/template/InstructorFeedbackResultsSessionPanel.java, src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java, src/test/java/teammates/test/cases/datatransfer/AdminEmailAttributesTest.java, src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java, src/test/java/teammates/test/cases/pagedata/StudentHomePageDataTest.java, src/test/java/teammates/test/cases/util/TimeHelperTest.java, src/test/java/teammates/test/driver/HtmlHelper.java, src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Fixes #8780 
This PR touches a lot of files due to the renaming of methods in `TimeHelper`. There are no changes in logic made by this PR.
- Remove `formatDate`: it's not used anywhere other than a unit test for itself.
- Standardize method naming: they should now follow the form `(verb)(date|datetime|object)[(direction)(destination|object)]` for clarity on their intended purpose and behavior.
- Some methods have to be renamed to accurately reflect what is expected/returned.
For example, this is before:
```java 
formatTime12H
formatDateTimeForInstructorCoursesPage // this method returns a date stamp, not a datetime stamp
formatActivityLogTime // this is only used in admin-facing pages
formatInstantToIso8601Utc // this makes a ISO 8601 datetime stamp
```
And after, in the same order:
``` …
```
=> TimeHelper: update documentation and standardize method naming #8780

src/test/java/teammates/test/cases/browsertests/AllJsTests.java
Fixes #8768
Removed assert which checks for minimum coverage. 
The test still prints the current coverage although it's not 100% true, it might be useful to have an estimate of what is it.
Ready for Review @Crphang @LiHaoTan
=> Remove JS coverage requirement #8768

src/main/java/teammates/common/util/Const.java, src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java, src/main/webapp/dev/js/main/feedbackSubmissionsEdit.js, src/main/webapp/stylesheets/teammatesCommon.css, src/test/java/teammates/test/cases/action/InstructorEditInstructorFeedbackSaveActionTest.java, src/test/java/teammates/test/cases/action/InstructorEditStudentFeedbackSaveActionTest.java, src/test/java/teammates/test/cases/action/InstructorFeedbackSubmissionEditSaveActionTest.java, src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditSaveActionTest.java, src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorEditStudentFeedbackPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java, src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java, src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java, src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Fixes #8598 
In the feedback submission page, create an HashSet to store the indexes of the incomplete questions. Using the question indexes, create a status message using INFO status. Then, use javascript to retrieve that status message to be shown in the modal. The results are shown below:
However, I hardcoded the exclamation mark in and I am not sure if it serves the purpose cos it is not that visible. Hope you can advise me on this @Haozhe321 before I work on all the test cases. Thanks.
=> Student: submit responses: warn if there are unanswered questions #8598

src/main/webapp/dev/js/common/sortBy.js
Fixes #8837
- Initially the statement `const $rowList = $('tr', $table);` found all rows of the `$table` object which included all rows of child table (Part of the `add Comment` modal for the instructor) and hence it extracted and sorted them as well.
- This also results in simpler logic to query rows which are to be sorted
- This PR queries only the rows inside required tbody which are to be sorted and hence doesn't add any more content thereby fixing the bug.
P.S. I will be investigating soon why no tests took care of this and add extra tests in future PR as this is of urgent priority and should be merged ASAP
=> Instructor: view results: fix bug: sorting results by team is broken #8837

src/main/webapp/dev/js/main/instructorCourseStudentEdit.js
Fixes #8880
1. Corrected the parameter name required by `studentInformationTable.tag`.
=> Instructor: edit student details: resend past links to the new email not working #8880

src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java, src/test/java/teammates/test/cases/datatransfer/StudentAttributesTest.java, src/test/java/teammates/test/cases/pagedata/InstructorFeedbackEditPageDataTest.java, src/test/java/teammates/test/driver/GaeSimulation.java, static-analysis/teammates-macker.xml
Fixes #8898 
- Added the hostname setup logic to `BaseTestCaseWithMinimalGaeEnvironment`
- `InstructorFeedbackEditPageDataTest` and `StudentAttributeTest` now extends `BaseTestCaseWithMinimalGaeEnvironment` class
@xpdavid  As BaseComponentTestCase extends `BaseTestCaseWithMinimalGaeEnvironment` and overrides `setUpGae()` and `tearDownGae()` to executes `gaeSimulation.setup()`, So I did not completely move the hostname setup logic to `BaseTestCaseWithMinimalGaeEnvironment`, instead I added it. 
Is this what you had in mind?
=> Testing: unstable behaviour in CI Config.APP_URL can be null sometimes #8898

src/test/resources/pages/instructorFeedbackResultsEditCommentByDifferentInstructor.html, src/test/resources/pages/instructorFeedbackResultsPageGQRWithSanitizedData.html, src/test/resources/pages/instructorFeedbackResultsPageWithSanitizedData.html
Fixes #8937
- Remove extra `empty` class added in due to godmode of unstable tests
- Reverted two sanitization places caused unnecessary changes
Note: Working on fixing the unstable test
=> Remove wrong Godmode changes due to unstable test #8937

src/main/java/teammates/logic/api/EmailGenerator.java, src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java, src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForUnregisteredStudent.html
Fixes #8935 
- Added a required variable to be replaced in the template literal. The template literal originated from the template file `studentEmailFragment-courseJoin.html`.
=> Instructor: edit student details: email contains raw template literals after resending past links to the new email #8935

src/main/java/teammates/storage/api/FeedbackResponsesDb.java, src/main/resources/InstructorSampleData.json, src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
Fixes #8929 
Instead of filtering both `givers` and `recipients` by `section`. Merely filter `givers` by `section` to be consistent with downloadable data.
=> InstructorFeedbackResultsPage: Show consistent data on the webpage and downloaded data #8929

src/main/java/teammates/common/util/Const.java, src/test/java/teammates/test/cases/action/InstructorCoursesPageActionTest.java, src/test/resources/pages/instructorCoursesNoCourse.html
Fixes #8980
Replaced message "You have not created any courses yet. Use the form above to create a course." with 
"You do not seem to have any courses. Use the form above to create a course." in main as well as test cases
=> Instructor: delete course: rephrase message shown when there are no more courses left #8980

src/main/webapp/dev/js/main/instructorCourseEnrollHelper.js, src/main/webapp/dev/js/main/instructorCourseEnrollPage.js
Fixes #8972 
1. Added new modal box in helper file for paste option in `Handsontable` context menu.
2. Added new paste option in `Handsontable` context menu.
=> Instructor: enroll students: add a 'paste' option to the context menu #8972

src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java, src/test/java/teammates/test/cases/BaseComponentTestCase.java, src/test/java/teammates/test/cases/action/FeedbackParticipantFeedbackResponseCommentDeleteActionTest.java, src/test/java/teammates/test/cases/action/InstructorEditInstructorFeedbackSaveActionTest.java, src/test/java/teammates/test/cases/action/InstructorEditStudentFeedbackSaveActionTest.java, src/test/java/teammates/test/cases/action/InstructorFeedbackSubmissionEditSaveActionTest.java, src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditSaveActionTest.java, src/test/java/teammates/test/cases/search/FeedbackResponseCommentSearchTest.java
=> Student: Comment on responses: Fix put document error #9034

src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java, src/client/java/teammates/client/scripts/DataMigrationWithCheckpointForEntities.java
Fixes #9044 
- In the script, data is fetch in batch (default to 100 entities each round) (so no chance to have `OutOfMemoryError`). In addition, the cursor position will also be printed after each batch. 
- By copying the cursor position printed on the console and paste it into the code, the script will start from the position specified instead of staring the query again.
<hr>
I have provided a sample script for #9060 
In order to create orphaned student profile. The following java code can be used:
```java
package teammates.client.scripts;
import java.io.IOException;
import java.lang.reflect.Field;
import teammates.client.remoteapi.RemoteApiClient;
import teammates.storage.entity.StudentProfile;
public class CreateOrphanedStudentProfile extends RemoteApiClient { …
```
=> Data Migration: Able to resume/restart from where it fails/stops #9044

src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java
Fixes #9065 
As `modifiedTime` is not carried over when creating a `StudentProfile` or calling 
`StudentProfileAttributes.toEntity()`, the test will fail or pass depending on if lines 177 and 179 are executed fast enough to produce the same modifiedTime.
`assertsEquals(expectedEntity.getModifiedDate().toString(), actualEntity.getModifiedDate().toString());` was removed. It would hide the fact that `toEntity()` is setting the modifiedDate by also calling new `StudentProfile(...)` but it seems this is correct behaviour as I was encouraged to submit this change as a PR.
=> [#9065] Fix unstable testToEntity() in StudentProfileAttributesTest

src/main/java/teammates/logic/api/EmailGenerator.java, src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java, src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java, src/test/resources/data/EmailGeneratorTest.json, src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForUnregisteredStudent.html
Fixes #9090
When student email is updated, its registration Key should be updated also.
`InstructorCourseStudentDetailsEditSaveAction` doesn't do the the job correctly.
There are two solutions to fix this.
1. Write `logic.getStudentForEmail()` in `InstructorCourseStudentDetailsEditSaveAction` to get the updated student. ---- However, it is really hard to test the behavior as we ignore comparision of registrationKey.
1. Push the logic of getting updated student to `EmailGenerator` (which is our logic API) ---- `registrationKey` still no verified but less likely to cause regression in the future.
=> [#9090] Instructor edit email of student: send the correct link to student

src/client/java/teammates/client/scripts/DataMigrationForSessions.java
Fixes #8448
- It turns out that `@OnLoad` will turn `isFollowingCourseTimeZone` to ture (although I don't know why it is written in this way :D). Therefore, we should use `wasFollowingCourseTimeZone`, `true` when `isFollowingCourseTimeZone` is ture, `false` when `isFollowingCourseTimeZone` has been changed from `true` to `false` by `OnLoad` method.
- Also, add the ability to change counting stats according to https://github.com/TEAMMATES/teammates/issues/9084#issuecomment-417996024
=> [#8448] Complete migration of FeedbackSession entities

src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/backdoor/BackDoorLogic.java, src/main/java/teammates/logic/backdoor/BackDoorOperation.java, src/main/java/teammates/logic/backdoor/BackDoorServlet.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/api/FeedbackSessionsDb.java, src/main/java/teammates/ui/controller/InstructorFeedbackDeleteSoftDeletedSessionAction.java, src/main/java/teammates/ui/controller/InstructorFeedbackRestoreSoftDeletedSessionAction.java, src/test/java/teammates/test/cases/action/InstructorFeedbackDeleteActionTest.java, src/test/java/teammates/test/cases/action/InstructorFeedbackResultsPageActionTest.java, src/test/java/teammates/test/cases/action/StudentFeedbackResultsPageActionTest.java, src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditPageActionTest.java, src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditSaveActionTest.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java, src/test/java/teammates/test/driver/BackDoor.java
Fixes #9109
@dalessr is busy right now so I am submitting the fix instead.
From this incident, I think we could further improve the design of soft delete. See https://github.com/TEAMMATES/teammates/projects/5#card-12752944 Will discuss with @dalessr later.
To reviewer:
It seems like the changes are a bit overkilled as we can simply add checks for every involved action. However, once you begin to think about the actions involved, you will give up XD (e.g. feedback submit + feedback result + student comment delete + instructor comment edit + instructor comment delete etc. maybe more in the future)).
Therefore, I decide to change `getFeedbackSession()` to ignore every soft-deleted session and provide a new method `getSoftDeletedFeedbackSession()` to retrieve soft-deleted session. There is …
=> [#9109] Deactivate deleted sessions

src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/storage/api/AdminEmailsDb.java, src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java, src/main/java/teammates/storage/api/FeedbackSessionsDb.java, src/main/java/teammates/storage/api/OfyHelper.java, src/main/java/teammates/storage/entity/Account.java, src/main/java/teammates/storage/entity/AdminEmail.java, src/main/java/teammates/storage/entity/BaseEntity.java, src/main/java/teammates/storage/entity/Course.java, src/main/java/teammates/storage/entity/CourseStudent.java, src/main/java/teammates/storage/entity/FeedbackQuestion.java, src/main/java/teammates/storage/entity/FeedbackResponse.java, src/main/java/teammates/storage/entity/FeedbackResponseComment.java, src/main/java/teammates/storage/entity/FeedbackSession.java, src/main/java/teammates/storage/entity/StudentProfile.java, static-analysis/teammates-macker.xml
Fixes #9082 
This step is necessary to prepare for upgrade to Objectify V6.
We shall wait for #9081 to get merged before removal of `Date` of `FeedbackSession` can be done. Or, we can release a version with the changes first. Up to the reviewer to decide.
=> [#9082] Objectify: Use java.time.Instant instead of java.util.Date for entity

build.gradle, src/test/java/teammates/test/cases/BaseTestCase.java, src/test/java/teammates/test/driver/AssertHelper.java, src/test/java/teammates/test/driver/EmailChecker.java, src/test/java/teammates/test/driver/GaeSimulation.java, src/test/java/teammates/test/driver/HtmlHelper.java, src/test/java/teammates/test/pageobjects/AdminAccountDetailsPage.java, src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java, src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java, src/test/java/teammates/test/pageobjects/AdminEmailLogPage.java, src/test/java/teammates/test/pageobjects/AppPage.java, src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java, src/test/java/teammates/test/pageobjects/InstructorCopyFsToModal.java, src/test/java/teammates/test/pageobjects/InstructorCourseDetailsPage.java, src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java, src/test/java/teammates/test/pageobjects/InstructorCourseEnrollPage.java, src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java, src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsViewPage.java, src/test/java/teammates/test/pageobjects/InstructorCoursesPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java, src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java, src/test/java/teammates/test/pageobjects/InstructorStudentRecordsPage.java, src/test/java/teammates/test/pageobjects/StudentProfilePage.java, src/test/java/teammates/test/pageobjects/StudentProfilePicturePage.java, src/test/java/teammates/test/pageobjects/UserErrorReportPage.java, static-analysis/teammates-checkstyle.xml
Part of #8527. Partially reverts #9155. 
@xpdavid this PR has two commits:
- First commit changed all `assertEquals` to `org.junit`'s implementation. This restored the IntelliJ and Eclipse built-in comparison functions as we know it.
- Second commit changed all other `assert*` to `org.junit`'s implementation, hard-coded `assertThrows` (it's actually a really simple function), and removed dependency to JUnit 5.
Only the first commit is necessary to resolve the issue discussed, but I feel the second commit makes the code base more consistent. If we're going to migrate to JUnit 5, one can simply revert this PR (regardless of whether the second commit is included) to benefit from the new Assertions API. Let me know if the second commit should be included.
=> [#8527] Migrate back to JUnit 4's Assert API

src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java, src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java, src/test/resources/data/InstructorFeedbackSubmitPageUiTest.json, src/test/resources/pages/instructorFeedbackSubmitPageFullyFilled.html, src/test/resources/pages/instructorFeedbackSubmitPageModified.html, src/test/resources/pages/instructorFeedbackSubmitPageOpen.html, src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html, src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
Fixes #9198 
The issue arose because constant sum (recipient) questions require responses for different recipients to be related, but constant sum (option) questions treat different recipients differently.
To resolve the issue, I have made the checks for constant sum (recipient) questions and constant sum (option) questions more distinct. For questions that force an uneven distribution (all uneven or at least some), if the question only have a single response, checks for the distribution are skipped.
I have also tidied up the tests in `InstructorFeedbackSubmitPageUiTest.java`, and made sure the tests are more comprehensive. The tests now include the following cases and check both unsuccessful and successful submissions:
Q18: recipient, does not force uneven
Q19: …
=> [#9198] Student: submit response to distribute-points question: all responses are rejected

.travis.yml, appveyor.yml, build.gradle, src/e2e/resources/test.travis-chrome.properties
(still) Part of #9079
Benefits:
- Build time reduced from (currently) ~11 mins to ~8.5 mins
- If linting fails, testing will still proceed but the build will still be marked as fail, but this time without wasting time because the linting stage is done in parallel.
Note that this is only possible in V7 because the component tests and E2E tests are independent. In V6, it can be done, but the benefit (in terms of time saving) is very limited.
=> [#9079] Use Travis build stages to make lint/test independent from each other

src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java
Fixes #9119
The initial testing code did not verify the case where a duplicate comment is added.
When a duplicate comment is added,  the expected behaviour is:
1. Check database and retrieve the ID of the existing comment
2. Set ID of the existing comment to the duplicate comment
3. Update this comment if needed
As such, in the test, I do a verification of whether the ID has been set correctly. I also change the `commentText` and check if the update works.
=> [#9119] FeedbackResponseCommentsLogicTest: Fix verification for test

src/main/java/teammates/logic/core/StudentsLogic.java, src/main/java/teammates/storage/api/StudentsDb.java, src/main/java/teammates/storage/entity/CourseStudent.java, src/test/java/teammates/test/cases/storage/StudentsDbTest.java
Fixes #9250 
Removed keepUpdateTimestamp from CourseStudent.java along with the parts that showed up within the StudentsDb.java file and StudentsLogic.java.  I also removed the corresponding test.
=> [#9250] Removed keepUpdateTimestamp in CourseStudent

docs/development.md
Fixes #9336 
Changed "chromedriver executable" to "geckodriver executable" in the Firefox E2E test setup section in development.md
=> [#9336] development.md: Fix Firefox E2E setup misinformation

sort-usermap.js
=> [#9354] Fix path for userMapData.json in sort-usermap.js

src/main/java/teammates/ui/webapi/action/CreateAccountAction.java
=> [#9390] Cannot create an instructor with an email that has a 2 letter domain

src/web/app/pages-help/instructor-help-page/instructor-help-section.component.ts, src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts
Part of #9382 
Done to avoid chaining of multiple boolean conditions using the Or operator. A single function is used to compute the value instead, and can be used for other sections where the number of conditions would be too many to feasibly chain.
=> [#9382] Refactor chained boolean values into function

src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.scss, src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.spec.ts, src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.ts, src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts, src/web/app/pages-instructor/instructor-pages.module.ts, src/web/app/pages-static/static-pages.module.ts
Part of #9382 
Current look in v7
The route for this page is `/web/front/getting-started`
PS: In the html file for the list of links at the beginning, I used `<a (click)="jumpTo(...)" href>` to maintain the link styling (blue color, underline and cursor) and for accessibility reasons.
Taken from [here](https://github.com/ng-bootstrap/ng-bootstrap/issues/142#issuecomment-231587330)
Things left to be done:
=> [#9382] Migrate instructor getting started page

src/main/java/teammates/ui/webapi/action/GetNationalitiesAction.java, src/main/java/teammates/ui/webapi/output/NationalitiesData.java, src/test/java/teammates/test/cases/webapi/GetNationalitiesActionTest.java, src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
Part of #9420 
Return a `NationalitiesData` DTO for the `GET /nationalities` endpoint.
Remaining changes are to fix action tests and frontend to use this new
response DTO.
Expected works:
* ~~Parameters are used to identify the resource to modify, use request body to pass data~~ (not applicable)
* ~~POST/PUT should return the updated entity if any~~ (not applicable)
=> [#9420] Consolidate nationalities RESTFul API

src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/ui/webapi/action/GetLocalDateTimeInfoAction.java, src/main/java/teammates/ui/webapi/action/GetTimeZonesAction.java, src/main/java/teammates/ui/webapi/output/LocalDateTimeInfo.java, src/main/java/teammates/ui/webapi/output/LocalDateTimeInfoData.java, src/main/java/teammates/ui/webapi/output/TimeZonesData.java, src/test/java/teammates/test/cases/webapi/GetLocalDateTimeInfoActionTest.java, src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java, src/web/app/pages-admin/admin-timezone-page/admin-timezone-page.component.ts, src/web/services/timezone.service.ts
Part of #9420
Implement response DTOs for the following endpoints:
- `GET /timezones` => `TimeZonesData`
- `GET /localdatetime` => `LocalDateTimeInfoData` (yes, I know. Unfortunately the `Data` suffix is stripped when the types are generated for ts, so I think it's easier to just name the class this way.)
=> [#9420] Consolidate time-related RESTFul APIs

src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Part of #9382 
This user flow wasn't thoroughly tested as there are no easy ways to add new courses during the time when this page was migrated. 
This PR fixes the issue where the `Existing students` panel stays expanded even when there are no existing students in the course.
=> [#9382] Fix logic bug when there are no existing students in course

src/web/app/page.component.scss
Fixes #9461
Made the behaviour of the `focus` state of the nav bar dropdown items consistent with the other nav bar items (it retains the properties of the `hover` state).
=> [#9461] Focus state of nav bar item results in bad readability

src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/ui/webapi/action/ActionFactory.java, src/main/java/teammates/ui/webapi/action/GetSessionResultsAction.java, src/main/java/teammates/ui/webapi/action/Intent.java, src/main/java/teammates/ui/webapi/action/SaveFeedbackResponseAction.java, src/main/java/teammates/ui/webapi/output/SessionResultsData.java
Part of #9382 (this is the most difficult API to migrate, by far)
The API is still in conceptual stage. It is designed with usages for student/instructor session result page in mind, but whether or not it actually works can only be known when the pages are actually migrated.
Endpoint: `/result`
Params:
- `courseId`, self-explanatory
- `feedbackSessionName`, self-explanatory
- `intent`, either `STUDENT_RESULT` or `INSTRUCTOR_RESULT` (cannot be abused as there will be access control check)
- `questionId` to filter by question ID (which is equivalent to question number)
- `sectionName` to filter by section
Presence of either `questionId` or `sectionName` or both will limit the API response to just the specified `questionId` and/or `sectionName`.
=> [#9382] Migrate session results skeleton back-end

src/main/java/teammates/common/util/FieldValidator.java
Part of #7285
Disallow team name to be valid emails.
=> [#7285] Live Server: disallow team name to be valid email

src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.ts, src/web/app/pages-instructor/instructor-pages.module.ts, src/web/app/pages-static/static-pages.module.ts
Fixes #9491 
I passed the corresponding instructor help page path as a route data, fetched it in the getting started component, and used interpolation to use the right path.
=> [#9491] Fix link from getting started page to instructor help page

src/main/java/teammates/ui/webapi/action/ActionFactory.java, src/main/java/teammates/ui/webapi/action/GetInstructorsAction.java, src/main/java/teammates/ui/webapi/output/InstructorData.java, src/main/java/teammates/ui/webapi/output/InstructorsData.java, src/test/java/teammates/test/cases/webapi/GetInstructorsActionTest.java, src/web/app/Instructor.ts, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Part of #9494
There are only two ways to use the API.
* Get all instructors of a course with full details (no information hiding) (by instructor)
* Get all instructors of a course with information hiding (by students)
The second commit also fix part of #9460
=> [#9494] Consolidate GET /instructors RESTFul API

src/main/java/teammates/common/util/Const.java, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Fixes #9516
I updated the endpoint to restore deleted course after the API consolidation.
=> [#9516] Instructor Course: Fix restoring a deleted course functionality

src/web/app/components/loading-spinner/loading-spinner.component.html, src/web/app/components/loading-spinner/loading-spinner.component.scss, src/web/app/components/loading-spinner/loading-spinner.component.spec.ts, src/web/app/components/loading-spinner/loading-spinner.component.ts, src/web/app/page.component.html, src/web/app/page.component.spec.ts, src/web/app/page.component.ts, src/web/app/pages-admin/admin-page.component.html, src/web/app/pages-admin/admin-page.component.spec.ts, src/web/app/pages-admin/admin-page.component.ts, src/web/app/pages-instructor/instructor-page.component.html, src/web/app/pages-instructor/instructor-page.component.spec.ts, src/web/app/pages-instructor/instructor-page.component.ts, src/web/app/pages-static/static-page.component.html, src/web/app/pages-static/static-page.component.spec.ts, src/web/app/pages-static/static-page.component.ts, src/web/app/pages-student/student-page.component.html, src/web/app/pages-student/student-page.component.spec.ts, src/web/app/pages-student/student-page.component.ts, src/web/app/pages.module.ts, src/web/app/public-page.component.spec.ts
Part of #9356 
How the page looks when the http request is incomplete:
I added a component for the loading spinner and use it in `admin-page`, `instructor-page`, `student-page` and `static-page`. Used a boolean flag to decide whether to show the loading spinner or not.
=> [#9356] Show loading spinner when fetching authentication details is ongoing

src/web/app/page.component.ts, src/web/app/pages-admin/admin-page.component.ts, src/web/app/pages-instructor/instructor-page.component.ts, src/web/app/pages-static/static-page.component.ts, src/web/app/pages-student/student-page.component.ts
Fixes #9542
Now `isFetchingAuthDetails` is set to `false` by default, only set to `true` just before the request is sent, and set back to `false` when the result is returned.
The public page is correctly shown:
`/web/sessions/result`
`/web/sessions/submission`
=> [#9542] Cannot load any public page

src/main/java/teammates/common/util/Const.java, src/main/java/teammates/ui/webapi/action/GetStudentAction.java, src/test/java/teammates/test/cases/webapi/GetStudentActionTest.java, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Part of #9494
Note: This PR has a dependancy on #9500 (re-uses the `StudentData` and `JoinState`)
This PR refactors the GET /student API call such that it can be reused for a number of actions, namely:
1. Student Feedback Submission 
2. Retrieve Student Records
3. Get Student Course Details
4. Get Student Edit Details
The PR cleans up the action and has only one required param - the course ID. The other params needed depend on who is using the API.
- **Unregistered Student**
Needs a `RegKey` that is used for verification. Can only view his own details
- **Logged in Student**
The `UserInfo` is sufficient to check accessibility. Can only view his own details.
- **Logged in Instructor**
Needs a `studentemail` param (the student whose details you need) The instructor's …
=> [#9494] Consolidate GET /student RESTFul API

src/web/services/timezone.service.spec.ts
Fixes #9434 
Very, very similar to #9434.
=> [#9434] Fix brittle asserts for time zone offsets in timezone.service.spec.ts

src/main/java/teammates/storage/api/InstructorsDb.java, src/main/java/teammates/storage/api/StudentsDb.java
Fixes #9598 
It turns out that we need index for projection query. It may be unecessary to create a new index (courseId, regKey) just for deletion. Thus, I just remove it.
=> [#9598] Bug fix: Cannot delete all courses in recycle bin

src/main/java/teammates/ui/webapi/action/ActionFactory.java, src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseCommentAction.java, src/main/java/teammates/ui/webapi/action/UpdateFeedbackQuestionAction.java, src/main/java/teammates/ui/webapi/action/UpdateFeedbackResponseAction.java, src/main/java/teammates/ui/webapi/action/UpdateFeedbackResponseCommentAction.java, src/main/java/teammates/ui/webapi/action/UpdateFeedbackSessionAction.java, src/main/java/teammates/ui/webapi/request/FeedbackQuestionSaveRequest.java, src/main/java/teammates/ui/webapi/request/FeedbackQuestionUpdateRequest.java, src/main/java/teammates/ui/webapi/request/FeedbackResponseCommentBasicRequest.java, src/main/java/teammates/ui/webapi/request/FeedbackResponseCommentCreateRequest.java, src/main/java/teammates/ui/webapi/request/FeedbackResponseCommentUpdateRequest.java, src/main/java/teammates/ui/webapi/request/FeedbackResponseSaveRequest.java, src/main/java/teammates/ui/webapi/request/FeedbackResponseUpdateRequest.java, src/main/java/teammates/ui/webapi/request/FeedbackSessionSaveRequest.java, src/main/java/teammates/ui/webapi/request/FeedbackSessionUpdateRequest.java, src/test/java/teammates/test/cases/webapi/CreateFeedbackResponseCommentActionTest.java, src/test/java/teammates/test/cases/webapi/UpdateFeedbackQuestionActionTest.java, src/test/java/teammates/test/cases/webapi/UpdateFeedbackResponseActionTest.java, src/test/java/teammates/test/cases/webapi/UpdateFeedbackResponseCommentActionTest.java, src/test/java/teammates/test/cases/webapi/UpdateFeedbackSessionActionTest.java, src/web/services/feedback-questions.service.ts, src/web/services/feedback-responses.service.ts, src/web/services/feedback-sessions.service.ts
Part of #9564 
After consulting with the maintainer, we need to standardize the naming convention of request DTO.
This PR mainly rename `SaveXXAction` and `SaveXXRequest` to `UpdateXXAction` and `UpdateXXRequest`.
Note:
The `CreateFeedbackResponseAction` used to use `FeedbackResponseCommentSaveRequest` because "save" can either represent "create" or "update". After the renaming, this is not applicable any more. Therefore, `FeedbackResponseCommentCreateRequest` is used although it is same as `FeedbackResponseCommentUpdateRequest`
=> [#9564] Standardize the naming convention of request DTO

src/test/java/teammates/test/cases/architecture/ArchitectureTest.java
Fixes #9737
- Use `includeSubpackages` when necessary
- Extend the range of classes for checking. See below as an example.
https://github.com/TEAMMATES/teammates/blob/08f6d8541022ddaf17ace15a6c97a196965b5a47/src/test/java/teammates/test/cases/architecture/ArchitectureTest.java#L118-L123
The above test won't fail even with `includeSubpackages` used because the range is limited to `.check(UI_CLASSES);`. Inside the range, it is impossible to have any violations and thus the test won't fail.
=> [#9737] ArchitectureTest not failing even with violations

.travis.yml
Part of #9782 
This is a hotfix while we are firing issues to Travis side. All build stage will run `npm install` (no cache will be used and the time for build processes will be longer)
=> [#9782] Cache in Travis is not fetched properly

src/web/app/components/question-types/question-edit-answer-form/msq-question-edit-answer-form.component.ts
Fixes #9805 
In `updateSelectedAnswers()` and `updateIsOtherOption()` , the method `disableNoneOfTheAboveOption()` is called. `disableNoneOfTheAboveOption()` calls `triggerResponseDetailsChange` to update the responseDetails. 
However, the input response details has yet to change and the following line#65 `const newAnswers: string[] = this.responseDetails.answers.slice();` will still have the list of answers which has the "None of the above" option.
To fix this, remove the "None of the above" in an internal list first then call `triggerResponseDetailsChange` at the end of the update methods.
=> [#9805] MSQ: Selecting another option does not deselect "None of the above" option

src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Fixes #9675
- Update the `archiveCourse` method in `instructor-home-page`.
- Make use of the `courseService` to make the API call.
=> [#9675] Cannot archive courses in the instructor home page

.travis.yml
Fixes #9846
Fetch the latest version of Chromedriver automatically in Travis
=> [#9846] Chromedriver used in Travis is outdated

package.json
Fixes #9799 
TINYMCE was grouping toolbars incorrectly, causing the editor to expand to the page's border.
Learn more from this issue: [https://github.com/tinymce/tinymce/issues/4819](url)
This bug was patched in TINYMCE v5.0.8. The changes in this pull request change the minimum
required version for TINYMCE in packages.json to v5.0.8.
=>  [#9799] Tinymce rich text box editor too long

src/main/java/teammates/common/util/TimeHelper.java
Fixes #9850 
`Locale.ROOT` is used as the language/country neutral locale, which can solve the wrong date format problem caused by different languages.
=> [#9850] Set default locale for date time parsing

.travis.yml
Fixes #9867
Update version according to the official documentation
https://docs.travis-ci.com/user/chrome
=> [#9867] Chrome version in travis is mismatched with the driver version

src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss
Fixes #9740 
Removes static height definition for row to allow responsiveness in extra small screen sizes. Fix verified in local dev environment.
=> [#9740] Fix Instructor Homepage UI

.gitignore, .travis.yml, docs/setting-up.md, package-lock.json
Fixes #9970
- Remove `npm update` and change `npm install` to `npm ci` in `.travis.yml`
- commit `package-lock.json` to the repo by editing `.gitignore`
- Edit setting up guide to change `npm install` to `npm ci`
=> [#9970] Fix failing Travis build 

src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap, src/web/app/pages-student/student-home-page/student-home-page.component.html
Fixes #10006
Regression introduced by https://github.com/TEAMMATES/teammates/pull/9827
Set `disable` to view responses button when session is not published.
=> [#10006] Fix incorrect `disabled` flag for student home page view responses button

src/main/java/teammates/ui/webapi/action/SearchInstructorsAction.java, src/main/java/teammates/ui/webapi/output/InstructorData.java, src/main/java/teammates/ui/webapi/output/InstructorsData.java, src/test/java/teammates/test/cases/webapi/SearchInstructorsActionTest.java
Fixes #9946
Since the course and links PR are going to be closed in favor of using the existing course endpoint and link generation, this PR adds two fields to the existing `InstructorData class`
The first is `key`, which is the registration key. This will be used for link generation.
The second is `institute`. This field is currently only in the admin search endpoint, so we add it here.
=> [#9946] Add additional fields for Instructor Search Migration 

src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.html, src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.ts, src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts, src/web/services/search.service.spec.ts, src/web/services/search.service.ts, src/web/services/student.service.spec.ts, src/web/services/student.service.ts
Part of #9946.
This PR: 
- Implements the new instructor search service
- Migrates the instructor search page/component to use the new service
- Removes options to search for feedback sessions (only visual changes, this feature is currently already disabled in the backend)
=> [#9946] Migration to new RESTful search endpoints - Instructor search service

src/main/java/teammates/logic/api/TaskQueuer.java
Fixes #10020 
Cast variables numberOfEmailsSent and emailIntervalMillis to longs before performing multiplication operation to prevent overflow during integer multiplication. A really simple problem with an even simpler solution.
=> [#10020] Prevent potential overflow in TaskQueuer.java

docs/design.md
There was an old link to owasp.org about CSRF attacks that resulted in a 404 not found.
Fixes #10028
=> [#10028] Broken url in documentation

src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.html
Fixes #10036 
Use breakpoints to ensure that the help bar and dropdown show in two lines when screen size is small
=> [#10036] Improve layout on question edit form

src/web/app/pages-session/session-result-page/session-result-page.component.html
Part of #10042, Student Pages: Feedback Session Result Page
Add .col-md-* prefixes so text is centered for smaller screens, left aligned for larger screens
=> [#10042] Improve mobile layout for feedback session results page

src/web/app/page.component.html
Part of #10042, Webpage Bottom Banner
**Original**
The hamburger menu is only accessible if you scroll to the right
The banner at the bottom behaves weirdly.
Also notice that the navbar did not stick to the top of the page.
**After Change**
After this change, you can scroll to the bottom of the page, with the navbar and the hamburger menu remaining in view. The bottom banner content also stays in view.
Removed the nowrap rule such that the bottom banner would not stretch outside of the mobile screen, forcing users to have to scroll to view the hamburger menu
=> [#10042] Improve mobile layout for webpage bottom banner

src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html, src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
Part of #10042, Course Enrol Students Page
**Before-1**: There is awkward word break for the `status message` in mobile screen.
**After-1**: 
**Solution-1**
Re-ordered the `status-message` elements within HTML element of class `card-header`.
**Before-2**: `enroll-students-spreadsheet-buttons` are misaligned in mobile screen.
**After-2**:
**Solution-2**:
Removed redundant layer of `div` around `input`
Removed grid layout, using CSS for more stable alignment
=> [#10042] Improve mobile UI for Course Enrol Students Page

src/web/app/components/session-edit-form/session-edit-form.component.html
Part of #10042 
Added `-md` classes. 
Before:
After:
The remainder of the form has the exact same structure as the edit feedback session page which is already being done with #10051 except for the top banner shown in the pictures.
=> [#10042] Improve mobile UI for add feedback sessions page

src/web/app/components/session-edit-form/session-edit-form.component.html
Part of #10042 : improved page layout for part of the Edit Feedback Session page and centered the content for smaller screen sizes.
I used the col-xs-* and col-md-* prefixes which apply for mobile UI and desktop.
**Mobile UI**
This is what it looks like with the mobile UI:
**Smaller screen sizes UI**
This is what it looks like with the smaller screen sizes UI:
=> [#10042] Improve mobile UI for Edit Feedback Session page

src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
Part of #9382 
I'm assuming `EXAMPLE BODY` is meant to be `EXAMPLE BOX` for modularisation of help pages.
=> [#9382] Fix typo in instructor help pages

src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java, src/test/java/teammates/test/cases/webapi/ConfirmFeedbackSessionSubmissionActionTest.java, src/test/java/teammates/test/cases/webapi/GetFeedbackResponsesActionTest.java
Fixes #10058
Change null check in `BasicFeedbackSubmissionAction#checkAccessControlForStudentFeedbackSubmission` to throw `UnauthorizedAccessException` instead of `EntityNotFoundException`
=> [#10058] Fix inconsistent exception thrown in BasicFeedbackSubmissionAction#checkAccessControl*

src/main/java/teammates/logic/core/FeedbackResponseCommentsLogic.java, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.ts, src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html, src/web/app/components/question-responses/grouped-responses/grouped-responses.component.ts, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.ts, src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.ts, src/web/app/components/question-responses/student-view-responses/student-view-responses.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-view-type.enum.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-view.ts, src/web/app/pages-instructor/instructor-session-result-page/response-moderation-button/response-moderation-button.component.ts, src/web/app/pages-session/session-result-page/session-result-page.component.ts
Part of #9382
Using concrete type in TypeScript rather than `any` will provided many benefits. I believe it would be easier for others (especially the summer interns) to get involved in the result page migration (as the IDE will pop out proper type definition when needed).
The commits are very organized and can be reviewed one by one.
=> [#9382] Use concrete TypeScript type in result page

src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.spec.ts, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
Part of #9382 
Added in the create new feedback session form. Screenshot shown below:
Also, the box displaying the course ID seems to be not displaying in full for the form. It is a simple fix to the bootstrap classes in the template files. Should I resolve it within this PR or open another issue/PR for this?
=> [#9382] Add example for create feedback session form to help page for instructors

src/e2e/java/teammates/e2e/cases/lnp/BaseLNPTestCase.java, src/e2e/java/teammates/e2e/cases/lnp/FeedbackSessionSubmitLNPTest.java, src/e2e/java/teammates/e2e/cases/lnp/FeedbackSessionViewLNPTest.java, src/e2e/java/teammates/e2e/cases/lnp/InstructorSessionResultLNPTest.java, src/e2e/java/teammates/e2e/cases/lnp/InstructorStudentEnrollmentLNPTest.java, src/e2e/java/teammates/e2e/cases/lnp/StudentProfileLNPTest.java, src/e2e/java/teammates/e2e/util/LNPSpecification.java, static-analysis/teammates-checkstyle-suppressions.xml
Fixes #10041 
Improved the design of LNPSpecification class by applying Builder pattern.
**Outline of Solution**:
* refactored the `LNPSpecification` class to apply Builder pattern
* removed calling `LNPSpecification` constructor from `BaseLNPTestCase` class; using builder() method instead.
=> [#10041] Add builder pattern to LNPSpecification class

src/web/app/components/session-edit-form/session-edit-form.component.html
Fixes #10072
Wrap `div` in rows so the words can occupy all the space and not overflow until screen size is small. Also added some margins around to give some space between elements
=> [#10072] Session edit form UI is not ideal

src/test/java/teammates/test/cases/webapi/GetCourseSectionNamesActionTest.java
Part of #9382 , #10039 
Added JUnit test for `GetCourseSectionNamesAction`, which is used to get the section name of a course.
The new test file is placed under `src/test/java/teammates/test/cases/webapi/GetCourseSectionNamesActionTest.java`.
=> [#9382] Add unit test for GetCourseSectionNamesAction

src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.scss, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.spec.ts, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
Part of #9382
Copied over the relevant section from the edit session template and disabled all the buttons.
=> [#9382] Add example to preview session section of help

src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts
Part of #9382 
- add distribute point (option) question
- add distribute point (recipient) question
- add team contribution question
- add rubric question
=> [#9382] Add remaining question sections setup example boxes

src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html, src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.ts, src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.spec.ts, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
Part of #9382
Added boxes for the relevant sections and fixed some indentation for template file. 
Screenshots below
**Viewing Sessions**
**Restoring a deleted session**
**Permanently delete a session**
**Restore/Delete all sessions**
=> [#9382] Add example boxes for restoring deleted session section of instructor help page

src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
=> [#10087] Course Details page text should be aligned to the left

src/web/services/search.service.ts
Fixes #10088 
Add check for empty array for early termination.
The bug was caused by `forkJoin` not executing when given an empty array, so a check for empty array would solve the issue.
=> [#10088] Add notification on no result for instructor search

src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackContributionResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackMcqResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackRubricResponseDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java, src/main/java/teammates/common/datatransfer/questions/FeedbackTextResponseDetails.java, src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java, src/main/java/teammates/ui/webapi/action/CreateFeedbackQuestionAction.java, src/main/java/teammates/ui/webapi/action/UpdateFeedbackQuestionAction.java, src/test/java/teammates/test/cases/architecture/ArchitectureTest.java, src/test/java/teammates/test/cases/datatransfer/FeedbackMcqQuestionDetailsTest.java, src/test/java/teammates/test/cases/datatransfer/FeedbackMsqQuestionDetailsTest.java, src/test/java/teammates/test/cases/datatransfer/FeedbackRubricQuestionDetailsTest.java
Part of #9382
This removes unused methods `extractQuestionDetails`, `extractResponseDetails` (the question/response construction logic is moved to the front-end and sent as request body), `isQuestionSkipped`, and `validateResponseAttributes` (not the right place), and adds a slight refactor to `FeedbackMsqQuestionDetails` such that it is no longer dependent to logic package. One more architecture violation is fixed.
The `Feedback*QuestionDetailsTest` cases that involve only extraction are no longer meaningful and thus removed; those that involve validation are still meaningful and should be improved after this.
=> [#9382] Remove unused items in Feedback*QuestionDetails and Feedback*ResponseDetails classes

src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-edit-form/question-edit-form.component.html, src/web/app/components/rich-text-editor/rich-text-editor.component.ts
Added 'md' to the respective divs so the label and content feel better on small widths.
Updated the mi-width on the editor, this way the editor's placeholder will not overflow on smaller widths.
Part of #10042 
Before:
After:
=> [#10042] Add mobile compatibility to indivual question

src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
Fixes #10114 
**Before**:
**After**:
- add missing `dropdown-item` attribute to corresponding HTML element.
=> [#10114] Fix UI of disabled delete button in instructor courses page

src/main/java/teammates/ui/webapi/output/SessionResultsData.java, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.ts, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.ts
Fixes #10107
**GRQ**
**RQG**
- Add `recipientEmail` and `giverEmail` to backend output. The visibility is handled by the `getDisplayableEmailGiver/Recipient` method
- Made a map from user to email in the group by views and display them accordingly
=> [#10107] Append email after participants' name for GRQ/RGQ/GQR/RQG view

src/web/app/components/comment-box/comment-box.module.ts, src/web/app/components/comment-box/participant-comment-to-command-row-model-pipe.pipe.spec.ts, src/web/app/components/comment-box/participant-comment-to-command-row-model-pipe.pipe.ts, src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html, src/web/app/components/question-responses/grouped-responses/grouped-responses.component.ts, src/web/app/components/question-responses/student-view-responses/student-view-responses.component.html, src/web/app/components/question-responses/student-view-responses/student-view-responses.component.spec.ts, src/web/app/components/question-responses/student-view-responses/student-view-responses.component.ts, src/web/app/components/question-responses/student-view-responses/student-view-responses.module.ts, src/web/app/pages-session/session-result-page/session-result-page.component.html
Fixes #10102 
Add `tm-comment-row` in `tm-student-view-responses`.
**Questions**
1. Not sure what visibility options to pass in for `questionShowResponsesTo`. Should the comment's visibility follow the question's visibility?
2. Is it correct to use `CommentRowMode.EDIT` for the mode? There isn't a `VIEW` mode as far as I can tell.
=> [#10102] Add participant comment to student session result

src/main/java/teammates/common/util/Const.java, src/main/java/teammates/logic/api/EmailGenerator.java, src/main/java/teammates/ui/webapi/action/LegacyUrlMapper.java
Part of #9382
During the first few weeks (maybe even months) of V7, we will still have users accessing links from meant for V6, e.g. links sent via email. We cannot simply reject those links; they must be properly redirected to the V7 counterpart.
=> [#9382] Add redirect from old pages to new one

src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
Fixes #10168 
Clicking on label now checks the checkbox
Tooltip now shows above the label properly
=> [#10168] Fix checkbox ui at Instructor Session Result Page

src/web/app/components/question-types/question-statistics/rank-options-question-statistics.component.html, src/web/app/components/question-types/question-statistics/rank-options-question-statistics.component.spec.ts, src/web/app/components/question-types/question-statistics/rank-options-question-statistics.component.ts, src/web/app/components/question-types/question-statistics/rank-recipients-question-statistics.component.html, src/web/app/components/question-types/question-statistics/rank-recipients-question-statistics.component.spec.ts, src/web/app/components/question-types/question-statistics/rank-recipients-question-statistics.component.ts, src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html, src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.spec.ts, src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts, src/web/services/table-comparator.service.ts, src/web/types/sort-properties.ts
Part of #10155 
Add sortable statistics table for:
- `tm-rank-options-question-statistics`
- `tm-rank-recipients-question-statistics`
- `tm-rubric-question-statistics`
=> [#10155] Add sortable statistics tables for instructor result page

src/web/app/components/question-types/question-statistics/mcq-question-statistics.component.html, src/web/app/components/question-types/question-statistics/mcq-question-statistics.component.ts, src/web/app/components/question-types/question-statistics/msq-question-statistics.component.html, src/web/app/components/question-types/question-statistics/msq-question-statistics.component.spec.ts, src/web/app/components/question-types/question-statistics/msq-question-statistics.component.ts, src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.html, src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.spec.ts, src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.ts, src/web/app/components/sortable-table/sortable-table.component.html, src/web/app/components/sortable-table/sortable-table.component.scss, src/web/services/table-comparator.service.ts, src/web/types/sort-properties.ts
Fixes #10155 
- Refactor num scale statistics to use sortable table 
- Add sortable statistic table for MSQ
- Add sortable per recipient statistics table for MCQ
=> [#10155] Add sortable statistic table for MSQ, plus finishing up

src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-courses-page/add-course-form/__snapshots__/add-course-form.component.spec.ts.snap, src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.html, src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.scss, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.scss, src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss
**Previous snapshot** (mobile)
**Current snapshot** (mobile)
- set header text & button group to be non-break (home page)
- standardise input fields' length (add course form)
- add missing table name (active course table)
- fix course table overflow on mobile screen (active course table)
=> [#10176] Instructor home page UI fixes

src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap, src/web/app/components/question-text-with-info/question-text-with-info.component.html, src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.scss, src/web/app/pages-instructor/instructor-course-edit-page/custom-privilege-setting-panel/custom-privilege-setting-panel.component.html, src/web/app/pages-instructor/instructor-course-edit-page/custom-privilege-setting-panel/custom-privilege-setting-panel.component.ts, src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html, src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/response-moderation-button/response-moderation-button.component.html, src/web/app/pages-instructor/instructor-session-result-page/response-moderation-button/response-moderation-button.component.scss
Part of #10176
- Add bold tags where necessary
- Add label tags for checkboxes/radio buttons
- Add css styling for `Moderate Response` button
**Instructor Course Page Fix**
- Course page table should not show when instructors has no courses available to him. Currently, the headers are shown
**Instructor Edit Course Details Page Fix**
- Edit course details allows users to click on the Give different permissions for a specific section infinitely
- In edit course details page, labels for checkboxes are not clickable, only the checkboxes are clickable
**Instructor View Course Details Page Fix**
- In view course details page, the non-english characters not displayed properly does not change cursor to pointer when hovering above it
**Instructor View Results Page Fix**
- …
=> [#10176] UAT Round 1: Fix Instructor Pages UI

src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java, src/main/java/teammates/common/util/Const.java, src/test/java/teammates/test/cases/datatransfer/FeedbackMsqResponseDetailsTest.java, src/web/app/components/question-types/question-edit-answer-form/msq-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/msq-question-edit-answer-form.component.ts, src/web/app/components/question-types/question-response/msq-question-response.component.html, src/web/app/components/question-types/question-response/msq-question-response.component.ts, src/web/types/feedback-response-details.ts
Part of #10176
**V6 Behaviors**
- In V6, we use empty string to indicates `None of the above` answer.
- In V6, the `otherFieldContent` for MSQ is duplicated in the answer list as the last element.
I would the above practices are not ideal but change any of the behavior above would result in data migration.
=> [#10176] Update submission of MSQ to follow V6's format

src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html, src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.scss, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.scss, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.scss
**Previous snapshot** (mobile)
**Current snapshot** (mobile)
- fixed action buttons alignment in all screens
- bold all headers in the page and improve necessary spacing
- fix sortable table header alignment by giving min width and add horizontal scroll for overflow
=> [#10176] Instructor Session Result Page fixes

src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java, src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseAction.java, src/main/java/teammates/ui/webapi/action/UpdateFeedbackResponseAction.java, src/main/java/teammates/ui/webapi/output/SessionResultsData.java, src/main/resources/InstructorSampleData.json, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html
This fixes the following tickets:
- Missing "No specific section"
- Missing response to/from instructors
However, this PR also appears to solve an age-old problem in TEAMMATES where an entity who is a both a student and an instructor will have some mixed up logic in V6.
=> [#10176] Fix section-related problems in session results page

src/main/java/teammates/common/util/Const.java, src/main/java/teammates/ui/webapi/action/ActionFactory.java, src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java, src/main/java/teammates/ui/webapi/action/GetAuthInfoAction.java, src/main/java/teammates/ui/webapi/action/GetRegkeyValidityAction.java, src/main/java/teammates/ui/webapi/action/GetSessionResultsAction.java, src/main/java/teammates/ui/webapi/endpoints/ResourceEndpoints.java, src/main/java/teammates/ui/webapi/output/RegkeyValidityData.java, src/test/java/teammates/test/cases/webapi/GetAuthInfoActionTest.java, src/test/java/teammates/test/cases/webapi/GetFeedbackQuestionRecipientsActionTest.java, src/test/java/teammates/test/cases/webapi/GetRegkeyValidityActionTest.java, src/test/java/teammates/test/cases/webapi/GetSessionResultsActionTest.java, src/web/app/pages-session/session-result-page/session-result-page.component.html, src/web/app/pages-session/session-result-page/session-result-page.component.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts, src/web/app/user-join-page.component.ts, src/web/services/auth.service.ts, src/web/services/feedback-sessions.service.ts, src/web/services/link.service.spec.ts, src/web/services/link.service.ts
This fixes the following:
- v7 does not prompt user when logged in and accessing a link meant for another user (i.e. A & B both in course, logged in as A, accessing email link meant for B). V6 prompts user to associate session with a google account.
- Using regkey alone in incognito mode allows direct access to feedback submission in v7, but doing the same prompts for login in v6.
- No error handling for non google account logged in student when accessing results from link (server error, no option for resolution) v6 prompts you to login via google
- Accessing link will always show results based on logged in google account regardless of email shown in link -> if I access my link from a friend's laptop or device, I will see his results as if I were accessing his link; v6 …
=> [#10176] Fix authentication-related problems from UAT

src/web/app/components/student-list/__snapshots__/student-list.component.spec.ts.snap, src/web/app/components/student-list/student-list.component.html, src/web/app/components/student-list/student-list.component.ts, src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.spec.ts, src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.html, src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
Part of #10176
**Addressed Issues:**
- Managing session responses > How do I view the results of my session > 2nd example box > "Remind all" collapses the modal when clicked. Might be the problem of the actual component also.
- Finding students > How do I search for students in my course > 2nd and 3rd example boxes > the view/edit/all records buttons are active.
- Added a new `isActionButtonsDisabled` to `student-list` component
- Prevent propagation of click event in remind all button
- Also removed the stubs that were in the help section test files
=> [#10176] UAT Round 1: Fix Instructor Help Examples

src/web/app/components/question-edit-form/question-edit-form.component.html, src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.html, src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.ts
- Restrict min and max values to integers
- The backend only accepts integer values, and I don't see any compelling reason to change it
- Make edit question save warning less scary and more accurate
- Seems like popping out this modal only once is intended, so I did not touch that
- Indicate MCQ MSQ answer comments are optional
=> [#10176] UAT fixes

src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.spec.ts, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.module.ts, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.spec.ts, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.module.ts, src/web/app/page.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html, src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.html, src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.spec.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.spec.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.spec.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.scss, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.spec.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.spec.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.spec.ts, src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html, src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.module.ts, src/web/styles.scss
Part of #10213 
Most changes in this PR are mainly wrapping elements with `[ngbCollapse]`.
Note that this PR is mainly a workaround as the lack of animation for `[ngbCollapse]` is currently being worked on by [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap). Follow the progression at [this thread](https://github.com/ng-bootstrap/ng-bootstrap/issues/295). 
We should revert parts of this PR when they do a release for proper animations for collapsing.
Added animations for:
- Result page question collapsing
- Instructor help section
- Template question modal expanding
- Student list page
Some samples:
=> [#10213] Add animations for all collapsable tabs

src/e2e/java/teammates/e2e/pageobjects/InstructorCoursesPage.java, src/web/app/components/session-edit-form/session-edit-form.component.html, src/web/app/page.component.html, src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-courses-page/add-course-form/__snapshots__/add-course-form.component.spec.ts.snap, src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.html, src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.scss, src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.scss, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Part of #10213 
**Resolves**:
- Archived course table in the Courses tab is not collapsible but the Recycle Bin table is collapsible.
- Misaligned labels in Adding new course on instructor page
- Misaligned labels in Edit feedback session Course ID label and data in the top box
- Bottom banner not centralised in mobile view
- Add necessary css classes to views 
- Add new variable to control toggling of the archive table tab
- ~Fixing E2E tests for now~ Fixed
=> [#10213] Fix misaligned label and add collapsable archive table

src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap, src/web/services/session-result-csv.service.ts, src/web/types/question-details-impl/abstract-feedback-question-details.ts, src/web/types/question-details-impl/feedback-constsum-options-question-details.impl.ts, src/web/types/question-details-impl/feedback-constsum-recipient-question-details.impl.ts, src/web/types/question-details-impl/feedback-contribution-question-details.impl.ts, src/web/types/question-details-impl/feedback-mcq-question-details.impl.ts, src/web/types/question-details-impl/feedback-msq-question-details.impl.ts, src/web/types/question-details-impl/feedback-num-scale-question-details.impl.ts, src/web/types/question-details-impl/feedback-rank-options-question-details.impl.ts, src/web/types/question-details-impl/feedback-rank-recipients-question-details.impl.ts, src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts, src/web/types/question-details-impl/feedback-text-question-details.impl.ts
Fixes #10219 
- Added abstract method to check if instructor/participant can comment on the response
- Add the headers and actual comment to `csvRows`
- Manually verified all snapshot tests matches up with the CSV files generated in V6 for comments
**Concerns**
- For `should show responses along with stats for feedbackSessionResultC1S1` (The second test), the CSV file mentioned in the comment seems incorrect?
- There were some test data where there seems to be more data in the json in V7 compared to V6 so there wasn't a one to one match so I checked against the json for these tests for comments.
=> [#10219] Add instructor/participant comment in CSV

src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java, src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
Part of #10176
- Missing responses are not generated when the recipient type is "STUDENTS" (V6 enforces a more strict check where the generation is skipped when recipient is "TEAM". However, we assume the number of team will not grow that large).
=> [#10176] Avoid expensive missing responses generation when recipient type is all students

src/main/java/teammates/ui/webapi/action/GetFeedbackSessionAction.java, src/main/java/teammates/ui/webapi/output/FeedbackSessionData.java, src/web/app/components/comment-box/comment-table/comment-table.component.html, src/web/app/components/comment-box/comment-table/comment-table.component.scss, src/web/app/components/comment-box/comment-table/comment-table.component.ts, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.ts, src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html, src/web/app/components/question-responses/grouped-responses/grouped-responses.component.ts, src/web/app/components/question-responses/grouped-responses/grouped-responses.module.ts, src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html, src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.ts, src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution-question-statistics.component.html, src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution-question-statistics.component.spec.ts, src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution-ratings-list.component.html, src/web/app/components/question-types/question-statistics/question-statistics.module.ts, src/web/app/components/teammates-common/view-photo-popover/view-photo-popover.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html, src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
This fixes the following issues:
- Instructor help page: Managing courses > What should I do if a student says his/her courses have disappeared from the system > The email address is hard-coded to `teammates@comp.nus.edu.sg` while it should be read from `environment.supportEmail`.
- Instructor results page: Edit feedback session detail button beside "Session:"
- V6 has a Results visible from info in the top info box but not in V7
- Responses should be ordered by giver team > giver name > recipient team > recipient name
- GRQ/RGQ view: Adding response comment interface is different
- Contribution question: should not be able to add response comment
- In V6, Team contribution question statistics table has a link to the help page on interpreting the E-20% E+20% etc... values …
=> [#10176] Fix most issues in instructor results page from UAT

src/web/app/components/question-types/question-edit-details-form/option-rich-text-editor/option-rich-text-editor.component.html
Can't believe this took me a full day to resolve...
The original bug is caused by the `trackBy: trackMcqOption` option, which is necessary to prevent the input field from rerendering every time the input value changes.
However, when the options gets reordered, this `trackBy` option causes the editor instances to not get reordered, which causes some sort of de-sync which I still do not fully understand. 
Thus, when a reordered option gets deleted, both the `onMcqOptionDeleted` and `onMcqOptionEntered` gets called, whereas only `onMcqOptionDeleted` is supposed to be called. The `onMcqOptionEntered` call would thus overwrite the result of the previous `onMcqOptionDeleted` and cause the model to become invalid (E.g. `numberOfMcqChoices=2` but there are …
=> [#10176] Fix MCQ delete after reorder bug

src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.html, src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.scss
Part of #10176
**Screenshots**
Fixes
- Missing “Currently no ongoing session” tab from v6, leaving large white space.
- "Filter by Range" button did not provide any feedback when no result is found. (V6 shows “Currently no ongoing session”)
- Filter panel should change to vertical mode starting from larger screen, prevent date and Time Zone input from being hidden by input box.
- Separators near “To” and “Time Zone” persist in vertical mode.
- No text explanation for number in result panel header. (which reports number of results found)
- No widget indication that panels are collapsable. (However, onHover is present)
- Click on creator link should open in new tab, since the current result is not cached when going back.
- Add appropriate size breakpoints
- Add no …
=> [#10176] UAT Round 1: Fix admin session page issues

src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/pages-instructor/instructor-student-records-page/__snapshots__/instructor-student-records-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.html, src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.spec.ts, src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts
This fixes:
- In student all records page, if a student submits an answer, and then deletes it, the a no response tab will show, with the comment button doing nothing.
- In student all records page, if a student has not submitted profile, many parts will be empty.
=> [#10176] Fix some UAT problems in instructor all records page

src/web/services/session-result-csv.service.ts, src/web/services/string-helper.spec.ts, src/web/services/string-helper.ts
Part of #10156
Added in a method in `string-helper` to convert `img` to links for use in csv comment geenration
=> [#10156] Add image to link for csv comment generation

src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
This fixes two critical bugs found after UAT round 1 that should be fixed before `V7.0.0-rc.0`:
- Instructor results page, GQR/RQG view: No response shown if all questions is either of text/contribution type (regression introduced in #10228)
- Session submission page: Wrong logic to determine whether there are only 15 minutes left before submission closing (regression introduced in #10246)
=> [#10176] UAT round 1 final fixes

src/e2e/java/teammates/e2e/cases/lnp/InstructorUpdateLNPTest.java
Part of #10221 
- add new `InstructorUpdateLNPTest` class
- target the backend API endpoint `updateInstructorByGoogleIdCascade`
- test the update cascade of instructor name/email to related response & responseComment.
**Test endpoint**:
```
webapi/instructor?courseid=${courseId}
```
**Test http payload**:
```
InstructorCreateRequest instructorCreateRequest =
new InstructorCreateRequest(
INSTRUCTOR_ID,
INSTRUCTOR_NAME,
UPDATE_INSTRUCTOR_EMAIL,
"Co-owner",
"Co-owner", true);
String updateData = sanitizeForCsv(JsonUtils.toJson(instructorCreateRequest));
```
=> [#10221] Add instructor update LNP test case

src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Fixes #10279
`deleteFeedbackSession` mistakenly called instead of `deleteSessionFromRecycleBin` in `restoreAllRecycleBinFeedbackSession`
**Screenshot**
=> [#10279] Restore all feedback sessions causes error 

src/web/app/components/copy-session-modal/__snapshots__/copy-session-modal.component.spec.ts.snap, src/web/app/components/copy-session-modal/copy-session-modal.component.html, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html, src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html, src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html, src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
Part of #10213 
Mostly change cursors to pointers on clickable surfaces, with some other fixes:
- Courses -> Enroll - Existing students
- Fix cursor not pointers on clickable surface
- Courses -> Enroll - New students
- Fix cursor not pointers on clickable surface
- Sessions -> Edit -> Add New Questions -> Choose from template questions
- Fix cursor not pointers on clickable surface
- Fixed not expanding on clicking outside of text as well
- Sessions -> View Results -  Participants who have not responded to any question
- Fix cursor not pointers on clickable surface
- Sessions -> View Results -> GRQ / RGQ / GQR / RQG: All header cursors are not pointer
- Fix cursor not pointers on clickable surface
- GQR / RQG - Questions
- Fixed not expanding on clicking outside of text as well
- …
=> [#10213] Fix clickable area / cursor related issues

src/main/java/teammates/ui/webapi/action/SearchStudentsAction.java, src/test/java/teammates/test/cases/webapi/SearchStudentsActionTest.java, src/web/services/search.service.spec.ts, src/web/services/search.service.ts
Part of #10245 
> Instructor search page: If an instructor who is admin searches for students, s/he will get all the matching students in the system. This is not accurate as the intention of this page is not for system-wide search.
Added new param `entitytype` for student search
=> [#10245] UAT Fix: Instructor Search Page

src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseCommentAction.java, src/main/java/teammates/ui/webapi/action/DeleteFeedbackResponseAction.java, src/main/java/teammates/ui/webapi/action/GetFeedbackResponseCommentAction.java, src/main/java/teammates/ui/webapi/action/UpdateFeedbackResponseAction.java, src/main/java/teammates/ui/webapi/output/FeedbackResponseData.java, src/main/java/teammates/ui/webapi/output/SessionResultsData.java, src/test/java/teammates/test/cases/webapi/CreateFeedbackResponseCommentActionTest.java, src/test/java/teammates/test/cases/webapi/DeleteFeedbackResponseActionTest.java, src/test/java/teammates/test/cases/webapi/GetFeedbackResponseCommentActionTest.java, src/test/java/teammates/test/cases/webapi/GetFeedbackResponsesActionTest.java, src/test/java/teammates/test/cases/webapi/UpdateFeedbackResponseActionTest.java
Part of #10264 
Without any consideration for the front-end, my intent here is to encrypt all output of `responseId` and subsequently decrypt any receipt of `feedbackResponseId` from the API endpoints. 
This approach was taken because I believe `ResponseOutput` which is supposed to be the data output format for question responses is really just a superset of a `FeedbackResponseData` since the `responseId ` is really just the `feedbackResponseId`. Please do correct me if I'm wrong in my assumption. I'd like to clarify this assumption first before continuing to work on the tests and verify the impact of the encryption on the front-end.
=> [#10264] Encrypt Feedback Response ID

src/main/java/teammates/ui/webapi/action/GetFeedbackResponseCommentAction.java, src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java, src/main/java/teammates/ui/webapi/action/GetStudentProfilePictureAction.java, src/main/java/teammates/ui/webapi/action/ImageResult.java, src/test/java/teammates/test/cases/webapi/GetFeedbackResponseCommentActionTest.java, src/test/java/teammates/test/cases/webapi/GetStudentProfilePictureActionTest.java, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts, src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
Part of #10245 
- Endpoints like profile picture, student profile, and response comments return `404` when the corresponding items are not found. While not 100% wrong, it is not accurate because they may not be found because they simply are not or have not been made.
- For those cases, the status should still be `200` with appropriate output, e.g. null profile picture (can use `204 NO CONTENT` status code here), empty student profile (_already implemented before this PR_), or empty list of comments.
- `404`, on the other hand, will be accurate if the corresponding student (whose profile or profile picture) or feedback response (whose response comments) is not found.
- Student profile not showing shortname and personal email
- Caused by misconfigured authentication when user is both …
=> [#10245] Change status codes for non-required entities from 404 to 204

src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/teammates-common/collapse-anim.ts
Fixes #10305
Set overflow to be set back to visible after animation ends instead of remaining as hidden in all states
Animation remains smooth and cut off problem is solved
**Screenshot**
=> [#10305] CollapseAnim causing elements to be cut off 

src/web/app/components/toast/toast.component.html, src/web/app/components/toast/toast.component.ts, src/web/app/components/toast/toast.ts, src/web/services/status-message.service.ts
Fixes #10307
- Toggle the autohide status when the toast is changed to ensure timer is reset if there is already a toast present
- Timeout is needed as toggling without it does not get registered
=> [#10307] Status message timeout does not reset 

src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEditPage.java, src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.ts, src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.scss, src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.html, src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html, src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts, src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html, src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts, src/web/app/pages-session/session-result-page/session-result-page.component.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.html, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Part of #10299, fixes #10302, fixes #10303 
- Rubric question submission: V6 has different interface in mobile view
- Instructor course edit: V6 has timezone offset information in the dropdown (
- Instructor course edit: for instructor access level, unless in "edit" mode, just show the existing access level name (i.e. no need to display all other access levels)
- Instructor search: Not working if not both "students" and "questions, responses, comments on responses" are selected.
- MSQ question: minimum selectable choice should be 1 instead of 2.
- Preview submission form as student shows the form in readonly mode. It shouldn’t be like that. Only the submission button should be disabled.
=> [#10299] Fix some issues from UAT round 3

src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.html, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-edit-form/question-edit-form.component.html, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html, src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap, src/web/app/components/question-text-with-info/question-text-with-info.component.html, src/web/app/components/question-types/question-edit-details-form/contribution-question-edit-details-form.component.html, src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.scss, src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.scss, src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.html, src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html, src/web/app/pages-instructor/instructor-course-edit-page/custom-privilege-setting-panel/custom-privilege-setting-panel.component.html, src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html, src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html, src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html, src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html, src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.html, src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html, src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.html, src/web/app/pages-instructor/student-profile/student-profile.component.html, src/web/app/pages-student/student-profile-page/__snapshots__/student-profile-page.component.spec.ts.snap, src/web/app/pages-student/student-profile-page/student-profile-page.component.html
Fixes #10042 
Went through the app in mobile view as a whole one more time and did minor fixes to the mobile UI. 99% of pages are mobile optimized now
- Table responsive in mobile view
- Make question text with info more mobile friendly
- Make headers show buttons/text in one row in mobile
- Make most labels centralised in mobile view. Some examples
=> [#10042] Improve UI for Mobile Compatibility 

src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Fixes #10330 
Set `SortOrder.DESC` while sorting by course creation date.
=> [#10330] Instructor home page: sort newest courses on top

src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
Fixes #10337
Regression introduced by #10042. Using `col-auto` does not enforce equal width across multiple rows. Changed to `col-sm-2`.
Desktop:
Mobile:
=> [#10337] Fix instructor edit student details: form fields are not aligned

src/web/app/components/question-types/question-response/rubric-question-response.component.html, src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts, src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap, src/web/services/table-comparator.service.ts, src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts, src/web/types/sort-properties.ts
Fixes #10352 
- Add ordering prefix to rubric choices
- Change to CSV generation `FeedbackRubricQuestionDetailsImpl`
- Change to `RubricQuestionStatisticsComponent`
- Change to `RubricQuestionResponseComponent`
Make initial sort to be the proper order
**Others**
~The solution is a little different from the original one as it uses number ordering instead of alphabet ordering. This is because it would be slightly more involved to roll out our alphabet ordering service and I don't see a reason for it.~
It turns out that there's currently a function implemented for alphabet ordering `StringHelper.integerToLowerCaseAlphabeticalIndex()`, so I'll use that instead.
=> [#10352] Fix inconsistency in rubric question summary

src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts, src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts, src/web/app/pages-student/student-home-page/student-home-page.component.ts
Fixes #10374
- Added checks for empty arrays
- Issue exist in student home and details page. Same thing there. Added in checks
=> [#10374] Instructor course details page: loading spinner does not disappear

src/web/app/pages-instructor/instructor-session-base-page.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
Fixes #10350
Make all filenames `${courseId}_${sessionName}_result.csv` or `${courseId}_${sessionName}_question1.csv`, same as V6.
Question: Why were there `.concat()` calls previously? I don't see their purpose and removed them.
=> [#10350] Change filename of csv file downloaded

src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html, src/web/app/components/question-responses/grouped-responses/grouped-responses.component.scss, src/web/app/components/question-responses/grouped-responses/grouped-responses.component.ts, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
Fixes #10343 
Extract bottom border into css class, only displays if not last response
Multiple Responses (last response): 
Single Response:
=> [#10343] Fix unnecessary bottom line for last response

src/main/java/teammates/ui/webapi/action/LegacyUrlMapper.java
Fixes #10470 
**Outline of Solution**: Add institute mac when institute is present during routing from old join link to new one
=> [#10470] Add v6 instructor join link support

src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap, src/web/app/components/sessions-table/sessions-table.component.html, src/web/app/components/sessions-table/sessions-table.component.spec.ts, src/web/app/components/sessions-table/sessions-table.module.ts, src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html, src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts, src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
Fixes #10421 
- Added `routerLink` to `button` in `sessions-table`, `course-page`, `session-edit-page`
- Changed `button` tag to `a` tag to enable the `Open Link In New Tab`
- Removed unused code from `session-edit-page`
=> [#10421] Drop-down menus: allow opening in new tab

src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap, src/web/types/question-details-impl/feedback-constsum-options-question-details.impl.ts, src/web/types/question-details-impl/feedback-constsum-recipient-question-details.impl.ts, src/web/types/question-details-impl/feedback-contribution-question-details.impl.ts, src/web/types/question-details-impl/feedback-rank-options-question-details.impl.ts, src/web/types/question-details-impl/feedback-rank-recipients-question-details.impl.ts
Fixes #10462 
Fixes #10436 
Fixes #10453 
- Set `Ranks Received` to be the last column to be shown, and spread out the values to multiple cells
- For both rank-options and rank-recipients
- Set "Points Received" to be the last column to be shown, and spread out the values to multiple cells
- For both constsum-options and constsum-recipients
- Set "Ratings Received" to be the last column to be shown, and spread out the values to multiple cells
- For contribution-question
=> [#10462] CSV: Split rank received into multiple cells

src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/rank-options-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.html
Fixes #10458 
- Make input fields more compact
- Some mobile optimization
=> [#10458] Make input fields more compact

src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseEnrollPageE2ETest.java, src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html, src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Fixes #10465, #10038 
- Added in card for long error message
=> [#10465] Instructor enroll students: error message should be a modal

src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-edit-form/question-edit-form.component.html, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Fixes #10448
There are two UAT fixes also.
The first is button alignment in the question edit form:
Before:
After:
Looks like it is not fixed and I am wrong in my previous PR.
The second is the to add default empty handler when modal is closed (promise is rejected) (or there will be an error in the console)
=> [#10448] Add question to session: team-contribution questions should not inherit custom visibility from previous question

src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
Fixes #10517
- ngIf was set to false, causing the link to always not be present
- change back to using `emailOfInstructorToPreview` as the check
=> [#10517] Preview as instructor link not working 

src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html, src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.scss, src/web/app/components/question-types/question-statistics/question-statistics-calculation/mcq-question-statistics-calculation.ts, src/web/app/components/question-types/question-statistics/question-statistics-calculation/msq-question-statistics-calculation.ts, src/web/app/components/question-types/question-statistics/question-statistics-calculation/num-scale-question-statistics-calculation.ts, src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts, src/web/app/components/sessions-table/sessions-table.component.scss, src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts, src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap, src/web/styles.scss
- Fixes #10511 
- Note that I am not sure that the fix actually works, because the problem did not manifest in my environment. Likely to be specific to Win10 + Chrome.
- Fixes #10354 + fixes #10545 (similar issue)
- Reduced the site-wide L/R margin of bottoms to 5px as 10px looks too wide.
- Fixes #10428 
- The problem is not specific to MSQ; it applies to all question types.
- Fixes #10530 
- Also standardized the way rounding is done, by using `+` and `toFixed`.
And fixed a regression in #10543 where a flipped condition caused feedback session table to never finish loading.
=> [#10354] [#10428] [#10511] [#10530] [#10545] UAT round 5 fixes: miscellaneous

angular.json, package-lock.json, package.json, src/web/index.html
Fixes #10559 
Cause: one of the libraries recently added, `ng-in-viewport`, has `new Function` as part of its code, which is blocked under `unsafe-eval` CSP policy.
Solution:
- There is a very recent version that did not use any `unsafe-eval`-breaking code; use that version
- Change the local HTML file to also exclude `unsafe-eval` so that this kind of problem can be detected earlier
I have raised the issue to the library author: https://github.com/k3nsei/ng-in-viewport/issues/333
=> [#10559] Pages with rich text editors cannot be displayed

src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html, src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
Fixes #10565 
Sorting of student table was moved outside of student list component due to https://github.com/TEAMMATES/teammates/pull/10363.
=> [#10565] Instructor course details page: fix sortable header for student table

src/main/java/teammates/common/util/FieldValidator.java, src/main/java/teammates/logic/core/StudentsLogic.java, src/main/java/teammates/storage/api/FeedbackSessionsDb.java, src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/util/FieldValidatorTest.java, src/test/java/teammates/test/cases/webapi/GetOngoingSessionsActionTest.java, src/test/java/teammates/test/cases/webapi/GetStudentProfileActionTest.java, src/test/java/teammates/test/cases/webapi/UpdateStudentProfileActionTest.java
This fixes some back-end operations:
- Fixes #10574 
- Change `404` to `200` (cannot use `204` because the response body will be stripped) and return empty student profile if the student has not registered. `404` is appropriate when the target student is not found.
- Fixes #10575 
- This was due to HTML sanitization when constructing error message. HTML sanitization in the back-end is no longer necessary and in fact should not be done. The only place where HTML sanitization is still relevant is email content generation.
- Fixes #10576 
- This was due to the sessions queried via start time and end time are combined with OR operation, not AND.
=> [#10574] [#10575] [#10576] Fix back-end related issues

src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.scss, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
Fixes #10614 
Fixes #10616
Other fixes:
- Add "not applicable" for results visible from time for unpublished sessions
- Make the style of merge/expand all button consistent with edit session page
=> [#10614][#10616] Fix session results page issues

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
Part of #9936
This is just a temp fix for OutOfMemory error. We put the expensive DB check as the last condition, hoping that many session will be filtered out by the first several cheap checks. The underlying issue where:
1. We are still fetching associated course for every session under consideration
1. We only make use of the `isDeleted` of the course (other fields are not used and result in extra works for GC or just result in OOM)
We should strike to think of permanent fix for the issue. Right now, as reported in V6, this fix works for a while.
=> [#9936] Add logging and swap if condition order for expensive operation

angular.json, src/web/app/pages-static/features-page/features-page.component.html, src/web/app/pages-static/features-page/features-page.component.scss
Fixes #10516 
Added a wrapper div for each of the components to offset from the raise page img, and change the overall bootstrap offset class to one with smaller indentation.
Outcome:
=> [#10516] Features page: reduce indentation

src/e2e/java/teammates/e2e/cases/e2e/AdminSearchPageE2ETest.java, src/e2e/java/teammates/e2e/cases/e2e/BaseE2ETestCase.java, src/e2e/java/teammates/e2e/cases/e2e/FeedbackSubmitPageE2ETest.java, src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseEditPageE2ETest.java, src/e2e/java/teammates/e2e/cases/e2e/InstructorCoursesPageE2ETest.java, src/e2e/java/teammates/e2e/cases/e2e/InstructorFeedbackSessionsPageE2ETest.java, src/e2e/java/teammates/e2e/cases/e2e/StudentHomePageE2ETest.java, src/e2e/java/teammates/e2e/pageobjects/AppPage.java, src/e2e/java/teammates/e2e/pageobjects/Browser.java, src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEditPage.java, src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEnrollPage.java, src/e2e/java/teammates/e2e/pageobjects/InstructorCoursesPage.java, src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
Part of #9536
- **Add some delay to `waitUntilAnimationFinish`:** 
- tests are failing due to elements being not found/having empty values because animation has not completely finished. 
- Added a slight delay to ensure animation is completed and elements are loaded.
- **Allow test to continue even if page cannot load completely:** 
- using `waitForPageToLoad` results in many timeouts despite the page being 99% loaded. We should allow the test to continue even if something irrelevant to the critical functionality is not loaded properly. 
- Add try catch block to ignore exception thrown by `waitForPageToLoad`.
- **Add `waitForPageToLoad` to all page loading methods**: 
- Wait for pages to fully load before proceeding with test, which minimizes chance of any elements …
=> [#9536] Fix various issues in E2E tests

src/main/java/teammates/logic/core/FeedbackResponsesLogic.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/api/FeedbackResponsesDb.java, src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
Fixes #10697 
Copy logic from V6 to proactively fetch the viewable response.
Tested for "Session with different question types" and unit tests cover most of the cases (see line coverage)
=> [#10697] Performance improvements when getting session result as students

src/main/java/teammates/ui/webapi/action/GetRegkeyValidityAction.java, src/main/java/teammates/ui/webapi/output/RegkeyValidityData.java, src/test/java/teammates/test/cases/webapi/GetRegkeyValidityActionTest.java, src/web/app/pages-session/session-result-page/session-result-page.component.html, src/web/app/pages-session/session-result-page/session-result-page.component.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.html, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Fixes #10705 
Fixes #10718 
Dealing with two issues at once since both deal with regkey check.
The root cause for both is the check for regkey's validity only stops at whether the regkey was usable by the current user or not. It did not specify further the different kinds of validity there can be, e.g. valid because the logged in user match, valid because it has not been used, etc.
=> [#10705] [#10718] Improve user flow for unregistered student and invalid registration key

src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Fixes #10708 
Trim all values before passing it to enrolling logic. Now enrolling students with trailing whitespace will be trimmed first and will not throw an error:
=> [#10708] Trim cell values of Enroll Students page

src/main/java/teammates/ui/webapi/WebApiServlet.java, src/main/java/teammates/ui/webapi/WebPageServlet.java
Fixes #10702 
We cannot access `org.eclipse.jetty.*` classes, so the next best thing we can do is to catch the immediate parent exception and match based on name. Adding the [jetty-http library](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-http) doesn't help either because we don't know the exact version used by GAE's productions server (wrong version = different byte code = exception won't be caught even if we ask it to) (P.S. it's not 9.4.27 even though it's claimed as such).
Not sure how to add test (without putting in too much effort) because I don't see a good way to sneak in a non-UTF8 character.
References: [NotUtf8Exception](https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/util/Utf8Appendable.NotUtf8Exception.html), …
=> [#10702] Change status code to 400 for non-UTF8 inputs

src/web/app/components/question-responses/grouped-responses/grouped-responses.component.ts, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html, src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html, src/web/app/components/teammates-common/student-name/student-name-with-photo.component.html
Fixes #10595 
The following things were done in this PR - 
* In case the question is posed to no specific recipient, in the Recipient-Giver-Question view, instead of rendering - (-) as user, team under `No Specific Section`, render user (team) as `No Specific User (No Specific Team)`
* In per question view, in case the recipient user, team is marked as `-` render `No Specific User (No Specific Team)`
Attaching Screen shot for use cases
1. Use case fixed - 
2. Both Users are present in DB -
=> [#10595] Instructor session results page: better label for questions without specific recipients

src/main/java/teammates/common/util/Config.java, src/main/java/teammates/ui/webapi/WebApiServlet.java, src/main/resources/build.template.properties, src/web/app/app.module.ts, src/web/app/maintenance-page.component.html, src/web/app/maintenance-page.component.spec.ts, src/web/app/maintenance-page.component.ts, src/web/app/public-page.component.ts, src/web/environments/config.template.ts
Fixes #3810 
API server and front-end are configured differently. The former returns `503 Service Unavailable` for all requests, the latter reroutes all requests to maintenance page. Technically speaking, with the way the system works right now (i.e. we don't offer standalone API services), only the latter needs to be done.
=> [#3810] Create a new 'under maintenance' version

src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap, src/web/app/components/sessions-table/sessions-table.component.html, src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Fixes #10523
**Old behavior**  
The user has to click on the edit button again to go into the edit mode.  
**New behavior**  
The page is opened in edit mode.  
**Outline of Solution**  
Set the parameter for editingMode to true in sessions-table.component.html and instructor-session-edit-page.component.ts.
=> [#10523] Edit session button should open the sessions page in edit mode

src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html, src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.ts, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html, src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html
Fixes #10798
Fixes #10795
- Add `*ngIf = showStatistics` check to remove statistics element when statistics should not be shown
- Standardize naming for `No Specific Team` across views
- Did not change naming for the titles as `No Specific Team Statistics` sounds weird to me.
- Add extra variable `sectionOfView` to differentiate filtering for the view and filtering because of the section.
- It is not possible to filter the section headers as the data is only loaded when the headers are expanded. Thus, added a empty message for sections that are empty after filtering.
**Statistic not shown when show statistics is not selected**
**Renamed to `No Specific Team` but titles are not renamed.**
**Filter by sections now shows other sections and has a message when the …
=> [#10645] [#10688] Fix bugs in instructor results page

src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
Fixes #10844
As the issue suggests, this PR basically changes the color of the instructor panel to `info` as in the below screenshot.
=> [#10844] Admin search page: show instructors and students in different colors

src/e2e/java/teammates/e2e/cases/AdminSessionsPageE2ETest.java, src/e2e/java/teammates/e2e/pageobjects/AdminSessionsPage.java
Part of #9536 
Reference: https://rules.sonarsource.com/java/RSPEC-3986
=> [#9536] Fix AdminSessionsPageE2ETest due to wrong year pattern

src/main/java/teammates/ui/webapi/GetFeedbackQuestionsAction.java, src/test/java/teammates/ui/webapi/GetFeedbackQuestionsActionTest.java
Fixes #10845 
Separated result access control check from submission access control check.
=> [#10845] Fix observers cannot view session results

src/e2e/java/teammates/e2e/cases/InstructorFeedbackResultsPageE2ETest.java, src/e2e/java/teammates/e2e/cases/InstructorSearchPageE2ETest.java, src/e2e/java/teammates/e2e/cases/TimezoneSyncerTest.java, src/e2e/java/teammates/e2e/pageobjects/AppPage.java, src/e2e/java/teammates/e2e/pageobjects/Browser.java, src/e2e/java/teammates/e2e/pageobjects/InstructorSearchPage.java, src/e2e/resources/data/InstructorSearchPageE2ETest.json, src/web/app/components/comment-box/comment-row/comment-row.component.html, src/web/app/pages-instructor/instructor-search-page/comment-result-table/comment-result-table.component.html
This will be an extended part of #9536 
- Resolved the high failure rate of Chrome-based E2E tests. It seems that a somewhat recent version of Chromedriver has a bug in setting page load timeout, so it is resolved by using native JS method. There may be other places where that bug occurs, but `driver.get` is the most obvious and by far most widely used call site.
- Separated `InstructorFeedbackResultsPageE2ETest` to multiple test cases. This is preferable because:
- The entire test runs in 5.5 mins, so if anything breaks in the middle, everything has to be run all over again
- The different view types of the results page technically create "different pages"
- Improved stability of `InstructorSearchPageE2ETest` sllightly
- Added some minor fixes to the search comments functionality: minor …
=> [#9536] Improve E2E test stability and add test for searching response comments

src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
This PR fixes #10809 by:
- removing all instances of 'Done Editing' button
- removing the instruction related to the button
- removing `doneEditingHandler`
=> [#10809] Instructor editing sessions: Remove 'Done Editing' button

src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap, src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
Fixes #10922
Surrounded 'Add All Instructors' button with div containing class="top-padded" in /teammates/src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
Changed top padding of 'Add All Instructors' button form this -
To this -
=> [#10922] Added top padding to Add All Instructors button

src/web/app/components/question-edit-form/question-edit-form.component.html
Fixes #10931
Fix typo in src/web/app/components/question-edit-form/question-edit-form.component.html
Line 246 change “Save Questions” button text to “Save Question” singular
=> [#10931] Adding a new question typo in save button

.github/workflows/component.yml, .github/workflows/e2e.yml, .github/workflows/lnp.yml
Part of #10955 
* included `objectify-v6-migration` branch trigger for GitHub Actions
* CI included: `lint`, `component-testing`, `E2E-testing` and `LnP-testing`
=> [#10955] Configure CI for 'objectify-v6-migration' branch

src/client/java/teammates/client/scripts/ListActiveInstructors.java
Fix #10928
Solution outline:
- Filter feedback sessions based on given start and end times
- Get creator email from filtered sessions and print them
=> [#10928] Add script to list active instructors within a period

src/main/java/teammates/common/util/JsonUtils.java, src/main/java/teammates/ui/webapi/JsonResult.java
Fixes #11008 
Utilize the `toJson(Object, Appendable)` function that allows streaming json output directly to writer to reduce memory consumption. Note that this memory consumption scales with the output size, which is of some concern when dealing with large size return.
**Before**
**After**
=> [#11008] Add toJson with writer as input for JsonResult to reduce unnecessary

src/main/java/teammates/storage/entity/FeedbackQuestion.java, src/main/java/teammates/storage/entity/FeedbackResponseComment.java, src/main/java/teammates/storage/entity/FeedbackSession.java, src/main/java/teammates/storage/entity/Instructor.java, src/main/java/teammates/storage/entity/StudentProfile.java, src/test/java/teammates/architecture/ArchitectureTest.java
Part of #11001
This PR cleans up existing code which still contain traces using the old `com.google.appengine.api` used before the Objectify 6 migration. 
In Objectify 6, there's no way to explicitly store a `Text` type with the Google-provided SDK. The alternative,`StringValue` does not support `null`. 
- Replace `Text` type from the `com.google.appengine.api.datastore` package used in Objectify 5 with unindexed `String`.
=> [#11001] Migrate App Engine Text datastore type

src/main/java/teammates/common/util/Const.java, src/main/java/teammates/ui/output/FeedbackSessionLog.java, src/main/java/teammates/ui/output/FeedbackSessionLogEntry.java, src/main/java/teammates/ui/output/FeedbackSessionLogsData.java, src/main/java/teammates/ui/webapi/ActionFactory.java, src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
Part of #10950 
Added base files for the audit logs
- `FeedbackResponseAccessType`, `FeedbackResponseLog`, `FeedbackResponseLogsData`, `StudentResponseAccessLog` in the `output` package for API Output
- New endpoint `webapi/sesion/accesslogs` and `GetSessionAccessLogsAction`
=> [#10950] Add base files for audit logs backend

src/main/java/teammates/ui/constants/LogTypes.java, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts, src/web/services/log.service.spec.ts, src/web/services/log.service.ts
Part of #10950 
Outline of solution
- Added new log service in frontend and call the create logs API in the session submission page for access and submission
- Added the log types in `teammates.ui.constants` so that the type is generated for frontend use (and extensibility in case more log types apart from feedback session in future?)
=> [#10950] Track student feedback session in frontend

src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java, src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java, src/main/java/teammates/ui/webapi/WebApiServlet.java, src/test/java/teammates/ui/webapi/WebApiServletTest.java
Part of #11001 
In the new Google-provided SDK used by Objectify 6 to access the datastore, exceptions are handled using `DatastoreException` which classifies errors based on canonical error codes (e.g. `NOT_FOUND`, `DEADLINE_EXCEEDED` etc). 
Considerations made:
* Previously, `DatastoreTimeoutException` (provided by the old appengine api) is thrown if a timeout is encountered when trying to access the the datastore. Now the Google-provided SDK used by Objectify 6 does not have such a specific class to handle timeouts, canonical error codes are used instead to specify error type. 
Solution:
- Handle `DatastoreException` separately from `DeadlineExceededException` to throw more specific datastore error messages.
=> [#11001] Handle datastore exceptions using the new Google-provided SDK

.github/workflows/e2e.yml, .github/workflows/lnp.yml, src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java, src/test/java/teammates/test/BaseTestCaseWithObjectifyAccess.java, src/test/java/teammates/test/TestProperties.java, src/test/resources/test.template.properties
Fixes #11002 
* removed emulator setup for e2e tests
* add emulator setup in CI for e2e and LNP
* separate datastore port of component tests from development
=> [#11002] Separate emulator ports and include its setup into CI for tests

src/web/app/components/session-edit-form/session-edit-form.module.ts, src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html, src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.scss, src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts, src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts, src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.module.ts, src/web/app/pages-instructor/instructor-page.component.ts, src/web/app/pages-instructor/instructor-pages.module.ts
Part of #10969
- Added a search form to audit logs page as per wireframe in #10969
**Current Page**
=> [#10969] Search form for audit logs page

.github/workflows/e2e.yml, .github/workflows/lnp.yml, build.gradle, src/client/java/teammates/client/remoteapi/RemoteApiClient.java, src/client/resources/client.template.properties, src/lnp/java/teammates/lnp/cases/InstructorSessionResultLNPTest.java, src/main/java/teammates/storage/api/OfyHelper.java, src/main/webapp/WEB-INF/web.xml, src/test/java/teammates/architecture/ArchitectureTest.java, src/test/java/teammates/test/GaeSimulation.java
Fixes #10955 
All remaining references to internal Datastore API are removed, and Remote API is replaced with direct connection to Google Cloud Datastore instance.
=> [#10955] Remove all references to internal Datastore API usage

src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
Part of #10950
- Simple refactoring, no change in the overall functionality of the cloud logging service
- Shifted searching of logs in `getRecentErrorLogs` to `getLogEntries`, left TODOs as they are
=> [#10950] Refactor getting of error log entries

src/main/java/teammates/ui/output/FeedbackSessionLogData.java, src/main/java/teammates/ui/webapi/CreateFeedbackSessionLogAction.java, src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java, src/test/java/teammates/test/MockLogsProcessor.java, src/test/java/teammates/ui/webapi/CompileLogsActionTest.java, src/test/java/teammates/ui/webapi/CreateFeedbackSessionLogActionTest.java, src/test/java/teammates/ui/webapi/GetFeedbackSessionLogsActionTest.java
Part of #10950 
- Added unit tests for `CreateFeedbackSessionLogAction` and `GetFeedbackSessionLogsAction`
- Added an extra check for creating a feedback session log, such that log type is either an access or a submission: this should be OK, because it doesn't involve db reads
- Added an extra check for getting feedback session logs, requiring instructor privilege to access it
=> [#10950] Add backend tests for audit logs

build.gradle, src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java, src/main/java/teammates/common/util/Config.java, src/main/java/teammates/ui/webapi/ActionResult.java, src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java, src/main/java/teammates/ui/webapi/DatastoreBackupAction.java, src/main/java/teammates/ui/webapi/JsonResult.java, src/main/java/teammates/ui/webapi/OriginCheckFilter.java, src/main/java/teammates/ui/webapi/WebApiServlet.java, src/test/java/teammates/ui/webapi/WebApiServletTest.java
Fixes #11079 
After this PR it can be confirmed that there are no more references to `com.google.appengine.api.*` and `com.google.apphosting.api.*`, other than `com.google.appengine.api.users.*` (will be resolved in #11073) and `com.google.appengine.api.search.*` (will be resolved in #11064).
=> [#11079] Migrate remaining usages of internal App Engine APIs

src/web/app/components/datepicker/datepicker.component.html, src/web/app/components/datepicker/datepicker.component.ts
Fixes #11096
Create a separate function to set today date which takes in a `NgInputDatepicker` and use the `navigateTo` method to navigate to today date
=> [#11096] Navigate to today date on click

src/web/app/components/question-responses/single-statistics/single-statistics.component.ts, src/web/app/components/question-types/question-statistics/constsum-options-question-statistics.component.html, src/web/app/components/question-types/question-statistics/constsum-recipients-question-statistics.component.html
Fixes #2673
Display statistics to students for constant sum recipient questions and constant sum options questions.
The responses will be filtered in `SingleStatisticsComponent.ts` and will only show statistics of responses from others to self.
No statistics are displayed if responses are not visible to students
Constant sum options question before
Constant sum options question after
Constant sum recipients question before
Constant sum recipients question after
=> [#2673] Student: view responses: show response statistics of 'constant sum' questions

src/web/app/pages-instructor/instructor-session-base-page.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts, src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap, src/web/services/session-result-csv.service.ts
Fixes #11124
Before
After
The Course and Session Name will only appear once at the top after the change.
=> [#11124] Instructor downloading session results: course/session details are repeated for each question

src/main/java/teammates/logic/api/EmailGenerator.java, src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.html
Fixes #11144 
Move the magic number to named constant.
Change UI display of recovery duration.
=> [#11144] Update session link recovery search duration

src/web/app/components/sortable-table/sortable-table.component.html, src/web/app/components/sortable-table/sortable-table.component.ts, src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
=> [#11103] Audit logs: right-align timestamps

src/web/app/pages-static/index-page/index-page.component.html, src/web/app/pages-static/index-page/index-page.component.scss
Fixes #10481
Remove `div` tag for video tour. Make the remaining button center.
Before:
After:
=> [#10481] Remove video tour on home page

build.gradle, src/main/appengine/app.template.yaml, src/main/java/teammates/common/util/Logger.java, src/main/java/teammates/common/util/RequestTracer.java, src/main/java/teammates/common/util/StdOutConsoleHandler.java, src/main/java/teammates/ui/webapi/ActionResult.java, src/main/java/teammates/ui/webapi/JsonResult.java, src/main/java/teammates/ui/webapi/OriginCheckFilter.java, src/main/java/teammates/ui/webapi/RequestTraceFilter.java, src/main/java/teammates/ui/webapi/WebApiServlet.java, src/main/webapp/WEB-INF/logging-dev.properties, src/main/webapp/WEB-INF/web.xml, src/test/java/teammates/architecture/ArchitectureTest.java
Fixes #11120 
Fixes #11121 
Fixing two issues together because both involves creating a filter to intercept incoming HTTP requests.
The last commit enables [structured logging](https://cloud.google.com/logging/docs/structured-logging).
=> [#11120] [#11121] Implement HTTP request interceptor and structured logging

src/e2e/java/teammates/e2e/pageobjects/InstructorAuditLogsPage.java, src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Fixes #11126 
* Modified that tap expand status depends on whether feedback session log entry is empty or not
before
after
=> [#11126] Expand empty search results for feedback session logs

src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html, src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Fixes #11182
It seems like the reason for empty proof is because all the responses were not saved. 
Updated:
Students will be unable to download the proof of submission if all questions are not saved.
If partial saving is done (ie some questions are saved), students can download the proof of submission and an error message will be displayed for questions unsaved.
@damithc do you want to allow the students to download the proof if there is a question saved properly? (ie some questions are saved and some are not, so the proof will not be entirely empty)
I think an alternative is to display in the proof of submission which questions are not saved.
=> [#11182] Proof-of-submission file: Add a warning if no answers were saved

src/web/app/components/session-edit-form/session-edit-form.component.html
Fixes #11191 
Add a space between save button icon and label.
=> [#11191] Instructor editing session: Save button is missing a space between icon and label

src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts, src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts, src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap, src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts
Fixes #11196 
Patches a bug from #10621
Added missing division by length.
Also decorate the numbers with `.toFixed(2)`.
=> [#11196] Fix incorrect display of average value for rubric question stats

src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Fixes #11161 
This bug is due to uncaught promise when a user click the `Cancel` ,  `Delete Permanently` or `Delete All` button, or when a user click outside the pop up window. Functions are added to catch these uncaught promises and set the `is*Loading` attribute to false.
Delete Permanently:
Before:
After:
Delete All:
Before:
After:
Copy from previous feedback sessions:
Before:
After:
=> [#11161] Fix modal cancel loading bug

src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-edit-form/question-edit-form-model.ts, src/web/app/components/question-edit-form/question-edit-form.component.html, src/web/app/components/question-edit-form/question-edit-form.component.ts, src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts, src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.ts
Part of #10569 
Delete Button:
https://user-images.githubusercontent.com/60355570/122361017-737d6900-cf89-11eb-948e-ff28a268c99e.mov
Duplicate Button:
https://user-images.githubusercontent.com/60355570/122361136-8db74700-cf89-11eb-930b-b1188addd559.mov
For both buttons, similar to current implementation for the save button, I added boolean values that control whether the spinner is displayed.
=> [#10569] Missing loading icons for Question Edit Form

src/web/app/components/session-edit-form/submission-status-name.pipe.ts, src/web/app/components/sessions-table/submission-status-tooltip.pipe.ts, src/web/app/components/teammates-common/submission-status-name.pipe.ts
Fixes #11237 
Added text descriptions for grace period and open status submission sessions at relevant switch case blocks.
Time of screenshot 6:03 pm.
=> [#11237] Feedback session table doesn't differentiate grace period and open status

src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java, src/main/java/teammates/common/exception/DeadlineExceededException.java, src/main/java/teammates/common/util/RequestTracer.java, src/main/java/teammates/logic/api/EmailGenerator.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/logic/core/StudentsLogic.java, src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java, src/main/java/teammates/ui/webapi/EnrollStudentsAction.java, src/main/java/teammates/ui/webapi/FeedbackSessionClosedRemindersAction.java, src/main/java/teammates/ui/webapi/FeedbackSessionClosingRemindersAction.java, src/main/java/teammates/ui/webapi/FeedbackSessionOpeningRemindersAction.java, src/main/java/teammates/ui/webapi/FeedbackSessionPublishedRemindersAction.java, src/main/java/teammates/ui/webapi/RequestTraceFilter.java, src/main/java/teammates/ui/webapi/WebApiServlet.java
Fixes #11252 
This brings back handling of `DeadlineExceededException` within the API layer itself together with other types of exceptions. (also, borrowing the name from the same class from the GAE first generation runtime)
While the idea of having codes liberally throwing `DeadlineExceededException` is inspired by GAE first generation runtime, the process is not automatic and the checks need to be manually added. While technically adding the check in every single action/function is harmless, it is waste of CPU time to do it as only very few operations are known to be possibly exceeding time limit.
=> [#11252] Use different method to impose request timeout limit

.github/workflows/lnp.yml, docker-compose.yml, src/lnp/java/teammates/lnp/cases/BaseLNPTestCase.java, src/lnp/java/teammates/lnp/cases/FeedbackQuestionUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/FeedbackSessionSubmitLNPTest.java, src/lnp/java/teammates/lnp/cases/FeedbackSessionViewLNPTest.java, src/lnp/java/teammates/lnp/cases/InstructorCourseUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/InstructorSessionResultLNPTest.java, src/lnp/java/teammates/lnp/cases/InstructorStudentCascadingUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/InstructorStudentEnrollmentLNPTest.java, src/lnp/java/teammates/lnp/cases/InstructorUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/StudentEmailUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/StudentProfileLNPTest.java, src/lnp/java/teammates/lnp/cases/StudentSectionUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/StudentTeamUpdateLNPTest.java, src/lnp/java/teammates/lnp/util/JMeterElements.java, src/main/java/teammates/ui/servlets/RequestTraceFilter.java
Fixes #11234
There are two reasons for recent L&P test failures:
- Due to feedback question ID being made `transient` recently, the way to pass in question ID to the test plan needs to be modified
- The request timeout for user-invoked requests was misconfigured to be 10s instead of 60s (I don't think we're ready for that kind of latency... yet)
You may note that those changes are very recent. Previously, all errors are caused by misconfigured request timeout handling (or really, lack thereof) which has since been fixed but caused a new problem due to slight carelessness.
In addition:
- The Datastore emulator was not run with the indexes configuration `index.yaml` which adds up to some latency (this doesn't cause failure, but is something performance-related that needs to be fixed)
- …
=> [#11234] Fix request timeout value + failing L&P tests

src/main/java/teammates/common/datatransfer/QueryLogsParams.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/logic/core/GoogleCloudLoggingService.java, src/main/java/teammates/ui/webapi/QueryLogsAction.java, src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap, src/web/app/pages-logs/logs-page.component.html, src/web/app/pages-logs/logs-page.component.spec.ts, src/web/app/pages-logs/logs-page.component.ts, src/web/services/log.service.ts
Fixes #11310
The logs are now displayed in descending order.
Users can extend the search period for "before" and "after".
The "Extend start time" button will only appear if there are no more logs to fetch in the selected time period.
Extend end time
=> [#11310] Logs Interface: Support fetching more logs for both "before" and "after"

solr/solr.sh, src/main/java/teammates/storage/search/InstructorSearchDocument.java, src/main/java/teammates/storage/search/StudentSearchDocument.java, src/main/java/teammates/storage/search/StudentSearchManager.java
Fixes #2917 
This change will make additional filtering to be no longer necessary (kept there just for safety net), as the `courseId` field is now made into a `string` instead of `text` (auto-created fields default to `text`), and `string` fields only allow exact matches ([reference](https://answers.sap.com/questions/12771972/what-is-the-difference-between-string-and-text-typ.html)).
Auto-created fields are not considered good practice (in fact it's the first thing that Solr warns after starting up the server), and thus it is also removed here. The only remaining fields are `courseId` and `email` (they are the basic identifiers of the indexed student/instructor), on top of the default fields which include `id` (search document identifier) and `_text_` (this is where the searchable terms …
=> [#2917] Modify Solr to not use auto-created fields to prevent unnecessary tokenization

src/client/java/teammates/client/scripts/DataMigrationForConstSumForceUnevenDistribution.java, src/client/java/teammates/client/scripts/DataMigrationForNullCommentGiverType.java, src/client/java/teammates/client/scripts/DataMigrationForSampleGoogleIdInStudentAttributes.java, src/client/java/teammates/client/scripts/DataMigrationForTextQuestionRecommendedLength.java, src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java, src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionType.java, src/main/java/teammates/storage/entity/Instructor.java, src/main/java/teammates/ui/output/FeedbackQuestionData.java, src/main/java/teammates/ui/request/FeedbackQuestionBasicRequest.java, src/main/resources/InstructorSampleData.json, src/test/java/teammates/common/datatransfer/attributes/InstructorAttributesTest.java
- Fixes #11039. Added script to remove the fake google IDs from the sample students.
- Part of #10677 
- Part of #9083 
- Part of #8577 (the follow-up action is not documented here)
- Added `updatedAt` and `createdAt` fields for `Instructor`, in the somewhat likely event we're going to need it
- Removed the misleading comments about the need to migrate CONSTSUM question type; that is never a candidate for migration in the first place
=> [#11039] [#10677] [#9083] Remove fake google ID in sample students + add migration scripts

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, build.gradle, docs/design.md, docs/development.md, docs/e2e-testing.md, docs/performance-testing.md, docs/setting-up.md, src/client/resources/client.template.properties, src/e2e/resources/test.template.properties, src/lnp/java/teammates/lnp/cases/FeedbackQuestionUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/FeedbackSessionSubmitLNPTest.java, src/lnp/java/teammates/lnp/cases/FeedbackSessionViewLNPTest.java, src/lnp/java/teammates/lnp/cases/InstructorSessionResultLNPTest.java, src/lnp/java/teammates/lnp/cases/InstructorUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/StudentEmailUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/StudentSectionUpdateLNPTest.java, src/lnp/java/teammates/lnp/cases/StudentTeamUpdateLNPTest.java, src/lnp/resources/test.template.properties, src/main/java/teammates/storage/search/SearchManager.java, src/main/java/teammates/ui/servlets/WebSecurityHeaderFilter.java, src/main/resources/build.template.properties, src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.html, src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts, src/web/data/developers.json, src/web/environments/config.template.ts
Part of #11329 
- Two minor backend updates: connection timeout values for Solr and slightly more secure `img-src` CSP rule
- Fixed L&P test failures introduced by upgrading to Java 11 (due to timestamp now being calculated in microsecond precision)
- Updated `developers.json`:
- Updated committers/core team members after a long while
- Added new contributors
- Updated some outdated GH usernames; many past contributors unfortunately became @ghost and are subsequently removed
- Some documentation update
- In particular, Python is no longer a requirement as we have decoupled from Cloud SDK
- Python is needed if deployment is involved, but this is a separate requirement and will be reflected in the ops repository instead
- Added note for search feature brownout while we're indexing data …
=> [#11329] Release V8.0.0

src/client/java/teammates/client/scripts/DataMigrationForTextQuestionDetailsFormat.java, src/client/java/teammates/client/scripts/IndexFeedbackSessionFields.java, src/main/java/teammates/storage/entity/FeedbackSession.java, src/main/java/teammates/ui/servlets/DevServerLoginServlet.java, src/main/java/teammates/ui/servlets/LoginServlet.java, src/web/app/pages-session/session-result-page/session-result-page.component.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts, src/web/app/public-page.component.ts, src/web/app/user-join-page.component.ts
Fixes #11352 
Part of #11348: added script to rewrite all the feedback session entities so that the new indexes are correctly generated
Part of #11344: apparently, plaintext format for text question details occurred much more recently and not just on old data, so the script had to be extended to cover all time period
Fixes a bug introduced in #10791 whereby `studentEmail` parameter is wrongfully used when calling the student API
=> [#11352] Logging in does not preserve query parameters other than the first one

src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts, src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Fixes #11202 
Changes the search to use the timezone of the feedback course/session, instead of the user web browser's timezone.
This assumes that the feedback course timezone is the same as that of its feedback sessions, which makes sense (I hope) as setting the timezone of a course changes those of its sessions too.
Before (browser in UTC+8, course in UTC):
After (browser in UTC+8, course in UTC):
=> [#11202] Instructor checking activity logs: start time is not used correctly

src/client/java/teammates/client/scripts/DataMigrationForCourseInstitutes.java, src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/logic/core/AccountsLogic.java, src/main/java/teammates/storage/api/CoursesDb.java, src/main/java/teammates/storage/entity/Course.java, src/main/java/teammates/ui/webapi/CreateAccountAction.java, src/main/java/teammates/ui/webapi/CreateCourseAction.java, src/main/java/teammates/ui/webapi/GetOngoingSessionsAction.java, src/main/java/teammates/ui/webapi/SearchInstructorsAction.java, src/main/java/teammates/ui/webapi/SearchStudentsAction.java, src/main/resources/InstructorSampleData.json, src/test/java/teammates/common/datatransfer/attributes/CourseAttributesTest.java, src/test/java/teammates/logic/core/AccountsLogicTest.java, src/test/java/teammates/ui/webapi/CreateAccountActionTest.java, src/test/java/teammates/ui/webapi/CreateCourseActionTest.java
First part of #11362 
This is only the preparatory step.
- Added `institute` field to `Course` object. This field is not yet used by any business logic, i.e. retrieval of institute will still use `Account` object, however newly created courses from this point onwards will have `institute` field reflected.
- For courses created by admin, the `institute` will be set right from the start.
- For courses created by instructors, the `institute` will be set using the institute from their `Account` object.
- For existing courses yet to be joined by the first instructor (i.e. freshly created), the `institute` will be set when the first instructor joins.
- Added script to populate institute of courses. If institute cannot be found, the default `Unknown Institution` will be used instead. This …
=> [#11362] Add institute field to Course object

build.gradle, src/main/appengine/app.template.yaml, src/main/java/teammates/common/util/TimeHelper.java, src/main/java/teammates/main/Application.java, src/main/java/teammates/ui/servlets/WebApiServlet.java
Fixes #9645
This is now possible because in the new runtime we control exactly how the system is started, including the system property flags.
=> [#9645] Use system property instead of reflection to determine timezone rules provider

src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts
Fixes #11468
- Change intent from INSTRUCTOR_RESULT to FULL_DETAIL when viewing all student records
Note: I didn't find `loadStudentResults()` used anywhere else other than in instructor-student-records so I suppose this should be a rather safe change. Kindly advice if I have overlooked anything, thank you!
=> [#11468] Fix instructor view all records not showing results

.github/workflows/e2e-cross.yml, .github/workflows/e2e.yml, src/web/app/components/feedback-path-panel/feedback-path-panel.component.html, src/web/app/components/feedback-path-panel/feedback-path-panel.component.ts, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-edit-form/question-edit-form.component.html, src/web/app/components/question-edit-form/question-edit-form.component.ts
Fixes #11474 
Root cause: wrong attribute being bubbled up in the event of modifying the custom number of entities to give responses to.
This also removes the need for `saveChangeClicked` which was a wrong attempt to circumvent the problem.
=> [#11474] Fix feedback path event bubbleup error

src/main/java/teammates/ui/servlets/AuthServlet.java
Fixes #11520 
Add `ngsw-bypass` to the redirect URI to bypass service worker when callback page is loaded, in light of the change of service worker as suggested by https://github.com/TEAMMATES/teammates/issues/11520#issuecomment-1013286861,
=> [#11520] Infinite loop when logging in using Google account on a Chromium-based browser

src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Fixes #11539 
Added check that prevents `feedbackResponsesService` from submitting the question feedback response if said response is invalid, as well as testcases for this.
=> [#11539] Feedback response submission: Requests sent to backend despite invalid response

src/web/app/pages-student/student-profile-page/__snapshots__/student-profile-page.component.spec.ts.snap, src/web/app/pages-student/student-profile-page/student-profile-page.component.html, src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html, src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts
Fixes #11152 
1. Update description and tool tip for valid file types
2. Show an error message when invalid file type has been uploaded
3. Disable the upload button by default, and only enable when valid file type uploaded
Demonstration of solution:
https://user-images.githubusercontent.com/10182564/151968195-b1227447-c12d-49e4-b837-a6177a5e29fc.mp4
Note: Some of the mentioned file types in the issue cannot be prevented (e.g apng), as they are inherently .png/.jpg files.
=> [#11152] Student update profile: profile image does not display correctly when certain formats are used 

.github/workflows/component.yml, .github/workflows/e2e-cross.yml, .github/workflows/e2e.yml, .github/workflows/lnp.yml
Part of #11571 
This allows CI to run on the `selective-deadline-extension` feature branch.
=> [#11571] Add selective-deadline-extension to CI workflow

src/main/java/teammates/common/datatransfer/UserInfoCookie.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/ui/servlets/AuthServlet.java, src/test/java/teammates/common/datatransfer/UserInfoCookieTest.java
Fixes #11578 
Added expiration time to UserInfoCookie, 7 days from when cookie is created, invalidates cookie if after this time.
=> [#11578] Make user cookie time sensitive

src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java, src/test/java/teammates/logic/core/FeedbackQuestionsLogicTest.java
Fixes #11592
Arguments in populateFieldsToGenerateInQuestion are now in the correct order
Also included two new tests in FeedbackQuestionsLogicTest to ensure the code runs and does not produce any NullPointerExceptions.
=> [#11592] Wrong argument order in populateFieldsToGenerateInQuestion causes NPE

src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.spec.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
Fixes #10843 
Added a loading spinner for instructors no response panel.
The spinner will show until loading of students finishes, and show the appropriate message.
In the event of failure of loading the students, there'll be a message to show "Failed to load students who have not responded". (So there's no infinite spinning).
Happy Path:
(Personally I'm unable to replicate the problem myself on both production and dev server due to speed, so this video is simulated with a 5s timer)
https://user-images.githubusercontent.com/10182564/155762223-c84d4181-6d92-4149-a903-a433ef314460.mp4
=> [#10843] Instructor viewing results: incorrect state shown briefly when expanding the non-submitters panel 

src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java, src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/api/FeedbackResponsesDb.java, src/main/java/teammates/storage/api/FeedbackSessionsDb.java, src/main/java/teammates/storage/api/StudentsDb.java, src/test/java/teammates/logic/core/FeedbackQuestionsLogicTest.java, src/test/java/teammates/logic/core/FeedbackSessionsLogicTest.java, src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java, src/test/resources/data/typicalDataBundle.json
Fixes part of #11585
Fixes 
```
FeedbackResponsesDb.hasExistingEntities
FeedbackSessionsDb.hasExistingEntities
StudentsDb.hasExistingEntities
FeedbackSessionLogic.isFeedbackSessionForUserTypeToAnswer
```
=> [#11585] Remove unnecessary data read

src/main/java/teammates/common/datatransfer/DataBundle.java, src/main/java/teammates/common/datatransfer/attributes/NotificationAttributes.java, src/main/java/teammates/logic/core/DataBundleLogic.java, src/main/java/teammates/ui/webapi/GetNotificationAction.java, src/test/java/teammates/common/datatransfer/attributes/NotificationAttributesTest.java, src/test/java/teammates/common/util/FieldValidatorTest.java, src/test/java/teammates/ui/webapi/GetNotificationActionTest.java, src/test/resources/data/typicalDataBundle.json
* Add tests for `NotificationAttributes`
* Add notifications to typical data bundle
* Add tests for GET API
**Has not include:**
* `isfetchingall` related feature / tests.
=> [#11572] Notification: GET API test and access control

src/main/appengine/index.yaml, src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/common/util/FieldValidator.java, src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/InstructorsLogic.java, src/main/java/teammates/logic/core/StudentsLogic.java, src/main/java/teammates/storage/api/InstructorsDb.java, src/main/java/teammates/storage/api/StudentsDb.java, src/main/java/teammates/ui/request/FeedbackSessionUpdateRequest.java, src/main/java/teammates/ui/webapi/UpdateFeedbackSessionAction.java, src/test/java/teammates/common/util/FieldValidatorTest.java, src/test/java/teammates/logic/core/InstructorsLogicTest.java, src/test/java/teammates/logic/core/StudentsLogicTest.java, src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java, src/test/java/teammates/storage/api/InstructorsDbTest.java, src/test/java/teammates/storage/api/StudentsDbTest.java, src/test/java/teammates/ui/webapi/UpdateFeedbackSessionActionTest.java, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts, src/web/services/feedback-sessions.service.ts
Part of #11571
The deadline maps are added to `FeedbackSessionUpdateRequest`. This allows deadlines to be created, updated, or deleted, by adding, modifying, or removing the deadline respectively from the corresponding deadline map(s) in the new updated feedback session sent as a request. This is done by allowing updates to the deadline maps in the feedback session through changes in `UpdateFeedbackSessionAction`.
The emails in the deadline maps are all checked for their existence in the database if there are any extra emails (when a new deadline is created; not when updated or deleted). An error is thrown if this is not the case. A single projection query over all emails in a course for either students or instructors is used to reduce database reads.
The deadlines …
=> [#11571] Selective Deadline Extensions - C_UD selective deadlines

src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java, src/main/java/teammates/common/datatransfer/attributes/NotificationAttributes.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/ui/constants/ResourceEndpoints.java, src/main/java/teammates/ui/output/NotificationData.java, src/main/java/teammates/ui/webapi/ActionFactory.java, src/main/java/teammates/ui/webapi/GetNotificationAction.java, src/main/java/teammates/ui/webapi/GetNotificationsAction.java, src/test/java/teammates/test/AbstractBackDoor.java, src/test/java/teammates/test/BaseTestCaseWithDatabaseAccess.java, src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java, src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java, src/test/java/teammates/ui/webapi/GetNotificationsActionTest.java, src/web/services/notification.service.ts
Part of #11572
- Moved GET route for `Notification` to `Notifications` (`GetNotificationAction` renamed to `GetNotificationsAction`)
- `Notification` GET route is now used to get a single notification based on ID (Uses the new `GetNotificationAction` class)
- Add methods required in `BaseTestCaseWithDatabaseAccess` to allow methods like `verifyAbsentInDatabase` to be used by notifications. (Needed for testing notification logic layer and E2E tests)
=> [#11572] Add get notification route and helper functions for testing

src/web/app/components/sortable-table/sortable-table.component.ts, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts, src/web/services/feedback-sessions.service.ts, src/web/services/log.service.ts, src/web/services/search.service.ts, static-analysis/teammates-eslint.yml
Fixes #11673 
Config:
```yaml
"@typescript-eslint/member-delimiter-style":
- error
- multiline:
delimiter: "comma"
requireLast: true
singleline:
delimiter: "comma"
requireLast: false
overrides:
interface:
multiline:
delimiter: "semi"
requireLast: true
```
Doubts:
I picked `false` for single line `requireLast` delimiter option (trailing comma) because it required the least changes to existing files. I'm not too sure what the convention is and if we should be standardizing and changing this to true instead.
=> [#11673] Add ESLint rule for member delimiter style

src/main/appengine/queue.yaml, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/logic/api/TaskQueuer.java, src/main/java/teammates/ui/webapi/UpdateFeedbackSessionAction.java, src/test/java/teammates/ui/webapi/UpdateFeedbackSessionActionTest.java
Part of #11571
A queue is created to allow the enqueueing of `DeadlineExtensionsWorkerAction` tasks. A task is enqueued in each `UpdateFeedbackSessionAction` when there are changes to the deadline maps. This task then creates, updates, or deletes the deadline extension entities if necessary, and notifies users of such changes if specified. Thus, the backend is integrated.
=> [#11571] Selective Deadline Extensions - Integrate the backend

src/main/java/teammates/ui/webapi/CreateFeedbackResponseCommentAction.java, src/main/java/teammates/ui/webapi/DeleteFeedbackResponseCommentAction.java, src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java, src/main/java/teammates/ui/webapi/UpdateFeedbackResponseCommentAction.java, src/test/java/teammates/ui/webapi/CreateFeedbackResponseCommentActionTest.java, src/test/java/teammates/ui/webapi/DeleteFeedbackResponseCommentActionTest.java, src/test/java/teammates/ui/webapi/SubmitFeedbackResponsesActionTest.java, src/test/java/teammates/ui/webapi/UpdateFeedbackResponseCommentActionTest.java
Part of #11571 
The feedback sessions were sanitized depending on what type of user was using the action. This meant that the correct deadline was used for the user regardless of whether it was the default session end time or their own selective deadline, if they had one. This allows the user to use actions such as submitting feedback responses when it is still open for them, even if it is already closed for others, if they have a selective deadline that is still in the future.
=> [#11571] Add selective deadlines into access control checks

src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.html, src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts, src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form-model.ts, src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html, src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.scss, src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.ts, src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table-model.ts, src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.html, src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.ts, src/web/services/notification.service.ts
Part of #11572
This PR consists of code for the pages enabling the admin to update a notification. Since notification is rather simple and there is nothing linked to it to be edited together unlike feedback sessions, the same edit form (the one for creating notifications) will be reused.
Other improvements related to this is also included, including the removal of redundant code such as `isEditable` 
This PR is ready for review.
=> [#11572] Notification feature - Admin page update (edit) feature

src/main/java/teammates/ui/webapi/FeedbackSessionClosingRemindersAction.java, src/test/java/teammates/ui/webapi/FeedbackSessionClosingRemindersActionTest.java, src/test/resources/data/typicalDataBundle.json
Part of #11571
Since `DeadlineExtension` is not a source of truth for student deadlines, we cannot guarantee that the deadline is valid at the point where we need to send closing emails. For example, there might be eventual consistency issues (esp since we using an index) or the task queue worker used to DeadlineExtension entities might have failed to update/delete the entity.
Solution:
Check the validity of DeadlineExtensions before sending closing emails. In particular, check that the deadline exists in feedback session and is the correct time.
=> [#11571] Verify deadline extensions are valid before sending closing emails

src/main/java/teammates/storage/api/InstructorsDb.java
Fixes #11697 
We should not add an index to Instructor just for this small impact change.
Revert to entity query for instructor email instead.
=> [#11697] Remove projection query without index

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/main/java/teammates/logic/core/InstructorsLogic.java, src/main/java/teammates/logic/core/StudentsLogic.java, src/test/java/teammates/logic/core/FeedbackSessionsLogicTest.java, src/test/java/teammates/logic/core/InstructorsLogicTest.java, src/test/java/teammates/logic/core/StudentsLogicTest.java, src/test/resources/data/FeedbackSessionsLogicTest.json, src/test/resources/data/typicalDataBundle.json
Part of #11571 
Any user email address update or any user deletion is cascaded down to the deadline maps. This is implemented by finding all the feedback sessions in the course the user belongs to. For each feedback session, the email is updated or deleted accordingly in the respective deadline map if that map contains a selective deadline for that user.
=> [#11571] Cascade user updates/deletes to deadline maps

src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts, src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html, src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.ts
Part of #11572
This PR contains the following fixes:
- Fix the issue that edit button cannot open edit form (way to replicate: edit notif 1 -> edit notif 2 without saving 1 -> save notif 2 without changing message field -> click "edit" button for notif 2 again)
- Move style demo to the side of the selector
- Remove redundant code
The style demo looks like this now and it should work for all OS and browser:
Thanks @moziliar for pointing out the bugs.
=> [#11572] Notification feature - Fix edit button and move style demo to the side

src/main/java/teammates/ui/webapi/DeleteNotificationAction.java, src/test/java/teammates/ui/webapi/CreateNotificationActionTest.java, src/test/java/teammates/ui/webapi/DeleteNotificationActionTest.java, src/test/java/teammates/ui/webapi/UpdateNotificationActionTest.java
Part of #11572
- Add tests for PUT and DELETE routes
- Add missing test annotation for `CreateNotificationAction` and fix test
=> [#11572] Notification feature - Add tests PUT and DELETE route

src/test/java/teammates/logic/core/NotificationsLogicTest.java, src/test/java/teammates/storage/api/NotificationsDbTest.java
* Add tests for NotificationLogic, especially for functions related to GET, PUT and DELETE.
=> [#11572] Notification Feature - Notification Logic Tests

src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
Removed the following line from the Instuctors help section
`Tick the option <b>Students</b> below the search box.`
This PR is ready for review.
Fixes #11710
=> [#11710] Instructor Help Page: Outdated search bar documentation

src/main/java/teammates/logic/external/GoogleCloudLoggingService.java
Fixes #11497
The issue should occur due to the call to `iterateAll()` happening after `logging.close()`, so this fix shifts the call to `iterateAll` to before closing the logging resource. (props to @t-cheepeng for identifying the issue)
Have tested on staging and the functionality still works as before, but since I can't reproduce the issue on my staging will need some external help to check that the fix works as intended.
=> [#11497] Fix server error when retrieving log entries from cloud logging 

src/main/appengine/index.yaml
Fixes #11715 
Swapped ordering of properties as properties used in equality filters should come before those used in inequality filters.
See https://github.com/TEAMMATES/teammates/issues/11715#issuecomment-1094072639 and https://cloud.google.com/appengine/docs/standard/java-gen2/configuring-datastore-indexes-with-index-yaml#index_definitions.
=> [#11715] Selective Deadline Extension - Error in getting deadline extension entities possibly needing closing email 

src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/AccountsLogic.java, src/main/java/teammates/ui/output/NotificationData.java, src/main/java/teammates/ui/webapi/Action.java, src/main/java/teammates/ui/webapi/GetNotificationsAction.java, src/test/java/teammates/ui/webapi/GetNotificationsActionTest.java, src/test/resources/data/typicalDataBundle.json
* Filter out unread notification list using notification ids stored in individual accounts.
* Add more tests for `isfetchingall` in test for `GetNotificationsAction`.
* Update `shown` feature of a notification when a non-admin user get notifications.
* Hide admin information(createdAt and target user) when non-admin get notifications.
=> [#11572] Notification Feature - Add mark as read to notification GET API

.github/workflows/dev-docs.yml, docs/documentation.md
Fixes #11732
Supersedes and hence closes ##11733
PlantUML diagrams are used in dev docs (Design), which MarkBind requires both Java and Graphviz to be installed, in order to generate these diagrams on build.
Let's add an installation step for Graphviz (Java is available by default since we use `ubuntu-lastest`) in CI such that the diagrams can be generated before deploying to gh-pages.
Let's also include such details in our dev docs (Documentation), to remind developers who intend to contribute to teammates' documentation to install the required dependencies.
The expected outcome of the dev docs page on "design" (that contains broken images) is available at this [link](https://tlylt.github.io/test-docs/design.html) for inspection.
**Others**
There are also some …
=> [#11732] Broken PUML diagrams in developer guide

src/web/app/page.component.html, src/web/app/page.component.ts
Part of #11729 
It is noteworthy that all the non-IE browsers we officially support (Chrome, Edge, Firefox, Safari) are evergreen browsers, i.e. self-updating.
- Updated the supported browsers list. While [Bootstrap](https://getbootstrap.com/docs/4.6/getting-started/browsers-devices/) mentions explicit minimum versions for the browsers, [Angular](https://v12.angular.io/guide/browser-support) only mentions "latest" or "2 most recent" versions, thus the risk of having broken front-end is not small, but at the same time not large because the browsers are self-updating anyway.
- As the middle ground, the minimum version numbers are updated based on [browser market share in the past one year](https://gs.statcounter.com/browser-version-market-share/desktop/worldwide/). …
=> [#11729] Update supported browsers list + add IE deprecation warning

src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/logic/core/AccountsLogic.java, src/main/java/teammates/ui/output/ReadNotificationsData.java, src/main/java/teammates/ui/webapi/ActionFactory.java, src/main/java/teammates/ui/webapi/GetReadNotificationsAction.java, src/main/java/teammates/ui/webapi/MarkNotificationAsReadAction.java, src/test/java/teammates/logic/core/AccountsLogicTest.java, src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java, src/test/java/teammates/ui/webapi/GetReadNotificationsActionTest.java, src/test/java/teammates/ui/webapi/MarkNotificationAsReadActionTest.java, src/web/app/components/notification-banner/notification-banner.component.ts, src/web/app/components/user-notifications-list/user-notifications-list.component.html, src/web/app/components/user-notifications-list/user-notifications-list.component.ts, src/web/app/page.component.html, src/web/app/page.component.ts, src/web/services/notification.service.ts
This PR is based on changes in #11720 for styles.
* Add a GET API Route `GetReadNotificationsAction` to retrieve read notification ids for the user.
* Add relevant backend tests for `GetReadNotificationsAction`.
* Add mark as read button to past notification page, such that once a user marks a notification as read, the button will disappear and the tab will close (See the demo below).
* * Notification tab that has been marked as read will by default be closed.
https://user-images.githubusercontent.com/69516975/163303433-d3a8013c-4c0f-4b55-bfdc-001d4f5f19fc.mov
=> [#11572] Notification Feature - Add Mark As Read to Past Notification Page

src/main/java/teammates/ui/webapi/GetNotificationsAction.java, src/web/app/components/user-notifications-list/user-notifications-list.component.html, src/web/app/page.component.html
Part of #11572
This fixes the problem that a non-admin instructor has no permission to fetch any notification.
Also, it prevents a user that is neither student nor instructor (e.g. someone logs in with an email address not registered for any courses) to load the notification banner component. It removes banner for this situation:
Also, this removes duplicated loading spinner at the notification page for both students and instructors.
=> [#11572] Notification feature - Fix permission problem for instructors

src/web/app/components/notification-banner/notification-banner.component.scss, src/web/app/page.component.html
Removes sticky behaviour of notification banner due to a bug in Safari 14 that causes `position: sticky` to not work properly.
=> [#11572] Notification Feature - Remove notif banner sticky behaviour

src/main/java/teammates/storage/entity/FeedbackSession.java
Fixes #11751 
Add `@Unindex` annotation to prevent `studentDeadlines` and `instructorDeadlines` from being indexed, which removes the 1500 byte constraint.
=> [#11751] Deadline extensions in FeedbackSession entity have unnecessary constraint

src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap, src/web/app/pages-student/student-home-page/student-home-page.component.html, src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts, src/web/app/pages-student/student-home-page/student-home-page.component.ts
Fixes #11551
The original PR #11563 did not fix the issue completely. It moved the assignment of value to `isCourseLoading` after the sessions are loaded. This works only the case when there is 1 course.
When there are multiple courses, the first course that finish loading sessions will set `isCourseLoading = false` and therefore all remaining courses will be displayed with the wrong message again.
This PR reworks the mechanism of this. It adds a `isFeedbackSessionLoading` and `hasFeedbackSessionLoadingFailed` to every single courses. Loading of sessions will be independent and will have their own spinner/retry button now. For more information, see the recording below.
Before:
After:
When it loads the courses successfully but failed to load the sessions:
=> [#11551] Fix incorrect loading message (rework)

src/main/java/teammates/logic/api/EmailGenerator.java, src/test/resources/data/EmailGeneratorTest.json, src/test/resources/emails/sessionClosingEmailForInstructorWithExtension.html, src/test/resources/emails/sessionClosingEmailForStudentWithExtension.html
Fixes #11756
- Update deadline to show correct deadline after extension is accounted for
- If deadline has been extended, update deadline to `... (after extension)`
=> [#11756] Session closing email contains no information about extended deadline

src/web/app/components/question-edit-form/question-edit-form.component.ts
Fixes #11759 
I changed the argument of the confirmation model to match the issue's request.
=> [#11759] Instructor editing questions: tweak the confirmation dialog for cancelling an edit

src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts, src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/sessions-section-questions.ts, src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
Part of #11794 . Made some changes to the instructor help pages.
Partially fixes #11794 . Reopen the issue after PR is merged.
Trying to create small PRs, so there're still more updates to the instructor pages needed, even besides #2874 and #8769 . However, the current contents on the help page should make sense as well, just not being comprehensive somewhere (probably).
I didn't do much content proof reading and there might still be some changes needed. @damithc
=> [#11794] Update instructor help page

src/e2e/java/teammates/e2e/pageobjects/AppPage.java, src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java, src/e2e/resources/data/FeedbackSubmitPageE2ETest.json, src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java, src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java, src/main/java/teammates/logic/core/FeedbackResponsesLogic.java, src/test/resources/data/GetFeedbackQuestionRecipientsActionTest.json, src/test/resources/data/typicalDataBundle.json, src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-submission-form/recipient-type-name.pipe.ts, src/web/app/components/visibility-messages/visibility-entity-name.pipe.ts, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts, src/web/services/feedback-questions.service.ts
Fixes #2488
* Add the new definition/logic for `STUDENTS` and `TEAMS`
* Add the new recipient type options, i.e. `STUDENTS` and `TEAMS`
=> [#2488] Instructor: edit questions: give more recipient type options

src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
Fixes #11858
Timeout is believed to be caused by the building of missing responses for `Other teams in the same section`, where a query is made instead of utilizing the course roster provided. Hence, the fix is just to utilize the course roster.
=> [#11858] Instructor viewing results: 'Other teams in the same section' path is causing timeout

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap, src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html, src/web/styles.scss
Fixes #11753 
* Button text for the individual question and all-question submission is now more specific.
* Dialog makes it clear that submitting an individual question does not submit all other questions.
| Individual question    | All questions |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/53614454/172632818-a31ea369-3f5d-4f09-963f-bd2117fbb2c2.png) | ![image](https://user-images.githubusercontent.com/53614454/172632931-ebd33f51-9a6a-4866-a9b5-a7ea6f860d4c.png)    |
| ![image](https://user-images.githubusercontent.com/53614454/172633058-696b6cf7-2be8-4e24-b85e-c9b0f23039fb.png) | ![image](https://user-images.githubusercontent.com/53614454/172633119-03b147c6-5fa2-4aa2-a488-2a04c45456d9.png) |
=> [#11753] Differentiate button/dialog for individual/all-question submissions

src/web/app/components/session-edit-form/session-edit-form.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-session-individual-extension-page/__snapshots__/instructor-session-individual-extension-page.spec.ts.snap, src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.ts, src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.spec.ts, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html, src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.spec.ts
Fixes #11764 
Added a button next to the 'Remind All' button that takes the instructor to the individual extension page with the non-submitters pre-selected.
https://user-images.githubusercontent.com/8349063/176203771-b572d450-6ccd-429a-82fa-a700b93a4756.mp4
=> [#11764] Give an easy way to extend deadline for non-submitters

src/client/java/teammates/client/scripts/DataMigrationForContributionQuestionDetailsIsZeroSum.java
Part of #11772
1. Modify the default constructor for `FeedbackContributionQuestionDetails`, which is used in deserialization, such that `isZeroSum` is set to `false` by default if absent, as in old feedback contribution questions.
2. Write and run a data migration script to set `isZeroSum` of old questions to `false`.
3. Revert the logic for the default constructor such that both constructors, i.e. `FeedbackContributionQuestionDetails()` and `FeedbackContributionQuestionDetails(String questionText)`, have the same set of default values.
=> [#11772] Set `FeedbackContributionQuestionDetails.isZeroSum` of old questions to `false`

src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Fixes #11911.
Previously, when an instructor creates a course by copying another course **without any feedback session** selected, user gets stuck on the copying and no progress is shown on the progress bar.
The fix is to check if there is any feedback session to copy, else we just need to resolve the `Promise` and this would update the progress bar as well.
Additionally, shifted out the `ProgressBarService` update lines as there are code duplications in the above fix and the current implementation (5e50c39).
https://user-images.githubusercontent.com/46486515/181818057-3c7f4922-5aa3-45eb-9c02-1035a08fdd27.mp4
=> [#11911] Instructor copying course: Progress bar does not load when no feedback sessions are copied

src/web/app/components/question-submission-form/question-submission-form.component.spec.ts, src/web/app/components/question-submission-form/question-submission-form.component.ts
Fixes #11917
- Updated the `QuestionSubmissionFormComponent` to use `DoCheck` instead of `OnInit` Lifecycle hook inorder to sort the recipients only after the model (which is an input) is loaded. 
- As mentioned in the [Angular documentation](https://angular.io/guide/lifecycle-hooks#docheck), `ngDoCheck` can be used to monitor changes that won't be catched by `ngOnChanges`. Hence the former was preferred.
=> [#11917] `QuestionSubmissionFormComponent` sorts `recipientList` and `recipientSubmissionForms` before being loaded 

src/main/java/teammates/storage/api/AccountsDb.java, src/main/java/teammates/storage/api/InstructorsDb.java, src/main/java/teammates/storage/api/StudentsDb.java
Part of #11586
- > java.lang.AssertionError: Trying to create a course for a non-existent instructor [abcd@gmail.com](mailto:abcd@gmail.com)
at teammates.logic.core.CoursesLogic.createCourseAndInstructor(CoursesLogic.java:104)
As the above error due to PR #11903 was caused by some missing code to deal with the old `Account` data, the corresponding code has been added.
- Also, when debugging, some flaws to the query logic were discovered. Firstly, filtered queries involving `googleId` should be done in one go instead of splitting them up so that the target entity could be searched. Secondly, when retrieving courses of an instructor, `Instructor` entities of both `googleId` and `email` should be retrieved to include courses created before and after the change.
=> [#11586] Fix errors due to missed instances of trimming of `@gmail.com`

src/main/java/teammates/ui/webapi/Action.java, src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java, src/main/java/teammates/ui/webapi/DeleteStudentProfilePictureAction.java, src/main/java/teammates/ui/webapi/GetRegkeyValidityAction.java
=> [#11586] Remove trailing `@gmail.com` when checking for user ID equality

src/e2e/resources/data/AdminAccountsPageE2ETest.json, src/main/java/teammates/ui/webapi/DeleteInstructorAction.java, src/test/java/teammates/ui/webapi/DeleteInstructorActionTest.java
Fixes #9534
1. Removed the truth check in `DeleteInstructorAction` that allowed admins to bypass the truth checking stopping the last instructor of a course from being deleted from said course.
2. Modified the corresponding unit test, `testExecute_deleteLastInstructorByGoogleId_shouldPass`, by flipping asserts, and renaming accordingly.
=> [#9534] Deleting the last instructor in the course leaves a dangling course object in the database

src/web/app/components/question-types/question-constraint/contribution-question-constraint.component.ts
Fixes #11950.
Previously, the zero-sum contribution question overflows when it exceeds the total required contribution percentage i.e. `Number of members in the team * 100%`, as it is not captured in the logic flow for the error message.
Now, we have introduced another way of checking for this overflow and reducing the number of `Equal Share` with a cap based on the number of members in a team by `Total required contribution percentage / 100`. The excess will then be calculated separately.
And now, it should read `Current total 5 x Equal share + 100% ...` when the total required contribution percentage exceeds `n * 100`, where `n` is the number of members.
=> [#11950] Fix bug with overflow of members count in error message

src/web/app/pages-static/features-page/features-page.component.html, src/web/app/pages-static/index-page/index-page.component.html
Fixes #11962
Issue has been solved by adding aria hidden to decorative images, therefore removing them from the accessibility tree on assistive technologies such as JAWs, Voiceover etc. [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden](aria-hidden) alternatively this could be done by adding alt="" to the image.
Before: 
After:
=> [#11962] Decorative images are not hidden from accessibility tree

package.json
Fixes #11981
As proposed by @tenebrius1, modify linting such that lintspaces is skipped if there are no files changed that need to be checked, thereby fixing failing lint checks.
=> [#11981] Ubuntu lint checks failing due to lintspaces

src/web/app/components/question-submission-form/question-submission-form.component.spec.ts, src/web/app/components/question-submission-form/question-submission-form.component.ts
Fixes #11991
Fix made by having empty responses having a higher index when sorting.
The index made to index+1 since it will conflict with the first element and result in lexicographically unsorted order.
=> [#11991] Student submitting fewer responses than allowed: show empty responses at the bottom when reloading the submission page

src/web/app/components/progress-bar/progress-bar.component.ts
Fixes #11876.
Previously, the progress bar component starts with a default value of 0. This has caused some confusion to what the component is or its progress of the current task.
Let's instead give it a default value of `10%` for clarity. Now, the progress bars start from 10% and scales up as per usual to 100%.
An example for when copying a course:
=> [#11876] Improve UX of Progress Bars

src/main/java/teammates/logic/core/FeedbackResponsesLogic.java, src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java, src/test/resources/data/FeedbackResponseVisibilityTest.json
Fixes #12029 
There are no logic handling questions with recipient type being `TEAM_EXCLUDING_SELF`. Therefore, additional logic is added to handle such situations in the method `isResponseVisibleForUser` in `FeedbackResponsesLogic`.
Relevant unit tests are also added.
=> [#12029] Fix team members cannot see responses received by team issue and add relevant tests

src/web/app/page.component.html
Fixes #12043
Added flex-nowrap bootstrap class so as to prevent unpredictable wrapping
Please find below screenshots for reference:
* Before flex-nowrap
* After flex-nowrap
=> [#12043] Navigation menu got collapsed

src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts, src/web/app/components/question-types/question-statistics/test-data/rubricQuestionResponses.json, src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
Fixes #12065
Fixes calculations for rubric statistics:
- Percentage average for each recipient is now calculated using the ratio of number of responses in each column to total number of responses.
- Overall weighted sum is calculated by summing the total chosen weight for each subquestion.
=> [#12065] Student viewing rubric results: average doesn't match

src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java, src/it/java/teammates/it/test/DbMigrationUtil.java, src/main/java/teammates/common/util/HibernateUtil.java
Part of #12048
Temporarily disable liquidate migrations until while the db schema is still changing rapidly.
=> [#12048] V9: temporarily disable liquibase migrations

src/main/java/teammates/storage/sqlentity/Notification.java
Create Notification entity to be used for PostgreSQL migration.
=> Create Notification Entity for PostgreSQL migration

src/main/java/teammates/storage/sqlapi/NotificationsDb.java, src/main/java/teammates/storage/sqlentity/Notification.java
Part of #12048
Create notification DB layer with CRUD. Minor update to notification sql entity to fix the wrong implementation.
=> Create notification DB layer for v9 migration

src/main/java/teammates/common/util/HibernateUtil.java, src/main/java/teammates/storage/sqlentity/Account.java, src/main/java/teammates/storage/sqlentity/Notification.java, src/main/java/teammates/storage/sqlentity/ReadNotification.java
Fixes #12048
- Add Account entity
- Add ReadNotification entity, which represents an association class between Account and Notification. Keeps track of which notifications have been read by which Accounts. Reason ManyToMany annotation was not used is that the association class has to have an extra readAt field that is not automatically populated if ManyToMany is used.
=> [#12048] Add Account Entity

src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java, src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/LogicStarter.java, src/main/java/teammates/sqllogic/core/NotificationsLogic.java, src/main/java/teammates/storage/sqlapi/NotificationsDb.java, src/main/java/teammates/storage/sqlentity/Notification.java, src/main/java/teammates/ui/output/NotificationData.java, src/main/java/teammates/ui/webapi/CreateNotificationAction.java, src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java
Create SQL logic for `CreateNotificationAction` and add relevant tests.
=> Create SQL logic for CreateNotificationAction and add relevant tests for v9 migration

src/main/java/teammates/common/datatransfer/InstructorPermissionRole.java, src/main/java/teammates/common/util/HibernateUtil.java, src/main/java/teammates/storage/sqlentity/Instructor.java, src/main/java/teammates/storage/sqlentity/Student.java, src/main/java/teammates/storage/sqlentity/User.java
**Outline**
This PR creates the new Student and Instructor Entity to be used for PostgreSQL Migration.
Below are the findings for the 4 available inheritance strategies in [Hibernate](https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#entity-inheritance):
**MappedSuperclass**
- Not scalable. If we use this, ancestors cannot contain associations with other entities
- Each DB table contains both base and sub classes properties
**Single Table**
- Performant (polymorphic query performance) as only 1 table needs to be accessed when querying parent entities. Best performance among the other strategies
- However, can no longer use NOT NULL constraints on subclass entity properties. I think this means that the identifying attributes of the …
=> Create Student, Instructor and User Entities for PostgreSQL Migration

src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java, src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java, src/main/java/teammates/storage/sqlapi/CoursesDb.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlapi/NotificationsDb.java, src/main/java/teammates/storage/sqlentity/Account.java, src/main/java/teammates/storage/sqlentity/BaseEntity.java, src/main/java/teammates/storage/sqlentity/Course.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/storage/sqlentity/Instructor.java, src/main/java/teammates/storage/sqlentity/Notification.java, src/main/java/teammates/storage/sqlentity/ReadNotification.java, src/main/java/teammates/storage/sqlentity/Student.java, src/main/java/teammates/storage/sqlentity/UsageStatistics.java, src/main/java/teammates/storage/sqlentity/User.java, src/main/java/teammates/ui/webapi/CreateCourseAction.java, src/main/java/teammates/ui/webapi/CreateNotificationAction.java, src/test/java/teammates/storage/sqlapi/CoursesDbTest.java, src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java, src/test/java/teammates/ui/webapi/CreateCourseActionTest.java, src/test/java/teammates/ui/webapi/CreateNotificationActionTest.java
Part of #12048
Periodic cleanup and refactor of v9-migration branch to keep things neat. Changes are as follows:
1. Remove builder pattern from entities.
- We do not have a very strong reason to continue to use the builder pattern in our entities. Blindly applying design patterns is itself an anti-pattern.
- Removal of this pattern allows us to more freely use whichever creational pattern best suits the needs of the particular entity in question.
- It is easy to refactor the code to support this pattern in the future, if desired. However, removing something that is already in place is will be much more difficult.
2. Standardise use of wrapper type Integer for ids
- These ids can be null at the point of creation (before they are inserted into the db). Wrapper types allow us to check for …
=> [#12048] V9: Cleanup and refactor

build.gradle, src/main/java/teammates/main/Application.java
Fixes #12021
Upgrade from Jetty 9 to Jetty 10
- Refactored deprecated class in Jetty 9
- The Jetty Logging facade is deprecated and moved to Slf4j instead, using the standard `jetty-sl4fj-impl `implement which equivalent to the previous `StdError` facade implementation
- Remove deprecated `ClassList` configuration as look like it no longer needed
- Move `LifeCycle.Listener` to an object and add to server as `EventListerner` instead as there is no `addLifeCycleListener` anymore.
=> [#12021] Update Jetty library to 10 or 11

src/web/app/components/feedback-path-panel/feedback-path-panel.component.html, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-text-with-info/question-text-with-info.component.scss, src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap, src/web/app/components/sessions-table/sessions-table.component.html, src/web/app/page.component.scss, src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html, src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.scss, src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss, src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html, src/web/app/pages-monitoring/logs-page/logs-page.component.scss, src/web/app/pages-monitoring/usage-stats-page/usage-statistics-page.component.scss, src/web/app/pages-static/about-page/about-page.component.scss, src/web/app/pages-static/request-page/request-page.component.html
Sub-issue: [Fix margins on mobile for all content](https://github.com/TEAMMATES/teammates/projects/16#card-88044534)
Add padding for main content to combat the negative margins of `row`.
Main issues were that of table overflows, so I added the `table-responsive` classes and removed some classes that were causing overflow of content from the `div` + leaving some blank spaces at the side.
=> [#12081] User-friendliness: Fix margins on mobile

src/it/java/teammates/it/storage/sqlapi/UsageStatisticsDbIT.java, src/main/java/teammates/common/util/HibernateUtil.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/LogicStarter.java, src/main/java/teammates/sqllogic/core/UsageStatisticsLogic.java, src/main/java/teammates/storage/sqlapi/UsageStatisticsDb.java, src/main/java/teammates/storage/sqlentity/UsageStatistics.java, src/main/java/teammates/ui/output/UsageStatisticsData.java, src/main/java/teammates/ui/output/UsageStatisticsRangeData.java, src/main/java/teammates/ui/webapi/GetUsageStatisticsAction.java, src/test/java/teammates/storage/sqlapi/UsageStatisticsDbTest.java, src/test/java/teammates/ui/webapi/GetUsageStatisticsActionTest.java
Part of #12048
1. Update the action to include entities from sql db
2. Update `UsageStatisticsRangeData` to support mapping from the sql entities
=> Update GetUsageStatisticsAction to include SQL entities

src/web/app/page.component.html, src/web/app/page.component.scss
Sub-issue: [Header: Make dropdowns interactable](https://github.com/TEAMMATES/teammates/projects/16#card-88044576)
Dropdown unable to be focused:
- Problem: Dropdown was not focusable since there was no `href` tag. 
- Solution: Add `tabindex="0"` tag
Symmetric margins:
- Problem: There was `min-width` specified by Bootstrap's `dropdown-menu`, which forced the dropdown list to be wider than it needs to be.
- Solution: Override `min-width` with `0px`.
=> [#12081] User-friendliness: Make header dropdowns focusable

.github/workflows/axe.yml, .github/workflows/e2e.yml, src/web/app/page.component.html, src/web/app/page.component.scss, src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html, src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.html, src/web/app/pages-help/student-help-page/student-help-page.component.html, src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap, src/web/app/pages-session/session-result-page/session-result-page.component.html, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap, src/web/app/pages-session/session-submission-page/session-submission-page.component.html, src/web/app/pages-static/contact-page/contact-page.component.html, src/web/app/pages-static/features-page/features-page.component.html, src/web/app/pages-static/index-page/index-page.component.html, src/web/app/pages-static/request-page/request-page.component.html, src/web/app/pages-static/terms-page/terms-page.component.html
Part of #12081.
Refactored `page.component.html` so that all page content is wrapped in `<main>` tag.
Other miscellaneous fixes include:
- Removing trailing spaces in github workflow files
- Removing unnecessary `<div>` tags in `page.component.html`
- Making minor changes to wording (e.g. `login` used as noun, `log in` used as verb)
=> [#12081] Tag all TEAMMATES pages with <main>

src/it/java/teammates/it/storage/sqlapi/AccountRequestDbIT.java, src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java, src/main/java/teammates/common/util/HibernateUtil.java, src/main/java/teammates/storage/sqlapi/AccountRequestDb.java, src/main/java/teammates/storage/sqlapi/CoursesDb.java, src/main/java/teammates/storage/sqlapi/EntitiesDb.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlapi/NotificationsDb.java, src/main/java/teammates/storage/sqlapi/UsageStatisticsDb.java, src/main/java/teammates/ui/servlets/WebApiServlet.java, src/main/java/teammates/ui/webapi/CreateCourseAction.java, src/test/java/teammates/storage/sqlapi/AccountRequestDbTest.java, src/test/java/teammates/storage/sqlapi/CoursesDbTest.java, src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java, src/test/java/teammates/storage/sqlapi/UsageStatisticsDbTest.java, src/test/java/teammates/ui/servlets/WebApiServletTest.java
- Move hibernate related methods to HibernateUtil. Extra level of indirection to facilitate testing, see "Don't mock what you don't own" heuristic.
- Change parameters of remove in db layer from the entities id/natural key to the entity itself.
- Updated tests to use new mocks.
- Remove unnecessary methods in db layer.
=> [#12048] Refactor v9 unit tests

src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts, src/web/app/components/question-types/question-statistics/test-data/rubricQuestionResponses.json
Fixes #12115
- Issue (likely) caused by recipient (seems to be used interchangeably with recipient name) being identical.
- In this case, both recipients are counted as the same person for the purpose of displaying per recipient stats.
- Fix: Use email as key of perRecipientStats when available. When not available, default to using recipient.
=> [#12115] Instructor viewing results of rubric questions: some students not shown in the stats table

src/main/java/teammates/storage/sqlapi/EntitiesDb.java, src/main/java/teammates/storage/sqlapi/UserDb.java, src/main/java/teammates/storage/sqlapi/UsersDb.java, src/main/java/teammates/storage/sqlentity/Instructor.java, src/main/java/teammates/storage/sqlentity/Student.java, src/main/java/teammates/storage/sqlentity/User.java
The User DB layer supports CRUD ops for both Instructor and Student entities.
To add tests in the future.
=> Create User DB Layer for v9 Migration

src/web/app/components/timepicker/timepicker.component.ts, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
Fixes #12131
Error in logic here:
```
(t.hour < this.minTime?.hour || t.minute < this.minTime?.minute)
```
This does not correctly check that `currentTime` is before `minTime`.
=> [#12131] Instructor edit session times: timing restrictions are not as expected

src/it/java/teammates/it/sqllogic/core/NotificationsLogicIT.java, src/it/java/teammates/it/sqllogic/core/package-info.java, src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java, src/it/resources/testng-it.xml, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/NotificationsLogic.java, src/main/java/teammates/storage/sqlapi/AccountRequestDb.java, src/main/java/teammates/storage/sqlapi/AccountsDb.java, src/main/java/teammates/storage/sqlapi/CoursesDb.java, src/main/java/teammates/storage/sqlapi/DeadlineExtensionsDb.java, src/main/java/teammates/storage/sqlapi/EntitiesDb.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlapi/NotificationsDb.java, src/main/java/teammates/storage/sqlapi/UsersDb.java, src/main/java/teammates/ui/webapi/UpdateNotificationAction.java, src/test/java/teammates/sqllogic/core/NotificationsLogicTest.java, src/test/java/teammates/sqllogic/core/package-info.java, src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java, src/test/java/teammates/ui/webapi/UpdateNotificationActionTest.java, src/test/resources/testng-component.xml
Create SQL logic for `UpdateNotificationAction` and add relevant tests
=> Create SQL logic for UpdateNotificationAction and add relevant tests for v9 migration

src/main/java/teammates/common/util/HibernateUtil.java, src/main/java/teammates/storage/sqlentity/BaseEntity.java, src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java, src/main/java/teammates/storage/sqlentity/FeedbackResponse.java, src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackNumericalScaleResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackTextResponse.java, src/main/java/teammates/storage/sqlentity/responses/package-info.java
- Created the `FeedbackResponse` and `FeedbackResponseComment` entities.
- For `FeedbackResponse`, `answer` is question specific, and thus placed into subtypes, similar to how it's done for `FeedbackQuestion`.
- Moved `FeedbackParticipantTypeListConverter` from `FeedbackQuestion` into `BaseEntity` as its used by `FeedbackResponseComment`.
- Added OneToMany association from `FeedbackQuestion` to `FeedbackResponse`
=> Create FeedbackResponse and FeedbackResponseComment entities

src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java, src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap, src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap, src/web/app/components/question-text-with-info/question-text-with-info.component.html, src/web/app/components/question-text-with-info/question-text-with-info.component.scss, src/web/app/components/question-text-with-info/question-text-with-info.component.spec.ts
Sub-issue: [Feedback sessions results page: Landmark questions](https://github.com/TEAMMATES/teammates/projects/16#card-88047383)
1. Landmark questions
- Turn `span` element into `h3` element, so that screen reader can pick them up for more accessible navigation. 
- Add CSS `.question-number` to make `h3` element look the same as before.
3. Make [more] button focusable
- Add `tabindex="0"` tag
=> [#12081] User-friendliness: Landmark questions in feedback sessions results page

src/web/app/components/feedback-path-panel/feedback-path-panel.component.html, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-submission-form/question-submission-form-model.ts, src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-submission-form/question-submission-form.component.scss, src/web/app/components/question-submission-form/question-submission-form.component.spec.ts, src/web/app/components/question-submission-form/question-submission-form.component.ts, src/web/app/components/question-submission-form/question-submission-form.module.ts, src/web/app/components/question-types/question-edit-answer-form/text-question-edit-answer-form.component.html, src/web/app/page.component.scss, src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap, src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts, src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Sub-issue: [Landmark questions](https://github.com/TEAMMATES/teammates/projects/16#card-88047383)
Landmark questions by making question titles headers (`h2`). This allows the screenreader to pick them up, and in turn enables easier navigation up and down the page. Also added CSS for the `#question-details` to make it look the same as before (i.e. like a `span` instead of a `h2`).
Made questions collapsible by introducing a `isTabExpanded` field to the model. It is set to `true` by default. The mechanics are similar to collapsible questions in other pages.
Changed `div` to a `button`, which is more WCAG compliant (according to [this](https://stackoverflow.com/questions/32659099/making-a-clickable-div-accessible-through-tab-structure)) and immediately …
=> [#12081] Landmark questions in submit feedback page

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-submission-form/question-submission-form.component.scss, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue: [Submit feedback page: Fix text wrap of "Evaluee/Recipient" on mobile for all questions](https://github.com/TEAMMATES/teammates/projects/16#card-88047608)
- Problem: Text was wrapped due to `col-2` bootstrap styling.
- Solution: Change to use `col` instead
=> [#12081] User-friendliness: Fix evaluee/recipient mobile text wrap

src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Fixes #12145 
The value was hidden at screen widths around 769 to 800+ px due to the `col-md-2` class on the surrounding `div`. Made a simple fix to change the class to `col-md-3`. Comparison at screen width of 800 px:
=> Resolve width issue for num scale question

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-types/question-edit-answer-form/__snapshots__/mcq-question-edit-answer-form.component.spec.ts.snap, src/web/app/components/question-types/question-edit-answer-form/msq-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/msq-question-edit-answer-form.component.ts, src/web/app/components/question-types/question-edit-answer-form/question-edit-answer-form.ts, src/web/app/components/question-types/question-edit-answer-form/text-question-edit-answer-form.component.ts, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue: [Add label to MCQ (multiple) question](https://github.com/TEAMMATES/teammates/projects/16#card-88051035)
Similar to [this PR](https://github.com/TEAMMATES/teammates/pull/12140).
=> [#12081] User-friendliness: Add labels for MSQ checkboxes

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue: [Submit feedback page: numerical-scale question](https://github.com/TEAMMATES/teammates/projects/16#card-88051611)
- Similar to https://github.com/TEAMMATES/teammates/pull/12144
=> [#12081] User-friendliness: Add labels for numerical scale questions

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.ts
Sub-issue [Add labels to distribute points (options) question](https://github.com/TEAMMATES/teammates/projects/16#card-88052106)
Similar to previous issues for adding labels, except I added an extra function to get the `aria-label` for each recipient's option. The function takes in the `option` and builds on the `aria-label` returned by the existing `getAriaLabel()` function.
Options are grouped by recipients, which requires a surrounding `div` around all the options (else they won't be grouped together).
=> [#12081] User-friendliness: Add labels and groups to distribute points (options) question

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-submission-form/question-submission-form.component.ts, src/web/app/components/question-types/question-edit-answer-form/constsum-recipients-question-edit-answer-form.component.html, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue: [Submit feedback page: distribute points (recipients) question](https://github.com/TEAMMATES/teammates/projects/16#card-88052150)
- Add labels for distribute points (recipients) question
- Solution: Similar to #12144 
- Fix dropdown
- Problem: 
- I observed that the dropdown fails for all questions with constraints
- I'm not entirely sure, but I suspect that the `QuestionSubmissionFormComponent::updateValidity` may be the issue here, since we always emit to the parent component a model with `isTabExpanded: true`? And due to the 2-way binding, the `@Input formModel` will always receive the model from the parent with `isTabExpanded: true`. 
- However, with the 2-way binding, why don't the other questions without constraints face the same …
=> [#12081] User-friendliness: Add labels for distribute points by recipient questions

src/it/java/teammates/it/sqllogic/core/NotificationsLogicIT.java, src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java, src/main/java/teammates/storage/sqlapi/AccountsDb.java, src/main/java/teammates/storage/sqlapi/DeadlineExtensionsDb.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlapi/UsersDb.java, src/main/java/teammates/storage/sqlentity/Account.java, src/main/java/teammates/storage/sqlentity/AccountRequest.java, src/main/java/teammates/storage/sqlentity/DeadlineExtension.java, src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java, src/main/java/teammates/storage/sqlentity/FeedbackResponse.java, src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/storage/sqlentity/Notification.java, src/main/java/teammates/storage/sqlentity/ReadNotification.java, src/main/java/teammates/storage/sqlentity/Section.java, src/main/java/teammates/storage/sqlentity/Team.java, src/main/java/teammates/storage/sqlentity/UsageStatistics.java, src/main/java/teammates/storage/sqlentity/User.java, src/main/java/teammates/ui/output/NotificationData.java, src/test/java/teammates/sqllogic/core/NotificationsLogicTest.java, src/test/java/teammates/storage/sqlapi/AccountsDbTest.java, src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java
Part of #12048
**Rationale**
1) Consistency, some entities are using ID, some UUID.
2) Integer IDs are generated only when entity is persisted into db. This means that entity can be in two states, one where ID is null, another where ID is present. This leads to the following issues.
- Could lead to subtle bugs that might not be easily caught if ID field is used before ID is generated.
- Higher friction for new developers. This way, developers do not need to fully understand intricacies of Hibernate before they can start modifying entities. From our experience, the main issues so far have been to do with this. e.g. need to flush because ID is null, entity in detached rather than transient state because ID was set manually etc. Moving completely to UUID removes all these issues (and their …
=> [#12048] Update entities to use UUID instead of Integer as ID

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.ts, src/web/app/components/question-types/question-instruction/contribution-question-instruction.component.html, src/web/app/components/question-types/question-instruction/contribution-question-instruction.component.ts, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue: [Labels and "more info" button for team contribution question](https://github.com/TEAMMATES/teammates/projects/16#card-88052182)
Add labels similar to previous question types. Also changed the position of the "more info" button as I think that it makes more sense to come under question instructions. In addition, since `tabindex` is a global attribute, to allow for the button to come first while in its current position, there would be a need to add/change the `tabindex` of many elements on the page. Moving the "more info" button solves this problem.
I also altered the CSS a little to take into account the move. See below for a comparison.
Previously (v4):
After the change:
=> User-friendliness: Add labels and change "more info" button for team contribution questions

src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java, src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java, src/main/java/teammates/sqllogic/core/UsersLogic.java, src/main/java/teammates/storage/sqlapi/UsersDb.java, src/main/java/teammates/storage/sqlentity/BaseEntity.java, src/main/java/teammates/storage/sqlentity/Instructor.java, src/main/java/teammates/storage/sqlentity/Student.java, src/main/java/teammates/storage/sqlentity/User.java, src/test/java/teammates/storage/sqlapi/UsersDbTest.java
This PR has the following changes:
- Add db and user logic for get instructor and student
- Add unit and integration tests
- Update related entities
=> [#12048] Create SQL Logic for Get User Actions

src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
Fixes #12116 
Added a space in the beginning of the _Exclude self evaluation_ text in `rubric-question-statistics.component.html`
=> [#12116] Instructor viewing results of rubric questions: missing space after checkbox

src/main/java/teammates/common/util/HibernateUtil.java, src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java, src/main/java/teammates/storage/sqlapi/DeadlineExtensionsDb.java, src/main/java/teammates/storage/sqlapi/UsageStatisticsDb.java, src/main/java/teammates/storage/sqlapi/UsersDb.java
This PR consists of the following changes:
- Updated access visibility for `getSessionFactory` and `getCurrentSession` in HibernateUtils to be `private`
- Introduce `getCriteriaBuilder` and `createQuery` to support files that previously used the above `public` methods
=> [#12048] Update access visibility of HibernateUtils utility methods to private

src/web/app/page.component.html, src/web/app/page.component.scss, src/web/styles.scss
Part of #12081
For header, overrode default Bootstrap nav link colours to increase contrast, and modified text colour accordingly for dropdowns. For footer, made colour of text consistent with header.
Also removed the `text-decoration: none` style override on links given accessibility best practices.
Before change:
After change:
=> [#12081] Modify header and footer colours

src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.html, src/web/app/components/sortable-table/sortable-table.component.html, src/web/app/components/sortable-table/sortable-table.component.scss, src/web/app/components/sortable-table/sortable-table.component.ts, src/web/app/pages-instructor/instructor-student-activity-logs/__snapshots__/instructor-student-activity-logs.component.spec.ts.snap
Sub-issue: [View responses page: numerical scale question](https://github.com/TEAMMATES/teammates/projects/16#card-88067825)
Added a 20% width to the sort image so that it doesn't overflow into the next table cell on mobile. For the table headers, added an `aria-sort` attribute to the header so that the screen reader picks up on whether or not it is sorted. Further enclosed the text and sort image in a button so users can tab to it and know that it is clickable.
Also removed a class so that the text above the table doesn't break into 2 lines if there's no need for it.
**Notes**
The screen reader does not convey changes to the `aria-sort` value if it changes while the element is in focus. It also does not convey the `none` `aria-sort` value by …
=> [#12081] User-friendliness: Fix numerical scale question table in view responses page

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-submission-form/question-submission-form.component.scss
Sub-issue: [Dropdown component text overlap with caret](https://github.com/TEAMMATES/teammates/projects/16#card-88331097)
Currently, the dropdown option text overlaps with the caret on the right if it's too long. `<select>` components in other pages mostly only have `.form-control` and `.form-select` classes and don't have the additional `.col` class. Hence, I removed the `.col` class which fixed the problem as it was overriding the padding, in particular the padding on the right. I also added a `.select-flex` class to add back the `flex` properties of the `.col` class so that the dropdown still looks the same as before. Example:
=> [#12081] User-friendliness: Fix dropdown caret overlap

src/e2e/java/teammates/e2e/cases/FeedbackResultsPageE2ETest.java, src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java, src/main/java/teammates/ui/output/SessionResultsData.java, src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts, src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html, src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts
Fixes #12182
Fixes #12068
See https://github.com/TEAMMATES/teammates/issues/12182#issuecomment-1462227482 for details of fix. The results for weighted rubric questions is now identical to that of non-weighted rubric questions for students (see below screenshot). Instructors are still able to see the detailed per recipient stats.
=> [#12182][#12068] student viewing results: the spinner keeps going until the user clicks on the page

src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
Fixes #12067 
Added a space between the heading "Response Summary (of received responses)" and the info icon.
=> [#12067] Inconsistent spacing in headings of rubric question statistics

src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java, src/main/java/teammates/sqllogic/core/LogicStarter.java, src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java
Create `FeedbackResponseCommentsDb` and `FeedbackResponseCommentsLogic`
=> Create feedback response question comment db and logic layer

src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap, src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap, src/web/app/components/question-text-with-info/question-text-with-info.component.html, src/web/app/components/question-text-with-info/question-text-with-info.component.scss
Sub-issue [View responses page: Modify header of each card to display content in column instead of row format on mobile](https://github.com/TEAMMATES/teammates/projects/16#card-88348625)
- Use `flex-column` by default to make header display content in column (Mobile)
- Use `flex-sm-row` to make header display content in row (Desktop)
=> [#12081] User-friendliness: Display card header content in column format for mobile

src/it/java/teammates/it/storage/sqlapi/FeedbackSessionsDbIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/ui/webapi/Action.java
- Make `(courseId, feedbackSessionName)` in `FeedbackSession` entity to be unique for existing APIs related to get feedback session by feedback session name and course id
- Create `FeedbackSession` methods for `FeedbackQuestion` use
=> [#12048] Update FeedbackSession entity and add methods for FeedbackQuestion use

src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.html, src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.ts, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue [Submit feedback response page: rubric question](https://github.com/TEAMMATES/teammates/projects/16#card-88416065)
- Problem: Nested elements inside `<td>` triggers click event twice due to bubbling
- Solution:
- Segregate out nested elements
- Generate unique id for each table cell's input, so that the label can explicitly label its corresponding input
=> [#12081] User-friendliness: Make submit feedback rubric table cell clickable

.github/workflows/pr.yml
Fixes #12194
Part of #11383
Adds simple Github Actions workflow using [actions/github-script](https://github.com/actions/github-script) to check PRs. The bot currently checks for the following:
- Title: starts with issue number in square brackets, followed by a space
- Description: contains either "Fixes" or "Part of", followed by the issue number. Only "Fixes" is checked since it is the keyword used in our PR template.
More checks can be added down the line as and when needed. The bot also only checks PRs that are newly opened/reopened, so as to avoid spam.
=> [#12194] Add simple workflow to vet pull requests

src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java, src/web/app/components/feedback-path-panel/feedback-path-panel.component.html, src/web/app/components/feedback-path-panel/feedback-path-panel.component.scss, src/web/app/components/feedback-path-panel/feedback-path-panel.component.ts, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Sub-issue: [Fix feedback path dropdown](https://github.com/TEAMMATES/teammates/projects/16#card-88348663)
Changed second dropdown to be below instead of to the side. Keeps track of which submenus are open via a map. Also added buttons for accessibility and added the `text-wrap` class to resolve overflow issues.
For E2E tests, changed the options to click on the button.
=> [#12081] User-friendliness: Fix feedback path dropdown

.github/workflows/pr.yml
Part of #11383
The PR checking workflow is currently running into permissions issues. This is because Github provides read-only tokens to all forks for security reasons.
To fix this, the workflow trigger has been changed from `pull_request` to `pull_request_target`, so that the workflow is run on the target branch `master` where write permissions can be provided. Permissions have been limited to write permissions for PRs only for security reasons.
Note that this workflow will now only run after the changes are merged into `master`, hence testing of the workflow is not possible in this PR. I have opened a PR in my own fork to test this fix, at https://github.com/zhaojj2209/teammates/pull/39.
In the future, if I have the capacity, I may expand this workflow to include other actions such as …
=> [#11383] Fix PR checking workflow permissions

src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/visibility-panel/visibility-panel.component.html, src/web/app/components/visibility-panel/visibility-panel.component.scss, src/web/app/components/visibility-panel/visibility-panel.component.ts, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Sub-issue: [Fix custom visibility options](https://github.com/TEAMMATES/teammates/projects/16#card-88348707)
Added `aria-label`s to the table and checkboxes, and changed the dropdown divider to `aria-hidden`. Also changed the dropdown items to be buttons, which fixed the screen reader issue.
The `getCheckboxAriaLabel` function looks rather inelegant to me. I'm considering moving most of the logic to 2 `Map` variables outside of the function... would that be better?
Edit: Thought about it and I think this improves understanding of the code, so I've made the change
=> [#12081] User-friendliness: Fix custom visibility options

src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/ui/output/FeedbackSessionData.java, src/main/java/teammates/ui/output/FeedbackSessionSubmissionStatus.java, src/main/java/teammates/ui/webapi/GetFeedbackSessionAction.java, src/test/java/teammates/sqlui/webapi/GetFeedbackSessionActionTest.java, src/test/java/teammates/ui/webapi/GetFeedbackSessionsActionTest.java
Since the new FeedbackSession no longer stores all student deadlines but rather Deadline Extensions, to deal with a specific user's feedback session deadline: 
* i perform a search to find if the user has a deadline extension. 
* if there is, then return the extended deadline. Else return the default endtime for the feedback session. 
Currently using the getDeadlineForUser method for DeadlineExtensions to get the specific FeedbackSessionData for a user.
=> [#12048] Migrate GetFeedbackSessionAction

src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.component.html, src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.component.scss, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Sub-issue: [Remove empty group between "[Optional]" and "Description" for question description](https://github.com/TEAMMATES/teammates/projects/16#card-88348922)
The `<br/>` was causing the screen reader to treat the "[Optional] Description" text as 2 separate elements. Tried several solutions found online, but none seemed to work.
Hence, I just removed the `<br>` in favour of `<pre>` and added some styles to make it look the same as before.
=> [#12081] User-friendliness: Fix screen reader issue for question description

src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Sub-issue: [Add label to recommended words input](https://github.com/TEAMMATES/teammates/projects/16#card-88348675)
Removed the `<a>` tag as it was causing the screen reader to read the text twice (and I don't think there's a use for it).
Wrapped the recommended length input text in a label and rephrased it slightly so that it flows better for the screen reader. Also added an `aria-label` to the input.
=> [#12081] User-friendliness: Add labels to input for essay question (instructor edit sessions page)

src/it/java/teammates/it/ui/webapi/GetInstructorsActionIT.java, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/ui/output/InstructorsData.java, src/main/java/teammates/ui/webapi/GetInstructorsAction.java, src/test/java/teammates/ui/webapi/GetInstructorsActionTest.java
**Things to highlight**
Not sure if it is the best way to do this (similar to PR #12211):
```java
EntitysData data = new EntitysData();
List<EntityData> entityDataList = entitysForCourse
.stream()
.map(EntityData::new)
.collect(Collectors.toList());
data.setEntitys(entityDataList);
```
As EntitysData class current constructor with EntityAttribute will cause a type erasure problem when adding another constructor taking in a List of different data type.
=> [#12048] Migrate Get Instructors Action

src/e2e/java/teammates/e2e/pageobjects/Browser.java
Part of #12035
Currently, all E2E tests fail when using ChromeDriver due to an `Unable to establish websocket connection` error. This PR fixes this error using a [fix found on StackOverflow](https://stackoverflow.com/questions/75680149/unable-to-establish-websocket-connection).
Since the cross-browser workflow is only run on push to the master/release branches, I've tested the workflow on my own fork instead. [Link to workflow](https://github.com/zhaojj2209/teammates/actions/runs/4436835989/jobs/7785762463)
Note that this PR only fixes ChromeDriver setup so that E2E tests can be run using ChromeDriver. A portion of tests are still failing due to timeouts or otherwise (even though they pass on Firefox).
=> [#12035] Fix ChromeDriver setup for E2E tests

src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.scss, src/web/styles.scss
Sub-issue [Minimise margins for modals on mobile (e.g. copy questions modal](https://github.com/TEAMMATES/teammates/projects/16#card-88348641)
- Set width for modal to `95vw` for mobile
- Tested for following modals:
- `comment-table-modal`
- `copy-course-modal`
- `copy-session-modal`
- `extension-confirm-modal`
- `resend-results-link-to-respondants-modal`
- `send-reminders-to-respondants-modal`
- `copy-instructors-from-other-courses-modal`
- `view-role-privileges-modal`
- `copy-questions-from-other-sessions-modal`
- `template-question-modal`
- `individual-extension-date-modal`
- `copy-from-other-sessions-modal`
- `session-permanent-deletion-confirm-modal`
- `sessions-permanent-deletion-confirm-modal`
- `saving-complete-modal-component`
=> [#12081] Minimise modal margin for mobile

src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-edit-form/question-edit-form.component.html, src/web/app/components/question-edit-form/question-edit-form.component.scss, src/web/app/components/visibility-panel/visibility-panel.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Part of #12081  
Sub-issue [Instructor edit sessions page: modify question headers](https://github.com/TEAMMATES/teammates/projects/16#card-88348694)
- Fixed question number to use `<h2>`
- Applied `flex-row` and `flex-col` to display in columns when in mobile and in rows when in desktop
- Fixed question header to use `<button>` for tab interaction
=> [#12081] Modify question headers for instructor 

src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html, src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts, src/web/styles.scss
Fixes #12222
To resolve this issue, I use to calculate the y coordinate of the section and I used the scrollTo function directly to do it.
The problem was in these two lines :
`el.scrollIntoView();
window.scrollBy(0, -50);`
The second instruction is not waiting for the first one to finish and do the scroll by -50px.
I removed the '#helpPage' because it is not necessary to get all the children and then search for the section using the id.
=> [#12222] Instructor help page: Page not scrolling to the right section

src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts, src/web/styles.scss
Fixes #12120
First of all, I made changes to the `ngAfterViewInit()` function to accommodate the `section` and `questionId` anchors:
- I introduced a `target` variable, which identifies the more precise anchor between `section` and `questionId`
- if the anchor has a `questionId`, the corresponding question tab is expanded directly, and not in `scrollTo()`, because we don't need to do this if we only have `section` in the URL parameters
- the call to `scrollTo()` is also modified to handle the case where we only have `section` in the URL parameters, without a `questionId`
I also changed the `scrollOffset` in `scrollTo()` to 60, because I think it feels better. However, feel free to undo this change if you prefer the previous value.
Finally, I added the changes …
=> [#12120] Instructor help page: page not scrolling to content when anchor links used

src/it/resources/data/DataBundleLogicIT.json, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/storage/sqlentity/FeedbackSession.java
Part of #12048
Required because emails are sent when sessions are published manually.
Without the flag, it will be sent again when cron job is run.
=> [#12048] Add published email sent field to feedback sessions

src/web/app/components/feedback-path-panel/feedback-path-panel.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Sub-issue: [Change feedback path dropdowns to column format on mobile](https://github.com/TEAMMATES/teammates/projects/16#card-88540819)
Added breakpoints to `.col-6` classes. Also added a bottom margin for mobile.
=> [#12081] User-friendliness: Change feedback path dropdowns to column format on mobile

src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html, src/web/app/components/question-types/question-edit-details-form/contribution-question-edit-details-form.component.html, src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.html
Sub-issues: [Add labels for team contribution question](https://github.com/TEAMMATES/teammates/projects/16#card-88348684)
[Add labels for distribute points (recipients) question](https://github.com/TEAMMATES/teammates/projects/16#card-88348683)
[Add labels for numerical scale question](https://github.com/TEAMMATES/teammates/projects/16#card-88348680)
Usual `aria-label` changes for distribute points (recipients) question and numerical scale question. Also changed "X" to "times" for screen reader clarity. Shifted the `<label>` tag down for team contribution question to avoid screen reader reading the label twice. Unfortunately, this shift also means that the `<code>` tag has to be removed (extra tag in label = screen reader reads twice).
=> [#12081] User-friendliness: Add labels to instructor edit sessions page questions

src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/visibility-panel/visibility-panel.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Sub-issue: [Fix overflow on mobile for visibility dropdown](https://github.com/TEAMMATES/teammates/projects/16#card-88540814)
Add `.text-wrap` classes to the relevant dropdown items
=> [#12081] User-friendliness: Fix visibility dropdown overflow

src/web/app/components/datepicker/datepicker.component.html, src/web/app/components/datepicker/datepicker.component.ts, src/web/app/components/session-edit-form/session-edit-form.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Calendar button is now disabled when the Instructor is out of the editing view for Sessions
Author: pgfrank1
Fixes #12238 
I updated the datepicker component to use isDisabled instead of disabled to keep consistency with other components. I then applied that change to the button component so the calendar cannot be opened.
=> [#12238] Instructors editing session dates: disable calendar popup if the form is not in edit mode

src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-edit-form/question-edit-form.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Sub-issue [Instructor edit sessions page: shift buttons from rightmost column to bottommost row on mobile](https://github.com/TEAMMATES/teammates/projects/16#card-88612309)
- Applied `flex-row` and `flex-col` to display in columns when in mobile and in rows when in desktop
=> [#12081] Wrap buttons vertically in mobile for instructor edit sessions page

src/web/app/pages-static/about-page/about-page.component.html
Fixes  #12264  
Outline of Solution :
removed the space from the link and added it to the span tag.
=> [#12264] fix/removed extra space form links

src/it/java/teammates/it/sqllogic/core/DataBundleLogicIT.java, src/it/java/teammates/it/storage/sqlapi/FeedbackResponseCommentsDbIT.java, src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java, src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java, src/it/resources/data/DataBundleLogicIT.json, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/common/util/JsonUtils.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/DataBundleLogic.java, src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java, src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java, src/main/java/teammates/sqllogic/core/LogicStarter.java, src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java, src/main/java/teammates/storage/sqlapi/FeedbackResponsesDb.java, src/main/java/teammates/storage/sqlentity/FeedbackResponse.java, src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackConstantSumResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackContributionResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackMcqResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackMsqResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackNumericalScaleResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackRankOptionsResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackRankRecipientsResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackRubricResponse.java, src/main/java/teammates/storage/sqlentity/responses/FeedbackTextResponse.java, src/main/java/teammates/ui/output/FeedbackResponseCommentData.java, src/main/java/teammates/ui/output/FeedbackResponseData.java, src/main/java/teammates/ui/webapi/GetFeedbackQuestionRecipientsAction.java, src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java, src/test/java/teammates/ui/webapi/GetFeedbackResponsesActionTest.java
- Created factory method for `FeedbackResponse`, similar to `FeedbackQuestion`
- Changed `receiver` to `recipient` and `receiverSection` to `recipientSection` in `FeedbackResponse` and `FeedbackResponseComment`
- Added `FeedbackResponse` and `FeedbackResponseComments` to data bundle
- Added `getFeedbackResponsesFromGiverForQuestion` in `FeedbackResponsesDb`
- Added  `getFeedbackResponseCommentForResponseFromParticipant` in `FeedbackresponseCommentsDb`
=> [#12048] Migrate get feedback responses action

src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
=> [#12278] Instructor home page: Fix alignment of "Add New Course" button

src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/UsersLogic.java, src/main/java/teammates/ui/webapi/GenerateEmailAction.java, src/main/java/teammates/ui/webapi/SendJoinReminderEmailAction.java, src/test/java/teammates/sqllogic/core/UsersLogicTest.java, src/test/java/teammates/sqlui/webapi/GenerateEmailActionTest.java, src/test/java/teammates/sqlui/webapi/SendJoinReminderEmailActionTest.java
* Migrate `GenerateEmailAction` and `SendJoinReminderEmailAction` with minimal unit tests.
* Migrated `getUnregisteredStudentsForCourse` method (in logic layer).
=> [#12048] Migrate *EmailAction classes.

src/it/java/teammates/it/sqllogic/core/UsersLogicIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/UsersLogic.java, src/main/java/teammates/ui/webapi/UpdateInstructorPrivilegeAction.java, src/test/java/teammates/sqllogic/core/UsersLogicTest.java, src/test/java/teammates/sqlui/webapi/UpdateInstructorPrivilegeActionTest.java, src/test/java/teammates/ui/webapi/UpdateInstructorPrivilegeActionTest.java
As per title.
The old Datastore approach retrieves the `InstructorAttributes`, sets the new privileges, calls `updateToEnsureValidityOfInstructorsForTheCourse` to update the privileges again if needed, then calls `updateInstructor` to actually perform the update. Now that we are using the `Instructor` entity directly, it should be sufficient to simply set the new privileges and call `updateToEnsureValidityOfInstructorsForTheCourse` on the entity directly.
Migrated most tests for now, can remove if needed for easier review.
=> [#12048] Migrate UpdateInstructorPrivilegeAction

src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/__snapshots__/copy-questions-from-other-sessions-modal.component.spec.ts.snap, src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.html, src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.scss
Fixes #12335 Fix copy questions modal checkbox
=> [#12335] fix copy questions modal checkbox

src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/__snapshots__/copy-instructors-from-other-courses-modal.component.spec.ts.snap, src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.html
=> [#12334] Instructor courses page: fix copy instructors from other courses modal checkbox

src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.scss
Fixes #12344
Fixes mobile margin by only applying width constraint on media 768 pixels or wider.
(ready for review)
Desktop View:
Mobile View:
=> [#12344] Instructor courses page: fix margin of copy instructors from other courses modal on mobile

src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap, src/web/app/pages-monitoring/logs-page/logs-page.component.html, src/web/app/pages-monitoring/usage-stats-page/__snapshots__/usage-statistics-page.component.spec.ts.snap, src/web/app/pages-monitoring/usage-stats-page/usage-statistics-page.component.html
Fixes #12289
I made changes to the following files so that the hour selection is besides the date picker instead of below on mobiles:
- [logs-page.component.html](https://github.com/TEAMMATES/teammates/compare/master...aorlandou:teammates:team-mast?expand=1#diff-ee2477d2f4c61cebb26a8abf3bb8fb690a22ddff913400dfd322f51a01db0a80)
- [usage-statistics-page.component.html](https://github.com/TEAMMATES/teammates/compare/master...aorlandou:teammates:team-mast?expand=1#diff-7f560ba4f7dc66e249b704cb1f6a492222d8dac0fb4fa026a836241c18cff07c)
**Logs page after the changes**
**Usage Statistics page after the changes**
=> [#12289] Usage statistics and logs page: Improve date/time input on mobile

src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
Fixes #12333
Fixed the issue by merging the two tags into one 'div' tag. 
Removed the unnecessary classes and fixed style by using Bootstrap 
("fw-bold fs-5" for making the text bold and changing the font size).
Here is the updated UI
=> [#12333] Instructor students page: accessibility issue for course summary headers

src/web/app/components/feedback-path-panel/feedback-path-panel.component.html, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Fixes #12399 
Fix the issue by removing "overflow-scroll" which was the reason for the unnecessary scrollbars when an instructor is editing a question of an existing session (feedback path)
Here is the updated UI
=> [#12399] Instructor editing feedback path of a question: unnecessary scrollbars

src/web/app/components/modified-timestamps-modal/__snapshots__/modified-timestamps-modal.component.spec.ts.snap, src/web/app/components/modified-timestamps-modal/modified-timestamps-modal.component.html, src/web/app/components/modified-timestamps-modal/modified-timestamps-modal.component.spec.ts, src/web/app/components/modified-timestamps-modal/modified-timestamps-modal.component.ts, src/web/app/components/modified-timestamps-modal/modified-timestamps-module.module.ts, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.module.ts, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.module.ts, src/web/app/pages-instructor/instructor-session-base-page.component.ts, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html, src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.module.ts, src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html, src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.module.ts
Fixes #12327 
Refactored timestamp modals as seperate component
UI remains unchanged
=> [#12327] Consolidate duplicate modified timestamp modals

src/web/app/components/logs-table/logs-table.component.html, src/web/app/components/logs-table/logs-table.component.scss, src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap, src/web/app/pages-monitoring/logs-page/logs-page.component.html, src/web/app/pages-monitoring/logs-page/logs-page.component.scss
Fixes #12292 
Added overflow-x: scroll below a minimum width.
Added a logs-table-container class to remove right padding and margin which were causing the table to overflow even when it was above minimum width.
=> [#12292] Admin logs page: Fix display of logs table on mobile

src/web/app/components/student-list/student-list.component.scss
Fixes #12407 
I changed the respective scss file and added the white color in all fa-sort elements so that the sort icons have a white color instead of the grey one. 
Here is the updated UI
Here is the UI when a table is sorted by a specific column
=> [#12407] Sort icons in info table headings are hard to see

src/it/java/teammates/it/sqllogic/core/DataBundleLogicIT.java, src/it/resources/data/DataBundleLogicIT.json, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java, src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/sqlentity/DeadlineExtension.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/ui/output/DeadlineExtensionData.java, src/main/java/teammates/ui/webapi/FeedbackSessionPublishedEmailWorkerAction.java, src/main/java/teammates/ui/webapi/FeedbackSessionUnpublishedEmailWorkerAction.java
* Restores `FeedbackSession` entities' fields: 
* `isOpeningSoonEmailSent`
* `isOpenEmailSent`
* `isClosingSoonEmailSent`
* `isClosingEmailSent`
* Restores `DeadlineExtension` entities' fields: 
* `isClosingSoonEmailSent`
* These fields enable the conditional check if a particular email type has been sent for a particular feedbackSession.
* They are used in the Cron Jobs RemindersAction classes (see: `FeedbackSessionClosedRemindersAction`, `FeedbackSessionClosingRemindersAction`, `FeedbackSessionOpeningRemindersAction`, `FeedbackSessionOpeningSoonRemindersAction`, `FeedbackSessionPublishedRemindersAction`)
* Without these fields, no longer able to check if a cron job has been run to send an email.
=> [#12048] Restore sent*email fields

src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap, src/web/types/question-details-impl/feedback-constsum-recipient-question-details.impl.ts, src/web/types/question-details-impl/feedback-num-scale-question-details.impl.ts, src/web/types/question-details-impl/feedback-rank-recipients-question-details.impl.ts
Fixes #12430 Include student email in 'distribute points' type question summary table CSV
I changed the method which generated the csv file. Added one more columnfor the email stat.
For distribute points type question
For rank participants type question  
For Numerical-scale type question:
=> [#12430] Include student email in 'distribute points' type question summary table CSV

src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.spec.ts
Part of #10920 
Added a test case for onRestore(), used to restore a course that had previously been deleted on the Instructor Course Page
=> [#10920] Add test for restoreCourse in Instructor Courses Page

src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.module.ts
Fixes #12099
I've added the course copy element to the html in the instructor home page, added the course copy logic to the typescript files while using functions declared in its ancestor InstructorSessionBasePageComponent, and I also updated the snapshot tests.
=> [#12099] Add 'course -> copy' option to the instructor home page

src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.spec.ts
Part of #10920 
Tested that Instructor details are correctly updated when SAVE is requested on instructor-course-edit-page
=> [#10920] Added test for Instructor Course Edit Page

docs/development.md
Fixes #12464
Add verification step to docs, tested on local Markbind server
=> [#12464] Add verification step for Docker instance of Datastore in docs

build.gradle
The previous strategy of choosing the command for deleting temporary files relied on the Windows CMD command `del`. This command does not exist in PowerShell, so the task fails.
Thankfully, there is a `delete` method we can use. This method takes care of platform differences for us.
Fixes #12481 
Using gradle's [`delete`](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#delete-java.lang.Object...-) method fixes the problem and takes care of all other platform issues (I hope).
=> [#12481] Fix running of component tests using Windows Powershell

src/test/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetailsTest.java
Part of #1501
Approach:
- Based on jacoco reports and the coverage of the method validateQuestionDetails
- I applied mulitple-conditions white-box test 
- And added 2 tests cases to cover 100% of the method 
- In the test method testValidateQuestionDetails_invalidMaxMinOptions_errorReturned
=> [#1501] Add tests cases to FeedbackRankOptionsQuestionDetails

src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Fixes #12400 
`isQuestionHasResponses` of `questionEditFormModel` was set back to default when discard action was executed. I simply mutated the new `questionEditFormModel` created with the previous `isQuestionHasResponses` status.
https://github.com/Zxun2/teammates/assets/63457492/d8790667-02f7-4a50-81f5-51fff5e17e60
=> [#12400] Instructor editing questions: warning about visibility is removed if the edit is cancelled. 

src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java, src/e2e/java/teammates/e2e/cases/InstructorCourseEditPageE2ETest.java, src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java, src/e2e/java/teammates/e2e/pageobjects/AppPage.java, src/main/java/teammates/ui/webapi/CreateFeedbackQuestionAction.java, src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java, src/main/java/teammates/ui/webapi/UpdateFeedbackQuestionAction.java, src/web/app/components/toast/toast.component.scss, src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts, src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Fixes #11947
This PR improves the appearance of error toasts by formatting them to separate each error into a new line, by adjusting the `whitespace` CSS property on the toast component. 
Additionally, due to the adjustment of this property, some of the status messages within the toasts turn up with odd spaces and line breaks. This PR also adds the necessary fixes for those messages.
Lastly, due to the modification, some E2E tests also fail with the odd errors unrelated to toast itself. I found that adding a fixed timeout and closing the toast popup after verification of the message fixes this issue. These changes are also within this PR.
=> [#11947] Format error toasts

src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Fixes #12517 
Overwrite default attributes inherited from base class.
=> [#12517] Instructors creating sessions: response visible time should be 'not now' by default

src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
Fixes #12533 
The solution is similar to issue #12535. 
For all the selection in the dropdown that cannot be tabbed, I added a `tmRouterLink` and assign the current route as the link. 
https://github.com/TEAMMATES/teammates/assets/66376253/53fb5940-a103-4a9c-b132-3f027bae82ae
=> [#12533] Instructor Home Page: tabbing on Course Dropdown

src/web/app/page.component.html, src/web/app/page.component.scss
Fixes #12530
The current dropdown toggle on the header is created using `<a>` tags, so currently, the dropdown can actually be toggled  using the arrow down key. 
This PR changes those `<a>` tags to use `<button>`tags also with added classes to reduce any change in the visual appearance. This change will now allow the dropdown to be toggled with the Enter key instead of the arrow key.
This PR also allows tabbing to the Log Out button and fixes #12531 by adding `tabindex=0` to the element
=> [#12530] Allow header dropdown to be opened with enter key

src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
Fixes #12538
I added an alert for Deleted Sessions table that is displayed when there are no deleted courses.
=> [#12538] Instructor sessions page: Empty deleted sessions table is not displayed

src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.html
Fixes #12313
Used form-check and form-check-inline class from bootstrap for proper formatting of checkbox and label.
=> [#12313] Instructor sending submission reminders: missing space between checkbox and label

src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/pages-session/session-submission-page/session-submission-page.component.html
Fixes #12314
- add mouse enter event to enable the tooltip
- close tooltip when the button to save the responses is clicked
**Laptop size:**
**Mobile size:**
=> [#12314] Popover appears in front of modal blocking buttons

src/web/app/components/question-response-panel/question-response-panel.component.ts, src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts, src/web/app/pages-session/session-result-page/session-result-page.component.ts
Fixes #12499
Changed the hasResponse field to be false by default. Now the questions won't show up briefly and then be hidden due to not having responses. 
Previous:
https://user-images.githubusercontent.com/63457492/247068301-1e5b68cc-5bec-4f07-aa57-e3837ec1847b.mp4
New:
https://github.com/TEAMMATES/teammates/assets/83157275/592b008d-9290-4ecb-b6dc-af993ee0f710
=> [#12499] Flickering questions when loading session results

src/web/app/components/panel-chevron/panel-chevron.component.html, src/web/app/components/panel-chevron/panel-chevron.component.scss, src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap, src/web/app/components/question-submission-form/question-submission-form.component.html, src/web/app/components/question-types/question-edit-answer-form/text-question-edit-answer-form.component.html, src/web/app/components/user-notifications-list/__snapshots__/user-notifications-list.component.spec.ts.snap, src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/__snapshots__/copy-instructors-from-other-courses-modal.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/__snapshots__/copy-questions-from-other-sessions-modal.component.spec.ts.snap, src/web/app/pages-instructor/instructor-student-activity-logs/__snapshots__/instructor-student-activity-logs.component.spec.ts.snap, src/web/app/pages-instructor/instructor-student-list-page/__snapshots__/instructor-student-list-page.component.spec.ts.snap, src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap, src/web/data/developers.json
Fixes #12279 
Card-header-toolbar changed to display as flex-container on mobile screens (see screenshots below) and changed from div-element to button element for screenreader compatibility.
An other option would be with using grid to create a 2X2 grid with all 4 buttons. I also think the panel-chevron component  (drop-down icon) could be positioned to the right instead of below. 
Any opinions?
Screen-size of 450px
Screen-size of 320px 
Screen-size of 768px
=> [#12279]  Instructor home page: Improve display of card header on mobile

src/web/app/components/datepicker/datepicker-formatter.spec.ts
Part of #12588
Added unit tests for the methods in DatePickerFormatter.
=> [#12588] Add unit tests to DatePickerFormatter

docs/CONTRIBUTING.md
Fixes  #12599
added "the" within the paragraph for better readability
=> [#12599] fixes typo error 

src/web/app/components/course-edit-form/course-edit-form.component.spec.ts
Part of #12588 
Added unit tests to CourseEditForm component for following methods:
setIsEditing,
updateInstitutes,
detectTimezoneHandler,
submitHandler,
closeFormHandler,
deleteCourseHandler
=> [#12588] Added unit tests to CourseEditForm component.

src/main/java/teammates/logic/core/FeedbackSessionsLogic.java, src/test/java/teammates/logic/core/FeedbackSessionsLogicTest.java, src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
Fixes #12594
Deadline extensions map in `FeedbackSession` was not being updated when a student's email was updated.
This was due to updating of the feedback session's map, and then checking if the feedback session's attributes had changed, which would always be false since we were just comparing the same map.
Creating a new map and passing it into the update options fixes this.
=> [#12594] Fix deadline extensions update issue

src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java, src/web/app/components/question-types/question-response/rubric-question-response.component.html
Fixes #12644 
Changed the `id` to a `class` and edited the E2E test accordingly. I also looked at passing in some id to append to `rubric-answers` but it seemed like overkill... (too much work to have the component implementation fit the test, when it should be that the test is written based off the component)
=> [#12644] Fix Failing Accessibility Test

src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java, src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java, src/web/app/components/comment-box/comment-row/comment-row.component.html, src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap, src/web/app/components/question-response-panel/question-response-panel.component.html, src/web/app/components/question-responses/student-view-responses/student-view-responses.component.html, src/web/app/components/question-types/question-response/rubric-question-response.component.html
Fixes #12647 
Change `id`s to `class` and edit E2E tests accordingly. Also merged 2 methods into `getGivenResponseField` method because the previous method for getting the index first wasn't really improving readability - with the merged method, now it's clear that the response field being returned is the one tied to the receiver we're looking for.
Added a `span` into the rubric question response as well and edited the aria label so that the unticked table cell wouldn't just be read as "blank"
=> [#12647] Fix accessibility tests

src/web/app/components/error-report/error-report.component.spec.ts
Fixes [#12588]
Add unit tests for ErrorReportComponent
=> [#12588] Added unit tests for ErrorReportComponent

src/web/styles.scss
Fixes #12345 
- The issue causing this is the IOS specific property of smooth touching scrolling.
- I fixed it by changing the overflow-scrolling property of the responsive table from touch to auto.
**The below screenshot is before I fixed it:**
**The below screenshot is after I fixed it:**
=> [#12345] Instructor courses page: other actions dropdown cut off

src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.spec.ts
Fixes #12588
Add unit test for every method in CommentEditFormComponent
=> [#12588] Add unit test for every method in CommentEditFormComponent

src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.html
Fixes #12665 
This pull request addresses misleading name for canceling of comment edit reported in #12665 .
The changes include changing the button that conditionally displays "Discard" or "Cancel " to only display "Cancel"
=> [#12665]  Instructor's Student Records Page: Misleading name for canceling of comment edit

docs/development.md
Remove redundant newline in Development section of Docs #12671
Fixes #12671 
Updated docs/development.md to remove redundant newline.
=> [#12671] Remove redundant newline in Development section of Docs 

src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.html
Fixes #12668
In this PR, I've updated the color of the `tm-panel-chevron` from white to black. This change aims to improve the visibility of the chevron on white backgrounds, based on the feedback and suggestions from the community.
Changes made:
- Modified the `chevronColor` in `PanelChevronComponent` to black.
- Checked and ensured that this color change integrates well with the existing user interface.
I've tested this change and believe it enhances the visibility of the chevron without impacting other design aspects. I'm open to any further suggestions or feedback.
=> [#3942] Instructor's Student Records Page: Feedback session panel chevron barely visible #12668

src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java, src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html, src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.spec.ts
Fixes #12658 
**Made  Responsive Drop-down Menu for the Instructor Home Page**
**Modified Screens**
- Tested with all screen widths.
- Run all the test cases including  lint cases & passed
=> [#12658] Instructor Home Page: Dropdown buttons on mobile

src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap, src/web/app/pages-student/student-home-page/student-home-page.component.ts
Fixes #12656
The problem was that the default sortBy was set to NONE. Changed this to COURSE_CREATION_DATE to result in the desired functionality.
=> [#12656] Student Home Page: Indicate default sort 

src/web/app/components/session-edit-form/session-edit-form.component.html, src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap, src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
Fixes #12654
* Move the tooltip target from the wrapping div of `Grace period` label to the label itself.
* Apply the class `ngb-tooltip-class` to the label, to apply the underline styling.
=> [#12654] Instructor Edit Session Page: Bug in Grace Period Tooltip

src/web/app/components/comment-box/comment-row/comment-row.component.html, src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
Fixes #12663
The tooltip for comment/edit time causes the rest of the text to go into the next line is because comment/edit time's parent element is a `<span>`. The tooltip window element created when hovering over the comment/edit time will be a a child element of this `<span>`. Changing it to a block element `<ng-container>` fixes the issue.
Alternative:
An alternative is to set `container="body"` so that the tooltip will be attached as a last child of the <body> element ([doc](https://ng-bootstrap.github.io/#/guides/positioning#api)) this makes sure that the tooltip window is outside of the `<span>` element.
**Screenshots:**
=> [#12663] Instructor's Student Records Page: Tooltips for comments 

src/web/app/components/comment-box/comment-row/comment-row.component.spec.ts, src/web/app/components/course-edit-form/__snapshots__/course-edit-form.component.spec.ts.snap, src/web/app/components/course-edit-form/course-edit-form.component.spec.ts, src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.spec.ts, src/web/services/account.service.spec.ts, src/web/services/auth.service.spec.ts, src/web/services/course.service.spec.ts, src/web/services/error-report.service.spec.ts, src/web/services/feedback-questions.service.spec.ts, src/web/services/feedback-response-comment.service.spec.ts, src/web/services/feedback-responses.service.spec.ts, src/web/services/feedback-sessions.service.spec.ts, src/web/services/http-request.service.spec.ts, src/web/services/instructor.service.spec.ts, src/web/services/notification.service.spec.ts, src/web/services/search.service.spec.ts, src/web/services/timezone.service.spec.ts, src/web/test-helpers/create-spy-from-class.ts
Fixes #12695
Create `createSpyFromClass` test utility function to automatically create spy objects for us
=> [#12695] implement createSpyFromClass test-helper

docs/setting-up.md
Fixes #12699  
Replace the command `ng` with `ng --help` in the setting-up.md in the `/docs` directory
=> [#12699] Replace ng command in setting-up.md

src/it/java/teammates/it/sqllogic/core/FeedbackSessionsLogicIT.java, src/it/java/teammates/it/storage/sqlapi/FeedbackSessionsDbIT.java, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/ui/output/OngoingSession.java, src/main/java/teammates/ui/webapi/Action.java, src/main/java/teammates/ui/webapi/GetOngoingSessionsAction.java, src/test/java/teammates/sqlui/webapi/BaseActionTest.java, src/test/java/teammates/sqlui/webapi/GetOngoingSessionsActionTest.java
The code was first refactored to make it easier to migrate, and improve readability. This is until the [commit with the message "Remove dependency on account in ongoing session"](https://github.com/TEAMMATES/teammates/commit/f34d1199b68f7b3778fa4cd5823a90afecdf2631). The commits from the [commit with the message "Add method to get ongoing feedback sessions"](https://github.com/TEAMMATES/teammates/commit/66fb6c7a4d609b3aad24937b120159230ad422d0) onwards were for the main migration work.
The main migration work involved adding methods to get ongoing feedback sessions in the SQL logic and SQL storage classes so that they can be called by the action to get ongoing feedback sessions. A mock datastore logic class instance was injected into actions during …
=> [#12048] Migrate GetOngoingSessionsAction for V9

src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java, src/it/java/teammates/it/storage/sqlsearch/InstructorSearchIT.java, src/it/java/teammates/it/ui/webapi/DeleteStudentsActionIT.java, src/it/java/teammates/it/ui/webapi/GetCourseJoinStatusActionIT.java, src/it/java/teammates/it/ui/webapi/GetInstructorsActionIT.java, src/it/java/teammates/it/ui/webapi/GetStudentsActionIT.java, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java, src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java, src/main/java/teammates/ui/webapi/GetCourseJoinStatusAction.java
- Change `GetCourseJoinStatusAction` to use SQL DB if possible
- Add `getAccountRequestByRegistrationKey` to AccountRequestLogic class
- Add data required for tests to `typicalDataBundle.json`
- Add test cases
=> [#12048] Migrate GetCourseJoinStatusAction

src/main/java/teammates/logic/api/EmailGenerator.java
Part of #12056 
Abstract parts of `generateSessionLinksRecoveryEmailForStudent` in datastore `EmailGenerator` so that some methods can reused in #12712, in particular (`generateLinkFragmentsMap`)when searching both SQL database and datastore
=> [#12048] Refactor email generator

src/it/java/teammates/it/sqllogic/core/AccountsLogicIT.java, src/it/java/teammates/it/storage/sqlsearch/InstructorSearchIT.java, src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java, src/it/java/teammates/it/ui/webapi/JoinCourseActionIT.java, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/AccountsLogic.java, src/main/java/teammates/sqllogic/core/LogicStarter.java, src/main/java/teammates/ui/webapi/JoinCourseAction.java, src/test/java/teammates/sqllogic/core/AccountsLogicTest.java
Part of #12048
- Modified `JoinCourseAction` to use `sqlLogic` when course is migrated
- Used registration key in the http param to query the DB for `courseId`. 
- Default to use the result of querying datastore if it is not null. If both are null, default to "not migrated" instead of throwing exception as the logic for checking if registration key is valid is already present in the logic layer.
- Added `joinCourseForStudent` and `joinCourseForInstructor` to`sqllogic.core.AccountsLogic`
- Added integration test for `JoinCourseAction`
- Added test cases for testing the `joinCourseForStudent` and `joinCourseForInstructor` to `AccountsLogicIT.java`
=> [#12048] Migrate join course action

src/main/java/teammates/ui/webapi/SearchInstructorsAction.java, src/test/java/teammates/ui/webapi/SearchInstructorsActionTest.java
Reworking some code from #12340:
- Previously, the `SearchInstructorsActionTest` was failing because the `SearchInstructorsAction` only uses the new `sqlsearch`
- However, this leads to 2 issues: we lack the original test for searching in datastore, and we are also unable to support search for twin db
Solution:
- Add back in the original search and concatenate the results
- Add back the original test, now that we have the ability to search both
- Currently unable to test both together since we would need to somehow initialise both search managers at once...
=> [#12048] Support for twin db for search + replace datastore test

src/it/java/teammates/it/storage/sqlsearch/AccountRequestSearchIT.java, src/it/java/teammates/it/ui/webapi/GetCourseJoinStatusActionIT.java, src/it/java/teammates/it/ui/webapi/SearchAccountRequestsActionIT.java, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java, src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java, src/main/java/teammates/ui/webapi/SearchAccountRequestsAction.java
- Change `SearchAccountRequestsAction` to handle search on both datastore and SQL db
- Created necessary functions in `AccountRequestsLogic` and `AccountRequestsDb`
- Add in tests for search on SQL db for this action
- Support for twin db implemented similarly to #12728
=> [#12048] Migrate search account requests action

src/main/java/teammates/ui/webapi/PutDataBundleDocumentsAction.java, src/test/java/teammates/test/AbstractBackDoor.java
The documents are added for both datastore and SQL.
This should allow for tests that rely solely on datastore or SQL to be executed.
This should also allow testing for dual-db search behaviors where one entry might exist in both the datastore and SQL database
=> [#12048] Migrate PutDataBundleDocumentsAction

src/it/java/teammates/it/sqllogic/core/UsersLogicIT.java, src/it/java/teammates/it/storage/sqlapi/AccountsDbIT.java, src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java, src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java, src/test/java/teammates/sqllogic/core/AccountsLogicTest.java, src/test/java/teammates/sqllogic/core/CoursesLogicTest.java, src/test/java/teammates/sqllogic/core/NotificationsLogicTest.java, src/test/java/teammates/sqllogic/core/UsersLogicTest.java, src/test/java/teammates/storage/sqlapi/AccountsDbTest.java, src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java, src/test/java/teammates/storage/sqlapi/UsersDbTest.java, src/test/java/teammates/test/BaseTestCase.java
Moves the getTypicalX functionality to BaseTestCase
=> [#12048] Move getTypicalEntity functions to BaseTestCase

src/it/java/teammates/it/ui/webapi/StudentSearchIndexingWorkerActionIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/ui/webapi/StudentSearchIndexingWorkerAction.java
Part of #12048
**Changes**
* Use SQL logic for StudentSearchIndexingWorkerAction execution if course is migrated
* Add IT for StudentSearchIndexingWorkerAction
Note:
~~As the test relies on Logic::searchStudentsInWholeSystem which is to be implemented in #12735, that PR should be merged first~~ (#12735 has been merged)
=> [#12048] Migrate StudentSearchIndexingWorkerAction

src/web/app/components/question-types/question-constraint/constsum-recipients-question-constraint.component.spec.ts, src/web/app/components/question-types/question-constraint/contribution-question-constraint.component.spec.ts
Part of #12588
Add unit tests for improve codecov for questionconstraint: https://app.codecov.io/github/TEAMMATES/teammates/tree/master/src%2Fweb%2Fapp%2Fcomponents%2Fquestion-types%2Fquestion-constraint
utilised new builder, placed them in the test file instead of a central location (lmk if theres any comments on this)
also for descriptions, i would like to propose that we include the method name that we are testing if it is a test for a particular function, which is the way its done in this PR
=> [#12588] Add tests to question constraint

src/it/java/teammates/it/sqllogic/api/EmailGeneratorTestIT.java, src/it/java/teammates/it/storage/sqlsearch/StudentSearchIT.java, src/it/java/teammates/it/ui/webapi/SearchStudentsActionIT.java, src/it/java/teammates/it/ui/webapi/SessionLinksRecoveryActionTestIT.java, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/logic/api/EmailGenerator.java, src/main/java/teammates/logic/api/Logic.java, src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java, src/main/java/teammates/ui/webapi/SessionLinksRecoveryAction.java
Using the refactored email generator (#12723), the links of feedback sessions which students are in are fetched from data store and Postgres server and are combined into a single email to be sent to students (this should be removed after migration)
=> [#12048] Migrate Session Links Recovery Action

src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
Previously, `restoreDeletedFeedbackSession()` in `FeedbackSessionsDb.java` did not save the changes to db
Save updated entity to db
=> [#12048] Update restoreDeletedFeedbackSession to save updated entity to db

src/test/java/teammates/sqllogic/core/FeedbackQuestionsLogicTest.java, src/test/java/teammates/test/BaseTestCase.java
Part of  #12048 
Remove typicalDataBundle from FeedbackQuestionLogicTest as unit tests should not use databundle
=> [#12048] Remove typical data bundle from feedbackquestionlogic test

src/it/java/teammates/it/sqllogic/core/FeedbackResponsesLogicIT.java, src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java, src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java, src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java, src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
This PR is part 1 of 2, and is related to #12720. Splitting it up as the PR is quite big.
This PR will handle the database and logic layer needed for the actual migration of SubmitFeedbackResponseAction.
=> [#12048] Migrate SubmitFeedbackResponseAction's Logic and Db methods

src/it/java/teammates/it/ui/webapi/FeedbackSessionOpeningSoonRemindersActionIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/ui/webapi/FeedbackSessionOpeningSoonRemindersAction.java
OpeningSoon emails are only sent to co-owner instructors of a course. 
---
Integration tests for this action have been added.
When referencing the old tests for this class (FeedbackSessionOpeningSoonRemindersActionTest.java), there are tests for emails to or not to be added when feedback session is modified, but I think it makes more sense to add them in UpdateFeedbackSessionActionIT.java instead.
=> [#12048] Migrate FeedbackSessionOpeningSoonRemindersAction

src/it/java/teammates/it/ui/webapi/FeedbackSessionClosingRemindersActionIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java, src/main/java/teammates/sqllogic/core/DeadlineExtensionsLogic.java, src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/sqlapi/DeadlineExtensionsDb.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/ui/webapi/FeedbackSessionClosingRemindersAction.java
Per session, Closing-soon emails are sent for all co-owners, students and instructors (except students and instructors with deadline extensions).
---
For IT Tests, upon loading from data bundle, feedback sessions don't have association with deadline extension and feedback questions entities (ie: session.getDeadlineExtensions() and session.getFeedbackQuestions() return empty array). `prepareSession` function manually adds this association.
=> [#12048] Migrate FeedbackSessionClosingRemindersAction

src/it/java/teammates/it/ui/webapi/FeedbackSessionClosedRemindersActionIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/ui/webapi/FeedbackSessionClosedRemindersAction.java
Closed emails are only sent to co-owner instructors.
=> [#12048] Migrate FeedbackSessionClosedRemindersAction

src/e2e/java/teammates/e2e/cases/sql/BaseE2ETestCase.java
Part of #12048 and #12775.
As per title.
=> [#12048] Fix incorrect usage of `recipient` as param for E2E test

src/e2e/java/teammates/e2e/cases/InstructorNotificationsPageE2ETest.java, src/e2e/resources/data/InstructorNotificationsPageE2ETest_SqlEntities.json
Part of #12048
Update test to use sqlentity
=> [#12048] Migrate instructor notification page e2e test

src/client/java/teammates/client/scripts/sql/DataMigrationForUsageStatisticsSql.java, src/client/java/teammates/client/scripts/sql/SeedUsageStatistics.java
Write script to migrate all usage statistics from datastore to cloudSQL 
Verification: 
1. Seed DB with UsageStatistics. 
`./gradlew -PuserScript=sql/SeedUsageStatistics execScript`
2. Run the migration script in preview (im using non preview to check on live CloudSQL in the screenshot) 
`./gradlew -PuserScript=sql/DataMigrationForUsageStatisticsSql execScript` 
We can see the 2 seeded UsageStatistics are reported to be migrated. 
3. Verify on CloudSQL 
the fields seem to match seeded datastore records.
=> [#12048] Add migration script for Usage Statistics

src/client/java/teammates/client/scripts/sql/DataMigrationForAccountRequestSql.java
Add migration script for Account Request 
Verification: 
1. Seed the db with TypicalJsonBundle 
2. Migrate on preview mode
`./gradlew -PuserScript=sql/DataMigrationForAccountRequestSql execScript`
16 matches with the # of seed account requests 
4. Migrate on non-preview on test CloudSQL, verify fields match with seed data in datastore. 
`./gradlew -PuserScript=sql/DataMigrationForAccountRequestSql execScript`
fields seem to map correctly apart from createdAt which is always overwritten by the hibernate @CreatedTimestamp annotation
=> [#12048] Add migration script for Account Request

src/e2e/java/teammates/e2e/pageobjects/AppPage.java
**Outline of Solution:**
In `InstructorHomePage` page object, the datatime formatter for feedback session start and end time in the feedback session table does not include a Locale. This may cause the am/pm to be formatted in lowercase instead of uppercase, causing the test to fail in some cases.
=> [#12048] Add locale for java datetime formatter

src/client/java/teammates/client/scripts/sql/VerifyNonCourseEntityCounts.java
Script compares datastore entity count with the postgres entities count to ensure that all entities have been migrated.
**Other alternatives**
Datastore Statistics: Apparently these [aren't updated in realtime](https://github.com/googleapis/google-cloud-node/issues/413#issuecomment-299784784).
Todo
=> Create script to verify row count for non-course entities

src/e2e/java/teammates/e2e/cases/AutomatedSessionRemindersE2ETest.java, src/e2e/resources/data/AutomatedSessionRemindersE2ETest.json, src/e2e/resources/data/AutomatedSessionRemindersE2ETest_SqlEntities.json
=> [#12048] Move accounts JSON for AutomatedSessionRemindersE2ETest

src/web/app/components/student-list/student-list.component.spec.ts, src/web/app/components/student-list/student-list.component.ts, src/web/test-helpers/generic-builder.ts
Part of #12588
Add tests to improve code coverage of student list component
Removed getAriaSort for student list component, as it is unused (sortable-table's getAriaSort is being used instead)
=> [#12588] Add tests for student list component

src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java
Part of #12048
Added sql injection tests to relevant methods in UsersDb
=> [#12048] SQL injection test for UsersDbIT 

src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java
SQL injection tests were added into NotificationsDbIT, covering methods, and inputs, except non-string input, and methods with no user input.
=> [#12048] Add SQL injection tests in NotificationDbIT

src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
=> [#12048] SQL injection test for AccountRequestsDbIT

src/it/java/teammates/it/ui/webapi/GetFeedbackSessionLogsActionIT.java, src/main/java/teammates/ui/output/FeedbackSessionLogData.java, src/main/java/teammates/ui/output/FeedbackSessionLogEntryData.java, src/main/java/teammates/ui/output/FeedbackSessionLogsData.java, src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
Couldn't create an alternate constructor because the generic types used in `Map<String, *>` are erased, so constructors will conflict. I instead used generic types for the 2 affected constructors, and placed all the type checks in `FeedbackSessionLogData` to reduce messiness. Also left a comment so that after migration is done, the generic types can be replaced with the actual types used (i.e. `FeedbackSession` and `Student`)
=> [#12048] Migrate GetFeedbackSessionLogsAction

src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java
=> [#12048] SQL injection test for CoursesDbIT

src/it/java/teammates/it/storage/sqlapi/FeedbackResponseCommentsDbIT.java
=> [#12048] SQL Injection tests for FeedbackResponseCommentsDbIT

src/client/java/teammates/client/scripts/sql/SeedDb.java
**Context**
VerificationAccountAttributes state there was errors in the data migration of accounts. After investigation, discovered script was ok, the seeding of mock data to the datastore was incorrect and caused the script to fail.
- Notification and readNotification now use the same instant
- endTime is rounded to nearest millisecond to correspond with the 2 actions that create and update notifications, MarkNotificationAsReadAction.class and CreateNotificationAction.class
=> Fix seeding of data for data migration

src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java, src/client/java/teammates/client/scripts/sql/MigrateAndVerifyNonCourseEntities.java
* To enable patch update of accounts for data migration, we decide to use the `isMigrated` flag in Account.
* If the account is migrated in the online update, the isMigrated flag will be set to true.
* Then when we do patch update in the offline migration for Account and ReadNotification, we check this flag to determine if this account has been migrated or not.
=> [#12048] Prepare Patch Data Migration Script for Account

src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java, src/client/java/teammates/client/scripts/sql/SeedDb.java
* Revert the getFilterQuery to not filter by `isMigrated`, instead check this flag in `isMigrationNeeded` method.
* Seed account with the `isMigrated` check to be false.
=> [#12048] Revert getFilterQuery for Account Data Migration Script

src/main/java/teammates/common/datatransfer/FeedbackSessionLogEntry.java, src/main/java/teammates/common/util/Const.java, src/main/java/teammates/logic/api/LogsProcessor.java, src/main/java/teammates/logic/external/GoogleCloudLoggingService.java, src/main/java/teammates/logic/external/LocalLoggingService.java, src/main/java/teammates/logic/external/LogService.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/storage/sqlentity/FeedbackSessionLog.java, src/main/java/teammates/ui/webapi/ActionFactory.java, src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java, src/main/java/teammates/ui/webapi/UpdateFeedbackSessionLogsAction.java, src/test/java/teammates/logic/api/MockLogsProcessor.java, src/test/java/teammates/sqlui/webapi/UpdateFeedbackSessionLogsActionTest.java, src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Part of #11843
- Create FeedbackSessionLog Entity
- Create UpdateFeedbackSessionLogsAction
- Processes all logs from the past hour similar to UsageStatistics
- Ensure that logs of the  same type by the same student in the same session are only passed to the logic layer if they are at least 2 seconds apart
=> [#11843] Create FeedbackSessionLog entity and cron job action

src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.spec.ts
Part of #12588 
Add unit tests to cover uncovered functions: https://app.codecov.io/github/TEAMMATES/teammates/blob/master/src%2Fweb%2Fapp%2Fcomponents%2Fquestion-types%2Fquestion-edit-details-form%2Frubric-question-edit-details-form.component.ts
=> [#12588] Add unit test to rubric-question-edit-details-form

src/test/java/teammates/test/BaseTestCaseWithSqlDatabaseAccess.java
=> [#12048] Add deep comparison for entities in `verifyEquals` for E2E

src/client/java/teammates/client/scripts/sql/DataMigrationForAccountRequestSql.java, src/client/java/teammates/client/scripts/sql/VerifyDataMigrationConnection.java, src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java, src/it/java/teammates/it/sqllogic/core/DataBundleLogicIT.java, src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java, src/it/resources/data/DataBundleLogicIT.json, src/main/java/teammates/common/datatransfer/AccountRequestStatus.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java, src/main/java/teammates/storage/sqlentity/AccountRequest.java, src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java, src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
Added status (and its type, `AccountRequestStatus`) and comments attributes to `AccountRequest`.
=> [#11878] Add status and comments to AccountRequest

src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java, src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
Fixes #12921 
Search indexing for `AccountRequest` was reintroduced. There were effectively no integration tests for `CreateAccountRequestAction`; `teammates.ui.webapi.CreateAccountRequestActionTest` is not enabled, and even if it were, it tests using Datastore, not SQL. Thus, I also added `CreateAccountRequestActionIT`. However, I only give a minimal test because the behaviour of `CreateAccountRequestAction` will change with the upcoming account request form upgrade (see #12913). I felt it would not be very productive to test every single case. The minimal test only serves to give confidence that the core functionality of `CreateAccountRequestAction` works, especially the newly reintroduced search indexing.
=> [#12921] Reintroduce AccountRequest search indexing

src/main/java/teammates/common/util/Config.java, src/main/resources/build-dev.template.properties, src/main/resources/build.template.properties
=> [#12048] Add SQL description for postgres config

src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java, src/main/java/teammates/common/util/EmailType.java, src/main/java/teammates/common/util/Templates.java, src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java, src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java, src/main/resources/adminEmailTemplate-newAccountRequestAlert.html, src/test/java/teammates/sqllogic/api/SqlEmailGeneratorTest.java, src/test/resources/emails/adminNewAccountRequestAlertEmailWithComments.html, src/test/resources/emails/adminNewAccountRequestAlertEmailWithNoComments.html
Part of #11878
Added the new account request alert email for admins. If `comments` is null, we leave the table entry blank.
The following is a preview of the email template.
=> [#11878] Add new account request alert email for admins

src/client/java/teammates/client/scripts/sql/DataMigrationForAccountRequestSql.java
* [Just for v9-beta.1 release] Clean the account request table and run the script. This is okay because with the batched operation, migrating 13k account requests is fast. Moreover, this will be done while the system is online as AccountRequest is a standalone entity.
=> [#12048] Rerunnable Account Request Migration Script

src/client/java/teammates/client/scripts/sql/SeedDb.java, src/client/java/teammates/client/scripts/sql/VerifyAccountAttributes.java
Part of #12048
**Context**
Due to a flaw in the datastore implementation of read notifications, a deleted notification will not be removed from each accounts read notification list. This would cause the verification script to fail as the postgres entity would not have migrated that an account has seen this deleted notification. e.g datastore account has seen deleted notification Y, postgres would not migrate notification Y and therefore not be able to create a foreign key in the read notification table for notification Y.
- Relax read notification verification by not verifying them but we still migrate any that are seen.
- Fixed incorrect field order for account request in SeedDb (unrelated to problem)
=> [#12048] Relax read notif verification for migration verification script

src/web/app/components/view-results-panel/view-results-panel.component.spec.ts
Part of #12588 
Add test cases in `src/web/app/components/view-results-panel/view-results-panel.component.spec.ts`
=> [#12588] Improve test code coverage of core components - ViewResultsPanelComponent

src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java, src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java, src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java, src/test/java/teammates/sqllogic/core/AccountRequestsLogicTest.java, src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
Part of #11878
Added methods to get an account request by ID in:
- `AccountRequestsDb`
- `AccountRequestsLogic`
- `Logic`
=> [#11878] Add methods to get an account request by ID

src/web/app/pages-static/request-page/__snapshots__/request-page.component.spec.ts.snap, src/web/app/pages-static/request-page/instructor-request-form/__snapshots__/instructor-request-form.component.spec.ts.snap, src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.spec.ts, src/web/app/pages-static/request-page/request-page.component.spec.ts
Part of #11878
Depends on #12929
* Add snapshot tests for `RequestPageComponent` and `InstructorRequestFormComponent`
=> [#11878] Add snapshot tests for instructor request form UI

src/main/java/teammates/common/util/Const.java, src/web/app/components/account-requests-table/account-request-table-model.ts, src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts, src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts, src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts, src/web/services/search.service.spec.ts, src/web/services/search.service.ts
Part of #11878
This is needed for a number of account request API endpoints.
- Added account request ID query parameter
- Added ID in
- `AccountRequestTableRowModel`
- This is necessary so that we can pass the ID as the query parameter for API endpoints.
- `AccountRequestSearchResult`
- This is necessary so that we can pass the ID into `AccountRequestTableRowModel`.
=> [#11878] Foundation for getting by ID in account request endpoints

src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java
=> V9 non course migration for accounts not migrating

src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java, src/client/java/teammates/client/scripts/sql/MarkIsMigratedForAccounts.java
=> V9 non course migration fix to check extra SQL accounts

src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
Part of #11878
Get by ID instead in the SQL injection tests. The SQL injection test using `SELECT` will no longer be relevant, so it was removed.
=> [#11878] Get by account request ID in SQL injection tests

src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java, src/main/java/teammates/logic/api/TaskQueuer.java, src/main/java/teammates/logic/api/UserProvision.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java, src/main/java/teammates/ui/servlets/WebApiServlet.java, src/main/java/teammates/ui/webapi/Action.java, src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
Part of #12048
Account request was not indexing due to a race condition: the account request was not in the database before indexing, as the transaction was not committed.
This PR allows CreateAccountRequestAction to handle its own transactions and queues the indexing action after the AccountRequestCreation is commited.
=> [#12048] Fix account request indexing

build.gradle, src/main/java/teammates/common/util/HibernateUtil.java
Part of #12048
Configure agroal for connection pooling in production, as recommended by the docs: https://docs.jboss.org/hibernate/orm/6.4/introduction/html_single/Hibernate_Introduction.html#tuning-and-performance
=> [#12048] configure agroal connection pool

src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java, src/main/java/teammates/common/util/EmailType.java, src/main/java/teammates/common/util/Templates.java, src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java, src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java, src/main/resources/instructorEmailTemplate-newAccountRequestAcknowledgement.html, src/test/java/teammates/sqllogic/api/SqlEmailGeneratorTest.java, src/test/resources/emails/instructorNewAccountRequestAcknowledgementEmailWithComments.html, src/test/resources/emails/instructorNewAccountRequestAcknowledgementEmailWithNoComments.html
Part of #11878
* Add acknowledgement email to be sent to users who fill in the instructor request form (similar to admin alert email)
* Add test cases
Preview of email format:
=> [#11878] Create instructor request acknowledgement email

src/client/java/teammates/client/scripts/sql/PatchDataMigrationForUsageStatisticsSql.java
* Batch select datastore entities, and then batch select SQL entities with the same start timestamps.
* Compare the size of the two list, if is not equal, find the missing one in SQL and migrate it.
=> Add patch data migration script for usage stats

src/main/java/teammates/common/util/FieldValidator.java, src/test/java/teammates/common/util/FieldValidatorTest.java
Part of #11878
* Change `INSTITUTE_NAME_MAX_LENGTH` to 128 to accommodate longer institution names. (No need to modify DB as the relevant columns are `varchar(255)`)
=> [#11878] Change institute length limit

src/main/java/teammates/storage/sqlentity/Course.java, src/main/java/teammates/storage/sqlentity/CourseStructure.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java, src/main/java/teammates/storage/sqlentity/Section.java, src/main/java/teammates/storage/sqlentity/Student.java, src/main/java/teammates/storage/sqlentity/Team.java, src/main/java/teammates/storage/sqlentity/TeamToStudentMap.java, src/main/java/teammates/storage/sqlentity/User.java
Part of https://github.com/TEAMMATES/teammates/issues/12946.
Initialise entities needed for Course Structure.
=> [#12946] Initialise Entities for Course Structure

src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java, src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java, src/it/resources/data/typicalDataBundle.json, src/main/java/teammates/ui/request/AccountRequestUpdateRequest.java, src/main/java/teammates/ui/webapi/ActionFactory.java, src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java, src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Created `AccountRequestUpdateRequests` to handle and validate update request fields.
Add `PUT` endpoint for editing Account Request fields (name, email, institute, comments), and for approving account requests. Only `REJECTED` and `PENDING` account requests can be approved, other statuses will just go through the normal updating branch, as it should not be possible to trigger account requests with other statuses (`REGISTERED`, `APPROVED`) to be approved either.
Upon approval, an email containing the registration url is sent to the specified email address.
Reason for adding an `AfterMethod` to the `CreateAccountRequestActionIT`:
During testing, I realised that the `GetAccountRequestsActionIT` kept failing locally with a initial 4 pending account …
=> [#11878] Create Update Account Request Action

src/web/app/components/account-requests-table/account-request-table-model.ts, src/web/app/components/account-requests-table/account-request-table.component.html, src/web/app/components/account-requests-table/account-request-table.component.ts, src/web/app/components/account-requests-table/account-request-table.module.ts, src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal-model.ts, src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal.component.html, src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal.component.ts, src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap, src/web/app/pages-admin/admin-search-page/admin-search-page.component.html, src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts, src/web/services/account.service.ts, src/web/services/search.service.ts
Adds in the UI for editing and approving account requests, same functionality as in admin search and admin home page.
Demonstration of editing various fields and approving the request
<video src="https://github.com/TEAMMATES/teammates/assets/74132255/07c6cc41-59c3-4005-be87-ee5ceb49b81f"><video>
Demonstration of invalid edits
<video src="https://github.com/TEAMMATES/teammates/assets/74132255/f4a271a9-959d-4692-b020-0a7e486f2085"></video>
=> [#11878] Add Edit and Approve Account Requests functionality

src/client/java/teammates/client/scripts/sql/DataMigrationForFeedbackSessionSql.java, src/client/java/teammates/client/scripts/sql/SeedDb.java, src/client/java/teammates/client/scripts/sql/VerifyCourseEntityCounts.java, src/client/java/teammates/client/scripts/sql/VerifyFeedbackSessionAttributes.java, src/main/java/teammates/common/util/HibernateUtil.java
- Added migration and verification script for feedback session.
- Added function to seed feedback sessions in `SeedDb.java`
Edit:
- Migration script initially took very long due to the need to fetch the course reference and set it in the new feedback session entity. 
- Added a function `getReference(entity class, id)` in `Hibernate.util` to use [EntityManager.getReference](https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManager.html#getReference-java.lang.Class-java.lang.Object-)  and use this instead of the normal `get`. Increased performance from nearly 1 hr to 1 minute for 30K entities. 
- Stats (tested on Google cloud):
| No of entities tested    | Seed time | Migration time | Verification …
=> [#12048]  Data migration for feedback session entities

src/test/java/teammates/sqllogic/core/AccountRequestsLogicTest.java, src/test/java/teammates/test/BaseTestCase.java
Part of #12048
* Rewrite tests for AccountRequestsLogicTest to be unit tests
=> [#12048] Migrate AccountRequestsLogicTest

src/main/java/teammates/storage/sqlentity/FeedbackSession.java
Part of #12048
**Context**
Using the @fetch annotation to eagerly fetching attributes can slow down operations by performing joins on 2 extra tables (deadlineExtension and feedbackResponseQuestion) even if these attributes are not required. This performance hit was seen during migration of feedbackSession entities #12986.
Remove @fetch annotation from deadlineExtensions and feedbackQuestions attributes to lazily load attributes.
=> [#12048] Remove feedbackSession attributes @fetch annotation

src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap, src/web/app/pages-admin/admin-home-page/admin-home-page.component.html, src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts, src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts, src/web/app/pages-admin/admin-home-page/instructor-data.ts, src/web/app/pages-admin/admin-home-page/new-instructor-data-row/__snapshots__/new-instructor-data-row.component.spec.ts.snap, src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.html, src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.spec.ts, src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.ts
Previously admin home page included a `registeredInstructorModal`.
This modal is only accessible if `createAccountRequest` returns a response with the http status code 409. 
The reponse would only have a 409 status code if `CreateAccountRequestAction` throws a `InvalidOperationException`. 
`CreateAccountRequestAction` used to throw a `InvalidOperationException` when a user tries to add an instructor that is already registered.
Since `CreateAccountRequestAction` no longer throws `InvalidOperationException`, this modal is no longer accessible.
All functions that are only used by the modal is removed in this pr.
=> [#11878] Remove unused modal in AdminHomePage

src/main/resources/db/changelog/db.changelog-v9.0.0.xml
Add a tag to the V9 liquibase changelog
Note: This changelog was not run on production since Hibernate had created the tables. Instead we have marked this changelog as "run" and deployed using the command `./gradlew liquibaseChangelogSync`. [Changelog Sync command](https://docs.liquibase.com/commands/utility/changelog-sync.html)
=> [#12048] Add v9.0.0 tag to liquibase changelog

src/e2e/java/teammates/e2e/cases/AdminHomePageE2ETest.java, src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java, src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java, src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java, src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java, src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java, src/main/java/teammates/sqllogic/core/DataBundleLogic.java, src/main/java/teammates/ui/webapi/DeleteAccountRequestAction.java, src/test/java/teammates/test/AbstractBackDoor.java, src/web/app/components/account-requests-table/account-request-table.component.ts, src/web/services/account.service.spec.ts, src/web/services/account.service.ts
=> [#11878] Update DeleteAccountRequest to reference by ID

src/e2e/java/teammates/e2e/cases/AdminHomePageE2ETest.java, src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java, src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java, src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java, src/it/java/teammates/it/ui/webapi/RejectAccountRequestActionIT.java, src/main/java/teammates/ui/webapi/GetAccountRequestAction.java, src/test/java/teammates/test/AbstractBackDoor.java
Part of #11878
Change Action to get account request by UUID
Update tests to fetch account requests by UUID
=> [#11878] Get account request by uuid

src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java, src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java, src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java, src/it/java/teammates/it/ui/webapi/CreateAccountActionIT.java, src/it/java/teammates/it/ui/webapi/GetCourseJoinStatusActionIT.java, src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
Tests were changed to reference account requests by ID. There were no longer any checks for account requests with the same email address and institute in `AccountRequestsDb::createAccountRequest`, so `AccountRequestsDbTest::testCreateAccountRequest_accountRequestAlreadyExists_createsSuccessfully` was removed. I do not think there is a way to check the behaviour through a unit test without that method. There is still an existing integration test that checks that exact behaviour when there are multiple account requests with the same email address and institute, so I think it's fine.
=> [#11878] Reference account requests by ID in tests

src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.ts
=> [#11878] Fix reject email content

src/main/resources/instructorEmailTemplate-newAccountRequestAcknowledgement.html, src/test/resources/emails/instructorNewAccountRequestAcknowledgementEmailWithComments.html, src/test/resources/emails/instructorNewAccountRequestAcknowledgementEmailWithNoComments.html
Part of #11878
Remove mention of home page URL in account request acknowledgement email as the form no longer takes in home page URL.
=> [#11878] Remove mention of home page URL in email

src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java, src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
Part of #11878
* Check that user is not logged in as admin in create account request action. Send acknowledgement email to instructor and notification email to admin only if the user is not admin.
* Add test case to check that no emails are sent for admin
=> [#11878] Check if account request is not created by admin before sending email

src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java, src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java, src/main/java/teammates/storage/sqlentity/BaseEntity.java, src/main/java/teammates/storage/sqlentity/User.java
Part of  #12048
Cascade migrate student
Verify migrated students
Change createdAt to be updatable
Remove creationTimeStamp annotation from createdAt
Reemove updateTimeStamp annotation from updatedAt
**Things left to do in other PR**
=> [#12048] data migration student chain students

src/client/java/teammates/client/scripts/sql/DataMigrationForTeamSql.java, src/client/java/teammates/client/scripts/sql/SeedDb.java, src/client/java/teammates/client/scripts/sql/VerifyCourseEntityCounts.java, src/client/java/teammates/client/scripts/sql/VerifyTeamAttributes.java
- Adjusted `SeedDb.java` for `teamName` seeding
- Added migration and verification scripts
- Used `root.fetch("sections")` to optimise fetching of `sections` field
| Entity  | Test counts | Migration Time | Verification Time |
|---------|-------------|----------------|-------------------|
| Team | 100 courses * 10 sections * 10 teams | 47s | 1m 4s |
=> [#12048] Data migration for team entities

src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java, src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
=> [#11878] Remove ref by email and institute

src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
Part of #11878
* Add SQL injection test cases for `AccountRequestsDb`:
* `CreateAccountRequest` comments field
* `getApprovedAccountRequestsForEmail`
=> [#11878] Add SQL injection tests for AccountRequestsDb

.github/workflows/axe.yml, .github/workflows/component.yml, .github/workflows/e2e-sql.yml, .github/workflows/e2e.yml, .github/workflows/jdk17.yml, .github/workflows/lnp.yml, .github/workflows/pr.yml
This reverts commit 186a97a2bc8efd5d5f350eacdb9288cad2dafc64.
Revert the GitHub action check as the last PR against feature branch.
=> [#11878] Revert "Enable CI on account request form branch"

src/web/app/pages-instructor/instructor-student-activity-logs/__snapshots__/instructor-student-activity-logs.component.spec.ts.snap, src/web/app/pages-instructor/instructor-student-activity-logs/instructor-student-activity-logs.component.html, src/web/app/pages-instructor/instructor-student-activity-logs/instructor-student-activity-logs.component.ts
Part of #11843 
- Fix not viewed since message
- Updated disclaimer message
=> [#11843] Fix front end bugs

src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java, src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java, src/main/java/teammates/storage/sqlentity/FeedbackResponse.java, src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java, src/main/java/teammates/storage/sqlentity/FeedbackSession.java
- Added methods for cascading migration of `FeedbackSession`, `FeedbackQuestion`, `FeedbackResponse` and `FeedbackResponseComment`
- Remove `@UpdateTimestamp` annotation for affected entities
Todo in other PRs:
=> [#12048] Data migration for feedback entities chain

src/client/java/teammates/client/scripts/sql/IndexCourseFields.java, src/main/appengine/index.yaml
Part of #12048
- Added composite indexes for `Course` entity in `index.yaml`
- Added `IndexCourseFields` script
=> [#12048] Add composite index for data migration

docs/schema-migration.md, src/main/resources/db/changelog/db.changelog-root.xml, src/main/resources/db/changelog/db.changelog-v9.0.0-beta.5.xml, src/main/resources/db/changelog/db.changelog-v9.0.0.beta.5.xml
Part of #12048
**Context**
Previously I mentioned that liquibase runs changelogs in alphanumeric order, but this is incorrect. Changelogs are run in numeric order if the [includeAll tag](https://docs.liquibase.com/change-types/includeall.html) is used to run changelogs. In Teammates, we use the [include tag](https://docs.liquibase.com/change-types/include.htm) which runs in the order they are placed in the `changelog-root.xml` file
- Amend documentation to remind devs to add newest changelog to bottom of file.
- Rename changelog name and tag name
Note: I'll update the Teammates Ops process which is more critical
=> [#12048] Update changelog docs and changelog name

src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java, src/client/java/teammates/client/scripts/sql/SeedDb.java, src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
- Added methods to seed and verify feedback chain entities
- Constraints - only seeds: 
- `FeedbackTextQuestions`, with
- `giverType = STUDENTS`, and
- `recipientType = INSTRUCTORS`
- Tested for `MAX_RESPONSE_COUNT` values of -1 and 1000
=> [#12048] Add seed and verification scripts for feedback chain

src/main/java/teammates/ui/request/AccountCreateRequest.java, src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java, src/web/app/pages-static/request-page/instructor-request-form/__snapshots__/instructor-request-form.component.spec.ts.snap, src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.html, src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.spec.ts, src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts, src/web/app/pages-static/request-page/request-page.module.ts
* Add CAPTCHA to create account request form
=> [#11878] Add CAPTCHA to ARF

src/web/app/components/account-requests-table/account-request-table.component.ts, src/web/services/account.service.ts
=>  [#13064] Use AccountRequestUpdateRequest as parameter  

src/client/java/teammates/client/scripts/sql/PatchCreatedAtAccountRequest.java, src/client/java/teammates/client/scripts/sql/PatchCreatedAtTimeNotification.java, src/client/java/teammates/client/scripts/sql/VerifyAccountRequestAttributes.java, src/client/java/teammates/client/scripts/sql/VerifyNotificationAttributes.java
Part of #12048
**Context**
Previously during the non-course migration, `createdAt` was not migrated due to having the `@createdTimestamp` annotation. This was removed in the v9-course-migration branch and can be used for this as well.
Add 2 scripts based of `PatchDataMigrationForUsageStatisticsSql` to fetch existing account requests and notifications using fields which are identifiers for the entity and amend their `createdAt` timestamp. Most of the changes are in `MigrateEntity` method. Verification Scripts can handle the case where an entity exist in postgres but not in datastore (since we have started created new account requests and notification in postgres)
Fields which are identifiers
- notifications: title
- accountRequest: email and institute
=> [#12048] Add patch script for account request and notifications to amend createdAt field

src/client/java/teammates/client/scripts/sql/SeedDb.java
Part of #12048
Remove datastore deletion code (used to clear local datastore when re-seeding test data), to prevent any carelessness
=> [#12048] Remove clear datastore function

src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java, src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java, src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql50Newest.java, src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql50Oldest.java, src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
Disables optimization for migration of feedback responses.
=> [#12048] Hot fix for migration

src/client/java/teammates/client/scripts/sql/PatchCreatedAtAccountRequest.java
Part of #12048
- Add registration key when querying account requests (likely to be unique)
=> [#12048] Add unique field to patch account request timestamp script

src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql50Newest.java, src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql50Oldest.java, src/main/java/teammates/storage/sqlentity/User.java
Fixes #12048
Deletes constraint for email and course id
=> [#12048] Delete redundant index

src/client/java/teammates/client/scripts/sql/DeleteDanglingCourseScript.java, src/client/java/teammates/client/scripts/sql/SeedDb.java
Part of #12048
When `DataMigrationForCourseEntitySql.java` script is stopped abruptly, there may be dangling course entities related to the last migrated course, leaving the course in a half migrated state.
Created `DeleteDanglingCourseScript.java` to clean up any entities related to this partially migrated entity.
=> [#12048] Add dangling course delete script

src/web/app/pages-student/student-home-page/student-home-page.component.ts
Fixes #12875
Removed the duplicate invocation of `loadFeedbackSessionsForCourse()` in both `sortCoursesBy()` and `loadStudentCourses()`.
Kept the call to `loadFeedbackSessionsForCourse()` inside `sortCourseBy()` method to handle the sorting and loading in one place.
=> [#12875] Some feedback sessions duplicated in student home page

src/web/app/components/question-types/question-statistics/mcq-question-statistics.component.ts, src/web/app/components/question-types/question-statistics/msq-question-statistics.component.ts, src/web/app/components/question-types/question-statistics/question-statistics-calculation/msq-question-statistics-calculation.ts, src/web/app/components/question-types/question-statistics/test-data/msqQuestionResponses.json
Fixes #12894
Following the discussion in #12894, I modified `msq-question-statistics.component.ts` to take recipient emails into account.
I also updated the code in `msq-question-statistics.component.ts` to be more in line with the code in `mcq-question-statistics.component.ts`, calling `toFixed(2)` to format the values in the table.
In addition, I changed the tests to reflect the change from indexing students by name to indexing them by email.
I'd like to credit the authors of #12981, as I used their work to formulate my solution.
=> [#12894] Calculate msq totals by student email instead of name

src/web/app/components/session-edit-form/session-edit-form.component.html, src/web/app/components/session-edit-form/session-edit-form.component.spec.ts, src/web/app/components/session-edit-form/session-edit-form.component.ts
Fixes #12655
Added logic to ensure that when the submission opening date and time are changed, the session visibility date and time are also adjusted if necessary.
Introduced `configureSessionVisibleDateTime` to adjust the session visibility date and time if they are earlier than the submission opening date and time.
https://github.com/user-attachments/assets/5ad14748-5aa9-4be6-8af7-187f0921debd
=> [#12655] Instructor Edit Session Page: If make session visible is later than submission opening time, automatically default to opening time

src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
Fixes #13147
Added `.tz()` to account for the timezones when comparing the datetimes.
=> [#13147] Didn't Account for the Timezone in Session Edit Form component tests

src/web/app/pages-static/request-page/instructor-request-form/__snapshots__/instructor-request-form.component.spec.ts.snap, src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.html
Fixes #13122 
* Add a Cancel button next to the Submit button so users can undo their form request and return to the homepage.
* Added accessibility features to both cancel and submit button
**UI changes**
=> [#13122] Create cancel button for instructor request form

src/web/app/pages-static/contact-page/contact-page.component.html
Fixes #12375
Changed the text hyperlinked to the TEAMMATES GitHub on the contact page to be Project Website to be consistent with the phrasing used on the [NUS-OSS](https://nus-oss.github.io/index.html#projects) projects page.
=> [#12375] Update phrasing of contact page

src/main/java/teammates/ui/webapi/DeleteAccountAction.java, src/test/java/teammates/sqlui/webapi/DeleteAccountActionTest.java
Change DeleteAccountActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for DeleteAccountActionTest

src/test/java/teammates/sqlui/webapi/DeleteFeedbackQuestionActionTest.java
Change DeleteFeedbackQuestionActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for DeleteFeedbackQuestionActionTest

src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
Fixes #13104
Made the dictionary of mappings in [3f5f68d](https://github.com/TEAMMATES/teammates/commit/3f5f68dc971ebabc2eb0f5d8541a24b36d716807) more extensive, covering more countries and cases.
Updated mappings:
```javascript
const countryMapping: { [key: string]: string } = {
'united states': 'USA',
'u.s.a': 'USA',
'u.s.a.': 'USA',
us: 'USA',
america: 'USA',
'united states of america': 'USA',
'united kingdom': 'UK',
uk: 'UK',
britain: 'UK',
'great britain': 'UK',
england: 'UK',
'united arab emirates': 'UAE',
uae: 'UAE',
emirates: 'UAE',
deutschland: 'Germany',
germany: 'Germany',
netherlands: 'Netherlands',
'the netherlands': 'Netherlands',
nederland: 'Netherlands',
holland: 'Netherlands',
belgium: 'Belgium',
belgië: 'Belgium',
brazil: 'Brazil',
brasil: …
```
=> [#13104] Add mappings

src/main/java/teammates/common/util/StringHelper.java, src/main/java/teammates/common/util/TimeHelper.java
Fixes #8557 
```shell
OS: macOS Sonoma 14.2.1 arm64
Host: MacBook Pro (14-inch, 2021)
Locale: en_GB.UTF-8, de_DE.UTF-8
```
When running tests locally, some tests fail because of differences in locale, like `teammates.common.util.TimeHelperTest.testGetMidnightAdjustedInstantBasedOnZone`. Even though this might not be a problem when running tests as part of a workflow, it might cause confusion to some users who are running tests locally and encountering errors.
Testing on `en_GB.UTF-8`:
```shell
org.gradle.internal.serialize.PlaceholderAssertionError: expected: <Sun, 29 Nov 2015, 11:59 PM UTC> but was: <Sun, 29 Nov 2015, 11:59 pm UTC>
```
Testing on `de_DE.UTF-8`:
```shell
org.gradle.internal.serialize.PlaceholderAssertionError: expected: <Sun, 29 Nov 2015, 11:59 PM UTC> but was: <So., 29 …
```
=> [#8557] Standardize locale

src/test/java/teammates/sqlui/webapi/DeleteFeedbackSessionActionTest.java, src/test/java/teammates/sqlui/webapi/EnrollStudentsActionTest.java
Change EnrollStudentsActionTest.java and DeleteFeedbackSessionActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests

src/test/java/teammates/sqlui/webapi/DeleteStudentsActionTest.java, src/web/app/pages-static/contact-page/contact-page.component.html
Part of [#12048](https://github.com/TEAMMATES/teammates/issues/12048)
Migrated `DeleteStudentsActionTest` to use SQL-based logic instead of the previous Datastore model.
=> [#12048] Migrate Tests for DeleteStudentsActionTest

src/test/java/teammates/sqlui/webapi/DeleteStudentActionTest.java
Part of [#12048](https://github.com/TEAMMATES/teammates/issues/12048)
Migrated `DeleteStudentActionTest` to use SQL-based logic instead of the previous Datastore model.
=> [#12048] Migrate Tests for DeleteStudentActionTest

src/main/java/teammates/ui/webapi/GetAccountsAction.java, src/test/java/teammates/sqlui/webapi/GetAccountsActionTest.java
Change GetAccountsActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for GetAccountsAction.java

src/test/java/teammates/sqlui/webapi/BaseActionTest.java, src/test/java/teammates/sqlui/webapi/MarkNotificationAsReadActionTest.java
Part of #12048
Added the unit tests for MarkNotificationAsReadActionTest for PostgreSQL.
=> [#12048] Migrate tests for MarkNotificationAsReadActionTest

docs/development.md, docs/search.md
=> [#13160] Update documentation to use Docker Compose v2

src/test/java/teammates/sqlui/webapi/BaseActionTest.java, src/test/java/teammates/sqlui/webapi/GetReadNotificationsActionTest.java
Part of #12048
Added the unit tests for GetReadNotificationsActionTest for PostgreSQL.
=> [#12048] Migrate tests for GetReadNotificationsActionTest

src/test/java/teammates/sqlui/webapi/BaseActionTest.java, src/test/java/teammates/sqlui/webapi/GetNotificationActionTest.java
Part of #12048
Added the unit tests for GetNotificationActionTest for PostgreSQL.
PS: This is not a duplicate of #13219 if anyone gets confused by the similar name
=> [#12048] Migrate tests for GetNotificationActionTest

src/main/java/teammates/ui/webapi/GetUsageStatisticsAction.java, src/test/java/teammates/sqlui/webapi/GetUsageStatisticsActionTest.java
Part of #12048
Added the unit tests for GetUsageStatisticsActionTest for PostgreSQL.
=> [#12048] Migrate tests for GetUsageStatisticsActionTest

src/test/java/teammates/sqlui/webapi/DeleteFeedbackQuestionActionTest.java
To address comments from #13231, changed `DeleteFeedbackQuestionActionTest.java` to remove dependencies between each test case by using a `setUp()` method instead of a shared variable.
=> [#12048] Refactor tests for DeleteFeedbackQuestionActionTest

src/test/java/teammates/sqlui/webapi/BaseActionTest.java, src/test/java/teammates/sqlui/webapi/GetNotificationsActionTest.java
Part of #12048
Added the unit tests for GetNotificationsActionTest for PostgreSQL.
PS: This is not a duplicate of #13210 if anyone gets confused by the similar name
=> [#12048] Migrate tests for GetNotificationsActionTest

src/main/java/teammates/ui/webapi/GetAccountAction.java, src/test/java/teammates/sqlui/webapi/GetAccountActionTest.java
Change GetAccountActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for GetAccountActionTest

src/test/java/teammates/sqlui/webapi/CreateFeedbackQuestionActionTest.java
Change CreateFeedbackQuestionActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for CreateFeedbackQuestionActionTest

src/test/java/teammates/logic/api/MockEmailSender.java
Fixes #13261
- Added a `shouldFail` class field.
- Updated `sendEmail(email)` to check `shouldFail` during execution.
- Implemented `setShouldFail(boolean shouldFail)` method to manually toggle email sending failure.
=> [#13261] Implement Email Sending Failure Behavior in MockEmailSender

src/main/java/teammates/storage/sqlentity/Student.java
Fixes #13263 
Modified `getTeamName()`, `getSectionName()`, and `getSection()` to safely handle `null` values before accessing team properties.
=> [#13263] Add null checks to methods in Student class

src/main/java/teammates/ui/webapi/SendErrorReportAction.java, src/test/java/teammates/sqlui/webapi/SendErrorReportActionTest.java
=> [#12048] Migrate tests for SendErrorReportActionTest

src/main/java/teammates/ui/webapi/GetAuthInfoAction.java, src/main/java/teammates/ui/webapi/JsonResult.java, src/test/java/teammates/sqlui/webapi/GetAuthInfoActionTest.java
Change GetAuthInfoActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
Excluded tests where admin masquerades as user, because the user database cannot be accessed in the test.
=> [#12048] Migrate tests for GetAuthInfoActionTest

src/main/java/teammates/ui/webapi/ResetAccountRequestAction.java, src/test/java/teammates/sqlui/webapi/ResetAccountRequestActionTest.java
Change ResetAccountRequestActionTest to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for ResetAccountRequestActionTest

src/main/java/teammates/common/datatransfer/attributes/DeadlineExtensionAttributes.java, src/test/java/teammates/sqlui/webapi/GetDeadlineExtensionActionTest.java, src/test/java/teammates/test/BaseTestCase.java
Part of #12048
Added the unit tests for GetDeadlineExtensionActionTest for PostgreSQL.
=> [#12048] Migrate tests for GetDeadlineExtensionActionTest

src/test/java/teammates/sqlui/webapi/GetSessionResponseStatsActionTest.java
Change GetSessionResponseStatsActionTest to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for GetSessionResponseStatsActionTest

src/test/java/teammates/sqlui/webapi/ResetAccountActionTest.java
Change ResetAccountActionTest to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for ResetAccountActionTest

src/test/java/teammates/sqlui/webapi/GetInstructorsActionTest.java
Change GetInstructorsAction.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for GetInstructorsActionTest

src/test/java/teammates/sqlui/webapi/ActionFactoryTest.java
Migrate ActionFactoryTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for ActionFactoryTest

src/main/java/teammates/ui/webapi/GetHasResponsesAction.java
Fixes #13287 
Modified the code that uses `logic` instead of `sqlLogic`, when it is supposed to use `sqlLogic`, along the path where the `Course` is migrated.
=> [#13287] Fix GetHasResponsesAction

src/main/java/teammates/ui/webapi/GetHasResponsesAction.java, src/test/java/teammates/sqlui/webapi/GetHasResponsesActionTest.java
Change GetHasResponsesActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for GetHasResponsesActionTest

src/main/java/teammates/sqllogic/api/Logic.java, src/main/java/teammates/ui/webapi/Action.java, src/test/java/teammates/sqlui/webapi/BaseActionTest.java, src/test/java/teammates/sqlui/webapi/CompileLogsActionTest.java, src/test/java/teammates/sqlui/webapi/SendLoginEmailActionTest.java, src/test/java/teammates/sqlui/webapi/SessionLinksRecoveryActionTest.java
Migrate SessionLinksRecoveryActionTest
=> [#12048] Migrate tests for SessionLinksRecoveryAction

src/it/java/teammates/it/ui/webapi/FeedbackSessionClosingSoonRemindersActionIT.java, src/main/java/teammates/storage/api/FeedbackSessionsDb.java, src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
Fixes #13275 
1. Add a comment to explain the rationale behind using a 2-day offset in `getInstantDaysOffsetFromNow(-2)`.
2. Update the query to check for `isClosedEmailSent`, preventing closing soon email from being sent if the closed email has previously been sent.
=> [#13275] Fix potential incorrect sending of closing soon email

src/main/java/teammates/ui/webapi/UpdateStudentAction.java, src/test/java/teammates/sqlui/webapi/UpdateStudentActionTest.java
Migrated `UpdateStudentActionTest` to use SQL-based logic instead of the previous Datastore model.
=> [#12048] Migrate Tests for UpdateStudentActionTest

src/test/java/teammates/sqlui/webapi/UnpublishFeedbackSessionActionTest.java
Change UnpublishFeedbackSessionActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
=> [#12048] Migrate tests for UnpublishFeedbackSessionActionTest

src/e2e/java/teammates/e2e/cases/sql/BaseFeedbackQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackMcqQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackMsqQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackNumScaleQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackRankOptionQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackRubricQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackTextQuestionE2ETest.java, src/e2e/java/teammates/e2e/pageobjects/InstructorCourseStudentDetailsEditPageSql.java, src/e2e/java/teammates/e2e/pageobjects/InstructorCourseStudentDetailsViewPageSql.java, src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java, src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPageSql.java
Part of #13324 
- Added missing methods to `InstructorFeedbackEditPageSql`.
- Removed SQL-based methods from `InstructorFeedbackEditPage`.
- Updated all migrated tests to reference `InstructorFeedbackEditPageSql` instead of `InstructorFeedbackEditPage`.
- Cleaned up code in `InstructorCourseStudentDetailsEditPageSql` and `InstructorCourseStudentDetailsViewPageSql`.
=> [#13324] Migrate to InstructorFeedbackEditPageSql

src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
Fixes #13331
Moved the `<b>&nbsp;</b>`(non breaking space) character outside of the `<a>` tag.
Also replaced the `<b>` tag from around the `&nbsp;` character with `<span>` tag as making the space bold doesn't make sense.
=> [#13331] Remove extra underline under whitespace

src/e2e/java/teammates/e2e/cases/sql/BaseFeedbackQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackMcqQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackMsqQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackNumScaleQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackRankOptionQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackRubricQuestionE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/FeedbackTextQuestionE2ETest.java, src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPageSql.java
Part of #13324 
- Removed SQL-based methods from `FeedbackSubmitPage`.
- Updated all migrated tests to reference `FeedbackSubmitPageSql` instead of `FeedbackSubmitPage`.
=> [#13324] Migrate to FeedbackSubmitPageSql

src/e2e/java/teammates/e2e/cases/sql/AdminSearchPageE2ETest.java, src/e2e/java/teammates/e2e/pageobjects/AdminSearchPageSql.java
Part of #13324
- Migrated SQL-based methods to `AdminSearchPageSql`.
- Updated the migrated test to reference `AdminSearchPageSql` instead of `AdminSearchPage`.
=> [#13324] Migrate to AdminSearchPageSql

src/e2e/java/teammates/e2e/cases/sql/AdminNotificationsPageE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/BaseE2ETestCase.java, src/e2e/resources/data/AdminNotificationsPageE2ETestSql.json, src/e2e/resources/testng-e2e-sql.xml
- Migrated `AdminNotificationsPageE2ETest` to use SQL-based logic instead of the previous Datastore model.
- Alphabetize E2E tests in `testng-e2e-sql.xml`.
=> [#12048] Migrate Tests for AdminNotificationsPageE2ETest

src/e2e/java/teammates/e2e/cases/sql/FeedbackConstSumOptionQuestionE2ETest.java, src/e2e/resources/data/FeedbackConstSumOptionQuestionE2ETestSql.json, src/e2e/resources/testng-e2e-sql.xml
Part of #12048
- Migrated `FeedbackConstSumOptionQuestionE2ETest` to use SQL-based logic instead of the previous Datastore model.
=> [#12048] Migrate Tests for FeedbackConstSumOptionQuestionE2ETest

src/e2e/java/teammates/e2e/cases/sql/BaseE2ETestCase.java, src/e2e/java/teammates/e2e/cases/sql/InstructorCourseJoinConfirmationPageE2ETest.java, src/e2e/java/teammates/e2e/cases/sql/InstructorHomePageE2ETest.java, src/e2e/java/teammates/e2e/pageobjects/InstructorHomePageSql.java, src/e2e/resources/data/InstructorCourseJoinConfirmationPageE2ETestSql.json, src/e2e/resources/testng-e2e-sql.xml
Part of #12048
- Migrated `InstructorCourseJoinConfirmationPageE2ETest` to use SQL-based logic instead of the previous Datastore model.
- Migrated `InstructorHomePage` to `InstructorHomePageSql`.
- Add methods to get registration key for `Instructor` and `Student` in `sql\BaseE2ETestCase`.
=> [#12048] Migrate Tests for InstructorCourseJoinConfirmationPageE2ETest
