TEAMMATES/teammates

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.91 #6165

- src/main/java/teammates/logic/api/Logic.java
- src/main/java/teammates/logic/core/AccountsLogic.java
- src/main/java/teammates/logic/core/ProfilesLogic.java
- src/main/java/teammates/logic/core/StudentsLogic.java
- src/test/java/teammates/test/cases/logic/AccountsLogicTest.java
- src/test/java/teammates/test/cases/logic/ProfilesLogicTest.java
> Add ProfilesLogic and ProfilesLogicTest classes #6168

- src/main/webapp/about.jsp
- src/main/webapp/contact.jsp
- src/main/webapp/features.jsp
- src/main/webapp/index.jsp
- src/main/webapp/request.jsp
- src/main/webapp/stylesheets/teammates.css
- src/main/webapp/terms.jsp
- src/main/webapp/usermap.jsp
> id="caption" in static pages should be class instead #6190

- src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackSubmitPageUiTest.java
- src/test/java/teammates/test/cases/ui/browsertests/StudentFeedbackSubmitPageUiTest.java
- src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java
- src/test/java/teammates/test/pageobjects/InstructorCourseDetailsPage.java
- src/test/java/teammates/test/pageobjects/InstructorStudentRecordsPage.java
- src/test/resources/pages/instructorCommentsPageAddFrc.html
Fixes #6215 
Manually ensured that dev green is reached in both Windows and OSX.
> Fix unstable tests due to rich-text support for comments #6215

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.92 #6219

- src/main/webapp/WEB-INF/queue.xml
Fixes #6274 
i could't find out on which branch i should push , sorry about that.
> Remove "default" and "search-document" entries from queue.xml #6274

- src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java
- src/test/resources/emails/systemCrashReportEmail.html
- src/test/resources/emails/systemCrashReportEmailLessInfo.html
> EmailGeneratorTest failing due to change in year #6287

- src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
- src/main/webapp/WEB-INF/tags/instructor/results/filterPanel.tag
- src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java
> Typo in Const.java NO_SPECIFIC_RECEIPIENT #6183

- src/test/java/teammates/test/cases/logic/TaskQueuesLogicTest.java
> Disable TaskQueuesLogicTest #6304

- src/main/webapp/index.jsp
- src/main/webapp/js/index.js
> Update feedback entry count to 5 million #6319

- src/main/webapp/js/userMapData.json
> Invalid JSON in userMapData.json #6341

- src/main/webapp/instructorHelp.jsp
> instructorHelp.jsp: Reorder entries in Table of Contents #6328

- src/main/java/teammates/ui/controller/InstructorFeedbackRemindParticularStudentsAction.java
> "magic" string in "InstructorFeedbackRemindParticularStudentsAction" #6353

- src/main/webapp/WEB-INF/tags/staticPage.tag
Fixes #6376 Opening HTML tag added.
> staticPage.tag missing opening HTML tag #6376

- src/main/java/teammates/logic/api/Logic.java
- src/main/java/teammates/logic/core/CoursesLogic.java
- src/test/java/teammates/test/cases/logic/CoursesLogicTest.java
Fixes #6378 as the beginner PR
> Remove unused methods in CoursesLogic #6378

- build.gradle
- src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
Made a few refactorings for #5780
> Refactor FeedbackSessionsLogic.java #5780

- src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageData.java
- src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html
- src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiverTeam.html
> Change "Received Responses Statistics" to "Statistics for Received Responses" #3245

- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/ui/controller/InstructorStudentCommentAddAction.java
- src/test/java/teammates/test/cases/ui/InstructorStudentCommentAddActionTest.java
- src/test/java/teammates/test/cases/ui/browsertests/InstructorCourseDetailsPageUiTest.java
- src/test/java/teammates/test/cases/ui/browsertests/InstructorStudentRecordsPageUiTest.java
- src/test/resources/pages/instructorStudentRecordsPageAddComment.html
Fixes #1426  
**Problem**
Comment status messages too generic.
**Solution**
Use String.format to add comment excerpt into status messages.
> instructorStudentComment: Give more informative status messages #1426

- .travis.yml
Fixes #6427 
Adapted from https://github.com/tirodkar/EarlGrey/blob/3b38a5dea36a88aba42a42931e77a7c5429a1837/.travis.yml#L65
> Do not trigger CI build for documentation-only changes #6427

- src/main/java/teammates/ui/template/StudentListSectionData.java
- src/main/webapp/WEB-INF/tags/instructor/studentList.tag
- src/test/java/teammates/test/cases/pagedata/InstructorStudentListAjaxPageDataTest.java
- src/test/resources/data/InstructorStudentListPageUiTest.json
- src/test/resources/pages/instructorStudentListPageHideArchivedCourses.html
- src/test/resources/pages/instructorStudentListPageSearchStudentMultiple.html
- src/test/resources/pages/instructorStudentListPageWithPicture.html
- src/test/resources/pages/instructorStudentListWithHelperView.html
> Instructor Student List Page: Properly display sanitised text for Section Filter #5923

- src/test/java/teammates/test/pageobjects/InstructorStudentListPage.java
- src/test/resources/pages/instructorStudentList.html
- src/test/resources/pages/instructorStudentListPageDisplayArchivedCourses.html
Fixes #6446
Sorry about the trouble caused!
> InstructorStudentListPageUiTest failing at dev server #6446

- src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
- src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackSaveAction.java
- src/main/java/teammates/ui/controller/InstructorEditStudentFeedbackSaveAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackQuestionAddAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackQuestionVisibilityMessageAction.java
> Change HttpRequestHelper.getValueFromParamMap to getRequestParamValue in *Action classes #5572

- src/test/resources/test.template.properties
> Instructions for enabling GodMode are outdated #6466

- src/main/webapp/js/userMapData.json
> Update user map for Dec 2016 #6297

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.94 #6477

- src/main/webapp/instructorHelp.jsp
- src/main/webapp/jsp/adminEmailLog.jsp
> Duplicate "the" in jsp files #6460

- src/main/webapp/WEB-INF/appengine-web.template.xml
Fixes #6501
Add instance-class option in appengine config template
> Upgrade instance class to F2 #6501

- src/main/webapp/WEB-INF/tags/admin/activity/filterPanel.tag
> Duplicate "the" in filterPanel.tag #6461

- src/main/webapp/js/common.js
- src/test/javascript/CommonJsTest.js
- src/test/resources/pages/allJsUnitTests.html
> Improve isWithinView in common.js #5937

- src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java
- src/test/java/teammates/test/cases/browsertests/FeedbackConstSumRecipientQuestionUiTest.java
- src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java
- src/test/java/teammates/test/cases/browsertests/FeedbackMcqQuestionUiTest.java
- src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
- src/test/java/teammates/test/cases/browsertests/FeedbackNumScaleQuestionUiTest.java
- src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
- src/test/java/teammates/test/cases/browsertests/FeedbackRubricQuestionUiTest.java
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
- src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Fixes #6473
~~Work in progress~~
Files that hardcode `-1` yet to refactor:
~~`FeedbackConstSumOptionQuestionUiTest.java`~~
~~`FeedbackConstSumRecipientQuestionUiTest.java`~~
~~`FeedbackContributionQuestionUiTest.java`~~
~~`FeedbackMcqQuestionUiTest.java`~~
~~`FeedbackMsqQuestionUiTest.java`~~
~~`FeedbackNumScaleQuestionUiTest.java`~~
~~`FeedbackRankQuestionUiTest.java`~~
~~`FeedbackRubricQuestionUiTest.java`~~
~~`InstructorFeedbackEditPageUiTest.java`~~
All done!
> InstructorFeedbackEditPage uses -1 as question number of the new question #6473

- src/test/java/teammates/test/cases/action/InstructorCourseRemindActionTest.java
Fixes #6516 
Ready for review.
> InstructorCourseRemindActionTest: refactor duplicated code #6516

- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/ui/controller/StudentCourseJoinAction.java
- src/test/java/teammates/test/cases/action/StudentCourseJoinActionTest.java
> Deleted students trying to join: handle the NPE #5931

- src/main/webapp/contact.jsp
Fixes #6458 
' submit to above mail address '  has been changed to 'submit to the above mail address'
> Minor error under "Bug reports and feature requests" in contact.jsp #6458

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.95 #6555

- src/main/java/teammates/ui/controller/InstructorCourseRemindAction.java
- src/test/java/teammates/test/cases/action/InstructorCourseRemindActionTest.java
Fixes #6513
Originally, the emails are generated just to extract username and registration key. This process is removed and the data for logging is captured from the *Attribute objects directly.
> InstructorCourseRemindAction: extractUserName may not return username correctly #6513

- src/main/java/teammates/ui/controller/InstructorCourseDeleteAction.java
- src/main/java/teammates/ui/controller/InstructorCourseStudentDeleteAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackRemindAction.java
Fixes #6498 
Made it extend to `Action` class.
> Wrong usage of Inheritance in *action classes #6498

- .codecov.yml
> Enhancement: Enhance Codecov configuration #6590

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.96 #6607

- src/main/java/teammates/common/util/StatusMessage.java
> Use enum instead of string for status message colors #6512

- src/main/webapp/js/checkBrowserVersion.js
- src/main/webapp/js/index.js
Fixes #6648 , plus some minor additional cleanup.
Ready for review.
> Migrate all JS used by index page to strict mode #6648

- src/main/java/teammates/storage/api/EntitiesDb.java
Fixes #6668
Removed the method createAndReturnEntities as requested.
> Remove method createAndReturnEntities from EntitiesDb.java #6668

- src/main/webapp/dev/AdminHomeJsTest.js
- src/main/webapp/dev/allJsUnitTests.jsp
- src/main/webapp/js/adminHome.js
Fixes #6616 
Refactored some parts of adminHome.js because there were duplicated code. Then had to write tests for it. It's pretty comprehensive so changing this component to es6 syntax would be pretty easy now.
> Add tests for adminHome.js #6616

- src/main/webapp/js/datepicker.js
2/3/2017
Fixes #6700 
added comments for `@return` statements
> Unused @returns documentation tags in datepicker.js #6700

- src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
- src/main/webapp/index.jsp
> Update number of contributors in index.jsp #6561

- .github/template-bugReport.md
- .github/template-featureRequest.md
- docs/issues.md
Fixes #6631 
As per lined out in the issue thread.
> Issue templates: remove the requirement for issue title prefixes #6631

- src/main/java/teammates/logic/api/Logic.java
- src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
- src/main/java/teammates/ui/controller/InstructorFeedbackQuestionCopyAction.java
- src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
Fixes #6440 
> Updated all files calling `copyFeedbackQuestion()`, as well as declaration in [`teammates/logic/core/FeedbackQuestionsLogic`](https://github.com/domdomegg/teammates/blob/b2f96a40622b088651d7ba317ec00cf3487de11e/src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java#L90)
> Remove unused parameter in FeedbackQuestionsLogic.java #6440

- docs/settingUp.md
Changed the instruction Import existing project to Import project in #6724 
Fixes #6724
This is my first PR in teammates.I hope that I made the necessary changes to resolve this issue. Please review my change and tell me if it needs any modifications.
Thank You :)
> Setup guide: Change `Import existing project` to `Import project` #6724

- docs/process.md
1. Process document: Remove the requirement for branch name for forks #6736   
2. Fixes #6736
> Process document: Remove the requirement for branch name for forks #6736

- src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
- src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
Fixes #6576
Refactor 236-line method `getFeedbackSessionResultsForUserWithParams` to increase readability and maintainability.
> Refactor FeedbackSessionsLogic#getFeedbackSessionResultsForUserWithParams #6576

- src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
Fixes #6558
The two methods are extracted into a nested static class. 
Calculation for both arrays are done in the constructor of the nested static class.
> FeedbackRubricQuestionDetails: Refactor calculateRubricStats #6558

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.98 #6749

- docs/development.md
Hello! I'm new to Github and practicing how to contribute to open-source projects.
Fixes #6752 
> Changed 'Play' to 'Run...' in line 60 in development.md
> Change `Play` to `Run...` in development.md #6752

- src/main/java/teammates/common/util/ActivityLogEntry.java
- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
- src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java
- src/main/java/teammates/ui/template/AdminActivityLogTableRow.java
- src/main/webapp/WEB-INF/tags/admin/activity/activityLogTable.tag
- src/main/webapp/WEB-INF/tags/admin/activity/activityLogTableRow.tag
- src/main/webapp/WEB-INF/tags/admin/activity/filterPanel.tag
- src/main/webapp/js/adminActivityLog.js
- src/main/webapp/jsp/adminActivityLog.jsp
- src/main/webapp/jsp/adminActivityLogAjax.jsp
- src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java
- src/test/java/teammates/test/cases/util/ActivityLogEntryTest.java
- src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java
- src/test/resources/data/typicalLogMessage.json
Fixes #6503 
Continue from #6507
`ActivityLogEntry` will be refactored soon (#6531).
> Separate the UI part and logic part in ActivityLogEntry #6503

- docs/settingUp.md
Fixes #6722 
* Move indentation configuration instructions after instructions for importing the project.
> Reorder syntax validation instructions in setup guide #6722

- src/main/webapp/index.jsp
Fixes #6741 
> As per the discussion, the agreed solution is to update the very old and deprecated [Youtube AS2 API](https://youtube.googleapis.com/v/mDtfmNmRwBM&hd=1&autoplay=1&rel=0) link to use the new [Youtube IFrame Player API](https://www.youtube.com/embed/mDtfmNmRwBM?autoplay=1&rel=0).
**Caveats**
* No equivalent for deprecated parameter `hd=1` in the new Youtube IFrame API
**Suggested Workaround**
I suggest that we no longer need to force the player to play in HD as Youtube will automatically detect a suitable quality the video will play for the user.
If we do need to force the quality, we can only use undocumented methods that are unguaranteed to work or the use of the API's Javascript functions([Playback_Quality](https://developers.google.com/youtube/ifram …
> Video tour doesn't open on Chrome #6741

- src/client/java/teammates/client/scripts/DataMigrationForIsArchivedAttribute.java
- src/client/java/teammates/client/scripts/PerformanceProfiler.java
- src/main/java/teammates/logic/api/Logic.java
- src/main/java/teammates/logic/core/CommentsLogic.java
- src/main/java/teammates/storage/api/AccountsDb.java
- src/main/java/teammates/storage/api/CommentsDb.java
- src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java
- src/main/java/teammates/storage/api/FeedbackResponsesDb.java
- src/main/java/teammates/storage/api/FeedbackSessionsDb.java
- src/main/java/teammates/storage/api/InstructorsDb.java
- src/main/java/teammates/storage/api/StudentsDb.java
- src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java
- src/main/java/teammates/ui/controller/InstructorCommentsPageAction.java
- src/main/java/teammates/ui/controller/LoginServlet.java
- src/test/java/teammates/test/cases/browsertests/InstructorCourseStudentDetailsEditPageUiTest.java
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackPageUiTest.java
- src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
- src/test/java/teammates/test/driver/PriorityInterceptor.java
- static-analysis/teammates-checkstyle.xml
Fixes #6813 
> Add CheckStyle rule `CommentsIndentation`
> Add CheckStyle rule CommentsIndentation #6813

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.99 #6822

- .idea/runConfigurations/Staging_Tests.xml
> Add staging test configuration for IntelliJ #6824

- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/common/util/EmailLogEntry.java
- src/main/java/teammates/common/util/StringHelper.java
- src/main/java/teammates/ui/controller/AdminEmailLogPageAction.java
- src/main/java/teammates/ui/pagedata/AdminEmailLogPageData.java
- src/main/java/teammates/ui/template/AdminEmailTableRow.java
- src/main/webapp/WEB-INF/tags/admin/email/log/emailLogTable.tag
- src/main/webapp/WEB-INF/tags/admin/email/log/emailLogTableRow.tag
- src/main/webapp/WEB-INF/tags/admin/email/log/filterPanel.tag
- src/main/webapp/js/adminEmailLog.js
- src/main/webapp/jsp/adminEmailLog.jsp
- src/main/webapp/jsp/adminEmailLogAjax.jsp
- src/test/java/teammates/test/cases/util/EmailLogEntryTest.java
- src/test/java/teammates/test/cases/util/StringHelperTest.java
Fixes #6753 
> 1. This one would be very similar to #6503 
**What I have done:**
> 1. Separate the UI and Logic
> 1. Add a helper method `join` in `StringHelper` and write corresponding test cases. (It's just like `join` method in Java 8, but we use Java 7)
> 1. Add test case for `EmailLogEntry`
@leeyimin @wkurniawan07 I think this one would be much more easier.
> Separate the UI and logic for EmailLogEntry #6753

- .travis.yml
- build.gradle
- docs/staticAnalysis.md
- package.json
- src/main/resources/package.json
Fixes #6872 
Use NPM commands directly instead of wrapping them in `./gradlew` commands.
> Travis CI failing due to connectivity issue with NPM #6872

- static-analysis/teammates-eslint-es6.yml
Fixes #6870, @wkurniawan07 @Neurrone are you OK with this change?
> Forbid 'use strict' directive in ES6 code #6870

- src/main/webapp/features.jsp
Fixes #6457
> Corrected typo from belong to belongs in features.jsp.
> Minor error under "Downloadable data" writeup in features.jsp #6457

- src/main/java/teammates/storage/search/SearchManager.java
Fixes #6847
- Wrap persistence check in if block
- Use exponential backoff to handle transient backend errors (follow [Google](https://cloud.google.com/appengine/docs/standard/java/search/#Java_Putting_documents_in_an_index))
> Error while putting document #6847

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.100 #6915

- .gitignore
- .travis.yml
- appveyor.yml
- docs/development.md
- docs/settingUp.md
- docs/staticAnalysis.md
- package.json
Fixes #6875 
To be merged only after the other conversion PRs are done.
> Add instructions for building JS files #6875

- docs/settingUp.md
Fixes #5131 
> 
Modified docs/settingUp.md following instructions. And this is my first pull request. If I have made any mistake, please tell me so that I can do better next time. Thanks!
Screenshot:
> SettingUp.md: recommend Source Tree instead of GitHub for Windows #5131

- docs/development.md
Fixes #6758 
Well since no one takes this up... 😛
> Add deploying instructions for outside Eclipse and IntelliJ #6758

- .github/PULL_REQUEST_TEMPLATE.md
- docs/process.md
- docs/settingUp.md
Fixes #6904 
Will need some input on what things to and not to include; these are just some that popped up in my mind.
> Add checklist of things to do when submitting PR in the template #6904

- src/main/webapp/js/instructor.es6
- src/main/webapp/js/instructorCourseDetails.es6
- src/main/webapp/js/instructorCourseEdit.es6
- src/main/webapp/js/instructorCourseEditAjax.es6
- src/main/webapp/js/instructorFeedbackEdit.es6
- src/main/webapp/js/instructorFeedbackEdit/questionRubric.es6
- src/main/webapp/js/instructorFeedbackEdit/visibilityOptions.es6
- src/main/webapp/js/instructorFeedbackResults.es6
- src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.es6
- src/main/webapp/js/instructorFeedbackResultsAjaxResponse.es6
- src/main/webapp/js/instructorFeedbacks.es6
- src/main/webapp/js/instructorFeedbacksAjax.es6
- src/main/webapp/js/instructorStudentEdit.es6
- src/main/webapp/js/instructorStudentList.es6
- src/main/webapp/js/instructorStudentListAjax.es6
- src/main/webapp/js/instructorStudentRecords.es6
- static-analysis/teammates-eslint-es6.yml
Fixes #6964 
Made minimum changes to fix no-use-before-define violations.
> Enforce no-use-before-define on instructor*.es6 #6964

- src/main/webapp/js/adminAccountManagement.es6
- src/main/webapp/js/adminEmail.es6
- src/main/webapp/js/adminEmailLog.es6
- src/main/webapp/js/adminHome.es6
- src/main/webapp/js/ajaxResponseRate.es6
- src/main/webapp/js/common.es6
- src/main/webapp/js/contextualcomments.es6
- src/main/webapp/js/datepicker.es6
- src/main/webapp/js/feedbackResponseComments.es6
- src/main/webapp/js/feedbackSubmissionsEdit.es6
- src/main/webapp/js/googleAnalytics.es6
- src/main/webapp/js/index.es6
- src/main/webapp/js/omniComment.es6
- src/main/webapp/js/timezone.es6
- src/main/webapp/js/userMap.es6
> Enforce no-use-before-define on everything not instructor*.es6 #6965

- docs/README.md
- docs/archived/README.md
Fixes #6506 
- Marked all the documents mentioned in the issue thread as "archived"
- Added a sub-section on "How-to documents" on `README.md`
Policies documents need more time to design and formulate; defer to later time.
> Review the need for some documentation files #6506

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.101 #7034

- src/main/java/teammates/ui/controller/StudentCourseJoinAuthenticatedAction.java
> StudentCourseJoinAuthenticatedAction: NullPointerException in live server #7097

- src/main/webapp/instructorHelp.jsp
Fixes #7105
Fixed typo in "src/main/webapp/instructorHelp.jsp"
Changed from 'recieve' on line 5877 to 'receive' &  'percived' on line 6204 to 'perceived' & 'frquency' on line 7825 to 'frequency'.
> Typos in Instructor Help #7105

- src/client/java/teammates/client/scripts/AdminEmailListGenerator.java
- src/test/java/teammates/test/cases/action/AdminEmailLogPageActionTest.java
- src/test/java/teammates/test/driver/AssertHelper.java
> Change the repackaged import in some classes #7089

- src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
- src/main/java/teammates/storage/api/EntitiesDb.java
- src/main/java/teammates/storage/entity/FeedbackSession.java
Fixes #6985 
I fixed the typo that were listed in the in issue #6985.
> Typos in FeedbackSessionsLogic, EntitiesDb and FeedbackSession #6985

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.102 #7103

- src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java
- src/main/java/teammates/ui/pagedata/InstructorFeedbackResponseCommentAjaxPageData.java
Fixes #6989  
Ready for review
In `AdminSessionsPageData.java` - 
Changed `gettotalInstitutes` to:
```
public int getTotalInstitutes() {
return totalInstitutes;
}
```
In `InstructorFeedbackResponseCommentAjaxPageData.java` - 
Changed `responseVisiblities` to:
```
Map<FeedbackParticipantType, Boolean> responseVisibilities = new HashMap<>();
...
responseVisibilities.put(type, true);
...
return responseVisibilities;
```
> Typos in AdminSessionsPageData and InstructorFeedbackResponseCommentAjaxPageData #6989

- src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java
- src/main/java/teammates/ui/controller/StudentCourseDetailsPageAction.java
- src/test/java/teammates/test/cases/BaseTestCaseWithBackDoorApiAccess.java
- src/test/java/teammates/test/cases/BaseTestCaseWithDatastoreAccess.java
- src/test/java/teammates/test/cases/browsertests/BaseUiTestCase.java
- src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
- src/test/java/teammates/test/cases/storage/FeedbackResponseCommentsDbTest.java
- src/test/java/teammates/test/cases/testdriver/BackDoorTest.java
- static-analysis/teammates-macker.xml
Fixes #7086
I have gone through the design diagram to come up with the Macker rules.
Detail discussion can be found in https://xpdavid.github.io/CS2103R-Report/#abstraction-level
I am not sure about the last rule. Should we enforce this? @wkurniawan07 
"TestDriverComponent: action test cases should only interact with back-end through BackDoor API"
> Add more rules to Macker to enforce architectural rules #7086

- src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
> UI tests against live server: update automated login to match new Google login page #7247

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.103 #7246

- src/main/webapp/dev/AdminHomeJsTest.es6
- src/main/webapp/dev/allJsUnitTests.jsp
- src/main/webapp/dev/mashup.jsp
- src/main/webapp/dev/tableSort.jsp
- src/main/webapp/dev/timezone.jsp
Fixes #7091
- Initialise variables before, not after, each test (fixes `paramsList is undefined` error)
- Add encoding directive to `src/main/webapp/dev/*.jsp` (missed by #7221; required for `allJsUnitTests.jsp` to work)
> AllJsTests: fix failure against live server #7091

- src/main/java/teammates/common/exception/InvalidOriginException.java
- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/common/util/Url.java
- src/main/java/teammates/ui/controller/Action.java
- src/main/java/teammates/ui/controller/ControllerServlet.java
- src/main/webapp/invalidOrigin.jsp
- src/test/java/teammates/test/cases/browsertests/InstructorHomePageUiTest.java
- src/test/java/teammates/test/driver/GaeSimulation.java
Fixes #7261
Merging contents of #7308 from `release` back into `master` after hot patch. Contains one additional commit, squashed with the merge commit:
Use new log message generator (fixes compilation error after merging)
> Add HTTP referrer validation #7261

- src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java
- src/test/java/teammates/test/cases/browsertests/InstructorHomePageUiTest.java
- src/test/java/teammates/test/pageobjects/InstructorHomePage.java
> Fix typo in InstructorHomePage #7364

- src/main/java/teammates/common/util/FieldValidator.java
> Use sanitizeForHtml in FieldValidator #7348

- src/main/webapp/invalidOrigin.jsp
- src/main/webapp/partials/instructorHelpAddEditInstructors.jsp
- src/main/webapp/partials/instructorHelpComments.jsp
- src/main/webapp/partials/instructorHelpFAQ.jsp
- src/main/webapp/partials/instructorHelpGettingStarted.jsp
- src/main/webapp/partials/instructorHelpSessions.jsp
- src/main/webapp/partials/instructorHelpTips.jsp
> Add missing encoding page directive to several JSP files #7396

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.105 #7399

- docs/ide-usage.md
> ide-usage.md: add a table of contents #7429

- README.md
> Acknowledgements in README: Add GSoC2017 #7263

- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
- src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Fixes #7450
- Fix wrong assertion
- Add wait for visibility of visibility message element
> InstructorFeedbackEditPageUiTest: fix unstable visibility message verification #7450

- src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageAction.java
- src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
- src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackSaveAction.java
- src/main/java/teammates/ui/controller/InstructorEditStudentFeedbackSaveAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackSubmissionEditPageAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackSubmissionEditSaveAction.java
- src/main/java/teammates/ui/controller/StudentFeedbackSubmissionEditPageAction.java
- src/main/java/teammates/ui/controller/StudentFeedbackSubmissionEditSaveAction.java
Fixes #6987
Fixed typos in java files as my first pull request.
> FeedbackSubmissionEditPageAction, FeedbackSubmissionEditSaveAction, InstructorEditInstructorFeedbackSaveAction: fix typos #6987

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.106 #7471

- src/main/java/teammates/ui/controller/ImageResult.java
- src/main/webapp/js/common.es6
- src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.es6
- src/main/webapp/js/instructorFeedbackResultsAjaxByGRQ.es6
- src/main/webapp/js/instructorFeedbackResultsAjaxByQuestion.es6
- src/main/webapp/js/instructorFeedbackResultsAjaxByRGQ.es6
- src/main/webapp/js/instructorFeedbackResultsAjaxByRQG.es6
- src/main/webapp/js/instructorStudentList.es6
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java
- src/test/java/teammates/test/cases/browsertests/InstructorStudentListPageUiTest.java
- src/test/java/teammates/test/pageobjects/AppPage.java
- src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
- src/test/java/teammates/test/pageobjects/InstructorStudentListPage.java
- src/test/resources/pages/instructorSearchPageSearchStudentsForStudent2.html
- src/test/resources/pages/instructorStudentListPageWithPicture.html
- src/test/resources/pages/newlyJoinedInstructorStudentCourseDetailsPage.html
- src/test/resources/pages/studentCourseDetailsWithTeammatesHTML.html
> StudentProfilePictureAction: properly handle missing pictures #7365

- build.gradle
- src/test/resources/pages/commonAssertRegexTestPage.html
- src/test/resources/pages/godmode.html
- src/test/resources/pages/godmodeExpectedOutput.html
- src/test/resources/pages/sampleActual.html
- src/test/resources/pages/sampleExpected.html
Fixes #7483
More details here: https://github.com/TEAMMATES/teammates/issues/7483#issuecomment-307553234
**Caveats**
The invalid HTML causing a regression here cannot be fixed completely within this PR, so #7499
is created to address this.
> Fix HtmlHelperTest test failure on dev server #7483

- src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
> GoogleLoginPage: fix approval page handling #7491

- docs/development.md
- src/main/webapp/WEB-INF/datastore-indexes.xml
> Add datastore-indexes.xml for easier deployment #7513

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.107 #7527

- src/main/webapp/WEB-INF/tags/instructor/studentRecords/resultsTable.tag
- src/test/java/teammates/test/cases/browsertests/InstructorStudentRecordsPageUiTest.java
- src/test/resources/pages/instructorStudentRecords.html
> Make InstructorStudentRecordsPage comments id consistent with InstructorFeedbackResultsPage comments id #7544

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.108 #7619

- src/test/java/teammates/test/driver/EmailAccount.java
> InstructorCourseDetailsPageUiTest: fix failure against live server #7629

- src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
- src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java
- src/main/java/teammates/ui/controller/AdminSearchPageAction.java
- src/test/java/teammates/test/cases/action/AdminInstructorAccountAddActionTest.java
> Admin*Action.java: fix typos #6986

- src/main/webapp/dev/js/common/instructorFeedbackResults.es6
Fixes #7664
Very simple typo. 
ExapandMode -> ExpandMode
> instructorFeedbackResults.es6: fix typo #7664

- src/client/java/teammates/client/remoteapi/RemoteApiClient.java
- src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInAdminEmailAttributes.java
- src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInCourseAttributes.java
- src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInStudentProfileAttributes.java
- src/client/java/teammates/client/scripts/DataMigrationForSanitizedDatainCourseAttributes.java
Fixes #7571 
Loads all courses and updates the course name with its desanitized version of a course if it is sanitized.
> Add data migration script on CourseAttributes to convert fields to its html desanitized form #7571

- src/test/java/teammates/test/cases/browsertests/InstructorSubmissionAdjustmentUiTest.java
Fixes #7333
Use `RetryManager` when asserting zero new responses
> InstructorSubmissionAdjustmentUiTest: improve success rate against live server #7333

- src/test/java/teammates/test/cases/browsertests/InstructorSubmissionAdjustmentUiTest.java
Fixes #7681
Changed- testAdjustmentOfSubsmission() to testAdjustmentOfSubmissions() in InstructorSubmissionAdjustmentUiTest
> InstructorSubmissionAdjustmentUiTest: fix typo Subsmission --> Submissions #7681

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.109 #7712

- src/client/java/teammates/client/remoteapi/RemoteApiClient.java
- src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java
- static-analysis/teammates-macker.xml
> Instructor: search comments: migrate legacy search documents #7591

- src/main/java/teammates/storage/entity/FeedbackSession.java
> FeedbackSession: fix respondent lists not persisting #7768

- src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
> InstructorFeedbackEditPage pageobject: fix typo in method name #7760

- src/main/webapp/WEB-INF/tags/instructor/course/activeCoursesTable.tag
- src/main/webapp/WEB-INF/tags/instructor/course/addCoursePanel.tag
- src/main/webapp/WEB-INF/tags/instructor/course/archivedCoursesTable.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditAccessControlEditDivForInstr.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditAddInstructorPanel.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditCourseInfo.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorList.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorListPanelBody.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorListPanelHeading.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorRoleModal.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditTunePermissionsDivForInstructor.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditTuneSectionPermissionsDiv.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseEditTuneSessionPermissionsDiv.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseInformation.tag
- src/main/webapp/WEB-INF/tags/instructor/course/courseInformationContainer.tag
- src/main/webapp/WEB-INF/tags/instructor/course/loadCoursesTableByAjaxForm.tag
- src/main/webapp/WEB-INF/tags/instructor/course/studentInformationButtons.tag
- src/main/webapp/WEB-INF/tags/instructor/course/studentTableModal.tag
> tags/instructor/course/*.tag: change to 2-space indentation #7352

- src/main/java/teammates/ui/template/InstructorFeedbackResultsFilterPanel.java
- src/main/webapp/WEB-INF/tags/instructor/results/copyPasteModal.tag
- src/main/webapp/WEB-INF/tags/instructor/results/filterPanel.tag
- src/main/webapp/WEB-INF/tags/instructor/results/questionPanel.tag
- src/main/webapp/WEB-INF/tags/instructor/results/sectionPanel.tag
- src/main/webapp/WEB-INF/tags/instructor/results/sessionPanel.tag
- src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
- src/test/resources/pages/instructorFeedbackResultsPageWithSanitizedData.html
Fixes #7766 
* Removed sanitization of section list in java template file
* Used `fn:escapeXml` whenever section is displayed
* Updated InstructorFeedbackResultsPageUiTest
> InstructorFeedbackResultsPage: standardize sanitization for section #7766

- src/main/webapp/WEB-INF/tags/instructor/feedbacks/copyFromModal.tag
- src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionActions.tag
- src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionPublishButton.tag
- src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsForm.tag
- src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsFormAdditionalSettings.tag
- src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsFormHeader.tag
- src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsTable.tag
- src/main/webapp/WEB-INF/tags/instructor/feedbacks/loadSessionsTableByAjaxForm.tag
Fixes partially #7352 
Applied to all files in `src/main/webapp/WEB-INF/tags/instructor/feedbacks/*`
> tags/instructor/feedbacks/*.tag: change to 2-space indentation #7352

- src/main/java/teammates/ui/controller/InstructorFeedbackQuestionAddAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackQuestionCopyAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java
- src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionEditForm.tag
- src/main/webapp/WEB-INF/tags/instructor/results/questionPanel.tag
- src/main/webapp/WEB-INF/tags/instructor/search/searchCommentFeedbackQuestion.tag
- src/main/webapp/jsp/instructorFeedbackQuestionCopyModal.jsp
- src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java
- src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionCopyActionTest.java
- src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java
- src/test/java/teammates/test/cases/browsertests/InstructorSearchPageUiTest.java
- src/test/resources/data/InstructorFeedbackEditPageUiTest.json
- src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
- src/test/resources/data/InstructorSearchPageUiTest.json
- src/test/resources/pages/instructorFeedbackCopyQuestionModalTestingSanitization.html
- src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
- src/test/resources/pages/instructorFeedbackResultsPageGQRWithSanitizedData.html
- src/test/resources/pages/instructorFeedbackResultsPageWithSanitizedData.html
- src/test/resources/pages/instructorSearchPageSearchTestingSanitization.html
Fixes #7764 
* Sanitized display of question text in statusToAdmin or on html
* Updated tests
> FeedbackQuestionDetails: Sanitize question text when displayed #7764

- src/main/java/teammates/storage/entity/Instructor.java
> Instructor: remove unnecessary unboxing of Boolean value #7716

- src/main/webapp/WEB-INF/tags/instructor/feedbacks/loadSessionsTableByAjaxForm.tag
Fixes #7780 
Fixed typo: sessiosn -> sessions
> loadSessionsTableByAjaxForm.tag: fix typo #7780

- src/main/java/teammates/ui/controller/ControllerServlet.java
> ControllerServlet.java: add additional logging #7790

- src/main/webapp/stylesheets/teammatesCommon.css
Fixes #7880
Deleted "cursor: hand;" to fix the issue. Ready for review.
> `teammatesCommon.css`: Remove `cursor: hand;` #7880

- src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
Fixes #7886
Build passing on both [AppVeyor](https://ci.appveyor.com/project/whipermr5/teammates/build/1.0.285) and [Travis](https://travis-ci.org/whipermr5/teammates/builds/259826407).
> InstructorFeedbackResultsPage: avoid use of `.click()` #7886

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.110 #7894

- src/test/resources/emails/sessionClosedEmailForStudent.html
- src/test/resources/emails/sessionClosedEmailTestingSanitizationForStudent.html
> EmailGeneratorTest: Remove hard-coded app url #7936

- .travis.yml
- appveyor.yml
Fixes #6921 
Based on 
#6238 and #6432
> Skip CI for changes confined to IDE launch configurations and settings files #6921

- src/main/java/teammates/common/util/Url.java
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java
Fixes #7723 
Call toString on AppUrl object before calling the equals method so that 2 strings are compared.
> InstructorFeedbackResultsPageUiTest: Fix false positive assertion #7723

- src/main/webapp/WEB-INF/tags/instructor/copyModal.tag
- src/main/webapp/WEB-INF/tags/instructor/courseStudentDetails/studentInformationTable.tag
- src/main/webapp/WEB-INF/tags/instructor/courseStudentDetails/studentProfile.tag
- src/main/webapp/WEB-INF/tags/instructor/home/coursePanel.tag
- src/main/webapp/WEB-INF/tags/instructor/home/courseTable.tag
- src/main/webapp/WEB-INF/tags/instructor/home/search.tag
- src/main/webapp/WEB-INF/tags/instructor/home/sort.tag
- src/main/webapp/WEB-INF/tags/instructor/instructorPage.tag
- src/main/webapp/WEB-INF/tags/instructor/moreInfo.tag
- src/main/webapp/WEB-INF/tags/instructor/navBar.tag
- src/main/webapp/WEB-INF/tags/instructor/remindParticularStudentsModal.tag
- src/main/webapp/WEB-INF/tags/instructor/studentList.tag
- src/main/webapp/WEB-INF/tags/instructor/studentRecords/resultsTable.tag
Fixes partially #7352 
All leftover files in tags/instructor/*.tag
> tags/instructor/*.tag: change to 2-space indentation

- src/main/webapp/WEB-INF/tags/bodyFooter.tag
- src/main/webapp/WEB-INF/tags/bodyHeader.tag
- src/main/webapp/WEB-INF/tags/errorPage.tag
- src/main/webapp/WEB-INF/tags/helpPage.tag
- src/main/webapp/WEB-INF/tags/page.tag
- src/main/webapp/WEB-INF/tags/staticPage.tag
- src/main/webapp/WEB-INF/tags/statusMessage.tag
- src/main/webapp/WEB-INF/tags/teammatesLogo.tag
Fixes partially #7352
All remaining files in tags/*.tag
> tags/*.tag: change to 2-space indentation #7352

- src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
- src/main/java/teammates/storage/search/FeedbackResponseCommentSearchDocument.java
- src/main/java/teammates/ui/pagedata/InstructorFeedbackResponseCommentAjaxPageData.java
- src/main/java/teammates/ui/pagedata/InstructorSearchPageData.java
- src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java
- src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
- src/test/java/teammates/test/driver/HtmlHelper.java
> Replace "Anonymous" with Constant in `Const.java` #7932

- src/main/webapp/WEB-INF/tags/instructor/home/courseTable.tag
> Remove excess space in courseTable.tag #7961

- src/main/resources/InstructorSampleData.json
- src/main/webapp/partials/instructorHelpSessions.jsp
- src/test/resources/data/InstructorStudentRecordsPageUiTest.json
- src/test/resources/data/MashupPageUiTest.json
- src/test/resources/pages/newlyJoinedInstructorFirstFeedbackSessionResultsPage.html
Fixes #7980
Changes to the text regarding Alice.
> Instructor: Help page and sample course: Remove sexist example #7980

- docs/README.md
- docs/development.md
- docs/ide-usage.md
- static-analysis.md
> Rename staticAnalysis.md -> static-analysis.md #7742

- src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
Fixes #7960.
Refactored Variables as mentioned in issue #7960 
First time using GitHub and contributing. Hope I've done it correctly :)
> FeedbackRankQuestionUiTest: refactor variable names #7960

- src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocument.java
- src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java
- src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentParticipantName.java
- src/main/java/teammates/common/util/StringHelper.java
- src/main/java/teammates/storage/search/FeedbackResponseCommentSearchDocument.java
- src/main/java/teammates/storage/search/SearchDocument.java
- src/test/java/teammates/test/cases/util/StringHelperTest.java
> InstructorSearchPage: display team name for feedback response #7655

- src/main/webapp/partials/instructorHelpGettingStarted.jsp
- src/main/webapp/partials/instructorHelpProfile.jsp
- src/main/webapp/partials/instructorHelpSearch.jsp
- src/main/webapp/partials/instructorHelpSections.jsp
- src/main/webapp/partials/instructorHelpTips.jsp
> webapp/partials/*.jsp: change to 2-space indentation #7967

- src/main/java/teammates/common/util/Const.java
- src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
- src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperOne.html
- src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperTwo.html
Fixes #8030 
I changed the warning message to
> Instructor: view results: update warning for sessions with high response count #8030

- src/test/java/teammates/test/pageobjects/AppPage.java
- src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
> InstructorFeedbackResultsPageUiTest: fix failure on Chrome #8042

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.111 #8048

- src/main/webapp/data/userMapData.json
Fixes #7898 
Added new universities to userMapData.json
Haven't added EKR, Philippines. After thorough google search, I have found that there is no university with the acronym. Please correct me if I am wrong.
> Update user map for July 2017 #7898

- src/main/webapp/dev/js/main/feedbackSubmissionsEdit.es6
Fixes #8035 
*This is my first attempt at an open source contribution*
> feedbackSubmissionsEdit.es6: remove unnecessary if condition #8035

- src/main/webapp/index.jsp
> Home page: remove country list #8061

- docs/process.md
> process.md: fix git command for switching branch in step 3 / 2 #8076

- src/main/webapp/about.jsp
> Update about.jsp with contributors from V5.112 #8055

- docs/process.md
./gradlew staticAnalysis to ./gradlew lint
Fixes #7754
> process.md: update command to run static analysis #7754

- src/test/java/teammates/test/cases/browsertests/InstructorStudentRecordsPageUiTest.java
- src/test/resources/pages/instructorStudentRecordsPageEditedCommentOfDifferentInstructor.html
Fixes #8059
Move edit-to-empty-comment test case after test cases involving HTML verification.
> InstructorStudentRecordsPageUiTest: improve stability #8059

- src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
- src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
Fixes #7279 
(waiting review)
Removed function isQuestionFullyAnsweredByTeam and removed the associated lines of code from the unit test code
> FeedbackQuestionsLogic: remove unused method isQuestionFullyAnsweredByTeam #7279

- src/main/java/teammates/logic/api/EmailGenerator.java
- src/main/java/teammates/ui/controller/CourseJoinAuthenticatedAbstractAction.java
- src/main/java/teammates/ui/controller/InstructorCourseJoinAuthenticatedAction.java
- src/main/java/teammates/ui/controller/StudentCourseJoinAuthenticatedAction.java
- src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java
Fixes #7950
Refer here: https://github.com/TEAMMATES/teammates/issues/7950#issuecomment-336783468
> CourseJoinAuthenticatedAbstractAction: fix NullPointerException in live server #7950

- src/main/java/teammates/common/util/Const.java
- src/main/resources/InstructorSampleData.json
Fixes #8124 
Changed 00:00 AM to 12:00 AM.
> Const.java, InstructorSampleData.json: fix invalid date format #8124

- src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsResponseDetails.java
> FeedbackRankRecipientsResponseDetails: Refactor getAnswerCsv #7724

- src/main/java/teammates/ui/controller/Action.java
- src/main/webapp/invalidOrigin.jsp
> Allow requests with missing HTTP referrer information #8129

- src/main/webapp/dev/js/common/instructorFeedbackResults.js
> Instructor: feedback results: fix broken auto-highlighting of table #8128

- src/main/webapp/WEB-INF/cron.xml
Fixes #8139 
Simply changed the backup URL to one that is consistent with the current code. The PR/issue is never meant to improve the backup mechanism.
> Update weekly backup code #8139

- src/main/webapp/dev/js/common/onStart.js
> Fix broken touch device detection #8156

- src/main/webapp/dev/js/common/const.js
- src/main/webapp/dev/js/common/crypto.js
- src/main/webapp/dev/js/common/onStart.js
> Refresh session token before form submission #8158

- src/main/webapp/dev/js/main/instructorCourseDetails.js
Fixes #8174 
have deleted these lines in instructorCourseDetails.js
$('#btn-select-element-contents').on('click', () => { 
selectElementContents($('#detailsTable').get(0)); 
}); 
11/27
reverted above and deleted  lines 104-106
have added
selectElementContents(content.get(0));
> Instructor: course details: fix broken auto-highlighting of table #8174

- src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
> StudentCourseJoinConfirmationPageUiTest: fix Google login #8106

- docs/setting-up.md
Fixes #8241 
Added the missing line in setting-up.md doc
> setting-up.md: Fix tracking of upstream repository instructions #8241

- docs/development.md
Fixes #8267
changed link to match the heading
> development.md: Fix broken link for Gmail Notes #8267

- src/client/java/teammates/client/scripts/UploadBackupData.java
- src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
- src/main/java/teammates/common/datatransfer/InstructorPrivileges.java
- src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
- src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
- src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
- src/main/java/teammates/ui/template/InstructorFeedbackResultsSectionPanel.java
Fixes #8250 
**Remarks:**
I was able to find only 7 instances of `containsKey` that can be replaced with `getOrDefault`. Am I missing something?
> Java: Use Java 8 map.getOrDefault #8250

- src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
- src/main/java/teammates/ui/pagedata/StudentFeedbackResultsPageData.java
- src/test/resources/data/StudentFeedbackResultsPageUiTest.json
- src/test/resources/pages/studentFeedbackResultsPageMCQ.html
- src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html
- src/test/resources/pages/studentFeedbackResultsPageNewlyRegistered.html
- src/test/resources/pages/studentFeedbackResultsPageOpen.html
- src/test/resources/pages/studentFeedbackResultsPageRank.html
- src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
- src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html
- src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html
Fixes #8203
Demo for self-feedback question.
Code to hide the random identifier for recipients is removed (refer to #5228) as it doesn't help according to the discussion in #8203. The hot fix applied to the LIVE server already achieves fully random identifiers and thus it is OK to show the random identifier for recipients.
> Student view results: Fix anonymity breach for self-feedback questions #8203

- build.gradle
> Use dynamic versioning for App Engine SDK #8297

- build.gradle
- src/main/java/teammates/common/util/StringHelper.java
- src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
- src/test/java/teammates/test/cases/util/StringHelperTest.java
- src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
> Instructor: enroll students: leading spaces in email should be trimmed internally #8108

- src/main/webapp/dev/js/main/instructorFeedbackEdit.js
Fixes #8148 
The `edit` button's occasional erratic behaviours seems to be caused by jQuery's event propagation (source: [StackOverflow](https://stackoverflow.com/a/22962937/9246445)).
Proposed solution is to use `event.currentTarget` which is the propagated element the handler is attached to, instead of `event.target` which is the triggering element (source: [StackOverflow](https://stackoverflow.com/a/28325103/9246445)).
> Instructor: edit question: remove the need to click edit button multiple times #8148

- .templates/ideaPlugins/checkstyle-idea.xml
- build.gradle
- docs/intellij-automated-setup-behavior.md
- docs/static-analysis.md
> Sync Checkstyle version for IntelliJ with the version defined in build script #8347

- src/main/webapp/data/developers.json
> Release V6.1.0 #8385

- docs/ide-setup.md
Fixes #8388 
as discussed in the referenced issue with @wkurniawan07, I have made the slight modification to ide-setup.md
> Eclipse setup: refresh before cleaning the project for the first time #8388 

- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/logic/api/TaskQueuer.java
- src/main/java/teammates/storage/api/FeedbackSessionsDb.java
- src/main/java/teammates/ui/automated/AutomatedActionFactory.java
- src/main/java/teammates/ui/automated/FeedbackSessionUpdateRespondentWorkerAction.java
- src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackSaveAction.java
- src/main/java/teammates/ui/controller/InstructorEditStudentFeedbackSaveAction.java
- src/main/java/teammates/ui/controller/InstructorFeedbackSubmissionEditSaveAction.java
- src/main/java/teammates/ui/controller/StudentFeedbackSubmissionEditSaveAction.java
- src/main/webapp/WEB-INF/queue.xml
- src/test/java/teammates/test/cases/action/InstructorEditInstructorFeedbackSaveActionTest.java
- src/test/java/teammates/test/cases/action/InstructorEditStudentFeedbackSaveActionTest.java
- src/test/java/teammates/test/cases/action/InstructorFeedbackSubmissionEditSaveActionTest.java
- src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditSaveActionTest.java
- src/test/java/teammates/test/cases/automated/FeedbackSessionUpdateRespondentWorkerActionTest.java
Fixes #8097
- Use transactions to avoid race condition
- Use task queues to limit the impact of failing transactions
> Instructor results: fix unreliable respondents list #8097

- .travis.yml
Fixes #8414 
This can/should be reverted once whatever caused this issue is resolved.
> Address regression in Cloud SDK 188.0.0 #8414

- .travis.yml
> Revert Cloud SDK 188.0.0 regression workaround #8422

- src/main/webapp/data/developers.json
> Release V6.2.0 #8424

- src/main/java/teammates/ui/automated/AutomatedServlet.java
> AutomatedServlet: catch all Throwables for logging #8454

- src/test/java/teammates/test/cases/BaseTestCase.java
- src/test/java/teammates/test/cases/util/AdminLogQueryTest.java
> AdminLogQueryTest : Fix PMD problem #8459

- src/test/java/teammates/test/pageobjects/InstructorHomePage.java
Fixes #8483 
[Passing AppVeyor build](https://ci.appveyor.com/project/wkurniawan07/repo/build/1.0.202).
> Fix AppVeyor failing build due to InstructorHomePageUiTest #8483

- src/main/java/teammates/ui/automated/AutomatedServlet.java
> AutomatedServlet: always log request parameters #8481

- src/main/webapp/dev/js/common/instructorFeedbackResults.js
- src/main/webapp/dev/js/main/instructorFeedbackResultsGQR.js
- src/main/webapp/dev/js/main/instructorFeedbackResultsGRQ.js
- src/main/webapp/dev/js/main/instructorFeedbackResultsRGQ.js
- src/main/webapp/dev/js/main/instructorFeedbackResultsRQG.js
Fixes #5329 
Moved seeMoreRequest to commons lib instructorFeedbackResults.js
> Refactor instructorFeedbackResults<...>.js #5329

- src/main/webapp/jsp/instructorCourseEnroll.jsp
- src/test/java/teammates/test/cases/browsertests/InstructorCourseEnrollPageUiTest.java
- src/test/resources/pages/instructorCourseEnrollError.html
- src/test/resources/pages/instructorCourseEnrollPage.html
Fixes #8500 
Updated the link to the new spreadsheet as requested. Also changed all instances of `email.com` to `example.com` in the page.
> Instructor: enroll students in course: update link to sample spreadsheet #8500

- src/main/webapp/data/developers.json
> Release V6.3.0 #8519

- build.gradle
> Running dev server via CLI: preserve local datastore across builds #8567

- src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
> FeedbackSessionAttributes: isInGracePeriod: handle corner case #8569

- src/main/webapp/WEB-INF/tags/instructor/results/remindButton.tag
- src/test/resources/pages/instructorFeedbackResultsPageEmpty.html
- src/test/resources/pages/instructorFeedbackResultsPageOpen.html
- src/test/resources/pages/newlyJoinedInstructorFirstFeedbackSessionResultsPage.html
- src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
Fixes #8558 
All done, needs a review.
> Instructor: session results: add a tooltip to the 'Remind all' button #8558

- src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
- src/main/java/teammates/common/util/JsonUtils.java
- src/main/java/teammates/storage/api/FeedbackSessionsDb.java
- src/main/java/teammates/storage/entity/FeedbackSession.java
- src/main/java/teammates/ui/controller/InstructorFeedbackAbstractAction.java
- src/main/java/teammates/ui/pagedata/PageData.java
- src/main/java/teammates/ui/template/FeedbackSessionsForm.java
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
- src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java
- src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java
- src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
- src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
- src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
- src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
- src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
Fixes #8641
~~Based on #8639. Commits start from 3d588d3e4bbcf6868a181fe27c6be9752f7ca340.~~
> Migrate FeedbackSessionAttributes gracePeriod field to Duration #8641

- src/main/java/teammates/common/util/TimeHelper.java
- src/test/java/teammates/test/cases/util/TimeHelperTest.java
> TimeHelper: convertLocalDateToUtc: do not shift special time representations #8655

- src/main/webapp/data/developers.json
> Release V6.4.0 #8657

- src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java
- src/main/java/teammates/common/util/JsonUtils.java
> Instructor: search responses: handle legacy search documents #8662

- src/main/java/teammates/logic/core/EmailSenderService.java
- src/main/java/teammates/logic/core/MailgunService.java
- src/main/java/teammates/logic/core/MailjetService.java
- src/main/java/teammates/logic/core/SendgridService.java
> SendgridService: fix successful request detection #8663

- src/main/java/teammates/common/util/JsonUtils.java
> JsonUtils: remove code handling legacy data #8681

- src/main/java/teammates/ui/controller/AdminSearchPageAction.java
Fixes #8707 
fixed the typo in `AdminSearchPage.java`:
-changed `AdminSearchPaga Page Load` to `AdminSearchPage Page Load`
> AdminActivityLogPage: Typo in Log for adminSearchPage Load #8707

- src/client/java/teammates/client/scripts/DataMigrationBaseScript.java
- src/client/java/teammates/client/scripts/DataMigrationForEntities.java
- src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocument.java
- src/client/java/teammates/client/scripts/DataMigrationForOrphanedCommentSearchDocuments.java
- src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInAdminEmailAttributes.java
- src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInCourseAttributes.java
- src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInStudentAttributes.java
- src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInStudentProfileAttributes.java
> Add script to delete orphaned comment search documents #8702

- src/main/java/teammates/storage/entity/Account.java
> Account: update setStudentProfile javadoc #8757

- src/main/java/teammates/logic/api/EmailGenerator.java
- src/main/java/teammates/storage/entity/Account.java
Fixes #8761 
**Outline of Solution:** Added conditional for instructor similar to other email generators.
> Instructor: fix bug where session closed email copy is sent to the instructor even when it was not sent to students #8761

- docs/community.md
- src/main/webapp/about.jsp
- src/main/webapp/data/developers.json
- src/main/webapp/dev/js/main/about.js
- src/main/webapp/dev/js/main/index.js
> Release V6.5.0 #8777

- src/main/java/teammates/ui/template/FeedbackSessionsForm.java
- src/test/java/teammates/test/cases/action/InstructorFeedbackAddActionTest.java
> InstructorFeedbackAddAction: fix NullPointerException upon invalid publish time #8788

- docs/development.md
- docs/troubleshooting-guide.md
- src/main/java/teammates/common/util/Config.java
- src/main/resources/build.template.properties
- src/test/java/teammates/test/cases/testdriver/EmailCheckerTest.java
- src/test/java/teammates/test/driver/EmailChecker.java
- src/test/java/teammates/test/driver/GaeSimulation.java
> Remove the need to specify application URL in build.properties #8800

- src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
> AccountAttributesTest: fix instability due to modified timestamp comparison #8803

- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
Fixes #8811 
Start time changed to may 1st 2019
> InstructorFeedbackSessionsPageUiTest: New Session start and end with past date #8811

- src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
- src/main/java/teammates/common/util/Templates.java
- src/main/resources/feedbackQuestionMsqResultStatsOptionFragment.html
- src/main/resources/feedbackQuestionMsqResultStatsTemplate.html
Fixes #8894 
Added separate Result templates for MSQ questions so that it is not dependent on the design of MCQ template.
> Instructor: Results: Use separate result stats templates for MSQ questions instead of re-using MCQ templates #8894

- src/main/webapp/data/developers.json
> Release V6.6.0 #8903

- src/main/webapp/data/developers.json
Part of #8945
Can't find the real name of some users in Github profile. Use their usernames as their real names.
> Release V6.7.0 #8945

- docs/ide-setup.md
Fixes #8944
If there are any changes that you don't approve please leave me a comment. Thanks!
> Edit ide-setup.md #8944

- src/test/java/teammates/test/cases/browsertests/InstructorCoursesPageUiTest.java
- src/test/resources/pages/instructorHomeHTMLWithHelperView.html
> InstructorHomePageUiTest & InstructorCoursesPageUiTest failing due to rebase errors #8971

- src/main/java/teammates/common/util/StringHelper.java
- src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java
- src/main/webapp/WEB-INF/tags/admin/activity/filterPanel.tag
- src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java
- src/test/java/teammates/test/cases/util/StringHelperTest.java
Fixes #6711
- Explained in Commit messages
> AdminActivityLogPageAction: fix bug in generation of status message #6711

- src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java
- src/main/webapp/dev/js/main/instructorFeedbackResultsRQG.js
- src/main/webapp/jsp/instructorFeedbackResultsByRecipientQuestionGiver.jsp
- src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageResponseCommentUiTest.java
- src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html
- src/test/resources/pages/instructorFeedbackResultsPageRankRQGView.html
- src/test/resources/pages/instructorFeedbackResultsPageRubricRQGView.html
- src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
- src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html
- src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiver.html
- src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiverTeam.html
> Instructor: comment on responses: support entering comments for each response from view RQG #8987

- src/main/webapp/data/developers.json
Part of #8997
Expected some open PRs to get merged in this release. Shall wait for them and will update `developers.json` accordingly.
> Release V6.8.0 #8997

- src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java
- src/main/java/teammates/ui/automated/StudentCourseJoinEmailWorkerAction.java
- src/main/webapp/WEB-INF/queue.xml
Fixes #8452
Implemented two solutions:
778ea46
- Safety measure to increase retries and add delays 
- Explain in the commit message
https://github.com/TEAMMATES/teammates/commit/f4e899105edf15759a79ec39ac40178b15ebf594
- Use RetryManager to ensure it keeps trying to retrieve instructor till not-null.
- This will ensure that the task action doesn't fail and will give enough time to retry to retrieve the instructor until its visible to entities or indexed
- @LiHaoTan Please provide any input on this.
Either we can merge both commits or either one of them.
> Fix assertion error in instructorCourseJoinEmail on live server #8452

- src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
Fixes #9015 
It seems the google sign in page are stable now, we can stick to the new login page.
I am open for suggestions/discussion if we want to care about the old login UI.
> UI tests against live server: update automated login to match new Google login page #9015

- src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentFormForFeedbackParticipant.tag
- src/test/resources/pages/instructorEditStudentFeedbackPageModified.html
- src/test/resources/pages/instructorEditStudentFeedbackPageOpen.html
- src/test/resources/pages/instructorFeedbackSubmitPageClosed.html
- src/test/resources/pages/instructorFeedbackSubmitPageFullyFilled.html
- src/test/resources/pages/instructorFeedbackSubmitPageModified.html
- src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
- src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
- src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
- src/test/resources/pages/studentFeedbackSubmitPageClosed.html
- src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
- src/test/resources/pages/studentFeedbackSubmitPageModified.html
- src/test/resources/pages/studentFeedbackSubmitPageOpen.html
- src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
- src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
- src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Fixes #9029 
@xpdavid I have added `container-fluid` div. Does this look fine?
> Student: comment on MCQ response: tweak comment UI #9029

- src/main/webapp/dev/js/common/onStart.js
- src/main/webapp/dev/js/main/about.js
- src/main/webapp/dev/js/main/instructorCourses.js
- src/main/webapp/dev/js/main/instructorHelp.js
- src/main/webapp/dev/js/test/CommonTestFunctions.js
- src/test/resources/pages/instructorHelpPageSearchSingleKeyword.html
- static-analysis/teammates-eslint.yml
Fixes #9052 
The search results are ranked differently for keyword `course` in this case. The position of `How do I view sessions I have deleted?` and `How do I restore a deleted session?` seems to be swapped due to which the search results html has changed. 
Fixed by updating html file.
> InstructorHelpPageUiTest failing on AppVeyor master #9052

- src/main/webapp/dev/js/common/instructorEnroll.js
Fixes #9071
1. Hotfix to address issue faced.
> Instructor: enroll students: blank lines processed by back-end during enrollment #9071

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/data-migration.md
- docs/maintainer-guide.md
- docs/process.md
Fixes #8565 
These are the last two commits of #9077 (before being detached).
> [#8565] Update workflow/process documents

- src/client/java/teammates/client/scripts/DataMigrationForInstructorFeedbackResponseComments.java
> [#9083] Data Migration: FeedbackResponseComment commentGiverType and isCommentFromFeedbackParticipant

- src/main/webapp/data/developers.json
> [#9100] Release V6.11.0

- src/main/webapp/data/developers.json
> [#9141] Release V6.12.0

- build.gradle
- docs/static-analysis.md
- src/client/java/teammates/client/scripts/scalabilitytests/InstructorFeedbackResultsPageDataGenerator.java
- src/client/java/teammates/client/scripts/util/LoopHelper.java
- src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
- src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
- src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
- src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
- src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
- src/main/java/teammates/logic/core/InstructorsLogic.java
- src/main/java/teammates/ui/controller/InstructorSearchPageAction.java
- src/test/java/teammates/test/cases/BaseComponentTestCase.java
- src/test/java/teammates/test/cases/action/InstructorStudentRecordsAjaxPageActionTest.java
- src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
- src/test/java/teammates/test/cases/datatransfer/FeedbackMcqQuestionDetailsTest.java
- src/test/java/teammates/test/cases/datatransfer/FeedbackMsqQuestionDetailsTest.java
- src/test/java/teammates/test/cases/datatransfer/FeedbackRubricQuestionDetailsTest.java
- src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
- src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
- src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
- static-analysis/teammates-spotbugs.xml
Fixes #8277 
All of the following shortcomings of our current FindBugs usage are also solved:
The following shortcomings of SpotBugs still exist:
- Lack of IntelliJ plugin; see https://github.com/andrepdo/findbugs-idea/issues/265
- Slow, as it lints at bytecode level (problem exists even in FindBugs)
> [#8277] Adopt SpotBugs in place of FindBugs

- src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java
- src/main/java/teammates/ui/automated/StudentCourseJoinEmailWorkerAction.java
- src/main/java/teammates/ui/controller/InstructorCourseInstructorAddAction.java
- src/test/java/teammates/test/cases/action/InstructorCourseInstructorAddActionTest.java
Fixes #9157
This will also close #9025 as we found the reason.
The retries introduced in #8924 is removed (FYI @tshradheya) as #8452 and is not about data consistency error but a bug in the code as explained in https://github.com/TEAMMATES/teammates/issues/9157#issuecomment-425779323
> [#9157] AssertionError: If the instructor hasn't been retrieved yet there is some problem in adding of instructor

- src/main/webapp/dev/js/common/onStart.js
- src/main/webapp/dev/js/main/about.js
- src/main/webapp/dev/js/main/instructorCourses.js
- src/main/webapp/dev/js/test/CommonTestFunctions.js
- static-analysis/teammates-eslint.yml
> [#9179] Make JS code ES6-compliant

- .travis.yml
- appveyor.yml
- build.gradle
- docs/setting-up.md
> [#9184] Lock App Engine SDK at 1.9.65

- build.gradle
- src/e2e/java/teammates/e2e/util/TestProperties.java
- src/main/java/teammates/common/util/Config.java
- src/main/java/teammates/logic/api/EmailGenerator.java
- src/main/java/teammates/logic/api/EmailSender.java
- src/main/resources/build.template.properties
- src/main/webapp/WEB-INF/appengine-web.template.xml
- src/main/webapp/WEB-INF/tags/bodyFooter.tag
- src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java
- src/web/app/pages-admin/admin-timezone-page/admin-timezone-page.component.html
Fixes #9239 and fixes https://github.com/TEAMMATES/teammates-ops/issues/6
> [#9239] Move app ID and version number to build.properties

- src/main/webapp/data/developers.json
> [#9320] Release V6.16.0

- src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
> [#9331] Update automated login to match new Google login page

- src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
Fixes #9219 
Push to release branch to testify hypothesis about the cause of NPE.
> [#9219] live server: NPE in feedbackResponseAdjustment when changing student data

- src/main/java/teammates/ui/webapi/action/SendErrorReportAction.java
- src/main/java/teammates/ui/webapi/request/ErrorReportRequest.java
- src/test/java/teammates/test/cases/webapi/SendErrorReportActionTest.java
- src/web/app/components/error-report/error-report.component.ts
Part of #9420 
Implements a request DTO for the `POST /errorreport` endpoint.
> [#9420] Consolidate RPC RESTFul API

- src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
- src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
> [#9456] Fix editing question when option filed is empty

- src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
Part of #9467 
Added backend validation for v6.
> [#9467] Add validation check for "Not Sure" criteria in Contribution question

- src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
- src/web/app/pages-student/student-home-page/student-home-page.component.html
- src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts
- src/web/app/pages-student/student-home-page/student-home-page.component.ts
Part of #9480 
Added appropriate test cases based on the partitions. I don't think changing the specific values will throw any kind of error, so these should be enough.
> [#9480] Add student home page snapshot tests

- src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
- src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.scss
- src/web/app/pages-student/student-profile-page/student-profile-page.component.html
- src/web/app/pages-student/student-profile-page/student-profile-page.component.scss
- src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html
- src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.scss
- src/web/browserslist
- static-analysis/teammates-stylelint.yml
Part of #9382 
Modified stylelint config to cater the following:
- Enforcing `kebab-case` naming convention
- Disallowing prefixing as it is auto-configured via Angular CLI's autoprefixer
- [Improve `browserslist` to cater to PWA](https://angular.io/guide/build#configuring-browser-compatibility)
> [#9382] Improve stylelint configuration

- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.module.ts
Fixes #9520 
Updated frontend to use new endpoints (after #9443).
There is another regression bug here with regards to the form submission. I had to change the button to do `click()` instead of submit for now. Have to investigate further.
> [#9520] Update new instructor API endpoints on frontend

- src/web/app/page.component.ts
> [#9546] Unable to log out with log out button

- src/web/app/components/sessions-table/sessions-table.component.html
- src/web/app/components/sessions-table/sessions-table.component.scss
- src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.spec.ts
Part of #9480
Test cases added so far:
- default
- 1 course with no feedback session
- 1 course with unpopulated feedback sessions
- 1 course with error loading feedback sessions
- 1 course with unexpanded course tab
- 1 course with 1 feedback session with instructor privilege
- 1 course with 2 feedback sessions with tutor privilege
> [#9480] Add instructor home page snapshot tests

- src/web/app/pages-student/student-profile-page/__snapshots__/student-profile-page.component.spec.ts.snap
- src/web/app/pages-student/student-profile-page/student-profile-page.component.spec.ts
Part of #9480 
Summary of current test cases:
- Default fields
- Student with no details
- Student with values and a photo
> [#9480] Add Snapshot tests for Student profile page

- src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
- src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.spec.ts
- src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
- src/web/app/pages-instructor/student-list/student-list.component.html
Part of #9480 
Test cases added:
- default
- a course with instructor and no student
- a course with instructor and one student
> [#9480] Add instructor course details page snapshot tests

- src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap
- src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts
Fixes part of #9480 
I added two cases, namely:-
- Default
- Populated
Since there are no displayed error messages if one of the ngif conditions is not met, I think it'll be pointless to toggle those, as the only thing we'll get will be the absence of the particular element.
> [#9480] Add student course details snapshot tests

- src/main/java/teammates/common/datatransfer/questions/FeedbackContributionResponseDetails.java
- src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.html
> [#9467] Fix bug for isNotSure option in Contribution question

- src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.spec.ts
- src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
Part of #9480
Test cases:
- default
- student details populated
Note: The change in `ngOnDestroy` is because of [this issue](https://github.com/angular/angular/issues/17013#issuecomment-369976920)
> [#9480] Add snapshot test for instructor course student edit page

- src/web/app/page.component.ts
> [#9666] Modal is not removed when going back to the previous browser page

- src/e2e/java/teammates/e2e/cases/lnp/BaseLNPTestCase.java
- src/e2e/java/teammates/e2e/cases/lnp/InstructorStudentEnrollmentLNPTest.java
- src/test/java/teammates/test/cases/architecture/ArchitectureTest.java
Fixes #9689 
Modify the LNP test for the put '/students' after consolidation
> [#9689] Fix broken LNP test of put /students

- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.scss
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Part of #9510 
Add sorting for the table in the instructor/courses page
**Courses List**
> [#9510] Instructor: Course Page Component: Implement sorting for table headers

- src/main/webapp-backup/stylesheets/teammatesCommon.css
- src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html
- src/web/app/pages-session/session-submission-page/session-submission-page.component.scss
> [#9806] Submission page: Fix typo/grammatically incorrect error message

- src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.component.html
> [#9801] Admin Account Details page: Remove account from course not work

- src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
> [#9811]  Students List: Have a better way to show empty students list

- src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java
- src/web/app/components/question-edit-form/question-edit-form.component.html
- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-types/question-constraint/question-constraint.module.ts
- src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.html
- src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.scss
- src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.spec.ts
- src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts
- src/web/app/components/question-types/question-edit-answer-form/question-edit-answer-form.module.ts
- src/web/app/components/question-types/question-edit-answer-form/rank-options-question-edit-answer-form.component.ts
- src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.spec.ts
- src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.ts
- src/web/app/components/question-types/question-edit-details-form/question-edit-details-form.module.ts
- src/web/app/components/question-types/question-edit-details-form/rank-options-field/rank-options-field.component.html
- src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.ts
- src/web/app/components/question-types/question-edit-details-form/rank-recipients-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/rank-recipients-question-edit-details-form.component.scss
- src/web/app/components/question-types/question-edit-details-form/rank-recipients-question-edit-details-form.component.spec.ts
- src/web/app/components/question-types/question-edit-details-form/rank-recipients-question-edit-details-form.component.ts
- src/web/app/components/question-types/question-instruction/question-instruction.module.ts
- src/web/app/components/question-types/question-instruction/rank-recipients-question-instruction.component.html
- src/web/app/components/question-types/question-instruction/rank-recipients-question-instruction.component.spec.ts
- src/web/app/components/question-types/question-instruction/rank-recipients-question-instruction.component.ts
- src/web/app/components/teammates-common/question-type-name.pipe.ts
- src/web/services/feedback-questions.service.ts
- src/web/services/feedback-responses.service.ts
- src/web/types/default-question-structs.ts
- src/web/types/feedback-response-details.ts
> [#9382] Add support for rank recipient type questions

- src/web/app/components/sessions-table/format-date-brief.pipe.ts
> [#9835] Instructor/Home: Fix format of time display in session tables 

- src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
Fixes #9832 
Made deleted sessions title consistent with deleted courses.
On my local dev server npm run lint seems to be throwing a warning stating: 
> File: C:\Users\Vairon\Documents\Programming\TEAMMATES\src\main\webapp\ngsw.json
Line: 328 Expected a newline at the end of the file. [warning]
I believe this most likely is due to improper setup on my part and should not affect the project. However, if someone more experienced minds pointing me in the right direction I would be glad to correct the issue.
> [#9832] Inconsistent labelling of recycle bin 

- src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap
- src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
Fixes #9545 Adding Instrutor Results Action Buttons Cramped up
Added bootstrap class text-nowrap to the button.
> [#9545] Adding Instrutor Results Action Buttons Cramped up

- src/main/java/teammates/ui/webapi/action/PublishFeedbackSessionAction.java
- src/test/java/teammates/test/cases/webapi/PublishFeedbackSessionActionTest.java
> [#9780] PublishFeedbackSessionAction: Fix returned status from INTERNAL_SERVER_ERROR to NOT_FOUND

- src/test/java/teammates/test/cases/webapi/DeleteFeedbackResponseActionTest.java
Part of #9595 
Create tests in `DeleteFeedbackResponseActionTest.java`
> [#9595] Add tests for DELETE /response

- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Fixes #9920 
Use `filter` method to remove the target course from `courseTabModels`.
> [#9920] Don't load all courses again when deleting/archiving courses in InstructorHomePageComponent

- src/web/app/pages-session/session-submission-page/session-submission-page.component.html
- src/web/app/pages-session/session-submission-page/session-submission-page.component.scss
- src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Fixes #9679 
Just does a check of navbar height using `ngDoCheck`, and changes the padding on the top if the navbar height is too large and covers content
EDIT: Changed navbar to no longer make it fixed
> [#9679] Instructor: Preview Sessions Submission Page's navbar covers some content on the page

- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
> [#9948] Add Cancel Button for Course Editing

- .travis.yml
- src/web/services/account.service.spec.ts
> [#9382] Add AccountService Tests

- src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
- src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
- src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
- src/web/app/pages-instructor/instructor-session-base-page.component.ts
- src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
- src/web/app/pages-instructor/instructor-session-modal-page.component.ts
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
- src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts
- src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts
- src/web/services/course.service.spec.ts
- src/web/services/course.service.ts
- src/web/services/feedback-questions.service.spec.ts
- src/web/services/feedback-questions.service.ts
- src/web/services/feedback-sessions.service.spec.ts
- src/web/services/feedback-sessions.service.ts
- src/web/services/instructor.service.spec.ts
- src/web/services/instructor.service.ts
- src/web/services/student.service.spec.ts
- src/web/services/student.service.ts
> [#9940] Refactor remaining instructor endpoints

- src/web/app/components/error-report/__snapshots__/error-report.component.spec.ts.snap
- src/web/app/components/error-report/error-report.component.ts
- src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.component.ts
- src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.ts
- src/web/app/pages-admin/admin-timezone-page/admin-timezone-page.component.ts
- src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.ts
- src/web/app/pages-session/session-result-page/session-result-page.component.ts
- src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
- src/web/services/error-report.service.spec.ts
- src/web/services/error-report.service.ts
- src/web/services/feedback-questions.service.spec.ts
- src/web/services/feedback-questions.service.ts
- src/web/services/feedback-responses.service.ts
- src/web/services/feedback-sessions.service.ts
- src/web/services/instructor.service.ts
- src/web/services/student.service.ts
- src/web/services/timezone.service.spec.ts
- src/web/services/timezone.service.ts
> [#9940] Refactor Admin Endpoints

- src/web/app/pages-instructor/instructor-courses-page/add-course-form/__snapshots__/add-course-form.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.spec.ts
- src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts
Part of #9382
Added some unit tests for the form component. Mainly focusing on covering onSubmit() method. 
There was an issue with the timezone field causing snapshot tests to fail on travis since their servers are in other countries making the auto detect timezone have different values. Wonder if there are any ways around such timezone issues? Other than hardcoding the values in the tests themselves
> [#9382] Add unit test for add course component

- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
Fixes #10054 
**Outline of Solution**:
- added `<strong>` tag to distinguish the button text
- added CSS to include cursor feedback on hover
**After**:
> [#10054] Added visual feedback on "Scroll down" button

- src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.spec.ts
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts
> [#9382] Add essay question example box

- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Fixes #10064
Fix missing assignment
**GIF of fix**
> [#10064] Delete permanently does not remove course from UI 

- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.spec.ts
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts
Part of #9382
~~In the example component, the texts are editable. However, clicking on button or checking checkboxes do not change anything.~~
> [#9382] Add example components to instructor help questions MCQ

- src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.scss
Part of #9382
Since the example in this section is not a stand-alone component, I copy pasted the relevant parts of the original code for this example. I feel that it doesn't make sense to refactor them to their own components because they are only ever used in 1 specific component. Need some opinions on this.
> [#9382] Add example component for adding questions to a session

- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts
> [#9382] Add Rank Recipient question example box

- src/main/java/teammates/ui/webapi/action/GetCourseSectionNamesAction.java
- src/main/java/teammates/ui/webapi/action/GetFeedbackSessionStudentResponseAction.java
- src/main/java/teammates/ui/webapi/action/InstructorGetCoursesAction.java
- src/main/java/teammates/ui/webapi/action/SearchStudentsAndFeedbackSessionDataAction.java
- src/main/java/teammates/ui/webapi/action/StudentGetCourseDetailsAction.java
- src/test/java/teammates/test/cases/webapi/GetFeedbackSessionActionTest.java
- src/test/java/teammates/test/cases/webapi/SearchStudentsActionTest.java
- src/test/java/teammates/test/cases/webapi/UpdateFeedbackResponseActionTest.java
Part of #9382
Add todo for `webapi` files that need tests based on [codecov report](https://codecov.io/gh/TEAMMATES/teammates/tree/master/src/main/java/teammates/ui/webapi)
> [#9382] Add TODO for Tests (Java)

- src/web/app/components/question-edit-form/question-edit-form.component.scss
> [#10085] Fix edit feedback question number not fitting into box

- src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.spec.ts
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts
> [#9382] Add example box for rubric responder's view of question

- src/web/app/components/question-edit-form/question-edit-form.component.scss
- src/web/app/page.component.scss
Fixes #10084 
Add `cursor: pointer;` on relevant styles
> [#10084] Fix dropdown menu items cursor not changing to pointer on hover

- src/main/java/teammates/common/util/RecaptchaVerifier.java
- src/main/java/teammates/ui/webapi/action/Action.java
- src/main/java/teammates/ui/webapi/action/SessionLinksRecoveryAction.java
- src/test/java/teammates/test/cases/util/RecaptchaVerifierTest.java
- src/test/java/teammates/test/cases/webapi/ActionFactoryTest.java
- src/test/java/teammates/test/driver/GaeSimulation.java
> [#10111] Fix flaky tests

- src/main/java/teammates/ui/webapi/output/SessionResultsData.java
> [#10123] Remove removeAnonymousHash method from instructor result page

- src/web/app/pages-instructor/instructor-student-records-page/__snapshots__/instructor-student-records-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.html
- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.spec.ts
- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts
- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.module.ts
Resolves #10109, closes #9797, closes #9798
> [#10109] Add all responses for student in records page

- src/web/data/developers.json
> [#9481] Release 7.0.0-beta.0

- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts
- src/web/app/pages-session/session-result-page/session-result-page.component.ts
- src/web/services/feedback-sessions.service.spec.ts
- src/web/services/feedback-sessions.service.ts
Fixes #10134 
- Remove nested subscription
- Renamed `getFeedbackSessionsResult` to `getFeedbackSessionResults`
> [#10134] Remove nested subscription in instructor student records page

- static-analysis/teammates-checkstyle.xml
> [#10163] Prevent import of wrong test annotation

- src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.spec.ts
- src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
> [#10144] Add comment search result example box

- angular.json
> [#10178] Update Angular configuration to use different index page

- angular.json
- ngsw-config.json
- package.json
- src/web/app/app.module.ts
- src/web/app/pages-admin/admin-page.component.ts
- src/web/app/pages-instructor/instructor-page.component.ts
- src/web/app/pages-static/static-page.component.ts
- src/web/app/pages-student/student-page.component.ts
- src/web/index.prod.html
- src/web/main.ts
- src/web/manifest.webmanifest
> [#10184] Fix service worker configuration

- src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.scss
- src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-page.component.scss
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.scss
- src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.scss
- src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.scss
Fixes #10081, Closes #10099 
**Comparison with snapshot in original issue**
- changed sub-section header from h3 to h4
- improved spacing between header and question tab, and between sections.
> [#10081] Update font size & section header spacing

- src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-page.component.scss
Fixes #10193 
**Snapshot**
- added the side-nav's CSS attribute `position: fixed`
- removed offset for search bar
- bold the sider bar header
> [#10193] Fixed side bar to window and remove offset

- src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html
- src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.ts
- src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html
- src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
- src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.ts
- src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
- src/web/app/pages-instructor/instructor-session-result-page/response-moderation-button/response-moderation-button.component.html
- src/web/app/pages-instructor/instructor-session-result-page/response-moderation-button/response-moderation-button.component.ts
- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.html
- src/web/services/navigation.service.ts
Fixes the following problems:
- Attempting to preview as a student does not seem to work on my staging server but functions properly in dev environment
- In student all records page, if you click on the moderate response button, an error pops up showing The request is not valid. A 400 status code is returned by backend
- If the instructor is not student in the course, the moderate response page does not work. Should use public submission page instead.
- Moderate response need to generate URL based on student/instructor. Currently, it is all student.
> [#10176] Fix moderation-related problems from UAT

- src/web/app/components/sessions-recycle-bin-table/recycle-bin-table-format-date.pipe.spec.ts
- src/web/app/components/sessions-recycle-bin-table/recycle-bin-table-format-date.pipe.ts
- src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.spec.ts
- src/web/app/components/sessions-table/sessions-table.component.spec.ts
- src/web/app/components/teammates-common/format-date-brief.pipe.spec.ts
- src/web/app/components/teammates-common/format-date-brief.pipe.ts
- src/web/app/components/teammates-common/format-date-detail.pipe.spec.ts
- src/web/app/components/teammates-common/format-date-detail.pipe.ts
- src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.ts
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
- src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.spec.ts
- src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts
- src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
- src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
- src/web/app/pages-session/session-result-page/session-result-page.component.ts
- src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
- src/web/services/feedback-sessions.service.ts
- src/web/services/timezone.service.ts
> [#10152] Moment timezone data not loaded

- src/main/java/teammates/ui/webapi/action/DeleteStudentAction.java
- src/main/java/teammates/ui/webapi/action/GetAuthInfoAction.java
- src/main/java/teammates/ui/webapi/action/GetCourseAction.java
- src/main/java/teammates/ui/webapi/action/GetFeedbackQuestionsAction.java
- src/main/java/teammates/ui/webapi/action/JoinCourseAction.java
- src/main/java/teammates/ui/webapi/action/SearchCommentsAction.java
Resolves #10263 
Most issues found in first pass review already covered in #10231
> [#10263] Clean up endpoint access control

- src/main/java/teammates/common/util/FieldValidator.java
- src/test/java/teammates/test/cases/logic/AccountsLogicTest.java
- src/test/java/teammates/test/cases/util/FieldValidatorTest.java
- src/test/java/teammates/test/cases/webapi/EnrollStudentsActionTest.java
- src/test/java/teammates/test/cases/webapi/UpdateStudentActionTest.java
Fixes #9474
I found a good [stackoverflow discussion](https://stackoverflow.com/questions/46155/how-to-validate-an-email-address-in-javascript) that includes the downfalls of using regex for email validation if anyone's interested.
> [#9474] Change Email Validation to Enforce TLD

- src/main/java/teammates/ui/webapi/action/GetFeedbackQuestionsAction.java
- src/main/java/teammates/ui/webapi/output/FeedbackQuestionData.java
> [#10264] Hide MCQ/MSQ/Rubric Question Weights from Students

- src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseEditPageE2ETest.java
Part of #9536
- Adjust wait timing to reduce stale element error and time out error
> [#9536] Fix Instructor Course Edit Page E2E Test

- src/main/java/teammates/ui/webapi/action/GetCoursesAction.java
- src/main/java/teammates/ui/webapi/action/GetFeedbackSessionAction.java
- src/main/java/teammates/ui/webapi/action/GetFeedbackSessionsAction.java
- src/main/java/teammates/ui/webapi/output/CourseData.java
- src/main/java/teammates/ui/webapi/output/FeedbackSessionData.java
- src/test/java/teammates/test/cases/webapi/GetCoursesActionTest.java
- src/test/java/teammates/test/cases/webapi/GetFeedbackSessionsActionTest.java
> [#10264] Hide FeedbackSession and Course Data

- src/web/app/components/teammates-common/question-type-name.pipe.ts
- src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Fixes #10304
There are also two small UAT fixes:
Before:
After:
Before:
After:
V6:
> [#10304] Instructor adding questions: new question does not inherit setting from the previous question

- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.html
Fixes #10341 
- Set default expanded status to true
> [#10341] Set panel to expand on load

- docs/design.md
> [#9517] Document API layer design principles/policies

- src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html
- src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.scss
- src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html
- src/web/app/components/question-responses/grouped-responses/grouped-responses.component.scss
- src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
- src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.scss
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.scss
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.scss
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.scss
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.scss
Part of #10243 
GQR / RQG
GRQ / RGQ
> [#10243] Change multi level panel color to match V6

- src/web/styles.scss
Part of #10243
- Added darker colour to dropdown item
> [#10243] Darken hover colour of dropdown items

- src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
- src/web/app/components/sortable-table/sortable-table.component.html
- src/web/app/components/sortable-table/sortable-table.component.scss
Part of #10243, fixes #10353 
- As per title + centralise actions column
> [#10243] Add border to per question view and margin to sortable table

- src/web/app/components/question-types/question-constraint/msq-question-constraint.component.html
- src/web/app/components/question-types/question-constraint/msq-question-constraint.component.scss
- src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.html
- src/web/app/components/question-types/question-instruction/constsum-options-question-instruction.component.html
- src/web/app/components/question-types/question-instruction/constsum-options-question-instruction.component.scss
- src/web/app/components/question-types/question-instruction/constsum-recipients-question-instruction.component.html
- src/web/app/components/question-types/question-instruction/constsum-recipients-question-instruction.component.scss
- src/web/app/components/question-types/question-instruction/rank-options-question-instruction.component.html
- src/web/app/components/question-types/question-instruction/rank-options-question-instruction.component.scss
- src/web/app/components/question-types/question-instruction/rank-recipients-question-instruction.component.html
- src/web/app/components/question-types/question-instruction/rank-recipients-question-instruction.component.scss
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
> [#10427] Fix formatting for answer constraints

- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
> [#10466] Instructor enroll students: Make table span entire panel

- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
> [#10333] Make tooltip more readable

- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-submission-form/question-submission-form.component.ts
- src/web/app/pages-session/session-submission-page/session-submission-page.component.html
- src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Fixes #10429 
Remove button for comment saving in the response submission form. Problem only occurs in comment editing.
> [#10429] Remove comment save button for question submission form

- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
Fixes #10419 
- Change link from `web/student/sessions/submission` to `web/sessions/submission`
> [#10419] Instructor moderating submissions goes into student's home page

- src/web/app/components/toast/toast.component.html
- src/web/app/components/toast/toast.component.scss
- src/web/services/status-message.service.ts
Fixes #10410 
- Increase toast duration to 10 seconds
- Add 'X' button to close toast
> [#10410] Increase duration of toast to 10 seconds

- src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
- src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
- src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
- src/web/app/components/sessions-table/sessions-table.component.html
- src/web/app/components/sortable-table/sortable-table.component.html
- src/web/app/components/student-list/__snapshots__/student-list.component.spec.ts.snap
- src/web/app/components/student-list/student-list.component.html
- src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
- src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.html
- src/web/styles.scss
> [#10332] Sorting arrow icon change

- src/web/app/components/redirect-banner/redirect-banner.component.html
- src/web/app/components/redirect-banner/redirect-banner.component.spec.ts
- src/web/app/components/redirect-banner/redirect-banner.component.ts
- src/web/app/components/redirect-banner/redirect-banner.module.ts
- src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.module.ts
- src/web/app/pages-static/index-page/index-page.component.html
- src/web/app/pages-static/index-page/index-page.component.spec.ts
- src/web/app/pages-static/index-page/index-page.module.ts
- src/web/environments/config.template.ts
> [#10455] Add a redirect banner for users to switch versions

- src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
Fixes #10493 
Recycle bin for courses and sessions page
Session result page
> [#10493] Fix tooltip placements

- src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.html
- src/web/app/components/comment-box/comment-row/comment-row.component.html
- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-submission-form/question-submission-form.component.scss
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
Fixes #10450 
Fixes #10442
Fixes #10422 
*Visibility eye-con change*
*Uncheck all custom privileges when switching*
*Background for visibility messages*
> [#10450] [#10442] [#10422] UAT Round 4: Visiblity related UI fixes

- src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.html
- src/web/app/components/question-edit-form/question-edit-form.component.html
- src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html
- src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
- src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap
- src/web/app/components/question-text-with-info/question-text-with-info.component.html
Fixes #10402 
Fixes #10423 
Fixes #10432
> [#10402] [#10423] [#10432] UAT Round 4: Comment related UI fixes

- src/web/app/pages-instructor/instructor-course-edit-page/custom-privilege-setting-panel/custom-privilege-setting-panel.component.html
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
Fixes #10441 
Fixes #10443 
Fixes #10444
> [#10441] [#10443] [#10444] Fix add instructor to course

- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-submission-form/question-submission-form.component.scss
- src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.scss
- src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.scss
- src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.scss
Fixes #10437 
Fixes #10430
Fixes #10434 
Fixes #10457 
This PR adds indentation to all answering forms as well.
> [#10437] [#10430] [#10434] [#10457] Layout changes for question editing and submission

- src/main/java/teammates/ui/webapi/action/GetCourseJoinStatusAction.java
- src/test/java/teammates/test/cases/webapi/GetCourseJoinStatusActionTest.java
- src/web/app/user-join-page.component.ts
> [#10506] User cannot join multiple courses

- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts
Fixes #10415
Fixes #10416  
Fixes #10417 
- Add sort to no response panel
- Change `Submit Response` to `Submit Responses`
- Open `Submit Responses` in new page
> [#10415] [#10416] [#10417] No response panel related fixes

- src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.html
- src/web/app/components/comment-box/comment-row/comment-row.component.html
- src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
- src/web/app/components/question-edit-form/question-edit-form.component.html
- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.scss
- src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution-question-statistics.component.html
- src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution.component.html
- src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
- src/web/app/components/session-edit-form/session-edit-form.component.html
- src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
- src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
- src/web/app/components/sessions-table/sessions-table.component.html
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/add-course-form/__snapshots__/add-course-form.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.html
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
- src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
- src/web/app/pages-student/student-profile-page/__snapshots__/student-profile-page.component.spec.ts.snap
- src/web/app/pages-student/student-profile-page/student-profile-page.component.html
- src/web/styles.scss
> [#10522] Manually add underline to tooltips

- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.scss
- src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
- src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.html
- src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.scss
- src/web/styles.scss
Fixes #10510 
Fixes #10346
Fixes #10463 
Also fixes some other issues
- Make sort icon size less wide
- Fix bad student submission panel color
- Bad
- ![image](https://user-images.githubusercontent.com/32454748/89280434-3400a380-d67b-11ea-80ca-a126190ac42a.png)
- FIxed
- ![image](https://user-images.githubusercontent.com/32454748/89280550-5b577080-d67b-11ea-898b-0cfcbfb4d842.png)
> [#10510][#10346][#10463] Styling fixes

- src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Fixes #10428 
#10557 only fixed the case for response creation; the cases for response update and response deletion are missed.
> [#10428] Remove excessive toast showing in submission page

- src/web/app/components/redirect-banner/redirect-banner.component.html
- src/web/app/components/redirect-banner/redirect-banner.component.ts
> [#10570] Fix redirect banner dismiss button

- src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleResponseDetails.java
- src/web/app/components/question-edit-form/question-edit-form.component.ts
- src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.ts
- src/web/app/components/question-types/question-edit-details-form/mcq-field/mcq-field.component.html
- src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.ts
- src/web/app/components/question-types/question-edit-details-form/msq-field/msq-field.component.html
- src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.ts
- src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.ts
- src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
- src/web/app/pages-instructor/instructor-comments.component.ts
- src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
- src/web/app/pages-instructor/instructor-student-records-page/__snapshots__/instructor-student-records-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.html
- src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts
- src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.html
- src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.ts
- src/web/services/feedback-questions.service.ts
Fixes #10577 
Fixes #10582 
Fixes #10585 
Fixes #10587 
Fixes #10588 
Fixes #10589 
Except for #10588 which has one line of back-end fix, all are pure front-end fixes.
> [#10577] [#10582] [#10585] [#10587] [#10588] [#10589] Fix front-end related issues

- angular.json
- package-lock.json
- package.json
> [#10600] Update tinymce to 5.4.1

- src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java
- src/web/app/components/question-types/question-constraint/msq-question-constraint.component.html
- src/web/styles.scss
Fixes #10584 
Fixes #10606 
Fixes #10607
> [#10584] [#10606] [#10607] Fix MSQ question settings and modal scroll

- src/web/app/components/question-submission-form/question-submission-form.component.ts
> [#10638] Add guard clause to recipient submission form model update

- angular.json
- package.json
> [#10635] Remove extra comma from angular json

- src/web/data/developers.json
> [#10642] Update developers.json

- src/main/java/teammates/logic/api/EmailGenerator.java
> [#10630] Typo mistake

- src/main/java/teammates/ui/webapi/output/SessionResultsData.java
- src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.html
- src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
- src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
- src/web/app/pages-session/session-result-page/session-result-page.component.html
> [#10647] Improve student results page statistics for self-evaluation

- src/main/java/teammates/logic/api/Logic.java
- src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java
> [#10658] Do not reset feedback responses for question

- build.gradle
- docs/CONTRIBUTING.md
- docs/development.md
- docs/glossary.md
- docs/process.md
- docs/troubleshooting-guide.md
- src/test/java/teammates/test/cases/automated/FeedbackSessionClosingRemindersActionTest.java
- src/test/java/teammates/test/cases/logic/AccountsLogicTest.java
- src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
- src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
- src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
- src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
- src/test/java/teammates/test/cases/storage/StudentsDbTest.java
> [#10634] Run component tests only once in CI

- src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
- src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
- src/test/resources/data/typicalDataBundle.json
> [#10655] Fix getRecipientsOfQuestion in FeedbackQuestionsLogic

- build.gradle
Fixes #10684 
This PR goes with solution 1 and keeps the App Engine SDK at a fixed version.
> [#10684] Fix CI tests

- src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java
- src/main/java/teammates/ui/webapi/action/GetFeedbackSessionAction.java
- src/test/java/teammates/test/cases/webapi/GetFeedbackQuestionRecipientsActionTest.java
- src/test/java/teammates/test/cases/webapi/GetFeedbackSessionActionTest.java
> [#10613] Reconfigure InstructorFeedbackSubmission access control

- src/web/data/developers.json
> [#10704] Update developers.json

- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
> [#10715] Instructor viewing results: No responses shown for non-question view if there are no sections in course

- src/web/app/public-page.component.spec.ts
- src/web/app/public-page.component.ts
> [#10723] Missing call to AuthService.getAuthUser for public pages

- src/web/app/components/redirect-banner/redirect-banner.component.html
> [#10726] Change banner message for end of v6

- src/web/data/developers.json
> [#10726] Update developers.json

- src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Fixes #10664
- [ y] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
- [ y] Added the issue number to the "Fixes" keyword above
- [y ] Titled the PR as specified in the abovementioned document
- [y] Made your changes on a branch other than `master` and `release`
- [y ] Gone through all the changes in this PR and ensured that:
- [ y] No unintended changes were made
> [#10664] Student trying to access non-existent session: give a better error message 

- src/web/data/developers.json
> [#10774] Update developers.json

- src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
- src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
Fixes #10568
I changed the regex to also split the lines by tabs
> [#10568] Admin bulk-adding instructors: allow separation by tabs

- src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
- src/test/java/teammates/ui/webapi/GetSessionResultsActionTest.java
> [#10802] student viewing results: 'not authorized' error shown even if the link is correct

- src/web/data/developers.json
> [#10811] Update developers.json

- src/main/java/teammates/ui/output/FeedbackResponsesData.java
- src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
- src/test/java/teammates/ui/webapi/GetFeedbackResponsesActionTest.java
Fixes #10828 
@wkurniawan07 if no issues with the implementation I'll go write some tests for it
> [#10828] MCQ questions: submitted comments not shown

- src/web/data/developers.json
> [#10834] Update developers.json

- src/main/java/teammates/ui/webapi/DeleteInstructorAction.java
Fixes #10835
- Check for is not admin instead of is instructor.
> [#10835] Admin who is instructor cannot delete last instructor 

- src/web/data/developers.json
> [#10854] Update developers.json

- src/main/java/teammates/common/exception/UnauthorizedAccessException.java
- src/main/java/teammates/logic/api/GateKeeper.java
- src/main/java/teammates/ui/webapi/Action.java
- src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
- src/main/java/teammates/ui/webapi/DeleteStudentProfilePictureAction.java
- src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
- src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
- src/main/java/teammates/ui/webapi/UpdateStudentProfileAction.java
- src/main/java/teammates/ui/webapi/WebApiServlet.java
- src/test/java/teammates/ui/webapi/UpdateStudentProfileActionTest.java
> [#10870] Improve error messages for 403 errors

- src/web/data/developers.json
> [#10886] Update developers.json

- src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
- src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
Fixes #10891
Part of #1501 
Improve validation check for numerical scale question by using `BigDecimal`
> [#10891] Numerical Scale Question: Improve Validation 

- src/web/data/developers.json
> [#10909] Update developers.json

- src/web/data/developers.json
> [#10963] Update developers.json

- .github/workflows/component.yml
- .github/workflows/e2e.yml
- .github/workflows/lnp.yml
Part of #10950 
This initiates the start of the long-lived feature branch for development of the Audit Logs feature
> [#10950] Add audit-logs to CI workflow

- src/main/java/teammates/ui/webapi/CompileLogsAction.java
> [#10974] Fix log compilation cron job

- src/web/app/page.component.html
> [#10987] Open new tab for the contact page

- src/web/data/developers.json
> [#10996] Update developers

- src/main/java/teammates/logic/core/GoogleCloudStorageService.java
> [#10998] Fix NPE from GoogleCloudStorageService

- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
> [#11031] Update snapshots

- src/main/java/teammates/storage/entity/FeedbackQuestion.java
- src/main/java/teammates/storage/entity/FeedbackResponse.java
- src/main/java/teammates/storage/entity/FeedbackResponseComment.java
- src/main/java/teammates/storage/entity/FeedbackSession.java
Part of #11001 
This PR will be used to perform the final cleanups for the Objectify V6 migration.
> [#11001] Final cleanup for Objectify V6 migration

- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
> [#11051] Update snapshots to fix component tests

- src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
> [#11042] Fix label to record student email

- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/common/util/TimeHelper.java
- src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
- src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
- src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.scss
- src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
- src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.module.ts
- src/web/app/pages-instructor/instructor-page.component.ts
- src/web/services/log.service.ts
- src/web/services/table-comparator.service.ts
- src/web/types/sort-properties.ts
Fixes #10969 
- Added method to GET session logs
- Added search results table
> [#10969] Instructor Audit Logs Frontend

- .github/workflows/component.yml
- .github/workflows/e2e.yml
- .github/workflows/lnp.yml
Reverts TEAMMATES/teammates#10966
> Revert "[#10950] Add audit-logs to CI workflow (#10966)"

- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Fixes #11084
Clear the highlighting before each enrollment
> [#11084] Remove error highlighting on a new enrollment

- src/main/java/teammates/ui/webapi/CreateCourseAction.java
- src/test/java/teammates/ui/webapi/CreateCourseActionTest.java
- src/web/app/components/toast/toast.component.html
Fixes #11097
Return a better message in `CreateCourseAction`
> [#11097] Return a better message for conflicting course ids

- src/web/data/developers.json
> [#11109] Update developers

- src/web/data/developers.json
> [#11141] Update developers

- src/main/java/teammates/common/util/EmailWrapper.java
- src/main/java/teammates/common/util/HttpRequestHelper.java
- src/main/java/teammates/common/util/LogEvent.java
- src/main/java/teammates/common/util/Logger.java
- src/main/java/teammates/common/util/RequestTracer.java
- src/main/java/teammates/logic/api/EmailGenerator.java
- src/main/java/teammates/logic/api/EmailSender.java
- src/main/java/teammates/logic/api/LogsProcessor.java
- src/main/java/teammates/logic/core/EmptyEmailService.java
- src/main/java/teammates/ui/webapi/CreateFeedbackSessionLogAction.java
- src/main/java/teammates/ui/webapi/JsonResult.java
- src/main/java/teammates/ui/webapi/OriginCheckFilter.java
- src/main/java/teammates/ui/webapi/RequestTraceFilter.java
- src/main/java/teammates/ui/webapi/WebApiServlet.java
Fixes #11180 
Events are logged when HTTP request is received, HTTP response is dispatched, and emails are sent. Note that this PR's purpose is just to set up basic infrastructure and example.
> [#11180] Convert event-based log message to structured logs

- src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
- src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts
- src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
- src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts
Fixes #11196
Original authors: @rrtheonlyone and @moziliar
> [#11196] Fix incorrect display of average value for rubric question stats

- src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/ui/webapi/ActionFactory.java
- src/main/java/teammates/ui/webapi/GetUserCookieAction.java
- src/test/java/teammates/test/AbstractBackDoor.java
- src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
- src/test/java/teammates/ui/webapi/SearchInstructorsActionTest.java
- src/test/java/teammates/ui/webapi/SearchStudentsActionTest.java
- src/web/services/timezone.service.spec.ts
Fix some existing test-related issues, which includes fix #11304
> [#11304] Add fixes for existing test-related issues

- src/main/java/teammates/common/datatransfer/GeneralLogEntry.java
- src/main/java/teammates/common/util/HttpRequestHelper.java
- src/main/java/teammates/common/util/LogEvent.java
- src/main/java/teammates/common/util/Logger.java
- src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
- src/main/java/teammates/ui/servlets/OriginCheckFilter.java
- src/main/java/teammates/ui/servlets/RequestTraceFilter.java
- src/main/java/teammates/ui/servlets/WebApiServlet.java
- src/main/java/teammates/ui/webapi/QueryLogsAction.java
- src/test/java/teammates/test/MockLogsProcessor.java
- src/web/app/components/logs-table/logs-table-model.ts
- src/web/app/components/logs-table/logs-table.component.html
- src/web/app/components/logs-table/logs-table.component.ts
- src/web/app/components/logs-table/logs-table.module.ts
- src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap
- src/web/app/pages-logs/logs-page.component.html
- src/web/app/pages-logs/logs-page.component.spec.ts
- src/web/app/pages-logs/logs-page.component.ts
Fixes #11267 
Mostly minor modifications; each work done can be identified by the commit message.
The major change is the combining of `REQUEST_RECEIVED` and `RESPONSE_DISPATCHED` logs to a single `REQUEST_LOG`.
> [#11267] Improve usability of logs interface page

- src/client/java/teammates/client/scripts/PopulateCourseSearchDocuments.java
- src/main/java/teammates/storage/search/InstructorSearchManager.java
- src/main/java/teammates/storage/search/SearchManager.java
- src/main/java/teammates/storage/search/StudentSearchManager.java
> [#11298] Fix course ID filter for student search result

- src/main/appengine/index.yaml
- src/main/java/teammates/common/util/Logger.java
- src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
- src/main/java/teammates/storage/api/FeedbackSessionsDb.java
- src/main/java/teammates/storage/entity/FeedbackSession.java
- src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java
- src/test/java/teammates/storage/search/StudentSearchTest.java
- src/test/java/teammates/ui/webapi/FeedbackSessionPublishedRemindersActionTest.java
- src/test/resources/emails/sessionReminderEmailForInstructorNotJoinedYet.html
Fixes #11346 
Fixes #11348 
Also fixed two minor component test issues.
> [#11346] [#11348] Fix NPE/array OOB in logs and OOM in session published email cron job

- src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
- src/main/java/teammates/ui/webapi/QueryLogsAction.java
> [#11354] Empty results in instructor audit logs and results view tracking

- src/main/java/teammates/common/datatransfer/logs/RequestLogDetails.java
- src/main/java/teammates/common/util/Logger.java
- src/main/java/teammates/ui/servlets/OriginCheckFilter.java
- src/main/resources/logsForLocalDev.json
- src/test/java/teammates/ui/webapi/QueryLogsActionTest.java
- src/web/services/http-request.service.ts
> [#11364] Track version of web front-end used to call APIs

- src/main/java/teammates/common/datatransfer/logs/RequestLogDetails.java
- src/main/java/teammates/common/util/Logger.java
> [#11372] Add more system logs

- src/main/java/teammates/common/util/Config.java
- src/main/java/teammates/main/Application.java
- src/main/java/teammates/ui/servlets/DevServerLoginServlet.java
- src/main/java/teammates/ui/servlets/LoginServlet.java
- src/main/java/teammates/ui/servlets/OAuth2CallbackServlet.java
- src/main/resources/build.template.properties
> [#11381] Add build.properties flag to indicate whether dev server login page should be enabled

- src/main/java/teammates/ui/webapi/CreateCourseAction.java
- src/test/java/teammates/ui/webapi/CreateCourseActionTest.java
Fixes #11426 
**Before**
https://user-images.githubusercontent.com/59337195/134032166-894a5e0e-08b4-4677-8f7f-68bd391a18a1.mov
**After**
https://user-images.githubusercontent.com/59337195/134032471-2ea883d8-0f69-4075-ba31-4c22b9c41750.mov
> [#11426] Index instructor who created course for searching

- src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
- src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java
Fixes #11470 
- Do not generate missing responses for teams (similar to how it is done currently for students)
This is how a downloaded result (for a question with teams) looks before the change:
```
Question 13,"Rank the other teams, you can give the same rank multiple times."
Summary Statistics
Team,Recipient,Self Rank,Overall Rank,Overall Rank Excluding Self,Ranks Received,Team Rank,Team Rank Excluding Self
,Team 1,-,1,1,1
,Team 2,-,3,3,2
,Team 3,-,2,2,1,2
Team,Giver's Name,Giver's Email,Recipient's Team,Recipient's Name,Recipient's Email,Feedback
Team 1,Alice Betsy,alice.b.tmms@gmail.tmt,Team 2,Team 2,,2
Team 1,Alice Betsy,alice.b.tmms@gmail.tmt,Team 3,Team 3,,1
Team 1,Benny Charles,benny.c.tmms@gmail.tmt,Team 2,Team 2,,No Response
Team 1,Benny …
```
> [#11470] Add exclusion for generating missing responses for teams

- src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
- src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts
- src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Reverts TEAMMATES/teammates#11479 
Cross browser e2e tests seem to be consistently failing after merging this PR to master. Reverting for now so that changes don't get included in V8.4.0
> Revert "[#11122] Audit logs: student list is empty (#11479)"

- src/main/java/teammates/ui/servlets/OAuth2CallbackServlet.java
> [#11516] Use different messages for different auth callback problems

- src/e2e/java/teammates/e2e/cases/InstructorAuditLogsPageE2ETest.java
- src/e2e/java/teammates/e2e/pageobjects/AppPage.java
- src/e2e/java/teammates/e2e/pageobjects/StudentProfilePage.java
> [#11537] Fix unstable E2E tests

- docs/search.md
> [#11598] Outdated link in Solr documentation

- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/logic/api/Logic.java
- src/main/java/teammates/ui/webapi/ActionFactory.java
- src/main/java/teammates/ui/webapi/DeleteNotificationAction.java
- src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
- Add `deleteNotificationAction`
- Add `deleteNotification` method to `logic`
Note: Tests will be added after #11648 to reduce overlap of work
> [#11572] Add delete notification route

- src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.html
- src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts
- src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table-model.ts
- src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.html
- src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.ts
- src/web/services/notification.service.ts
Part of #11572
Demo:
Note that, as the entry will be removed from the list, there will be a gap between the index numbers if middle entries are deleted. Upon refresh, new index numbers will be assigned.
> [#11572] Notification feature - admin page delete notification function 

- src/main/java/teammates/storage/api/NotificationsDb.java
- src/test/java/teammates/storage/api/NotificationsDbTest.java
- src/test/java/teammates/ui/webapi/GetNotificationActionTest.java
- src/test/resources/data/typicalDataBundle.json
Part of #11572
This PR includes test cases for database (`NotificationsDb`). It also includes some fixes for issues found along the way of writing the test cases.
> [#11572] Notification feature - Database Test

- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.spec.ts
- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.module.ts
Fixes #11086 
Added a progress bar to the student enrollment. 
Example with 225 students for enrollment: 
https://user-images.githubusercontent.com/10182564/155832625-dd2e993a-7260-4152-bfd2-7c2a5986306f.mp4
> [#11086] Enrolling students: show a progress indicator when enrolling a large class

- docs/CONTRIBUTING.md
- docs/e2e-testing.md
- src/main/java/teammates/logic/api/Logic.java
- src/main/java/teammates/logic/core/AccountRequestsLogic.java
- src/main/java/teammates/logic/core/AccountsLogic.java
- src/main/java/teammates/logic/core/DataBundleLogic.java
- src/main/java/teammates/ui/webapi/BinFeedbackSessionAction.java
- src/test/java/teammates/common/util/StringHelperTest.java
- src/web/app/components/question-edit-form/question-edit-form.component.ts
- src/web/app/components/teammates-common/enum-to-array.pipe.ts
- src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/courses-section-questions.ts
- src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
- src/web/types/sort-properties.ts
Fixes #11684
- Fix typos described in #11684
- Also fixed other minor typos that I could find.
- Also changed the wording of two related comments to be gender neutral (removing "him" from the comment).
- Also replaced some non-ascii characters which can be replaced. (replacing unnecessary NBSP and non-standard double quotes).
> [#11684] Fix minor typos

- src/e2e/java/teammates/e2e/cases/AdminNotificationsPageE2ETest.java
- src/e2e/java/teammates/e2e/pageobjects/AdminNotificationsPage.java
- src/e2e/resources/data/AdminNotificationsPageE2ETest.json
- src/e2e/resources/testng-e2e.xml
- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/ui/webapi/DeleteNotificationAction.java
- src/test/java/teammates/test/AbstractBackDoor.java
- src/test/java/teammates/test/BaseTestCaseWithDatabaseAccess.java
- src/test/resources/data/typicalDataBundle.json
- src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.html
- src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts
- src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html
- src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.ts
- src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.html
- src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.ts
Adds E2E tests for CRUD of notifications on admin notifications page.
> [#11572] Notification Feature - E2E tests for admin features

- src/main/java/teammates/common/datatransfer/attributes/DeadlineExtensionAttributes.java
- src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
- src/main/java/teammates/common/util/EmailType.java
- src/main/java/teammates/logic/api/EmailGenerator.java
- src/main/java/teammates/ui/webapi/UpdateFeedbackSessionAction.java
- src/test/java/teammates/logic/api/EmailGeneratorTest.java
- src/test/java/teammates/ui/webapi/UpdateFeedbackSessionActionTest.java
- src/test/resources/emails/deadlineExtensionGivenInstructor.html
- src/test/resources/emails/deadlineExtensionGivenStudent.html
Part of #11571
Resolve comments in #11705
Edit: ~Temporarily changing target branch to master to trigger CI.~ This doesn't seem to work :/
> [#11571] Selective deadline extensions: resolve backend issues

- .github/workflows/e2e.yml
- build.gradle
- src/e2e/java/teammates/e2e/pageobjects/AdminHomePage.java
- src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java
Fixes #11591
- Revert temporary fix in #11611 
- Bump selenium to v4.1.3, which fixes the issue
> [#11591] Fix E2E Tests (Firefox) Failing Consistently

- src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
Fixes #11721
Add check for null student/instructor to prevent NPE.
See https://github.com/TEAMMATES/teammates/issues/11721#issuecomment-1094908918.
> [#11721] Selective deadline extension - NPE when submitting feedback responses

- src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
- src/web/app/pages-admin/admin-notifications-page/notification-edit-form/__snapshots__/notification-edit-form.component.spec.ts.snap
- src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html
- src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.spec.ts
- Adds warning alert to notification edit form if admin attempts to edit a notification that has already been shown to users
- Adds border to style demonstration box (as per comment [here](https://github.com/TEAMMATES/teammates/pull/11720#pullrequestreview-941824894))
- Adds snapshot tests for warning alert
> [#11572] Notification Feature - Add warning if admin edits shown notifications

- src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
- src/e2e/java/teammates/e2e/cases/InstructorSessionIndividualExtensionPageE2ETest.java
- src/e2e/java/teammates/e2e/pageobjects/InstructorSessionIndividualExtensionPage.java
- src/e2e/java/teammates/e2e/util/TestDataValidityTest.java
- src/e2e/resources/data/InstructorSessionIndividualExtensionPageE2ETest.json
- src/e2e/resources/testng-e2e.xml
- src/main/java/teammates/common/util/Const.java
- src/main/java/teammates/ui/output/DeadlineExtensionData.java
- src/main/java/teammates/ui/webapi/ActionFactory.java
- src/main/java/teammates/ui/webapi/GetDeadlineExtensionAction.java
- src/test/java/teammates/test/AbstractBackDoor.java
- src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
- src/test/java/teammates/ui/webapi/GetDeadlineExtensionActionTest.java
- src/web/app/pages-instructor/instructor-session-individual-extension-page/__snapshots__/instructor-session-individual-extension-page.spec.ts.snap
- src/web/app/pages-instructor/instructor-session-individual-extension-page/individual-extension-date-modal/__snapshots__/individual-extension-date-modal.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-session-individual-extension-page/individual-extension-date-modal/individual-extension-date-modal.component.html
- src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.html
Part of #11571
- Add e2e tests for selective deadline extension
> [#11571] Selective deadline extension:  E2E Tests

- .github/workflows/component.yml
Fixes #11761
This solution uses the dedicated [GitHub Actions wrapper for Codecov](https://github.com/codecov/codecov-action).
> [#11761] Use GitHub Actions wrapper for Codecov

- package.json
- src/web/app/components/notification-banner/notification-banner.component.spec.ts
- src/web/app/components/user-notifications-list/__snapshots__/user-notifications-list.component.spec.ts.snap
- src/web/app/components/user-notifications-list/user-notifications-list.component.spec.ts
- src/web/app/components/user-notifications-list/user-notifications-list.component.ts
- src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
- src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.spec.ts
- src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.spec.ts
- src/web/app/pages-instructor/instructor-notifications-page/__snapshots__/instructor-notifications-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.html
- src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.spec.ts
- src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.ts
- src/web/app/pages-student/student-notifications-page/__snapshots__/student-notifications-page.component.spec.ts.snap
- src/web/app/pages-student/student-notifications-page/student-notifications-page.component.html
- src/web/app/pages-student/student-notifications-page/student-notifications-page.component.spec.ts
- src/web/app/pages-student/student-notifications-page/student-notifications-page.component.ts
> [#11776] Refactor front-end tests to make TZ=UTC env unnecessary

- src/main/java/teammates/logic/api/TaskQueuer.java
- src/main/java/teammates/ui/request/FeedbackSessionRemindRequest.java
- src/main/java/teammates/ui/request/FeedbackSessionRespondentRemindRequest.java
- src/main/java/teammates/ui/webapi/FeedbackSessionRemindParticularUsersEmailWorkerAction.java
- src/main/java/teammates/ui/webapi/RemindFeedbackSessionSubmissionAction.java
- src/test/java/teammates/ui/webapi/FeedbackSessionRemindParticularUsersEmailWorkerActionTest.java
- src/test/java/teammates/ui/webapi/FeedbackSessionResendPublishedEmailWorkerActionTest.java
- src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.html
- src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.ts
- src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-model.ts
- src/web/app/pages-instructor/instructor-session-modal-page.component.ts
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts
- src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
Fixes #8529
As discussed, `FeedbackSessionRespondentRemindRequest` modified to include an additional `sendCopyToInstructor` boolean property and a check is done on this value during assignment of `instructorToNotify` in `FeedbackSessionRemindParticularUsersEmailWorkerAction`.
> [#8529] Instructor: remind particular students: give a 'send me a copy' tick box

- src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
- src/test/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetailsTest.java
- src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.ts
- src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Fixes #11837
Added support for multiples of 5 to give respondents more flexibility.
> [#11837] Add support for multiples of 5 for team contribution question

- src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap
- src/web/app/pages-monitoring/logs-page/logs-page.component.html
Fixes #11883 
Fixed the UI for screens of all sizes.
Desktop:
Tablet:
> [#11883] Admin/maintainer logs: Fix UI for small screen sizes

- src/web/app/pages-monitoring/logs-page/logs-page.component.ts
> [#11885] Admin/Maintainer Logs: Fix extendStartTime function

- datastore-dev/Dockerfile
> [#11908] Update Datastore emulator JRE version

- src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
- src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.spec.ts
Part of #10920 
Added unit tests for Instructor Sessions Page.
> [#10920] Add front-end tests for Instructor Session Page

- src/web/data/developers.json
Part of #12009 
Updated `developers.json` file including the core team members list.
> [#12009] Release V8.20.0

- src/web/data/developers.json
Part of #12036 
Updated `developers.json` file, including outdated usernames and two missed names from the past sprint; these are for some reason missed out before.
> [#12036] Release V8.21.0

- src/web/data/developers.json
Part of #12058
Updated developers.json file with new contributors.
> [#12058] Release V8.22.0

- src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
- src/main/java/teammates/storage/api/AccountsDb.java
- src/main/java/teammates/storage/api/CoursesDb.java
- src/main/java/teammates/storage/entity/Account.java
- src/test/java/teammates/common/datatransfer/attributes/AccountAttributesTest.java
Part of #12048
1. Add isMigrated flag to entity/Account and entity/AccountAttributes
> [#12048] Add is migrated flag to datastore account

- src/main/java/teammates/storage/sqlapi/UsageStatisticsDb.java
- src/main/java/teammates/storage/sqlentity/UsageStatistics.java
Part of #12048
Create UsageStatistics entity and db
> Add UsageStatistics entity and db

- src/web/data/developers.json
Part of #12097
Updates `developers.json`.
> [#12097] Release V8.23.0

- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/UsageStatisticsLogic.java
- src/main/java/teammates/ui/webapi/CalculateUsageStatisticsAction.java
- src/test/java/teammates/ui/webapi/CalculateUsageStatisticsActionTest.java
Part of #12048
1. Update the action to include entities from sql db
> Update CalculateUsageStatisticsAction to include SQL entities

- src/it/java/teammates/it/storage/sqlapi/AccountRequestDbIT.java
- src/main/java/teammates/common/util/HibernateUtil.java
- src/main/java/teammates/storage/sqlapi/AccountRequestDb.java
- src/main/java/teammates/storage/sqlentity/AccountRequest.java
- src/test/java/teammates/storage/sqlapi/AccountRequestDbTest.java
Implemented the AccountRequest entity, UT and IT for the v9 migration. 
Tests: 
The tests have been fully written. 
* unit tests: create, update and delete  
* integration tests: create, different reads, update and delete
> Account request v9 migration

- src/main/java/teammates/common/util/HibernateUtil.java
- src/main/java/teammates/storage/sqlentity/Account.java
- src/main/java/teammates/storage/sqlentity/AccountRequest.java
- src/main/java/teammates/storage/sqlentity/BaseEntity.java
- src/main/java/teammates/storage/sqlentity/Course.java
- src/main/java/teammates/storage/sqlentity/FeedbackSession.java
- src/main/java/teammates/storage/sqlentity/Notification.java
- src/main/java/teammates/storage/sqlentity/Section.java
- src/main/java/teammates/storage/sqlentity/Team.java
- src/main/java/teammates/storage/sqlentity/UsageStatistics.java
- src/main/java/teammates/storage/sqlentity/User.java
> [#12048] Add Section and Team entity

- src/test/java/teammates/architecture/ArchitectureTest.java
Part of #12048
Now that we have a clearer idea of the architecture, we can add back the architectural tests that were removed to facilitate ease of development.
> [#12048] V9 architecture test

- src/it/java/teammates/it/storage/sqlapi/AccountRequestDbIT.java
- src/it/java/teammates/it/storage/sqlapi/AccountsDbIT.java
- src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
- src/main/java/teammates/common/util/HibernateUtil.java
- src/main/java/teammates/storage/sqlapi/AccountsDb.java
- src/main/java/teammates/storage/sqlapi/EntitiesDb.java
- src/main/java/teammates/storage/sqlentity/Account.java
- src/test/java/teammates/storage/sqlapi/AccountsDbTest.java
- src/test/java/teammates/storage/sqlapi/CoursesDbTest.java
Part of #12048
Migrate accounts Db and clean up misc files.
> [#12048] Migrate accounts Db

- src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/NotificationsLogic.java
- src/main/java/teammates/ui/webapi/DeleteNotificationAction.java
- src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java
- src/test/java/teammates/ui/webapi/DeleteNotificationActionTest.java
Create `DeleteNotificationAction` SQL logic and add relevant tests. Minor update to some other notification related unit tests.
> Create DeleteNotificationAction SQL logic and add relevant tests and update other tests

- src/main/java/teammates/common/util/HibernateUtil.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackConstantSumQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackContributionQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackMcqQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackMsqQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackRankOptionsQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackRankRecipientsQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackRubricQuestion.java
- src/main/java/teammates/storage/sqlentity/responses/FeedbackConstantSumResponse.java
- src/main/java/teammates/storage/sqlentity/responses/FeedbackContributionResponse.java
- src/main/java/teammates/storage/sqlentity/responses/FeedbackMcqResponse.java
- src/main/java/teammates/storage/sqlentity/responses/FeedbackMsqResponse.java
- src/main/java/teammates/storage/sqlentity/responses/FeedbackRankOptionsResponse.java
- src/main/java/teammates/storage/sqlentity/responses/FeedbackRankRecipientsResponse.java
- src/main/java/teammates/storage/sqlentity/responses/FeedbackRubricResponse.java
- Created the remaining 7 `FeedbackQuestion` and `FeedbackResponse` subtypes
> create remaining question and response subtype entities

- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/__snapshots__/mcq-question-edit-answer-form.component.spec.ts.snap
- src/web/app/components/question-types/question-edit-answer-form/mcq-question-edit-answer-form.component.html
- src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue: [Submit feedback page: MCQ (single) question](https://github.com/TEAMMATES/teammates/projects/16#card-88050557)
- Similar to #12144
> [#12081] User-friendliness: Add labels for MCQ question

- src/it/java/teammates/it/sqllogic/core/AccountsLogicIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/AccountsLogic.java
- src/main/java/teammates/sqllogic/core/LogicStarter.java
- src/main/java/teammates/storage/sqlentity/Account.java
- src/main/java/teammates/storage/sqlentity/Notification.java
- src/main/java/teammates/ui/webapi/GetReadNotificationsAction.java
- src/main/java/teammates/ui/webapi/MarkNotificationAsReadAction.java
- src/test/java/teammates/sqllogic/core/AccountsLogicTest.java
- src/test/java/teammates/test/BaseTestCase.java
- src/test/java/teammates/ui/webapi/GetReadNotificationsActionTest.java
- src/test/java/teammates/ui/webapi/MarkNotificationAsReadActionTest.java
Update GetReadNotificationsAction and MarkNotificationAsReadAction for v9 migration.
> [#12048] Update GetReadNotificationsAction and MarkNotificationAsReadAction for v9 migration

- src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
- src/it/java/teammates/it/test/TestProperties.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/AccountsLogic.java
- src/main/java/teammates/sqllogic/core/DeadlineExtensionsLogic.java
- src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
- src/main/java/teammates/sqllogic/core/LogicStarter.java
- src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
- src/main/java/teammates/storage/sqlentity/DeadlineExtension.java
- src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
- src/main/java/teammates/storage/sqlentity/FeedbackSession.java
Add logic layer classes and fix misc issues. Part of a larger PR that is stalling, pushing the misc changes/fixes first so it can be used by the rest of the team.
> [#12048] Add logic layer classes

- src/e2e/java/teammates/e2e/util/AxeUtil.java
Part of #12081
Refactors `AxeUtil.java` so that accessibility rules can be enabled or disabled easily.
> [#12081] Refactor accessibility rule disabling logic

- src/main/java/teammates/storage/sqlentity/FeedbackSession.java
- src/main/java/teammates/storage/sqlentity/Instructor.java
- src/main/java/teammates/ui/webapi/GateKeeper.java
> [#12048] Migrate gatekeeper

- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.html
- src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue: [Add label to rank recipients question](https://github.com/TEAMMATES/teammates/projects/16#card-88052451)
Same solution as previous PRs addressing the adding of labels
> [#12081] User-friendliness: Add label to rank recipients question

- src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java
- src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java
- src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
- src/main/java/teammates/common/util/JsonUtils.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/CoursesLogic.java
- src/main/java/teammates/sqllogic/core/UsersLogic.java
- src/main/java/teammates/storage/sqlapi/CoursesDb.java
- src/main/java/teammates/storage/sqlapi/EntitiesDb.java
- src/main/java/teammates/storage/sqlapi/UsersDb.java
- src/main/java/teammates/storage/sqlentity/Course.java
- src/main/java/teammates/storage/sqlentity/Section.java
- src/main/java/teammates/ui/webapi/Action.java
- src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
> [#12048] Migrate action layer helper methods

- src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
- src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
> [#12048] Rename AccountRequestDb to AccountRequestsDb

- src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/NotificationsLogic.java
- src/main/java/teammates/storage/sqlapi/NotificationsDb.java
- src/main/java/teammates/ui/output/NotificationsData.java
- src/main/java/teammates/ui/webapi/GetNotificationsAction.java
- src/test/java/teammates/ui/webapi/GetNotificationsActionTest.java
Migrate `GetNotificationsAction`.
> [#12048] Migrate GetNotificationsAction

- src/it/java/teammates/it/storage/sqlapi/AccountsDbIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/AccountsLogic.java
- src/main/java/teammates/storage/sqlapi/AccountsDb.java
- src/main/java/teammates/ui/output/AccountData.java
- src/main/java/teammates/ui/output/AccountsData.java
- src/main/java/teammates/ui/webapi/GetAccountAction.java
- src/main/java/teammates/ui/webapi/GetAccountsAction.java
- src/test/java/teammates/storage/sqlapi/AccountsDbTest.java
- src/test/java/teammates/ui/webapi/GetAccountActionTest.java
- src/test/java/teammates/ui/webapi/GetAccountsActionTest.java
This PR consists of the following changes:
- Update GetAccountAction
- Update GetAccountsAction
- Introduce new methods to support above Actions
> [#12048] Get Account and Accounts actions

- src/web/data/developers.json
Part of #12185
Updated developers.json file with new contributors.
> [#12185] Release V8.24.0

- src/main/java/teammates/ui/webapi/Action.java
- src/main/java/teammates/ui/webapi/MarkNotificationAsReadAction.java
> [#12048] Update MarkNotificationAsReadAction logic for unmigrated accounts

- src/e2e/java/teammates/e2e/pageobjects/AppPage.java
- src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
- src/web/app/components/question-submission-form/question-submission-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.html
- src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.ts
- src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Sub-issue [Submit feedback page: rubric question](https://github.com/TEAMMATES/teammates/projects/16#card-88052378)
- Similar to #12149
> [#12081] User-friendliness: Add labels to rubric questions

- src/web/app/components/session-edit-form/session-edit-form.component.scss
Fixes #12161 
- [x ] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
- [x ] Added the issue number to the "Fixes" keyword above
- [x ] Titled the PR as specified in the above mentioned document
- [x ] Made your changes on a branch other than `master` and `release`
- [ x] Gone through all the changes in this PR and ensured that:
- [x ] They addressed one (and only one) issue
- [x ] No unintended changes were made
- [x ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
Added display flex properties and used justify-contents:right ; to move stray-x from left-top to right-top.
>  [#12161] Instructor adding a new session: stray X in the form UI 

- src/it/java/teammates/it/sqllogic/core/DataBundleLogicIT.java
- src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
- src/it/resources/data/DataBundleLogicIT.json
- src/main/java/teammates/common/datatransfer/InstructorPrivileges.java
- src/main/java/teammates/common/datatransfer/SqlDataBundle.java
- src/main/java/teammates/common/util/JsonUtils.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
- src/main/java/teammates/sqllogic/core/DataBundleLogic.java
- src/main/java/teammates/sqllogic/core/LogicStarter.java
- src/main/java/teammates/storage/sqlentity/Account.java
- src/main/java/teammates/storage/sqlentity/AccountRequest.java
- src/main/java/teammates/storage/sqlentity/BaseEntity.java
- src/main/java/teammates/storage/sqlentity/Course.java
- src/main/java/teammates/storage/sqlentity/Instructor.java
- src/main/java/teammates/storage/sqlentity/ReadNotification.java
- src/main/java/teammates/storage/sqlentity/User.java
- src/main/java/teammates/ui/webapi/Action.java
- src/test/java/teammates/test/BaseTestCase.java
Part of #12048
Partial migration of data bundle, the rest will be completed next week.
> [#12048] Migrate data bundle

- src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
- src/web/app/components/question-responses/student-view-responses/student-view-responses.component.html
Sub-issue: [Change white text on info background to black text](https://github.com/TEAMMATES/teammates/projects/16#card-88348608)
Simple change to make the `text-white` class conditional on `isSelfResponses`. Checked through and this is the only place where the change is needed.
> [#12081] User-friendliness: Change white text on info background

- src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
- src/web/app/components/question-responses/student-view-responses/student-view-responses.component.html
- src/web/app/components/question-types/question-response/rubric-question-response.component.html
Sub-issue [View responses page: rubric question](https://github.com/TEAMMATES/teammates/projects/16#card-88067867)
> [#12081] User-friendliness: Make rubric question response table mobile responsive

- src/it/java/teammates/it/sqllogic/core/UsersLogicIT.java
- src/it/java/teammates/it/ui/webapi/ResetAccountActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/LogicStarter.java
- src/main/java/teammates/sqllogic/core/UsersLogic.java
- src/main/java/teammates/storage/sqlapi/UsersDb.java
- src/main/java/teammates/storage/sqlentity/User.java
- src/main/java/teammates/ui/webapi/GetInstructorAction.java
- src/main/java/teammates/ui/webapi/ResetAccountAction.java
- src/test/java/teammates/sqllogic/core/AccountsLogicTest.java
- src/test/java/teammates/sqllogic/core/UsersLogicTest.java
- src/test/java/teammates/ui/webapi/ResetAccountActionTest.java
> [#12048] Migrate Reset Account Action

- src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java
- src/it/java/teammates/it/storage/sqlapi/FeedbackQuestionsDbIT.java
- src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/CoursesLogic.java
- src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
- src/main/java/teammates/sqllogic/core/LogicStarter.java
- src/main/java/teammates/sqllogic/core/UsersLogic.java
- src/main/java/teammates/storage/sqlapi/CoursesDb.java
- src/main/java/teammates/storage/sqlapi/FeedbackQuestionsDb.java
- src/main/java/teammates/storage/sqlapi/UsersDb.java
- src/main/java/teammates/ui/output/FeedbackQuestionsData.java
- src/main/java/teammates/ui/webapi/GetFeedbackQuestionsAction.java
- src/test/java/teammates/sqllogic/core/FeedbackQuestionsLogicTest.java
- src/test/java/teammates/sqlui/webapi/GetFeedbackQuestionsActionTest.java
As per title.
Added the following logic methods:
- `getFeedbackQuestionsForStudents`
- `getFeedbackQuestionsForInstructors`
- `populateFieldsToGenerateInQuestion`
- `getTeamsForSection`
- `getTeamsForCourse`
- `getStudentsForSection`
- `getStudentsForTeam`
> [#12048] Migrate GetFeedbackQuestionAction

- src/it/java/teammates/it/ui/webapi/GetStudentActionIT.java
- src/it/java/teammates/it/ui/webapi/GetStudentsActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/storage/sqlapi/UsersDb.java
- src/main/java/teammates/ui/output/StudentData.java
- src/main/java/teammates/ui/output/StudentsData.java
- src/main/java/teammates/ui/webapi/EnrollStudentsAction.java
- src/main/java/teammates/ui/webapi/GetStudentAction.java
- src/main/java/teammates/ui/webapi/GetStudentsAction.java
- src/test/java/teammates/ui/webapi/GetStudentActionTest.java
- src/test/java/teammates/ui/webapi/GetStudentsActionTest.java
**Things to highlight**
Not sure if it is the best way to do this (similar to PR #12210):
```java
EntitysData data = new EntitysData();
List<EntityData> entityDataList = entitysForCourse
.stream()
.map(EntityData::new)
.collect(Collectors.toList());
data.setEntitys(entityDataList);
```
As EntitysData class current constructor with EntityAttribute will cause a type erasure problem when adding another constructor taking in a List of different data type.
> [#12048] Migrate Get Student and Students Action

- src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
- src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
> [#12048] Fix Typo in Naming of DB Tables

- src/web/data/developers.json
Part of #12227
Updated developers.json file with new contributors.
> [#12227] Release V8.25.0

- src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java
- src/main/java/teammates/common/datatransfer/SqlCourseRoster.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
- src/main/java/teammates/sqllogic/core/UsersLogic.java
- src/main/java/teammates/storage/sqlapi/UsersDb.java
- src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
- src/main/java/teammates/ui/webapi/GetFeedbackQuestionRecipientsAction.java
- src/test/java/teammates/sqllogic/core/FeedbackQuestionsLogicTest.java
- As per title
- Added `getRecipientsOfQuestion`
- Created `SqlCourseRoster`
- Changed `getStudentsForTeam` to take in team name instead of `Team` (`getRecipientsOfQuestion` function requires `getStudentsForTeam` by the teamName)
> Migrate get feedback question recipients action

- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.spec.ts
- src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Fixes #12130 
I used the ngx-page-scroll service as the solution provided for ticket #12222.
I changed the method to be more generic so we can use it in the future two to scroll on that page.
> [#12130] Fix scrolling mechanism when user click on scroll down button.

- src/it/java/teammates/it/ui/webapi/GetStudentsActionIT.java
- src/main/java/teammates/common/datatransfer/SqlCourseRoster.java
- src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
- src/main/java/teammates/storage/sqlentity/Instructor.java
- src/main/java/teammates/storage/sqlentity/Student.java
- src/main/java/teammates/storage/sqlentity/User.java
- src/main/java/teammates/ui/output/StudentData.java
- src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
- src/main/java/teammates/ui/webapi/GetStudentAction.java
- src/main/java/teammates/ui/webapi/GetStudentsAction.java
Part of #12048
Resolves egregious Law of Demeter violation
> [#12048] Add getSectionName and getTeamName methods to User

- src/it/java/teammates/it/sqllogic/core/FeedbackSessionsLogicIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
- src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
- src/main/java/teammates/storage/sqlentity/DeadlineExtension.java
- src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
- src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
- src/main/java/teammates/storage/sqlentity/FeedbackSession.java
- src/main/java/teammates/ui/webapi/DeleteFeedbackSessionAction.java
* Completed testing and migration of DeleteFeedbackSessionAction. 
* Discovered cyclic dependency for toString methods in FeedbackAction, Course and DeadlineExtension. 
* Added clear to Hibernate Util.
> [#12048] Migrate Delete Feedback Session Action

- src/web/app/components/question-types/question-edit-details-form/constsum-options-field/constsum-options-field.component.html
- src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
Sub-issue: [Distribute points (options) question](https://github.com/TEAMMATES/teammates/projects/16#card-88348682)
Similar to previous question types: fix margins, add labels, etc.
> [#12081] User-friendliness: Fix distribute points options question

- src/it/java/teammates/it/storage/sqlapi/FeedbackSessionsDbIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
- src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
- src/main/java/teammates/ui/webapi/RestoreFeedbackSessionAction.java
Modified RestoreFeedbackSessionAction to work with dual DB.
> [#12048] Migrate RestoreFeedbackSessionAction

- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackConstantSumQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackContributionQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackMcqQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackMsqQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackNumericalScaleQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackRankOptionsQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackRankRecipientsQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackRubricQuestion.java
- src/main/java/teammates/storage/sqlentity/questions/FeedbackTextQuestion.java
- src/main/java/teammates/ui/output/FeedbackSessionData.java
- src/main/java/teammates/ui/webapi/CreateFeedbackSessionAction.java
- src/test/java/teammates/sqlui/webapi/BaseActionTest.java
- src/test/java/teammates/sqlui/webapi/CreateFeedbackSessionActionTest.java
Added deep copy for each question subclass 
Wrote unit tests for create feedback session action
> [#12048] Migrate create feedback session action

- src/web/app/components/question-types/question-edit-details-form/rank-options-field/rank-options-field.component.html
- src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.html
- src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.scss
Sub-issue [Instructor edit sessions page: rank options question](https://github.com/TEAMMATES/teammates/projects/16#card-88348686)
- Similar to #12236
> [#12081] Fix rank options question on instructor edit session page

- src/it/java/teammates/it/ui/webapi/GetFeedbackResponseCommentActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
- src/main/java/teammates/ui/webapi/Action.java
- src/main/java/teammates/ui/webapi/GetFeedbackResponseCommentAction.java
> [#12048] Migrate get feedback response comments action

- src/main/java/teammates/ui/webapi/RemindFeedbackSessionResultAction.java
- src/test/java/teammates/sqlui/webapi/RemindFeedbackSessionResultActionTest.java
> [#12048] Migrate RemindFeedbackSessionResultAction

- src/web/data/developers.json
Part of #12317
Updates `developers.json` with new contributors.
> [#12317] Release V8.26.0

- src/it/java/teammates/it/ui/webapi/UpdateFeedbackResponseCommentActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java
- src/main/java/teammates/storage/sqlentity/FeedbackSession.java
- src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
- src/main/java/teammates/ui/webapi/UpdateFeedbackResponseCommentAction.java
> #[12048] Migrate update feedback response comment action

- src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java
- src/it/java/teammates/it/ui/webapi/DeleteFeedbackQuestionActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
- src/main/java/teammates/ui/webapi/DeleteFeedbackQuestionAction.java
- src/test/java/teammates/ui/webapi/DeleteFeedbackQuestionActionTest.java
> [#12048] Migrate DeleteFeedbackQuestionAction

- src/main/java/teammates/ui/webapi/RemindFeedbackSessionSubmissionAction.java
- src/test/java/teammates/sqlui/webapi/RemindFeedbackSessionSubmissionActionTest.java
> [#12048] Migrate RemindFeedbackSessionSubmissionAction

- src/it/java/teammates/it/sqllogic/core/DeadlineExtensionsLogicIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/DeadlineExtensionsLogic.java
- src/main/java/teammates/storage/sqlapi/DeadlineExtensionsDb.java
- src/main/java/teammates/ui/output/DeadlineExtensionData.java
- src/main/java/teammates/ui/webapi/GetDeadlineExtensionAction.java
- src/test/java/teammates/ui/webapi/GetDeadlineExtensionActionTest.java
Migrated and wrote TC. 
Fixed deadline extension criteriaAPI bug.
> [#12048] Migrate GetDeadlineExtensionAction

- src/it/java/teammates/it/ui/webapi/RegenerateStudentKeyActionIT.java
- src/main/java/teammates/common/exception/StudentUpdateException.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/UsersLogic.java
- src/main/java/teammates/ui/webapi/RegenerateStudentKeyAction.java
Migrate `RegenerateStudentKeyAction` and write tests, similar to #12341
> [#12048] Migrate RegenerateStudentKeyAction

- src/it/java/teammates/it/ui/webapi/GetRegKeyValidityActionIT.java
- src/main/java/teammates/ui/webapi/GetRegkeyValidityAction.java
Migrate `GetRegkeyValidityAction` and write tests
> [#12048] Migrate GetRegkeyValidityAction

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #12361
Modifies the PR template according to proposed changes in #12361.
> [#12361] Enhance Pull Request Template

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #12380 
Modified comments in PR template. Made the same modifications to the description for this PR to verify that the GH actions bot now correctly flags incorrect PR descriptions.
> [#12380] PR template causing PR checker to automatically pass

- src/web/data/developers.json
Part of #12376
Updates `developers.json` with new contributors and committers.
> [#12376] Release V8.27.0

- src/test/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetailsTest.java
Part of #1501
I added a few tests to cover  testValidateQuestionDetails method from FeedbackConstantSumQuestionDetails class.
> [#1501] Create Unit Tests for FeedbackConstantSumQuestionDetails class

- src/it/java/teammates/it/sqllogic/core/FeedbackSessionsLogicIT.java
- src/it/java/teammates/it/storage/sqlapi/FeedbackSessionsDbIT.java
- src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
- src/main/java/teammates/sqllogic/core/UsersLogic.java
- src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
- src/main/java/teammates/storage/sqlapi/UsersDb.java
- src/main/java/teammates/ui/output/FeedbackSessionsData.java
- src/main/java/teammates/ui/webapi/GetFeedbackSessionsAction.java
- src/test/java/teammates/sqlui/webapi/GetFeedbackSessionsActionTest.java
Modified GetFeedbackSessionsAction to work with dual DB.
> [#12048] Migrate GetFeedbackSessionsAction

- src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
- src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.scss
Fixes #12281 
- Fixed the overflow issue of action cell by adding `overflow-auto` class tag. 
- Fixed background color issue by adding `d-flex` class tag. 
Below is updated UI.
> [#12281] Fix deleted feedback sessions table overflow

- docs/best-practices/ui-design.md
Fixes #10976
Added points to the UI design best practices page, continuing from #12413.
> [#10976] Document frontend standardizations

- src/it/java/teammates/it/ui/webapi/DeleteInstructorActionIT.java
- src/it/resources/data/typicalDataBundle.json
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/UsersLogic.java
- src/main/java/teammates/ui/webapi/DeleteInstructorAction.java
Migrates DeleteInstructorAction and adds integration tests.
> [#12048] Migrate DeleteInstructorAction

- src/test/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetailsTest.java
- src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
Part of #1501 
I added a few tests to cover the shouldChangesRequireResponseDeletion method for 2 classes:
- FeedbackMsqQuestionDetails
- FeedbackNumericalScaleQuestionDetails
> [#1501] Create Unit Tests for Feedback*QuestionDetails classes

- src/web/app/components/course-edit-form/__snapshots__/course-edit-form.component.spec.ts.snap
- src/web/app/components/course-edit-form/course-edit-form.component.html
- src/web/app/components/course-edit-form/course-edit-form.component.scss
- src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
Fixes #12280 
- Modified the CSS for screen widths  <= 768px for the card header elements to appear column-wise. Styling for larger screen sizes remains the same
> [#12280] Improve display for create course card header

- src/e2e/java/teammates/e2e/pageobjects/Browser.java
Part of #12035 
**Outline of Solution** 
Similar to what was proposed in https://github.com/TEAMMATES/teammates/pull/12216, but for the Edge browser instead
> Fix EdgeDriver setup for E2E Tests

- src/web/data/developers.json
Part of #12514
Update `developer.json` with new contributors.
> [#12514] Release V8.28.0

- docs/development.md
Fixes #12473 
1. Defined what a masquerade mode is.
2. Itemised steps to perform before using the masquerade mode.
3. Listed the steps on how to use the masquerade mode.
> [#12473]  Add steps on how to use the masquerade mode in developer guide

- src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
- src/web/app/components/visibility-panel/visibility-panel.component.html
- src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Fixes #12276
I added a div with the bootstrap class for responsive tables, which adds a horizontal scrollbar when the content is too big.
Added a screenshot to show how it looks.
> [#12276] Instructor edit session page: Fix custom visibility table overflow

- docs/development.md
> [#12466] Docs: Clarify masquerade mode

- docs/development.md
- docs/process.md
Fixes #12669 
Added links to how to run tests locally in the development process page, as well as a short paragraph in running the tests in the development page
> [#12669] Update Documentation to include updating of snapshot tests

- src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
Fixes #12657 
I have changed the required classes in "teammates\src\web\app\pages-instructor\instructor-home-page\instructor-home-page.component.html" and in "teammates\src\web\app\pages-instructor\instructor-home-page_snapshots_\instructor-home-page.component.spec.ts.snap" . I expect this updation will work well. Let me know if there is anything else you want to change.
> [#12657] Instructor Home Page: Students dropdown buttons of the wrong colour . 

- src/it/java/teammates/it/ui/webapi/UpdateInstructorActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java
- src/main/java/teammates/sqllogic/core/LogicStarter.java
- src/main/java/teammates/sqllogic/core/UsersLogic.java
- src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java
- src/main/java/teammates/storage/sqlapi/UsersDb.java
- src/main/java/teammates/ui/webapi/UpdateInstructorAction.java
- src/test/java/teammates/sqllogic/core/UsersLogicTest.java
Migrates UpdateInstructorAction and adds integration tests.
Marked as draft for now; to be merged after #12412.
> [#12048] Migrate UpdateInstructorAction

- docs/static-analysis.md
- docs/troubleshooting-guide.md
- src/web/data/developers.json
> [#12704] Release V8.30.0

- src/main/java/teammates/ui/webapi/CreateFeedbackQuestionAction.java
- src/main/java/teammates/ui/webapi/UpdateFeedbackQuestionAction.java
- src/test/java/teammates/ui/webapi/CreateFeedbackQuestionActionTest.java
- src/test/java/teammates/ui/webapi/UpdateFeedbackQuestionActionTest.java
Added return statement for access checking in `UpdateFeedbackQuestionAction.java`
Added back datastore code for `CreateFeedbackQuestionAction.java` (see: https://github.com/TEAMMATES/teammates/pull/12217/files#diff-c04fffbd5cbf6107d6ed5962aba55ca7ae35f940872a4091800900f19d925c7e)
Removed `@Ignore` annotation for `CreateFeedbackQuestionActionTest.java` and `UpdateFeedbackQuestionActionTest.java`
> [#12048] Fix update and create feedbackquestion actions

- src/it/java/teammates/it/sqllogic/core/DataBundleLogicIT.java
- src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
- src/main/java/teammates/common/util/HibernateUtil.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/CoursesLogic.java
- src/main/java/teammates/sqllogic/core/DataBundleLogic.java
- src/main/java/teammates/storage/sqlapi/CoursesDb.java
- src/main/java/teammates/storage/sqlapi/FeedbackResponsesDb.java
- src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
- src/main/java/teammates/storage/sqlentity/FeedbackSession.java
- src/main/java/teammates/storage/sqlentity/Section.java
> [#12048] Migrate RemoveDataBundle

- src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
- src/test/java/teammates/storage/sqlapi/CoursesDbTest.java
- src/test/java/teammates/storage/sqlapi/UsersDbTest.java
Finish up unit tests for AccountRequestsDb, CoursesDb and UsersDb
> [#12048] Finish partial testcases

- src/test/java/teammates/sqllogic/core/CoursesLogicTest.java
Add tests for the SQL `CourseLogic.java`
> [#12048] Add tests for CoursesLogic

- src/it/java/teammates/it/storage/sqlapi/UsageStatisticsDbIT.java
Part of #12048
Add missing test for getUsageStatisticsForTimeRange
> [#12048] Add test for getUsageStatisticsForTimeRange

- src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java
- src/test/java/teammates/storage/sqlapi/FeedbackResponseCommentsDbTest.java
- src/test/java/teammates/test/BaseTestCase.java
**Changes**
- Added testcases testing CRUD functionalities
- Added additional verification when updating the DB
> Add testcases for FeedbackResponseCommentsDbTest

- .github/workflows/e2e-sql.yml
- build.gradle
- src/e2e/resources/testng-e2e-sql.xml
- src/e2e/resources/testng-unstable-e2e-sql.xml
> Add config for e2e sql tests

- src/it/java/teammates/it/ui/webapi/FeedbackSessionPublishedRemindersActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
- src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
- src/main/java/teammates/ui/webapi/FeedbackSessionPublishedRemindersAction.java
> [#12048] Migrate feedbackSessionPublishedRemindersAction

- src/client/java/teammates/client/scripts/DataMigrationEntitiesBaseScriptSql.java
- src/client/java/teammates/client/scripts/DataMigrationForAccountSql.java
- src/main/java/teammates/ui/servlets/HibernateContextListener.java
Credit to the SQL migration team.
@ziqing26 @kevin9foong @NicolasCwy @domlimm
> [#12048] Add DataMigrationEntitiesBaseScriptSql and DataMigrationForAccountSql

- src/client/java/teammates/client/scripts/DataMigrationEntitiesBaseScriptSql.java
- src/client/java/teammates/client/scripts/SeedDb.java
> [#12048] Add verify to seed db

- src/client/java/teammates/client/scripts/SeedDb.java
Remove unnecessary methods from seed script
> Clean up seed script

- src/test/java/teammates/storage/sqlapi/FeedbackSessionsDbTest.java
- src/test/java/teammates/test/BaseTestCase.java
Add test cases for FeedbackSessionsDb
> [#12048] Add test cases for FeedbackSessionsDb

- src/it/java/teammates/it/ui/webapi/FeedbackSessionOpeningRemindersActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
- src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
- src/main/java/teammates/ui/webapi/FeedbackSessionOpeningRemindersAction.java
Opening emails are sent to co-owner instructors, students and instructors of a course. 
(co-owners are sent 2 different emails)
> [#12048] Migrate FeedbackSessionOpeningRemindersAction

- src/it/java/teammates/it/ui/webapi/GetCoursesActionIT.java
- src/main/java/teammates/ui/webapi/BasicCommentSubmissionAction.java
- src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
- src/main/java/teammates/ui/webapi/CreateFeedbackResponseCommentAction.java
- src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
- src/test/java/teammates/sqlui/webapi/GetCourseActionTest.java
- src/test/java/teammates/ui/webapi/GetFeedbackResponsesActionTest.java
- src/test/java/teammates/ui/webapi/GetFeedbackSessionActionTest.java
> [#12048] Resolve merge conflicts

- src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java
- src/e2e/resources/data/InstructorCourseJoinConfirmationPageE2ETest.json
- src/e2e/resources/data/InstructorCourseJoinConfirmationPageE2ETest_SqlEntities.json
> [#12048] migrate InstructorCourseJoinConfirmationPageE2ETest

- src/e2e/java/teammates/e2e/cases/AdminSessionsPageE2ETest.java
- src/e2e/resources/data/AdminSessionsPageE2ETest.json
- src/e2e/resources/data/AdminSessionsPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for AdminSessionsPageE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorFeedbackEditPageE2ETest.java
- src/e2e/resources/data/InstructorFeedbackEditPageE2ETest.json
- src/e2e/resources/data/InstructorFeedbackEditPageE2ETest_SqlEntities.json
- src/main/java/teammates/ui/webapi/DeleteFeedbackQuestionAction.java
> [#12048] Migrate instructor feedback edit page e2e test

- src/e2e/java/teammates/e2e/cases/StudentHomePageE2ETest.java
- src/e2e/resources/data/StudentHomePageE2ETest_SqlEntities.json
> [#12048] migrate StudentHomePageE2ETest

- src/e2e/java/teammates/e2e/cases/AdminAccountsPageE2ETest.java
- src/e2e/java/teammates/e2e/pageobjects/AdminAccountsPage.java
- src/e2e/resources/data/AdminAccountsPageE2ETest_SqlEntities.json
- src/main/java/teammates/ui/webapi/DeleteAccountAction.java
> [#12048] migrate AdminAccountsPageE2ETest

- src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java
- src/client/java/teammates/client/scripts/sql/DataMigrationForNotificationSql.java
* Check whether an entity is migrated for Notification
* Clear table for Account and ReadNotification
> Add checks to notification script

- src/e2e/java/teammates/e2e/cases/FeedbackConstSumOptionQuestionE2ETest.java
- src/e2e/resources/data/FeedbackConstSumOptionQuestionE2ETest.json
- src/e2e/resources/data/FeedbackConstSumOptionQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackConstSumOptionQuestionE2ETest

- src/it/java/teammates/it/ui/webapi/FeedbackSessionOpeningRemindersActionIT.java
- src/it/java/teammates/it/ui/webapi/GetSessionResponseStatsActionIT.java
> [#12048] Fix failing component tests

- src/e2e/java/teammates/e2e/cases/FeedbackConstSumRecipientQuestionE2ETest.java
- src/e2e/resources/data/FeedbackConstSumRecipientQuestionE2ETest.json
- src/e2e/resources/data/FeedbackConstSumRecipientQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackConstSumRecipientQuestionE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackContributionQuestionE2ETest.java
- src/e2e/resources/data/FeedbackContributionQuestionE2ETest.json
- src/e2e/resources/data/FeedbackContributionQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackContributionQuestionE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackMcqQuestionE2ETest.java
- src/e2e/resources/data/FeedbackMcqQuestionE2ETest.json
- src/e2e/resources/data/FeedbackMcqQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackMcqQuestionE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackMsqQuestionE2ETest.java
- src/e2e/resources/data/FeedbackMsqQuestionE2ETest.json
- src/e2e/resources/data/FeedbackMsqQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackMsqQuestionE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackNumScaleQuestionE2ETest.java
- src/e2e/resources/data/FeedbackNumScaleQuestionE2ETest.json
- src/e2e/resources/data/FeedbackNumScaleQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackNumScaleQuestionE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackResultsPageE2ETest.java
- src/e2e/resources/data/FeedbackResultsPageE2ETest.json
- src/e2e/resources/data/FeedbackResultsPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackResultsPageE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackRubricQuestionE2ETest.java
- src/e2e/resources/data/FeedbackRubricQuestionE2ETest.json
- src/e2e/resources/data/FeedbackRubricQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackRubricQuestionE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
- src/e2e/resources/data/FeedbackSubmitPageE2ETest.json
- src/e2e/resources/data/FeedbackSubmitPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackSubmitPageE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackTextQuestionE2ETest.java
- src/e2e/resources/data/FeedbackTextQuestionE2ETest.json
- src/e2e/resources/data/FeedbackTextQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackTextQuestionE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorCourseEditPageE2ETest.java
- src/e2e/resources/data/InstructorCourseEditPageE2ETest.json
- src/e2e/resources/data/InstructorCourseEditPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorCourseEditPageE2ETest

- src/e2e/java/teammates/e2e/cases/FeedbackRankRecipientQuestionE2ETest.java
- src/e2e/resources/data/FeedbackRankRecipientQuestionE2ETest.json
- src/e2e/resources/data/FeedbackRankRecipientQuestionE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for FeedbackRankRecipientQuestionE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorStudentRecordsPageE2ETest.java
- src/e2e/resources/data/InstructorStudentRecordsPageE2ETest.json
- src/e2e/resources/data/InstructorStudentRecordsPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorStudentRecordsPageE2ETest

- src/it/java/teammates/it/ui/webapi/CreateAccountActionIT.java
- src/main/java/teammates/ui/webapi/CreateAccountAction.java
- src/main/resources/InstructorSampleData.json
Part of #12048
Revert part of: https://github.com/TEAMMATES/teammates/pull/12702
> [#12048] Revert createaccountaction

- src/e2e/java/teammates/e2e/cases/InstructorCourseDetailsPageE2ETest.java
- src/e2e/resources/data/InstructorCourseDetailsPageE2ETest.json
- src/e2e/resources/data/InstructorCourseDetailsPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorCourseDetailsPageE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorCourseEnrollPageE2ETest.java
- src/e2e/resources/data/InstructorCourseEnrollPageE2ETest.json
- src/e2e/resources/data/InstructorCourseEnrollPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorCourseEnrollPageE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsEditPageE2ETest.java
- src/e2e/resources/data/InstructorCourseStudentDetailsEditPageE2ETest.json
- src/e2e/resources/data/InstructorCourseStudentDetailsEditPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorCourseStudentDetailsEditPageE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsPageE2ETest.java
- src/e2e/resources/data/InstructorCourseStudentDetailsPageE2ETest.json
- src/e2e/resources/data/InstructorCourseStudentDetailsPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorCourseStudentDetailsPageE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorFeedbackReportPageE2ETest.java
- src/e2e/resources/data/InstructorFeedbackReportPageE2ETest.json
- src/e2e/resources/data/InstructorFeedbackReportPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorFeedbackReportPageE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorSessionIndividualExtensionPageE2ETest.java
- src/e2e/resources/data/InstructorSessionIndividualExtensionPageE2ETest.json
- src/e2e/resources/data/InstructorSessionIndividualExtensionPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorSessionIndividualExtensionPageE2ETest

- src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
- src/e2e/resources/data/InstructorFeedbackSessionsPageE2ETest.json
- src/e2e/resources/data/InstructorFeedbackSessionsPageE2ETest_SqlEntities.json
> [#12048] Move accounts JSON for InstructorFeedbackSessionsPageE2ETest

- src/client/java/teammates/client/scripts/sql/VerifyNonCourseEntityAttributesBaseScript.java
- src/client/java/teammates/client/scripts/sql/VerifyNotificationAttributes.java
- src/main/java/teammates/storage/sqlentity/Account.java
- src/main/java/teammates/storage/sqlentity/AccountRequest.java
- src/main/java/teammates/storage/sqlentity/Notification.java
- src/main/java/teammates/storage/sqlentity/UsageStatistics.java
Add base script for verifying migrated attributes for the datastore migration
> Add base script for verifying migrated attributes

- src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
- src/e2e/resources/data/AutomatedSessionRemindersE2ETest_SqlEntities.json
- src/e2e/resources/data/InstructorHomePageE2ETest.json
- src/e2e/resources/data/InstructorHomePageE2ETest_SqlEntities.json
Part of #12048
Fix InstructorHomePageE2ETest
Fix AutomatedSessionRemindersE2ETest
> [#12048] fix InstructorHomePageE2ETest

- .github/workflows/axe.yml
- .github/workflows/component.yml
- .github/workflows/dev-docs.yml
- .github/workflows/e2e-cross.yml
- .github/workflows/e2e-sql.yml
- .github/workflows/e2e.yml
- .github/workflows/lnp.yml
- build.gradle
- src/e2e/resources/testng-e2e-sql.xml
- src/e2e/resources/testng-unstable-e2e-sql.xml
Fixes #12783
Search only for .gradle files in .gradle directory
Added github actions workflow for e2e sql tests
Ran on own fork: https://github.com/cedricongjh/teammates/pull/21
> [#12783] Fix GitHub actions

- src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.spec.ts
- src/web/test-helpers/test-event-emitter.ts
Fixes #12859 
Create a test-helper function to make it easier to test event emission
> [#12859] create utility to test event emitters

- src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
- src/main/java/teammates/ui/webapi/GetFeedbackQuestionsAction.java
- src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
Part of #12048
Change gatekeeper logic to be the same as preview as feature: https://github.com/xenosf/teammates/commit/7d15f6304f0a8a81d5517f0c4f5c11cab5659853#diff-cb4e4f96059200ef514244783fe47a423593a6e9797985aa2a82ebcf4e589525
> [#12048] Fix FeedbackResultsPageE2ETest

- src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java
Add more tests for methods in `CoursesDb.java`
> [#12048] Add tests for CourseDbIT

- src/it/java/teammates/it/storage/sqlapi/AccountsDbIT.java
> [#12048] SQL injection test for AccountsDbIT

- src/web/app/components/sessions-table/resend-results-link-to-respondent-modal/resend-results-link-to-respondent-modal.component.spec.ts
- src/web/app/components/sessions-table/respondent-list-info-table/respondent-list-info-table.component.spec.ts
- src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.spec.ts
Part of #12621 
Add unit tests for components in https://app.codecov.io/github/TEAMMATES/teammates/tree/master/src%2Fweb%2Fapp%2Fcomponents%2Fsessions-table
> [#12588] Add unit tests for sessions table

- build.gradle
- src/client/java/teammates/client/scripts/sql/RemoveNonCourseDataFromDataStore.java
- src/client/java/teammates/client/scripts/sql/SeedDb.java
* Create a script to remove non course entities from datastore (for testing purpose only, not for production)
* Fix the progress bar for SeedDb Script
> [#12048] Remove Non Course Data From Datastore (for testing)

- src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java
> [#12048] SQL Injection Test for FeedbackResponsesDb

- src/e2e/java/teammates/e2e/cases/StudentCourseJoinConfirmationPageE2ETest.java
- src/e2e/resources/data/StudentCourseJoinConfirmationPageE2ETest.json
- src/e2e/resources/data/StudentCourseJoinConfirmationPageE2ETest_SqlEntities.json
> [#12048] Migrate StudentCourseJoinConfirmationPageE2ETest

- src/e2e/java/teammates/e2e/util/TestNgXmlTest.java
- src/e2e/resources/testng-e2e-sql.xml
Add check for sql tests in TestNgXml
> [#12048] add check for sql tests in TestNgXml

- build.gradle
- src/test/java/teammates/sqllogic/core/FeedbackResponseCommentsLogicTest.java
**Changes**
- Added testcases testing logic test
> Add testcases for FeedbackResponseCommentsLogicTest

- src/main/java/teammates/logic/api/EmailGenerator.java
- src/main/java/teammates/logic/core/AccountsLogic.java
- src/main/java/teammates/logic/core/CoursesLogic.java
- src/main/java/teammates/storage/sqlentity/Account.java
- src/main/java/teammates/storage/sqlentity/Notification.java
- src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
- src/main/java/teammates/ui/webapi/GetFeedbackSessionsAction.java
- src/main/java/teammates/ui/webapi/InstructorCourseJoinEmailWorkerAction.java
- src/test/java/teammates/logic/api/EmailGeneratorTest.java
- src/test/java/teammates/logic/core/AccountsLogicTest.java
- src/test/java/teammates/logic/core/CoursesLogicTest.java
- src/test/java/teammates/sqlui/webapi/GetFeedbackSessionsActionTest.java
- src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
- src/test/java/teammates/ui/webapi/InstructorCourseJoinEmailWorkerActionTest.java
part of #12048
Ensure that new accounts are created only in postgres
Change logic of methods that check for account in datastore to check for account in postgres
Fix notifications unable to be deleted
Fix being unable to fetch feedback sessions
Fix unable to fetch feedback response comments (change logic to be in line with new changes since v9 was started), see: GetFeedbackResponsesAction in https://github.com/TEAMMATES/teammates/pull/12426
> [#12048] Fix account creation

- src/web/data/developers.json
Part of #12876
Update `developer.json` with new contributors.
> [#12876] Release V9.0.0-beta.0

- src/main/java/teammates/storage/sqlentity/Notification.java
Parts of #12048 
Change title and message field for notification to "TEXT"
> [#12048] Change title and message field for notification to "TEXT"

- src/main/java/teammates/storage/sqlentity/Notification.java
Revert change on the column type for Notification
> [#12048] Revert column type for notification title

- .github/workflows/axe.yml
- .github/workflows/component.yml
- .github/workflows/e2e-sql.yml
- .github/workflows/e2e.yml
- .github/workflows/jdk17.yml
- .github/workflows/lnp.yml
- .github/workflows/pr.yml
* Enable CI checks on `account-request-form` branch.
> [#11878] Enable CI on account request form branch

- docs/e2e-testing.md
Fixes #12909 
update chromedriver download link to the correct page.
>  [#12909] :Dev docs (E2E testing):  update Chromedriver link 

- src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
- src/main/java/teammates/common/datatransfer/attributes/AccountRequestAttributes.java
- src/main/java/teammates/ui/output/AccountRequestData.java
- src/main/java/teammates/ui/request/AccountCreateRequest.java
- src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
- src/test/java/teammates/logic/core/AccountRequestsLogicTest.java
- src/test/java/teammates/ui/webapi/CreateAccountRequestActionTest.java
- src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
- src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
- src/web/services/account.service.ts
- src/web/services/search.service.spec.ts
`AccountCreateRequest`
- added comments
`AccountRequestData`
- added id
- added status
- added comments
`CreateAccountRequestAction`
- removed check for registered `Instructor` to allow even them to create account requests
- removed sending of registration email (this should only occur when the instructor is approved, but in the new logic, creating account requests no longer implies approval)
- changed response to `AccountRequestData`
> [#11878] Modify CreateAccountRequestAction

- src/main/java/teammates/logic/api/TaskQueuer.java
Part of #12048
Temporary fix of account request indexing (indexing is called before insertion of AccountRequest)
> [#12048] add delay to task queuer for indexing account request

- .github/workflows/axe.yml
- .github/workflows/component.yml
- .github/workflows/e2e-sql.yml
- .github/workflows/e2e.yml
- .github/workflows/jdk17.yml
- .github/workflows/lnp.yml
- .github/workflows/pr.yml
> [#12946] Enable CI on Multiple Course Structures branch

- src/web/data/developers.json
> [#12939] Release V9.0.0-beta.1

- src/client/java/teammates/client/scripts/sql/ReverseDataMigrationForAccount.java
* Create a minimal script to reversely migrate data from sql to datastore for account entity. `isMigrated` flag set to true as they are already in sql.
* How to use: 
* Set the  `START_TIME_STRING` to be the time where release v9.0.0-beta.1 goes public.
* Then run `./gradlew -PuserScript=sql/ReverseDataMigrationForAccount execScript `
> [#12048] Add reverse data migration script for account

- src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
- src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
- src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
Part of #11878
Replaced the calls to get an account request by email address and institute with calls to get an account request by ID.
> [#11878] Get account requests by ID in storage update method

- src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
- src/main/java/teammates/logic/api/TaskQueuer.java
- src/main/java/teammates/logic/api/UserProvision.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
- src/main/java/teammates/ui/servlets/WebApiServlet.java
- src/main/java/teammates/ui/webapi/Action.java
- src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
> [#12968] Merge master to release

- src/it/java/teammates/it/ui/webapi/AccountRequestSearchIndexingWorkerActionIT.java
- src/it/java/teammates/it/ui/webapi/BaseActionIT.java
- src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
- src/main/java/teammates/logic/api/TaskQueuer.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
- src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
- src/main/java/teammates/ui/webapi/AccountRequestSearchIndexingWorkerAction.java
- src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
- src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
- src/test/java/teammates/logic/api/MockUserProvision.java
> [#11878] Fix Account Request Update Search Indexing

- src/client/java/teammates/client/connector/DatastoreClient.java
- src/client/java/teammates/client/scripts/sql/DataMigrationForSectionSql.java
- src/client/java/teammates/client/scripts/sql/SeedDb.java
- src/client/java/teammates/client/scripts/sql/VerifyCourseEntityCounts.java
- src/client/java/teammates/client/scripts/sql/VerifySectionAttributes.java
- Updated seedStudents to have 100 student per course and 10 section per course
- Add Migation script for section
- Add verifiction script for section
| Entity          | Test counts | Migration Time | Verification Time (Singapore) |
|-----------------|-------------|----------------|-------------------------------|
| Section| 10000 * 10  | 1m 46s      | 10 min 10 s       |
> [#12048] Data migration for section entities

- src/it/java/teammates/it/ui/webapi/RejectAccountRequestActionIT.java
- src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
- src/main/java/teammates/ui/webapi/RejectAccountRequestAction.java
- src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
> [#11878] Convert RejectAccountRequestAction to use transactions

- src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/AccountsLogic.java
- src/main/java/teammates/ui/webapi/CreateAccountAction.java
- src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
> [#11878] Add Error Message for Approving Existing Account

- src/it/java/teammates/it/ui/webapi/GetCoursesActionIT.java
Part of #12048
This test fails sometimes:
Sort the courses by courseId before comparing, as the courses returned from GetCoursesAction is not guaranteed to be in order of assertion
> [#12048] Fix flaky component test

- src/it/java/teammates/it/ui/webapi/RejectAccountRequestActionIT.java
- src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
- src/main/java/teammates/sqllogic/api/Logic.java
- src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
- src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
- src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
> [#11878] Handle Duplicate Approved Account Requests

- src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
Approval emails are not sent properly due to incorrect order of arguments
> [#11878] Fix Approval Email Bug

- src/web/app/components/account-requests-table/account-request-table.component.ts
> [#11878] Add Toasts

- src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
Part of #12048
Fix bug in FeedbackResponseLogic.java where assertion always fail
Fix bug where Team object is gotten instead of its name
> [#12048] Fix FeedBackResponsesLogic bug

- src/web/app/components/account-requests-table/__snapshots__/account-request-table.component.spec.ts.snap
- src/web/app/components/account-requests-table/account-request-table.component.html
- src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.ts
> [#11878] Fix Highlighting and Null Statuses

- src/it/java/teammates/it/ui/webapi/GetAccountRequestsActionIT.java
- src/it/resources/data/typicalDataBundle.json
- src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
> [#11878] Add sort by created_at for getAllPendingRequests

- src/e2e/java/teammates/e2e/cases/sql/RequestPageE2ETest.java
- src/e2e/java/teammates/e2e/pageobjects/RequestPage.java
- src/e2e/resources/testng-e2e-sql.xml
- src/main/java/teammates/common/util/Const.java
- src/web/app/pages-static/request-page/__snapshots__/request-page.component.spec.ts.snap
- src/web/app/pages-static/request-page/instructor-request-form/__snapshots__/instructor-request-form.component.spec.ts.snap
- src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.html
- src/web/app/pages-static/request-page/request-page.component.html
Similar to `AdminHomePageE2E`, we are unable to verify that the request has been added into the db. But we verify that the success page is rendered properly and acknowledgement email is sent to the user.
> [#11878] Request Page E2E

- src/main/java/teammates/ui/webapi/CreateAccountAction.java
Fixes #12954
Removed reduntant code  so it should not be necessary to set the email address, and the institute in this method. Firstly, the account request already has those values. Secondly, those values are also already in the database.
> [#12954] CreateAccountAction seems to have redundant code

- src/test/java/teammates/sqllogic/core/AccountRequestsLogicTest.java
- src/test/java/teammates/test/BaseTestCase.java
Part of #11878
* Port over #12780 unit tests to work with the ARF changes.
> [#11878] Migrate AccountRequestsLogic unit tests

- src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
- src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
Part of  #12048
Fixes the changes requested in [#13036](https://github.com/TEAMMATES/teammates/pull/13036#pullrequestreview-2002929549)
> [#12048] Data migration section chain fixs

- src/web/app/components/account-requests-table/__snapshots__/account-request-table.component.spec.ts.snap
- src/web/app/components/account-requests-table/account-request-table.component.html
- src/web/app/components/account-requests-table/account-request-table.component.ts
> [#11878] Fix console errors

- src/web/app/components/account-requests-table/account-request-table.component.spec.ts
- src/web/app/components/account-requests-table/account-request-table.component.ts
> [#11878] Fix Rejection Modal

- src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
- src/client/java/teammates/client/scripts/sql/DataMigrationForTeamSql.java
- src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
- src/client/java/teammates/client/scripts/sql/VerifyTeamAttributes.java
- src/main/java/teammates/storage/sqlentity/DeadlineExtension.java
- src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
- src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
- src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
- src/main/java/teammates/storage/sqlentity/FeedbackSession.java
Migrated instructor and deadline extensions
Verify instructor and deadline extensions
**TODO**
> [#12048] Add migration script for instructors and Deadline Extensions

- src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
- src/client/java/teammates/client/scripts/sql/SeedDb.java
- src/main/java/teammates/storage/api/EntitiesDb.java
- src/main/java/teammates/storage/sqlentity/DeadlineExtension.java
- src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
- src/main/java/teammates/storage/sqlentity/Section.java
- src/main/java/teammates/storage/sqlentity/Student.java
Part of #12048
1. Adds lengthening of fields
2. Adds unique indexes
3. Speeds up seeding
> [#12048] Add database changes and speed up seeding

- src/client/java/teammates/client/scripts/sql/SeedDb.java
- src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
- Added scripts to seed deadline extensions and instructors
- Fixed instructor verification for null googleID
> [#12048] Seed instructors and deadline extensions

- src/client/java/teammates/client/scripts/sql/SeedDb.java
Part of  #12048
Remove white space
> [#12048] data migration fix student email seed

- src/client/java/teammates/client/scripts/sql/DataMigrationEntitiesBaseScriptSql.java
- src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java
- src/client/java/teammates/client/scripts/sql/PatchCreatedAtAccountRequest.java
- src/client/java/teammates/client/scripts/sql/VerifyNonCourseEntityAttributesBaseScript.java
> [#12048] Optimse account request - createdAt patch script

- src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
- src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
- src/it/java/teammates/it/ui/webapi/UpdateFeedbackSessionLogsActionIT.java
Fixes #13126
- delete account on test teardown
- Give logs in `UpdateFeedbackSessionLogsActionIT` a unique sorting order
> [#13126] Fix failing component test cases

- .github/workflows/axe.yml
- .github/workflows/component.yml
- .github/workflows/e2e-sql.yml
- .github/workflows/e2e.yml
- .github/workflows/jdk17.yml
- .github/workflows/jdk21.yml
- .github/workflows/lnp.yml
> [#13158] Change docker compose command

- src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
> [#13164] Fix typo

- src/test/java/teammates/sqlui/webapi/DeleteNotificationActionTest.java
Added the unit tests for DeleteNotificationActionTest for PostgreSQL
> [#12048] Migrate tests for DeleteNotificationActionTest

- src/main/java/teammates/ui/webapi/DeleteAccountRequestAction.java
- src/test/java/teammates/sqlui/webapi/DeleteAccountRequestActionTest.java
Part of #12048
Change DeleteAccountRequestActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for DeleteAccountRequestActionTest

- src/main/java/teammates/ui/webapi/GetTimeZonesAction.java
- src/test/java/teammates/sqlui/webapi/GetTimeZonesActionTest.java
Part of #12048
Added the unit tests for GetTimeZonesActionTest for PostgreSQL.
> [#12048] Migrate tests for GetTimeZonesActionTest

- src/test/java/teammates/sqlui/webapi/UpdateFeedbackQuestionActionTest.java
- src/web/app/pages-static/contact-page/contact-page.component.html
Change UpdateFeedbackQuestionActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for UpdateFeedbackQuestionActionTest

- src/main/java/teammates/ui/webapi/SendLoginEmailAction.java
- src/test/java/teammates/sqlui/webapi/BaseActionTest.java
- src/test/java/teammates/sqlui/webapi/SendLoginEmailActionTest.java
> [#12048] Migrate tests for SendLoginEmailActionTest

- src/main/java/teammates/ui/webapi/JsonResult.java
- src/test/java/teammates/sqlui/webapi/JsonResultTest.java
Part of #12048
Added the unit tests for JsonResultTest for PostgreSQL.
> [#12048] Migrate tests for JsonResultTest

- src/test/java/teammates/sqlui/webapi/SearchAccountRequestsActionTest.java
Change SearchAccountRequestsActionTest to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for SearchAccountRequestsActionTest

- src/main/java/teammates/ui/webapi/GetAccountRequestAction.java
- src/test/java/teammates/sqlui/webapi/GetAccountRequestActionTest.java
Change GetAccountRequestActionTest to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for GetAccountRequestActionTest

- src/test/java/teammates/sqlui/webapi/GetRegkeyValidityActionTest.java
Change GetRegkeyValidityActionTest to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for GetRegkeyValidityActionTest

- src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java
- src/main/java/teammates/ui/webapi/ArchiveCourseAction.java
- src/main/java/teammates/ui/webapi/BinFeedbackSessionAction.java
- src/main/java/teammates/ui/webapi/DatastoreBackupAction.java
- src/main/java/teammates/ui/webapi/DeleteDataBundleAction.java
- src/main/java/teammates/ui/webapi/DeleteSqlDataBundleAction.java
- src/main/java/teammates/ui/webapi/GetActionClassesAction.java
- src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
- src/main/java/teammates/ui/webapi/PutDataBundleAction.java
- src/main/java/teammates/ui/webapi/PutSqlDataBundleAction.java
- src/main/java/teammates/ui/webapi/RestoreFeedbackSessionAction.java
- src/main/java/teammates/ui/webapi/SendEmailWorkerAction.java
- src/test/java/teammates/sqlui/webapi/GetActionClassesActionTest.java
Migrate GetActionClassesActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for GetActionClassesActionTest

- src/main/java/teammates/ui/webapi/BinFeedbackSessionAction.java
- src/test/java/teammates/sqlui/webapi/BinFeedbackSessionActionTest.java
Migrate BinFeedbackSessionActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for BinFeedbackSessionActionTest

- src/test/java/teammates/sqlui/webapi/StudentSearchIndexingWorkerActionTest.java
Migrate `src/test/java/teammates/sqlui/webapi/StudentSearchIndexingWorkerActionTest.java`
> [#12048] Migrate Student Search Indexing Worker Action Test

- src/test/java/teammates/sqlui/webapi/GetFeedbackSessionSubmittedGiverSetActionTest.java
Change GetFeedbackSessionSubmittedGiverSetActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for GetFeedbackSessionSubmittedGiverSetActionTest

- src/test/java/teammates/sqlui/webapi/GetInstructorPrivilegeActionTest.java
Migrated `src/test/java/teammates/ui/webapi/GetInstructorPrivilegeActionTest.java`
> [#12048]  Migrate GetInstructorPrivilegeActionTest

- src/test/java/teammates/sqlui/webapi/RestoreFeedbackSessionActionTest.java
> [#12048] Migrate tests for RestoreFeedbackSessionActionTest

- src/test/java/teammates/sqlui/webapi/GetCourseJoinStatusActionTest.java
Migrate `src/test/java/teammates/sqlui/webapi/GetCourseJoinStatusActionTest.java`
> [#12048] Migrate GetCourseJoinStatusActionTest

- src/test/java/teammates/sqlui/webapi/GetFeedbackQuestionRecipientsActionTest.java
Migrate `src/test/java/teammates/sqlui/webapi/GetCourseJoinStatusActionTest.java`
> [#12048] Migrate GetFeedbackQuestionRecipientsActionTest

- src/test/java/teammates/sqlui/webapi/PublishFeedbackSessionActionTest.java
Change PublishFeedbackSessionActionTest.java to ensure compatibility with the PostgreSQL database following the database migration.
> [#12048] Migrate tests for PublishFeedbackSessionActionTest

- src/web/data/developers.json
Fixes #13305 
Congratulations! 🥳 @DhiraPT @peasantbird @mingyang143 @InfinityTwo @BunnyHoppp
> [#13305] Add new committers

- src/e2e/java/teammates/e2e/cases/sql/InstructorCourseStudentDetailsPageE2ETest.java
- src/e2e/java/teammates/e2e/pageobjects/InstructorCourseStudentDetailsViewPage.java
- src/e2e/java/teammates/e2e/pageobjects/InstructorCourseStudentDetailsViewPageSql.java
- src/e2e/resources/data/InstructorCourseStudentDetailsPageE2ETestSql.json
- src/e2e/resources/testng-e2e-sql.xml
> [#12048] Migrate InstructorCourseStudentDetailsPageE2ETest

- src/e2e/java/teammates/e2e/cases/sql/InstructorFeedbackEditPageE2ETest.java
- src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
- src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPageSql.java
- src/e2e/resources/data/InstructorFeedbackEditPageE2ETestSql.json
- src/e2e/resources/testng-e2e-sql.xml
> [#12048] Migrate InstructorFeedbackEditPageE2ETest
